// GENERATED by tools/gen_th_landmarks.py — Thai landmark texts,
// keyed by '<citySlug>/<icon>'. Regenerate with the script; do not
// hand-edit individual entries.

const Map<String, (String nameTh, String descTh)> kLandmarkTh = {};
