#!/usr/bin/env python3
"""Add Turkish translations to remaining HSK6 entries (2001-end: 消耗 → 做主)."""
import re

DART_FILE = r'd:\Masaustu\github\Kandao\lib\core\constants\hsk6_words.dart'

TR = {
    '消耗': 'tüketmek; harcamak',
    '消灭': 'yok etmek; ortadan kaldırmak',
    '销毁': 'imha etmek (eritme veya yakarak)',
    '潇洒': 'özgür ve rahat',
    '小心翼翼': 'dikkatli; itinalı; çok dikkatli',
    '肖像': 'portre',
    '效益': 'fayda; sonuçlar',
    '协会': 'dernek; cemiyet',
    '协商': 'müzakere etmek; görüşmek',
    '协调': 'koordine etmek; uyum sağlamak',
    '协议': 'anlaşma; pakt; protokol',
    '协助': 'yardım etmek; desteklemek',
    '携带': 'yanında taşımak; taşınabilir',
    '泄露': 'sızdırmak (bilgi); ifşa etmek',
    '泄气': 'umutsuzluk; pes etmek; hayal kırıklığı',
    '屑': 'kırıntı; talaş; değer',
    '谢绝': 'nazikçe reddetmek',
    '心得': 'kazanılan bilgi; edinilen deneyim',
    '心甘情愿': 'tamamen istekli; memnuniyetle',
    '心灵': 'kalp; ruh; zeki; çabuk anlayan',
    '心态': 'psikoloji; zihinsel durum; ruh hali',
    '心疼': 'çok sevmek; aşkın acısı',
    '心血': 'emek; özen; gayret',
    '心眼儿': 'düşünceler; niyet',
    '辛勤': 'çalışkan; gayretli; azimli',
    '欣慰': 'memnun olmak; tatmin olmak',
    '欣欣向荣': 'gelişen; büyüyen; müreffeh',
    '新陈代谢': 'metabolizma; yeninin eskinin yerini alması',
    '新郎': 'damat',
    '新娘': 'gelin',
    '新颖': 'yeni ve özgün; özgün',
    '薪水': 'maaş; ücret; ödeme',
    '信赖': 'güvenmek; itimat etmek',
    '信念': 'iman; inanç; inanma',
    '信仰': 'inanç; iman; bir dine inanmak',
    '信誉': 'itibar; prestij; güven',
    '兴隆': 'müreffeh; gelişen',
    '兴旺': 'müreffeh; gelişen; başarılı olmak',
    '腥': 'balık kokusu',
    '刑事': 'cezai; ceza',
    '行政': 'yönetim; idari',
    '形态': 'şekil; biçim; desen',
    '兴高采烈': 'coşkulu; neşeli; coşkuyla',
    '兴致勃勃': 'coşkuyla; tam istekle',
    '性感': 'cinsel cazibe; seksi',
    '性命': 'can; hayat',
    '性能': 'işlev; performans',
    '凶恶': 'vahşi; sert; tehdit edici',
    '凶手': 'katil; saldırgan',
    '汹涌': 'şiddetle fışkırmak; çalkantılı',
    '胸怀': 'yürek; geniş yürekli',
    '胸膛': 'göğüs',
    '雄厚': 'bol; güçlü ve sağlam; zengin',
    '雄伟': 'görkemli; heybetli',
    '修复': 'restorasyon; tamir etmek',
    '修建': 'inşa etmek; yapmak; restore etmek',
    '修养': 'başarı; öz gelişim',
    '羞耻': 'utanç',
    '绣': 'işlemek; nakış',
    '嗅觉': 'koku alma duyusu; koku',
    '须知': 'gereksinimler; bilgi gereklilikleri',
    '虚假': 'yanlış; sahte; bahane; aldatmaca',
    '虚荣': 'kibir; gösteriş; boş ihtişam',
    '虚伪': 'sahte; ikiyüzlü; yapay',
    '需求': 'gereksinim; talep (ekonomi)',
    '许可': 'izin vermek; izin',
    '序言': 'önsöz; kitabın amacını açıklamak',
    '畜牧': 'hayvan yetiştirmek',
    '酗酒': 'aşırı içki içmek; içkiye düşkün olmak',
    '宣誓': 'yemin etmek; ant içmek',
    '宣扬': 'yaymak; kamuoyuna duyurmak',
    '喧哗': 'gürültü; kargaşa; gürültü patırtı',
    '悬挂': 'asmak; askıya almak',
    '悬念': 'gerilim; okuyucunun ilgisi',
    '悬殊': 'büyük uçurum; büyük fark',
    '悬崖峭壁': 'sarp kayalık; uçurum',
    '旋律': 'melodi; ritim',
    '旋转': 'dönmek; çevirmek',
    '选拔': 'en iyiyi seçmek; seçmek',
    '选举': 'seçmek; seçim',
    '选手': 'sporcu; yarışmacı; oyuncu',
    '炫耀': 'gösteriş yapmak; övünmek',
    '削弱': 'zayıflatmak; ezmek',
    '学说': 'teori; öğreti',
    '学位': 'akademik derece; eğitim düzeyi',
    '雪上加霜': 'bir felaketten sonra bir diğeri; haksızlığa hakaret eklenmesi',
    '血压': 'kan basıncı',
    '熏陶': 'olumlu etkilemek',
    '寻觅': 'aramak; bulmaya çalışmak',
    '巡逻': 'devriye gezmek',
    '循环': 'döngüsel döngü; dolaşmak',
    '循序渐进': 'adım adım ilerleme kaydetmek; aşamalı olarak',
    '压迫': 'baskı altına almak; ezdirmek',
    '压岁钱': 'Bahar Bayramı\'nda çocuklara verilen para',
    '压缩': 'sıkıştırmak',
    '压抑': 'duyguları bastırmak; baskıcı',
    '压榨': 'sıkmak; özünü çıkarmak',
    '压制': 'bastırmak; engellemek; boğmak',
    '鸦雀无声': 'sessizlik hâkim; derin sessizlik',
    '亚军': 'ikinci; ikinci gelen',
    '烟花爆竹': 'havai fişek ve maytap',
    '淹没': 'batırmak; boğmak; su basmak',
    '延期': 'ertelemek; uzatmak; geciktirmek',
    '延伸': 'uzatmak; yaymak; germek',
    '延续': 'devam etmek; daha uzun sürmek',
    '严寒': 'dondurucu soğuk; sert kış',
    '严禁': 'kesinlikle yasaklamak; yasak',
    '严峻': 'sert; zorlu; katı; acımasız',
    '严厉': 'sert; katı',
    '严密': 'sıkı; sıkıca örülmüş; sızdırmaz',
    '言论': 'siyasi görüş ifadesi; konuşma',
    '岩石': 'kaya; taş',
    '炎热': 'kavurucu sıcak; yakan sıcak',
    '沿海': 'kıyı şeridi; sahil',
    '掩盖': 'gizlemek; örtbas etmek',
    '掩护': 'örtü; koruma; siper',
    '掩饰': 'kusuru örtmek; hafifletmek',
    '眼光': 'görüş; vizyon',
    '眼色': 'göz kırpmak; gözle işaret etmek',
    '眼神': 'gözlerden okunan ifade veya duygu',
    '演变': 'gelişmek; evrilmek',
    '演习': 'prova yapmak; tatbikat',
    '演绎': 'tümdengelim; çıkarım yapmak',
    '演奏': 'çalgı performansı vermek',
    '厌恶': 'tiksinmek; nefret etmek',
    '验收': 'teslim alınan malları denetlemek',
    '验证': 'incelemek ve doğrulamak',
    '氧气': 'oksijen',
    '样品': 'örnek; numune',
    '谣言': 'söylenti; dedikodu',
    '摇摆': 'sallanmak; dalgalanmak; bocalamak',
    '摇滚': 'rock and roll',
    '遥控': 'uzaktan kumanda',
    '遥远': 'uzak; çok uzak',
    '要点': 'ana nokta; öz',
    '要命': 'birinin ölümüne neden olmak; çok; aşırı',
    '要素': 'temel etken; kilit bileşen',
    '耀眼': 'göz alıcı; parlamak',
    '野蛮': 'barbar; uygar olmayan; acımasız',
    '野心': 'hırs; çılgın planlar',
    '液体': 'sıvı',
    '一度': 'bir ara; bir zamanlar; bir kez',
    '一帆风顺': 'kolayca ilerlemek; sorunsuz yolculuk',
    '一贯': 'tutarlı; sürekli; hep öyle',
    '一举两得': 'bir taşla iki kuş vurmak',
    '一流': 'birinci sınıf',
    '一目了然': 'bakışta anlaşılır; açık seçik',
    '一如既往': 'geçmişte olduğu gibi; daima öyle',
    '一丝不苟': 'kurallara sıkı sıkıya uymak; titizce',
    '一向': 'hep; daima; sürekli',
    '衣裳': 'elbise; giysi',
    '依旧': 'eskisi gibi; hâlâ',
    '依据': 'göre; dayanak; temel',
    '依靠': 'güvenmek; dayanmak',
    '依赖': 'bağımlı olmak; dayanmak',
    '依托': 'güvenmek; dayanmak',
    '仪器': 'alet; bilimsel alet',
    '仪式': 'tören; seremoni',
    '遗产': 'miras; kalıt',
    '遗传': 'kalıtım; kalıtsal',
    '遗留': 'miras; geride bırakmak',
    '遗失': 'kaybetmek; dikkatsizce kaybetmek',
    '疑惑': 'şüphe; belirsizlik hissi',
    '以便': 'böylece; diye',
    '以免': 'ki olmasın; kaçınmak için',
    '以往': 'geçmişte; eskiden',
    '以至': 'kadar; -e kadar',
    '以致': 'sonucu olarak; bu yüzden',
    '亦': 'de; da; ayrıca',
    '异常': 'olağandışı; anormal',
    '意料': 'beklenti; tahmin etmek',
    '意识': 'farkında olmak; bilinç; farkındalık',
    '意图': 'niyet; maksat',
    '意味着': 'anlamına gelmek; ima etmek',
    '意向': 'irade; niyet; yönelim',
    '意志': 'irade; kararlılık',
    '毅力': 'irade gücü; azim; dayanıklılık',
    '毅然': 'tereddütsüzce; kararlılıkla',
    '翼': 'kanatlar; yüzgeç; sığınak',
    '阴谋': 'plan; komplo',
    '音响': 'hoparlörler; akustik; ses alanı',
    '引导': 'rehberlik etmek; yönetmek',
    '引擎': 'motor',
    '引用': 'alıntı yapmak; atıfta bulunmak',
    '饮食': 'yiyecek ve içecek; diyet',
    '隐蔽': 'gizlemek; saklamak; gizli',
    '隐患': 'gizli tehlike',
    '隐瞒': 'gizlemek; saklamak; gerçeği örtmek',
    '隐私': 'gizlilik; kişisel sır',
    '隐约': 'belirsiz; muğlak; silik',
    '英明': 'akıllı; parlak',
    '英勇': 'cesaret; kahraman; yiğit',
    '婴儿': 'bebek; çocuk',
    '迎面': 'yüz yüze; tam karşıdan',
    '盈利': 'kâr; kazanç',
    '应酬': 'sosyalleşmek; sosyal etkinlik',
    '应邀': 'davet üzerine',
    '拥护': 'desteklemek; onaylamak',
    '拥有': 'sahip olmak; bulundurmak',
    '庸俗': 'kaba; bayağı; ahlaksız',
    '永恒': 'ebedi; sonsuz',
    '勇于': 'cesareti olmak; yeterince cesur olmak',
    '涌现': 'ortaya çıkmak; belirginleşmek',
    '踊跃': 'istekli; coşkuyla',
    '用户': 'kullanıcı; tüketici; abone',
    '优胜劣汰': 'en güçlünün hayatta kalması',
    '优先': 'öncelik; tercihli',
    '优异': 'olağanüstü; mükemmel; çok iyi',
    '优越': 'üstün; üstünlük',
    '忧郁': 'melankolik; kederli',
    '犹如': 'sanki; benzer; görünmek',
    '油腻': 'yağlı (yemek)',
    '油漆': 'yağlı boya; vernik',
    '有条不紊': 'düzenli şekilde; metodolojik olarak',
    '幼稚': 'çocukça; saf; olgunlaşmamış',
    '诱惑': 'ayartmak; ayartma; cazibe',
    '渔民': 'balıkçı',
    '愚蠢': 'aptal; budala',
    '愚昧': 'cahil; bilgisiz',
    '舆论': 'kamuoyu',
    '与日俱增': 'her geçen gün büyümek',
    '宇宙': 'evren; kozmos',
    '羽绒服': 'tüy ceket; mont',
    '玉': 'yeşim taşı',
    '预料': 'tahmin etmek; beklemek',
    '预期': 'beklemek; beklenen; öngörmek',
    '预算': 'bütçe',
    '预先': 'önceden',
    '预言': 'öngörmek; kehanet',
    '预兆': 'alâmet; işaret',
    '欲望': 'arzu; şehvet',
    '寓言': 'masal; fabl',
    '愈': 'iyileşmek; ne kadar daha',
    '冤枉': 'haksızlık yapmak; haksızlık; değmez',
    '元首': 'devlet başkanı',
    '元素': 'element; kimyasal element',
    '元宵节': 'Fener Festivali',
    '园林': 'bahçeler; park; peyzaj',
    '原告': 'davacı; şikayetçi',
    '原理': 'prensip; teori',
    '原始': 'ilk; orijinal; ilkel',
    '原先': 'eski; orijinal',
    '圆满': 'tatmin edici',
    '缘故': 'neden; sebep',
    '源泉': 'kaynak; su kaynağı',
    '约束': 'kısıtlamak; sınırlamak',
    '乐谱': 'nota; müzik notası',
    '岳母': 'eşin annesi; kayınvalide',
    '孕育': 'hamile olmak; yavru doğurmak; beslemek',
    '运算': 'matematik işlemi',
    '运行': 'hareket; hareket halinde olmak; çalışmak',
    '酝酿': 'olgunlaşmak (bir konu); ön görüşmeler yapmak',
    '蕴藏': 'depolamak; dokunulmamış miktarlar içermek',
    '熨': 'ütülemek; basmak',
    '杂技': 'akrobasi',
    '杂交': 'melez oluşturmak; çapraz döllemek',
    '砸': 'parçalamak; ezmek; kırmak; başarısız olmak',
    '咋': 'nasıl veya neden (怎么\'nin kısaltması)',
    '灾难': 'felaket; yıkım',
    '栽培': 'yetiştirmek; eğitmek; kültüre almak',
    '宰': 'kesmek; kesip biçmek; yönetmek',
    '再接再厉': 'mücadeleye devam etmek; ısrar etmek',
    '在意': 'önemsemek; aldırmak',
    '攒': 'biriktirmek; stok etmek',
    '暂且': 'şimdilik; geçici olarak',
    '赞叹': 'hayranlıkla iç çekmek; övmek',
    '赞助': 'desteklemek; sponsor olmak',
    '遭受': 'acı çekmek; maruz kalmak',
    '遭殃': 'felakete uğramak',
    '遭遇': 'başına gelmek; karşılaşmak',
    '糟蹋': 'harcamak; mahvetmek; bozmak',
    '造型': 'model yapmak; şekillendirmek',
    '噪音': 'gürültü; ses; statik',
    '责怪': 'suçlamak; kınamak',
    '贼': 'hırsız',
    '增添': 'eklemek; artırmak',
    '赠送': 'hediye vermek',
    '扎': 'batırmak; iğne sokmak; delmek',
    '扎实': 'sağlam; güçlü; pratik',
    '渣': 'tortu; cüruf',
    '眨': 'göz kırpmak',
    '诈骗': 'dolandırmak; hilekarlık; aldatmak',
    '摘要': 'özet; soyut',
    '债券': 'tahvil; bono',
    '沾光': 'aydınlıktan yararlanmak; birinin sayesinde kazanmak',
    '瞻仰': 'saygıyla bakmak; hayran olmak',
    '斩钉截铁': 'kararlı ve kesin; kesinlikle',
    '展示': 'açmak; ortaya koymak; sergilemek',
    '展望': 'görünüm; beklenti; ileriye bakmak',
    '展现': 'çıkmak; ortaya çıkmak; göstermek',
    '崭新': 'bütünüyle yeni',
    '占据': 'işgal etmek; tutmak; yaşamak',
    '占领': 'toprak işgal etmek; ele geçirmek',
    '战斗': 'savaşmak; mücadele etmek',
    '战略': 'strateji',
    '战术': 'askeri taktik',
    '战役': 'askeri sefer; savaş',
    '章程': 'yazılı kurallar; tüzük; yönetmelik',
    '帐篷': 'çadır',
    '障碍': 'engel; bariyer',
    '招标': 'ihale açmak',
    '招收': 'işe almak; kabul etmek',
    '朝气蓬勃': 'gençlik enerjisiyle dolu; canlı ve dinamik',
    '着迷': 'büyülenmek; şaşkına dönmek',
    '沼泽': 'bataklık; sazlık',
    '照样': 'eskisi gibi; her zamanki gibi',
    '照耀': 'parlamak; aydınlatmak',
    '折腾': 'bir o yana bir bu yana atmak; tekrar tekrar yapmak; acı çektirmek',
    '遮挡': 'örtmek; dışarıda tutmak',
    '折': 'kırmak; kırılmak; dönüştürmek; katlamak',
    '折磨': 'işkence etmek; eziyet etmek',
    '侦探': 'dedektif',
    '珍贵': 'değerli; kıymetli',
    '珍稀': 'nadir; değerli ve az bulunan',
    '珍珠': 'inci',
    '真理': 'gerçek; hakikat',
    '真相': 'gerçek; gerçeklik',
    '真挚': 'samimi; içten; gerçek',
    '斟酌': 'düşünmek; değerlendirmek',
    '枕头': 'yastık',
    '阵地': 'mevzi; cephe',
    '阵容': 'sıralama; askeri düzen',
    '振奋': 'kendini heyecanlandırmak; ruhu yükseltmek',
    '振兴': 'güçlü biçimde geliştirmek; canlandırmak',
    '震撼': 'sarsmak',
    '震惊': 'şok etmek; hayrete düşürmek',
    '镇定': 'sakin; soğukkanlı',
    '镇静': 'sakin; soğukkanlı; dingin',
    '正月': 'Ay takviminin ilk ayı',
    '争端': 'anlaşmazlık; tartışma; çatışma',
    '争夺': 'üzerinde kavga etmek',
    '争气': 'bir şey için çok çalışmak; geride kalmamaya kararlı olmak',
    '争先恐后': 'birinciliği çekişmek; yarışmak',
    '争议': 'tartışma; anlaşmazlık',
    '征服': 'fethetmek; boyun eğdirmek',
    '征收': 'vergi almak; tarife uygulamak',
    '挣扎': 'mücadele etmek',
    '蒸发': 'buharlaşmak',
    '整顿': 'düzenlemek; pekiştirmek',
    '正当': 'zamanında; tam zamanında; uygun',
    '正负': 'pozitif ve negatif; artı eksi',
    '正规': 'resmi; düzenli; standartlara uygun',
    '正经': 'düzgün; ciddi; standart; gerçekten',
    '正气': 'sağlıklı ortam; sağlıklı atmosfer',
    '正义': 'adalet; adil',
    '正宗': 'özgün; geleneksel; eski okul',
    '证实': 'onaylamak; doğrulamak',
    '证书': 'sertifika; kimlik bilgileri',
    '郑重': 'ciddi; saygın',
    '政策': 'politika',
    '政权': 'rejim; siyasi güç; otorite',
    '症状': 'belirti; hastalık belirtisi',
    '之际': 'süresince; olduğu zaman',
    '支撑': 'desteklemek; dayak; destek',
    '支出': 'harcamak; ödemek; masraf',
    '支流': 'kol; küçük yön; dal',
    '支配': 'kontrol etmek',
    '支援': 'desteklemek; yardımcı olmak',
    '支柱': 'sütun; destek; temel taşı',
    '枝': 'dal; ince dal',
    '知觉': 'algı; bilinç; his',
    '知足常乐': 'sahip olduklarıyla yetinmek; kanaat etmek',
    '脂肪': 'vücut yağı',
    '执行': 'uygulama; yerine getirmek',
    '执着': 'görüşünü değiştirmeyi reddetmek; ısrar etmek',
    '直播': 'canlı yayın',
    '直径': 'çap',
    '侄子': 'yeğen; erkek kardeşin oğlu veya kızı',
    '值班': 'nöbet tutmak; vardiya çalışmak',
    '职能': 'işlev; rol',
    '职位': 'mesleki pozisyon',
    '职务': 'görev; pozisyon; iş',
    '殖民地': 'koloni',
    '指标': 'hedef; norm; endeks; gösterge',
    '指定': 'atamak; belirlemek',
    '指甲': 'tırnak',
    '指令': 'emir; komut; talimat',
    '指南针': 'pusula',
    '指示': 'göstermek; talimat vermek; talimatlar',
    '指望': 'ummak; güvenmek; umut',
    '指责': 'kınamak; eleştirmek; suçlamak',
    '志气': 'hırs; kararlılık; ruh; azim',
    '制裁': 'cezalandırmak; ekonomik yaptırımlar',
    '制服': 'üniforma; boyun eğdirmek; kontrol altına almak',
    '制约': 'kısıtlamak; koşullandırmak',
    '制止': 'durdurmak; son vermek',
    '治安': 'hukuk ve düzen; kamu güvenliği',
    '治理': 'kontrol altına almak; yönetmek',
    '致辞': 'konuşma yapmak; hitap etmek',
    '致力': 'çalışmak için; çaba göstermek',
    '致使': 'neden olmak; sonuç vermek',
    '智力': 'zeka; anlayış',
    '智能': 'zeki; yetenek; akıllı',
    '智商': 'IQ (zeka katsayısı)',
    '滞留': 'tutmak; alıkoyma',
    '中断': 'kesmek; ara vermek',
    '中立': 'tarafsız; tarafsızlık',
    '中央': 'merkezi; orta; merkez',
    '忠诚': 'dürüst; sadakat; bağlı',
    '忠实': 'sadık; güvenilir',
    '终点': 'son; son nokta; varış noktası; bitiş çizgisi',
    '终究': 'sonunda; her şey söylenip yapıldıktan sonra',
    '终身': 'ömür boyu',
    '终止': 'durdurmak; sona erdirmek',
    '衷心': 'içtenlikle; tam kalpten; samimi',
    '肿瘤': 'tümör; neoplazm',
    '种子': 'tohum',
    '种族': 'ırk; etnik köken',
    '众所周知': 'herkesin bildiği gibi',
    '种植': 'ekmek; yetiştirmek; ürün',
    '重心': 'ağırlık merkezi; merkezi çekirdek',
    '舟': 'tekne; kayık',
    '州': 'eyalet; il',
    '周边': 'çevre; civar',
    '周密': 'titiz; dikkatli; kapsamlı',
    '周年': 'yıldönümü; yıllık',
    '周期': 'dönem; döngü; ritim',
    '周折': 'engel; zorluklar; sorun; komplikasyon',
    '周转': 'devir hızı; kaynağa sahip olmak',
    '粥': 'pirinç lapası; çorba',
    '昼夜': 'gece ve gündüz; sürekli durmaksızın',
    '皱纹': 'kırışık; çizgi',
    '株': 'gövde; kök',
    '诸位': '(zamir) herkes; bayanlar ve baylar',
    '逐年': 'yıldan yıla; yıllık bazda',
    '主办': 'ev sahipliği yapmak (konferans veya spor etkinliği)',
    '主导': 'önde gelen; hâkim; yönlendirici',
    '主管': 'sorumlu kişi; başkanlık etmek',
    '主流': 'ana akım (nehrin); temel nokta',
    '主权': 'egemenlik',
    '主义': '-izm; ideoloji',
    '拄': 'destek; bastonla yaslanmak',
    '嘱咐': 'tembihleme; söylemek; öğütlemek',
    '助理': 'asistan',
    '助手': 'asistan; yardımcı',
    '住宅': 'konut; kiralık konut',
    '注射': 'enjeksiyon; ilaç enjekte etmek',
    '注视': 'dikkatle izlemek; bakmak',
    '注释': 'açıklama; dipnot; kenar notu yapmak',
    '注重': 'dikkat etmek; vurgulamak; üzerine durmak',
    '驻扎': 'konuşlanmak; askeri garnizon kurmak',
    '著作': 'eser; kitap; yazı',
    '铸造': 'dökmek (metali kalıba dökmek)',
    '拽': 'çekmek; sürüklemek',
    '专长': 'uzmanlık; özel bilgi veya beceri',
    '专程': 'özel amaçlı seyahat',
    '专利': 'patent',
    '专题': 'özel konu; özel mesele veya konu',
    '砖': 'tuğla',
    '转达': 'iletmek; aktarmak; bildirmek',
    '转让': 'devretmek (teknoloji, mal vb.)',
    '转移': 'kaydırmak; yönlendirmek; göç etmek',
    '转折': 'dönüm noktası; olayların seyri',
    '传记': 'biyografi',
    '庄稼': 'tarım ürünleri',
    '庄严': 'görkemli; vakur',
    '庄重': 'ağırbaşlı; resmi; vakur',
    '装备': 'ekipman; teçhizat etmek',
    '装卸': 'yüklemek ve boşaltmak; aktarmak',
    '壮观': 'muhteşem; görkemli',
    '壮丽': 'ihtişam; muhteşem; heybetli',
    '壮烈': 'cesur ve onurlu',
    '追悼': 'matem; anma töreni',
    '追究': 'araştırmak; sebep aramak',
    '坠': 'düşmek; sukut',
    '准则': 'prensip; standart veya norm',
    '卓越': 'üstünlük; mükemmellik; harika',
    '着手': 'elini koymak; başlamak',
    '着想': 'başkalarının ihtiyaçlarını düşünmek',
    '着重': 'önem vermek; vurgulamak',
    '琢磨': 'düşünmek; cilalamak (mücevher veya edebi eserler)',
    '姿态': 'tutum; duruş; tavır',
    '资本': '(ekonomi) sermaye; varlık',
    '资产': 'mülk; varlık',
    '资深': 'deneyimli; kıdemli',
    '资助': 'sübvansiyon; mali yardım sağlamak',
    '滋润': 'nemli; doymuş',
    '滋味': 'tat; lezzet; hissetme biçimi',
    '子弹': 'kurşun; fişek',
    '自卑': 'kendini yetersiz hissetmek',
    '自发': 'kendiliğinden; istemeden',
    '自力更生': 'öz yeterlilik; kendi kendine yetme',
    '自满': 'kendini beğenmişlik; memnuniyetkâr',
    '自主': 'bağımsız; kendi başına hareket etmek',
    '宗教': 'din',
    '宗旨': 'amaç; hedef; gaye',
    '棕色': 'kahverengi',
    '踪迹': 'iz; ayak izi; işaret',
    '总而言之': 'kısacası; bir sözle',
    '总和': 'toplam; yekün',
    '纵横': 'özgürce hareket edebilmek; uzunluk ve genişlik',
    '走廊': 'koridor; geçit',
    '走漏': 'sızdırmak (bilgi, sıvı vb.); ifşa etmek',
    '走私': 'kaçakçılık yapmak',
    '揍': 'dövmek; vurmak (gayri resmi)',
    '租赁': 'kiralamak; kiralama',
    '足以': 'yeterli; çok büyük ölçüde; yeterince',
    '阻碍': 'engellemek; mani olmak',
    '阻拦': 'durdurmak; engellemek; tıkamak',
    '阻挠': 'engellemek; direnmek; yolunu tıkamak',
    '祖父': 'baba tarafından büyükbaba',
    '祖国': 'vatan; anayurt',
    '祖先': 'ata; cet',
    '钻研': 'yoğun olarak çalışmak; derinlemesine incelemek',
    '钻石': 'elmas',
    '嘴唇': 'dudak',
    '罪犯': 'suçlu; cani',
    '尊严': 'onur; kutsallık; itibar',
    '遵循': 'uymak; takip etmek',
    '作弊': 'hile yapmak; kopya çekmek',
    '作废': 'iptal etmek; hükümsüz kılmak; geçerliliğini yitirmek',
    '作风': 'çalışma tarzı; biçim',
    '作息': 'çalışmak ve dinlenmek',
    '座右铭': 'motto; düstur',
    '做主': 'karar vermek; karar sorumluluğunu üstlenmek',
}

with open(DART_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

COUNT = [0]

def replace_tr(m):
    full = m.group(0)
    simp = m.group(1)
    tr_val = TR.get(simp, '')
    if not tr_val:
        return full
    COUNT[0] += 1
    tr_escaped = tr_val.replace("'", "\\'")
    return full[:-4] + f"'{tr_escaped}'],"

pattern = r"\['((?:[^'\\]|\\.)*)',\s*'(?:[^'\\]|\\.)*',\s*'(?:[^'\\]|\\.)*',\s*'(?:[^'\\]|\\.)*',\s*''\],"
result = re.sub(pattern, replace_tr, content)

with open(DART_FILE, 'w', encoding='utf-8') as f:
    f.write(result)

print(f'Done — {COUNT[0]} entries updated.')
