#!/usr/bin/env python3
"""Add Turkish translations to HSK6 entries 1001-2000 (竞选 → 消防)."""
import re

DART_FILE = r'd:\Masaustu\github\Kandao\lib\core\constants\hsk6_words.dart'

TR = {
    '竞选': 'seçim kampanyası yürütmek',
    '敬礼': 'selam vermek',
    '敬业': 'işine bağlı olmak',
    '境界': 'sınır; alan; seviye',
    '镜头': 'kamera planı; lens',
    '纠纷': 'anlaşmazlık; uyuşmazlık',
    '纠正': 'düzeltmek',
    '酒精': 'alkol; etanol',
    '救济': 'acil yardım; kurtarma',
    '就近': 'yakınında',
    '就业': 'istihdam; iş bulmak',
    '就职': 'göreve başlamak',
    '拘留': 'gözaltına almak; tutuklamak',
    '拘束': 'kısıtlamak; çekingen',
    '居民': 'sakin; ikamet eden',
    '居住': 'ikamet etmek; yaşamak',
    '鞠躬': 'eğilmek; reverans yapmak',
    '局部': 'kısmi; yerel',
    '局面': 'durum; görünüm',
    '局势': 'durum; hal',
    '局限': 'sınırlamak; kısıtlamak',
    '咀嚼': 'çiğnemek',
    '沮丧': 'cesareti kırık; morali bozuk',
    '举动': 'hareket; eylem',
    '举世瞩目': 'tüm dünyanın dikkatini çekmek',
    '举足轻重': 'kilit öneme sahip olmak',
    '剧本': 'senaryo; oyun metni',
    '剧烈': 'şiddetli; sert',
    '据悉': 'haberlere göre',
    '聚精会神': 'dikkatini toplamak',
    '卷': 'rulo; sarmak',
    '决策': 'karar vermek; politika belirlemek',
    '觉悟': 'bilinç; farkındalık',
    '觉醒': 'uyanmak; farkına varmak',
    '绝望': 'umutsuzluk; çaresizlik',
    '倔强': 'inatçı; boyun eğmez',
    '军队': 'ordu; kuvvetler',
    '君子': 'centilmen; asil kişi',
    '卡通': 'karikatür; çizgi film',
    '开采': 'çıkarmak; işletmek (maden)',
    '开除': 'ihraç etmek; çıkarmak',
    '开阔': 'geniş; açık',
    '开朗': 'neşeli; iyimser',
    '开明': 'aydın; açık fikirli',
    '开辟': 'açmak; kurmak',
    '开拓': 'yeni alan açmak; geliştirmek',
    '开展': 'geliştirmeye başlamak; başlatmak',
    '开支': 'harcama; masraf',
    '刊登': 'gazete veya dergide yayımlamak',
    '刊物': 'yayın; dergi',
    '勘探': 'keşif; arama',
    '侃侃而谈': 'sakin ve ölçülü konuşmak',
    '砍伐': 'kesmek; devirmek (ağaç)',
    '看待': 'bakmak; değerlendirmek',
    '慷慨': 'cömert; coşkulu',
    '扛': 'omzunda taşımak',
    '抗议': 'protesto etmek',
    '考察': 'incelemek; araştırmak',
    '考古': 'arkeoloji',
    '考核': 'sınav; denetlemek',
    '考验': 'sınamak; test etmek',
    '靠拢': 'yaklaşmak; birleşmek',
    '科目': 'okul dersi; konu',
    '磕': 'vurmak; dokunmak',
    '可观': 'önemli miktarda; etkileyici',
    '可口': 'lezzetli; tadı güzel',
    '可恶': 'iğrenç; nefret uyandıran',
    '可行': 'uygulanabilir; mümkün',
    '渴望': 'özlemek; arzulamak',
    '克制': 'kendini tutmak; kontrol etmek',
    '刻不容缓': 'acil müdahale gerektirmek; ertelenmez',
    '客户': 'müşteri; hesap sahibi',
    '课题': 'görev; konu; tartışma sorusu',
    '恳切': 'samimi; içten',
    '啃': 'kemirmek; ısırmak',
    '坑': 'çukur; delik; dolandırmak',
    '空洞': 'boş; içeriksiz',
    '空前绝后': 'eşi görülmemiş ve tekrarlanamaz',
    '空想': 'hayal kurmak; kuruntu',
    '空虚': 'boş; anlamsız',
    '孔': 'delik; gözenek',
    '恐怖': 'korku; terör',
    '恐吓': 'tehdit etmek',
    '恐惧': 'korku; fobi',
    '空白': 'boşluk; boş alan',
    '空隙': 'yarık; aralık',
    '口气': 'konuşma tonu; söyleyiş biçimi',
    '口腔': 'ağız boşluğu',
    '口头': 'sözlü; sözel',
    '口音': 'aksan',
    '扣': 'iliştirmek; düğmelemek; tutuklamak',
    '枯萎': 'solmak; kurumak',
    '枯燥': 'sıkıcı; monoton',
    '哭泣': 'ağlamak; sızlamak',
    '苦尽甘来': 'acı bittikten sonra tatlı gelir',
    '苦涩': 'acı ve buruk; acı verici',
    '挎': 'omzunda veya yanında taşımak',
    '跨': 'adımlamak; aşmak; geçmek',
    '快活': 'mutlu; neşeli',
    '宽敞': 'geniş; ferah',
    '宽容': 'hoşgörülü; müsamahalı',
    '款待': 'konuk ağırlamak; ikram etmek',
    '款式': 'desen; stil; model',
    '筐': 'sepet',
    '旷课': 'okulu asmak; dersi kesmek',
    '况且': 'üstelik; ayrıca; bunun yanı sıra',
    '矿产': 'maden; mineral',
    '框架': 'çerçeve; iskelet',
    '亏待': 'haksız davranmak',
    '亏损': 'zarar; açık (mali)',
    '捆绑': 'bağlamak; hapsetmek',
    '扩充': 'genişletmek; artırmak',
    '扩散': 'yayılmak; yaymak',
    '扩张': 'genişleme; büyüme',
    '喇叭': 'boru; trompet; hoparlör',
    '蜡烛': 'mum',
    '啦': 'cümle sonu partiküli',
    '来历': 'geçmiş; köken; tarihçe',
    '来源': 'kaynak; kaynaklanmak',
    '栏目': 'köşe yazısı; sütun',
    '懒惰': 'tembel; aylak',
    '狼狈': 'zor durumda; çıkmaza sıkışmış',
    '狼吞虎咽': 'aç kurt gibi yemek; oburcasına yemek',
    '捞': 'balık avlamak; çekip çıkarmak',
    '牢固': 'sağlam; güvenli',
    '牢骚': 'şikayet; sızlanma',
    '唠叨': 'gevezelik etmek; sürekli tekrarlamak',
    '乐趣': 'zevk; keyif; eğlence',
    '乐意': 'memnuniyetle yapmak; istekli',
    '雷达': 'radar',
    '类似': 'benzer; analoji',
    '冷酷': 'acımasız; katı yürekli',
    '冷落': 'soğuk davranmak; görmezden gelmek',
    '冷却': 'soğumak; serinlemek',
    '愣': 'şaşırmak; donakalmak',
    '黎明': 'şafak; gün doğumu',
    '礼节': 'görgü kuralları; nezaket',
    '礼尚往来': 'nezaket karşılık gerektirir',
    '里程碑': 'kilometre taşı; dönüm noktası',
    '理睬': 'ilgilenmek; dikkat etmek',
    '理所当然': 'tabii ki; doğal olarak',
    '理直气壮': 'haklı olduğunda cesur ve güvenli olmak',
    '理智': 'akıl; mantık; rasyonel',
    '力求': 'elinden geleni yapmak; çabalamak',
    '力所能及': 'gücü yettiğince; yapabildiği kadar',
    '力争': 'sert tartışmak; uğrunda mücadele etmek',
    '历代': 'ardışık hanedanlar; geçmiş dönemler',
    '历来': 'her zaman; tarih boyunca',
    '立场': 'tutum; duruş; görüş',
    '立方': 'küp; hacim birimi',
    '立交桥': 'köprülü kavşak; üst geçit',
    '立体': 'üç boyutlu; katı cisim',
    '立足': 'bir yerde durmak; köklenmek',
    '利害': 'ciddi; önemli; avantaj ve dezavantajlar',
    '例外': 'istisna',
    '粒': 'tanecik; tane; ölçü birimi',
    '连年': 'art arda yıllar; yıllarca',
    '连锁': 'zincir (mağaza); birbirine bağlı',
    '连同': 'birlikte; ile birlikte',
    '联欢': 'birlikte eğlenmek',
    '联络': 'iletişim; temas kurmak',
    '联盟': 'ittifak; birlik; koalisyon',
    '联想': 'çağrışım; zihinsel bağlantı kurmak',
    '廉洁': 'dürüst; yolsuzluğa bulaşmamış',
    '良心': 'vicdan',
    '谅解': 'anlayış; hoşgörü; affetmek',
    '晾': 'havada veya güneşte kurutmak',
    '辽阔': 'geniş; engin',
    '列举': 'liste yapmak; saymak; sıralamak',
    '临床': 'klinik',
    '淋': 'ıslatmak; damlamak',
    '吝啬': 'cimri; pinti',
    '伶俐': 'zeki; kurnaz; akıllı',
    '灵感': 'ilham; yaratıcı düşünce',
    '灵魂': 'ruh; vicdan',
    '灵敏': 'hassas; duyarlı',
    '凌晨': 'sabahın erken saatleri; gece yarısı sonrası',
    '零星': 'dağınık; parçalı; sporadik',
    '领会': 'anlamak; kavramak',
    '领事馆': 'konsolosluk',
    '领土': 'toprak; ülke',
    '领悟': 'kavramak; anlamak',
    '领先': 'önde olmak; başı çekmek',
    '领袖': 'lider',
    '溜': 'kaymak; gizlice kaçmak',
    '留恋': 'ayrılmak istemeyerek bağlı olmak',
    '留念': 'hatıra olarak saklamak',
    '留神': 'dikkat etmek; tedbirli olmak',
    '流浪': 'serserilik etmek; dolaşmak',
    '流露': 'ifade etmek; hissini ortaya koymak',
    '流氓': 'aşağılık kişi; kabadayı',
    '流通': 'dolaşım; para dolaşımı',
    '聋哑': 'sağır ve dilsiz',
    '隆重': 'görkemli; törensel',
    '垄断': 'tekel',
    '笼罩': 'örtmek; sarmalamak',
    '搂': 'sarılmak; kucaklamak',
    '炉灶': 'ocak; mutfak sobası',
    '屡次': 'defalarca; tekrar tekrar',
    '履行': 'yerine getirmek; ifa etmek',
    '掠夺': 'yağmalamak; soymak',
    '轮船': 'vapur; buharlı gemi',
    '轮廓': 'siluet; dış hat',
    '轮胎': 'lastik; tekerlek',
    '论坛': 'forum',
    '论证': 'kanıtlamak; tartışmak',
    '啰唆': 'gereksiz yere uzun; laf kalabalığı',
    '络绎不绝': 'aralıksız akış',
    '落成': 'inşaatı tamamlamak',
    '落实': 'uygulanabilir; hayata geçirmek',
    '麻痹': 'felç; uyuşma',
    '麻木': 'uyuşmuş; hissizleşmiş',
    '麻醉': 'anestezi',
    '码头': 'liman; iskele',
    '蚂蚁': 'karınca',
    '嘛': 'tabii ki; şüphesiz',
    '埋伏': 'pusu; pusuya yatmak',
    '埋没': 'gömmek; ihmal etmek',
    '埋葬': 'gömmek; defnetmek',
    '迈': 'adım atmak; ileri gitmek',
    '脉搏': 'nabız; atım',
    '埋怨': 'şikayet etmek; suçlamak',
    '蔓延': 'yayılmak; uzamak',
    '漫长': 'çok uzun; sonsuz',
    '漫画': 'çizgi roman; manga',
    '慢性': 'kronik (hastalık); yavaş ve sabırlı',
    '忙碌': 'meşgul olmak; koşturmak',
    '盲目': 'körlemesine; amaçsız',
    '茫茫': 'uçsuz bucaksız; belirsiz',
    '茫然': 'bilgisiz; farkında olmayan',
    '茂盛': 'bereketli; canlı (bitki)',
    '冒充': 'kendini başkası gibi göstermek; taklit etmek',
    '冒犯': 'gücendirmek; saldırmak',
    '枚': 'ölçü birimi (madeni para, madalya için)',
    '媒介': 'araç; medya',
    '美观': 'güzel; estetik',
    '美满': 'mutlu; mesut',
    '美妙': 'harika; muhteşem',
    '萌芽': 'filiz; tomurcuk; tohum',
    '猛烈': 'şiddetli; sert; kuvvetli',
    '眯': 'gözlerini kısmak; şekerleme yapmak',
    '弥补': 'telafi etmek; karşılamak',
    '弥漫': 'doldurmak; yaymak; kaplamak',
    '迷惑': 'şaşırtmak; yanıltmak',
    '迷人': 'büyüleyici; etkileyici',
    '迷信': 'batıl inanç; hurafeler',
    '谜语': 'bilmece; bulmaca',
    '密度': 'yoğunluk; kıvam',
    '密封': 'mühürlemek; hava geçirmez kapatmak',
    '棉花': 'pamuk',
    '免得': 'ki olmasın; önlemek için',
    '免疫': 'bağışıklık',
    '勉励': 'teşvik etmek; cesaret vermek',
    '勉强': 'isteksizce; zorla yaptırmak',
    '面貌': 'görünüş; yüz hatları',
    '面子': 'yüz; itibar; prestij',
    '描绘': 'tasvir etmek; betimlemek',
    '瞄准': 'nişan almak',
    '渺小': 'küçük; önemsiz; ufak',
    '藐视': 'küçümsemek; hor görmek',
    '灭亡': 'yok olmak; imha olmak',
    '蔑视': 'hor görmek; küçümsemek',
    '民间': 'halk arasında; geleneksel; folklorik',
    '民主': 'demokrasi',
    '敏捷': 'çevik; hızlı; zeki',
    '敏锐': 'keskin; sivri; duyarlı',
    '名次': 'sıralama; derece',
    '名额': 'kota; belirli sayıda kişi',
    '名副其实': 'gerçekten; sadece isimde değil gerçekte de',
    '名誉': 'şöhret; itibar; onur',
    '明明': 'açıkça; belli ki; şüphesiz',
    '明智': 'akıllıca; bilgece',
    '命名': 'isimlendirmek; ad koymak',
    '摸索': 'el yordamıyla aramak; yolunu bulmak',
    '模范': 'model; örnek kişi',
    '模式': 'model; desen; yöntem',
    '模型': 'model; kalıp; maket',
    '膜': 'zar; film',
    '摩擦': 'sürtünme; çatışma',
    '磨合': 'birbirine alışmak; çalıştırarak ayarlamak',
    '魔鬼': 'şeytan; iblis; canavar',
    '魔术': 'sihir; büyü',
    '抹杀': 'silip süpürmek; yok etmek',
    '莫名其妙': 'tuhaf; anlaşılmaz; açıklanamaz',
    '墨水儿': 'mürekkep',
    '默默': 'sessizce; söylemeden',
    '谋求': 'aramak; elde etmeye çalışmak',
    '模样': 'görünüş; biçim; yaklaşık',
    '母语': 'ana dili',
    '目睹': 'gözlemlemek; doğrudan görmek',
    '目光': 'bakış; görme',
    '沐浴': 'banyo yapmak; dalmak',
    '拿手': 'mahir; becerikli',
    '纳闷儿': 'şaşkın olmak; hayret etmek',
    '耐用': 'dayanıklı',
    '南辕北辙': 'amacın tam tersini yapmak',
    '难得': 'elde etmesi zor; nadir',
    '难堪': 'zor olmak; utandırıcı',
    '难能可贵': 'takdire değer; olağanüstü iyi',
    '恼火': 'kızmak; sinirlendirilmek',
    '内涵': 'anlam; içerik; içsellik',
    '内幕': 'perde arkası; gizli bilgi',
    '内在': 'içsel; doğuştan gelen',
    '能量': 'enerji; kapasite',
    '拟定': 'taslak hazırlamak; planlamak',
    '逆行': 'trafiğe ters gitmek; gerilemek',
    '年度': 'yıllık; takvim yılı',
    '捏': 'sıkıştırmak; yoğurmak',
    '凝固': 'katılaşmak; donmak',
    '凝聚': 'bir araya gelmek; bütünleşmek',
    '凝视': 'dalmak; bakakalmak',
    '拧': 'bükmek; sıkıştırmak',
    '宁肯': 'tercih etmek; daha iyi olur',
    '宁愿': 'tercih etmek; daha iyi',
    '扭转': 'tersine çevirmek; durumu kurtarmak',
    '纽扣儿': 'düğme',
    '农历': 'Çin takvimi; Ay takvimi',
    '浓厚': 'yoğun; kalın (sis, bulut)',
    '奴隶': 'köle',
    '虐待': 'istismar etmek; kötü muamele etmek',
    '挪': 'kaydırmak; taşımak',
    '哦': 'oh (anlama belirtir)',
    '殴打': 'dövmek; yumruklamak',
    '呕吐': 'kusma; mide bulantısı',
    '偶像': 'idol; put',
    '趴': 'yüzüstü yatmak',
    '排斥': 'reddetmek; itmek; dışlamak',
    '排除': 'elemek; kaldırmak; ortadan kaldırmak',
    '排放': 'salmak; yaymak (emisyon)',
    '排练': 'prova yapmak',
    '徘徊': 'öylece dolaşmak; kararsız kalmak',
    '派别': 'mezhep; grup; ekol; hizip',
    '派遣': 'göndermek (görevle); sevk etmek',
    '攀登': 'tırmanmak; çıkmak',
    '盘旋': 'dönmek; sarmal çizmek; dolaşmak',
    '判决': 'mahkeme kararı; karar vermek',
    '畔': 'nehir kıyısı; kenar; sınır',
    '庞大': 'dev; kocaman; muazzam',
    '抛弃': 'terk etmek; bırakmak',
    '泡沫': 'köpük; kabarcık; ekonomik balon',
    '培育': 'yetiştirmek; yetiştirip geliştirmek',
    '配备': 'donatmak; temin etmek',
    '配偶': 'eş; yaşam ortağı',
    '配套': 'tam set oluşturmak',
    '盆地': 'havza',
    '烹饪': 'yemek pişirme; mutfak sanatı',
    '捧': 'iki eliyle tutmak',
    '批发': 'toptan satmak',
    '批判': 'eleştirmek; eleştiri',
    '劈': 'ikiye bölmek; yarılmak',
    '皮革': 'deri; kösele',
    '疲惫': 'yorgun; bitkin',
    '疲倦': 'yorgun; bitap',
    '屁股': 'popo; kıç',
    '譬如': 'örneğin; mesela',
    '偏差': 'önyargı; sapma',
    '偏见': 'önyargı',
    '偏僻': 'ücra; şehirden uzak',
    '偏偏': 'beklenmedik şekilde; tersine',
    '片断': 'parça; kesit; alıntı',
    '片刻': 'kısa süre',
    '漂浮': 'yüzmek; sallanmak; sürüklenmek',
    '飘扬': 'dalgalanmak; sallanmak (bayrak gibi)',
    '撇': 'sola eğri vuruş; fırlatmak',
    '拼搏': 'mücadele etmek; uğraşmak',
    '拼命': 'canını tehlikeye atmak; çılgınca',
    '贫乏': 'yetersiz; eksik',
    '贫困': 'yoksul; fakir',
    '频繁': 'sık sık; çok kez',
    '频率': 'frekans; sıklık',
    '品尝': 'tatmak; denemek',
    '品德': 'ahlaki karakter; erdem',
    '品质': 'kalite; karakter',
    '品种': 'cins; çeşit',
    '平凡': 'sıradan; olağan',
    '平面': 'düzlem; yüzey',
    '平坦': 'düz; düzlük',
    '平行': 'paralel; eş zamanlı',
    '平庸': 'vasat; orta',
    '平原': 'ova; düzlük',
    '评估': 'değerlendirmek',
    '评论': 'yorum yapmak; tartışmak',
    '屏幕': 'ekran',
    '屏障': 'duvar; bariyer; koruyucu',
    '坡': 'eğim; yokuş',
    '泼': 'dökmek; saçmak; kaba ve mantıksız',
    '颇': 'oldukça; biraz',
    '迫不及待': 'sabırsızlıkla beklemek',
    '迫害': 'zulmetmek; baskı altına almak',
    '破例': 'istisna yapmak',
    '魄力': 'cesaret; kararlılık; yüreklilik',
    '扑': 'saldırmak; üzerine atlamak',
    '铺': 'yaymak; sermek; dükkan; yatak',
    '朴实': 'sade; doğal; yere basımlı',
    '朴素': 'sade; basit; tutumluluk',
    '普及': 'yaygın; yaygınlaştırmak',
    '瀑布': 'şelale; çağlayan',
    '凄凉': 'ıssız; terk edilmiş hissi',
    '期望': 'umut; beklenti',
    '期限': 'son tarih; süre',
    '欺负': 'zorbalık etmek; korkutmak',
    '欺骗': 'aldatmak; kandırmak',
    '齐全': 'eksiksiz; tam',
    '齐心协力': 'ortak çaba göstermek',
    '奇妙': 'harika; fantastik',
    '歧视': 'ayrımcılık yapmak',
    '旗袍': 'cheongsam; Çin geleneksel elbisesi',
    '旗帜': 'bayrak; flama',
    '乞丐': 'dilenci',
    '岂有此理': 'inanılmaz; saçma; mantıksız',
    '企图': 'teşebbüs etmek; planlamak',
    '启程': 'yola koyulmak; seyahate başlamak',
    '启蒙': 'aydınlatmak; gençleri eğitmek',
    '启示': 'aydınlanma; vahiy',
    '启事': 'duyuru; ilan',
    '起草': 'taslak hazırlamak; yazmak',
    '起初': 'başlangıçta; ilk önce',
    '起伏': 'iniş çıkış; dalgalanma',
    '起哄': 'kalabalık oluşturmak; kargaşa çıkarmak',
    '起码': 'en az; asgari',
    '起源': 'köken; kaynaklanmak',
    '气概': 'yiğitlik; ruh; gözüpeklik',
    '气功': 'nefes egzersizi sistemi; qi gong',
    '气魄': 'ruh; cesaret; yüreklilik',
    '气色': 'ten rengi; sağlık görünümü',
    '气势': 'etkileyici tavır; güçlü görünüm',
    '气味': 'koku; iz',
    '气象': 'meteoroloji; atmosfer',
    '气压': 'atmosferik basınç; barometrik basınç',
    '气质': 'mizaç; karakter',
    '迄今为止': 'bugüne kadar; şimdiye dek',
    '器材': 'ekipman; malzeme',
    '器官': 'organ; sistem',
    '掐': 'koparmak; sıkıştırmak',
    '洽谈': 'görüşmek; müzakere etmek',
    '恰当': 'uygun; yerinde; doğru',
    '恰到好处': 'tam yerinde; tam doğru',
    '恰巧': 'tesadüfen; rastlantıyla',
    '千方百计': 'her yolu denemek; mümkün olan her yolla',
    '迁就': 'pes etmek; uyum sağlamak; kollamak',
    '迁徙': 'göç etmek; yer değiştirmek',
    '牵': 'götürmek; çekmek',
    '牵扯': 'karıştırmak; içine çekmek',
    '牵制': 'kontrol etmek; sınırlamak',
    '谦逊': 'alçakgönüllü; mütevazı',
    '签署': 'imzalamak (anlaşma)',
    '前景': 'görünüm; gelecek beklentileri',
    '前提': 'önkoşul; varsayım',
    '潜力': 'potansiyel; kapasite',
    '潜水': 'dalmak; suya dalmak',
    '潜移默化': 'farkında olmadan etkilemek; sinsi etki',
    '谴责': 'kınamak; mahkum etmek',
    '强制': 'zorlamak; baskı yapmak',
    '抢劫': 'soymak; yağmalamak',
    '抢救': 'kurtarmak; imdada yetişmek',
    '强迫': 'zorlamak; baskı uygulamak',
    '桥梁': 'köprü',
    '窍门': 'özel numara; sır',
    '翘': 'yukarı kalkmak; bükülmek',
    '切实': 'gerçekçi; uygulanabilir; özenle',
    '锲而不舍': 'azimle çalışmak; vazgeçmemek',
    '钦佩': 'hayran olmak; saygı duymak',
    '侵犯': 'ihlal etmek; saldırmak',
    '侵略': 'istila; saldırı; işgal',
    '亲密': 'yakın; samimi; tanıdık',
    '亲热': 'samimi; sevecen; sıcak',
    '勤俭': 'çalışkan ve tutumlu',
    '勤劳': 'çalışkan; gayretli',
    '倾听': 'dikkatlice dinlemek; fikirlere kulak vermek',
    '倾向': 'eğilim; meyil',
    '倾斜': 'eğmek; yatırmak',
    '清澈': 'berrak; saf',
    '清晨': 'sabahın erken saatleri',
    '清除': 'yok etmek; kaldırmak',
    '清洁': 'temiz; pis olmayan',
    '清理': 'düzeltmek; temizlemek; kontrol etmek',
    '清晰': 'net; belirgin; açık',
    '清醒': 'uyanık; ayık; bilinci yerinde',
    '清真': 'İslami; helal; Müslümanlara ait',
    '情报': 'istihbarat; bilgi toplama',
    '情节': 'olay örgüsü; koşullar',
    '情理': 'akıl; mantık',
    '情形': 'durum; hal',
    '晴朗': 'güneşli ve bulutsuz',
    '请柬': 'davetiye; yazılı davet',
    '请教': 'danışmak; tavsiye almak',
    '请示': 'talimat istemek',
    '请帖': 'davetiye; yazılı davet',
    '丘陵': 'tepeler',
    '区分': 'ayırt etmek; farkını bulmak',
    '区域': 'alan; bölge; ilçe',
    '曲折': 'virajlı; karmaşık; kıvrımlı',
    '驱逐': 'sürgün etmek; kovmak; sınır dışı etmek',
    '屈服': 'boyun eğmek; teslim olmak',
    '渠道': 'sulama kanalı; iletişim kanalı',
    '曲子': 'halk türküsü; melodi',
    '取缔': 'yasaklamak; bastırmak',
    '趣味': 'eğlence; zevk; tat',
    '圈套': 'tuzak',
    '权衡': 'ödünleşim; avantaj ve dezavantajları tartmak',
    '权威': 'otorite; yetkili',
    '全局': 'genel durum; büyük resim',
    '全力以赴': 'var gücüyle çaba göstermek',
    '拳头': 'yumruk',
    '犬': 'köpek',
    '缺口': 'boşluk; gedik; açık',
    '缺席': 'devamsızlık; yokluk; gıyap',
    '缺陷': 'kusur; hata; bozukluk',
    '瘸': 'topal',
    '确保': 'sağlamak; garanti etmek',
    '确立': 'kurmak; tesis etmek',
    '确切': 'kesin; tam; doğru',
    '确信': 'emin olmak; kesinlikle inanmak',
    '群众': 'kitleler; halk çoğunluğu',
    '染': 'boyamak; hastalık kapmak',
    '嚷': 'bağırmak; haykırmak',
    '让步': 'geri adım atmak; taviz vermek',
    '饶恕': 'affetmek; bağışlamak',
    '扰乱': 'rahatsız etmek; karıştırmak',
    '惹祸': 'belaya girmek; bela çıkarmak',
    '热泪盈眶': 'gözleri yaşla dolmak; çok etkilenmek',
    '热门': 'popüler; rağbette',
    '人道': 'insancıllık; insanî',
    '人格': 'kişilik; dürüstlük',
    '人工': 'yapay; insan eli; manüel iş',
    '人家': 'başkaları; aile; hane',
    '人间': 'dünya; insanların dünyası',
    '人士': 'kişi; kamuya mal olmuş kişi',
    '人为': 'yapay; insan yapımı',
    '人性': 'insan doğası; insanlık',
    '人质': 'rehine',
    '仁慈': 'iyicil; yürekli; hayırsever',
    '忍耐': 'sabretmek; dayanmak; tahammül etmek',
    '忍受': 'katlanmak; tahammül etmek',
    '认定': 'kanaat getirmek; kesinlikle inanmak',
    '认可': 'onaylamak; kabul etmek',
    '任命': 'atamak; göreve getirmek',
    '任性': 'inatçı; keyfi davranan',
    '任意': 'keyfi; rastgele; dilediği gibi',
    '任重道远': 'uzun yolda ağır sorumluluk',
    '仍旧': 'hâlâ; yine de; aynı şekilde',
    '日新月异': 'her geçen gün değişmek',
    '日益': 'günden güne; giderek daha fazla',
    '荣幸': 'şeref duymak; onurlanmak',
    '荣誉': 'onur; şan; şeref',
    '容貌': 'yüz görünümü; fiziksel görünüş',
    '容纳': 'kapsamak; barındırmak; katlanmak',
    '容器': 'kap; kaba; kabız',
    '容忍': 'tahammül etmek; hoşgörmek',
    '溶解': 'çözülmek; çözmek',
    '融化': 'erimek; çözülmek; kaynaşmak',
    '融洽': 'uyumlu; dostane ilişkiler',
    '柔和': 'yumuşak; nazik; hafif',
    '揉': 'yoğurmak; ovuşturmak',
    '儒家': 'Konfüçyüsçülük',
    '若干': 'bir miktar; birkaç',
    '弱点': 'zayıf nokta; zafiyet',
    '撒谎': 'yalan söylemek',
    '散文': 'nesir; deneme',
    '散布': 'yaymak; dağıtmak',
    '散发': 'dağıtmak; yaymak; salmak',
    '丧失': 'kaybetmek; yitirmek',
    '骚扰': 'taciz etmek; rahatsız etmek; kargaşa çıkarmak',
    '嫂子': 'ağabey eşi; görümce',
    '刹车': 'fren yapmak; durdurmak',
    '啥': '(konuşma dili) ne',
    '筛选': 'süzmek; elemek',
    '山脉': 'dağ silsilesi',
    '闪烁': 'titremek; parlamak; titrek ışık vermek',
    '擅长': 'iyi olmak; uzman olmak',
    '擅自': 'yetkisiz; izinsiz',
    '伤脑筋': 'sıkıntılı; baş belası',
    '商标': 'marka; ticari marka',
    '上级': 'üst amir; yetkili',
    '上进': 'ilerleme kaydetmek; daha iyi yapmak',
    '上任': 'göreve başlamak',
    '上瘾': 'bağımlı olmak; alışkanlık edinmek',
    '上游': 'nehrin üst kısmı; ileri konum',
    '尚且': 'yine de; hatta; dahi',
    '捎': 'yanında götürmek; iletmek',
    '梢': 'dal ucu; uç',
    '哨': 'düdük; nöbet yeri',
    '奢侈': 'lüks; israf; gösteriş',
    '舌头': 'dil (vücut organı)',
    '设立': 'kurmak; tesis etmek',
    '设想': 'hayal etmek; düşünmek; taslak plan',
    '设置': 'kurmak; yerleştirmek',
    '社区': 'topluluk; mahalle',
    '涉及': 'içermek; değinmek; ilgili olmak',
    '摄氏度': 'Santigrat derece',
    '申报': 'bildirmek; beyan etmek',
    '呻吟': 'inlemek; sızlanmak',
    '绅士': 'centilmen',
    '深奥': 'derin; gizemli',
    '深沉': 'derin; ağır; çok ciddi',
    '深情厚谊': 'derin dostluk',
    '神经': 'sinir',
    '神奇': 'mucizevi; sihirli',
    '神气': 'ifade; hali; hareketli',
    '神圣': 'kutsal; ilahi',
    '神态': 'görünüm; ifade; tavır',
    '神仙': 'Taoist ölümsüz; üstün varlık',
    '审查': 'incelemek; soruşturmak; sansür',
    '审理': 'davayı dinlemek; yargılamak',
    '审美': 'estetik duygusu; sanat anlayışı',
    '审判': 'yargılamak; yargı',
    '渗透': 'sızmak; nüfuz etmek',
    '慎重': 'ihtiyatlı; dikkatli; temkinli',
    '生存': 'var olmak; hayatta kalmak',
    '生机': 'yaşam gücü; canlılık',
    '生理': 'fizyoloji',
    '生疏': 'yabancı; yabancılaşmış; paslanmış',
    '生态': 'yaşam tarzı; ekoloji',
    '生物': 'canlı; yaratık; organizma',
    '生肖': 'Çin burçları',
    '生效': 'yürürlüğe girmek; geçerli olmak',
    '生锈': 'paslanmak',
    '生育': 'doğurmak; yetiştirmek; çocuk büyütmek',
    '声明': 'açıklama; bildirmek; ilan etmek',
    '声势': 'ivme; şöhret ve güç',
    '声誉': 'itibar; şöhret',
    '牲畜': 'evcil hayvanlar; çiftlik hayvanları',
    '省会': 'il başkenti',
    '胜负': 'galibiyet ya da yenilgi',
    '盛产': 'bol miktarda üretmek; bereketli',
    '盛开': 'çiçek açmak; tam çiçekte',
    '盛情': 'büyük nezaket; sınırsız konukseverlik',
    '盛行': 'modaya uygun; yaygın; hâkim olmak',
    '尸体': 'ölü beden; ceset',
    '失事': 'kazaya karışmak; kaza geçirmek',
    '失误': 'hata; kayıp; eksiklik',
    '失踪': 'kayıp olmak; iz bırakmadan kaybolmak',
    '师范': 'öğretmen yetiştiren; pedagojik; normal okul',
    '施加': 'uygulamak (baskı veya çaba)',
    '施展': 'tam olarak kullanmak; yeteneklerini kullanmak',
    '十足': 'tam; eksiksiz; yüzde yüz',
    '石油': 'petrol; ham yağ',
    '时常': 'arada sırada; sık sık',
    '时而': 'ara sıra; zaman zaman',
    '时光': 'zaman; dönem; süre',
    '时机': 'uygun an; fırsat',
    '时事': 'güncel olaylar; gündem',
    '识别': 'tanımlamak; ayırt etmek',
    '实惠': 'somut maddi fayda; avantajlı',
    '实力': 'güç; kuvvet',
    '实施': 'uygulamak; hayata geçirmek',
    '实事求是': 'gerçekçi ve pratik olmak; gerçeği aramak',
    '实行': 'uygulamak; pratiğe dökmek',
    '实质': 'öz; gerçek; asıl mesele',
    '拾': 'almak; on (bankacılık rakamı)',
    '使命': 'görev; misyon',
    '示范': 'gösteri yapmak; yol göstermek',
    '示威': 'protesto gösterisi yapmak',
    '示意': 'işaret etmek; ima etmek; göstermek',
    '世代': 'nesiller boyu; kuşaktan kuşağa',
    '势必': 'kaçınılmaz olarak gerçekleşecek',
    '势力': 'güç; nüfuz',
    '事故': 'kaza',
    '事迹': 'başarı; eylem',
    '事件': 'olay; vaka',
    '事态': 'durum; mevcut hal',
    '事务': 'işler; görevler',
    '事项': 'mesele; kalem',
    '事业': 'girişim; proje; dava; işletme',
    '试图': 'denemek; teşebbüs etmek',
    '试验': 'deney; test',
    '视力': 'görme gücü; göz',
    '视频': 'video',
    '视线': 'görüş hattı',
    '视野': 'görüş alanı',
    '是非': 'doğru ve yanlış; hakikat ve kurgu; anlaşmazlık',
    '适宜': 'uygun; münasip',
    '逝世': 'vefat etmek; ölmek',
    '释放': 'serbest bırakmak; salıvermek',
    '收藏': 'toplamak; saklamak',
    '收缩': 'geri çekilmek; büzülmek',
    '收益': 'kazanç; kâr',
    '收音机': 'radyo',
    '手法': 'teknik; numara; beceri',
    '手势': 'jest; işaret',
    '手艺': 'zanaat; el işi becerisi',
    '守护': 'korumak; savunmak',
    '首饰': 'takı; mücevher',
    '首要': 'en önemli; başlıca; temel',
    '受罪': 'sıkıntı çekmek; zor zamanlar geçirmek',
    '授予': 'vermek; ödüllendirmek',
    '书法': 'hat; yazı sanatı',
    '书籍': 'kitaplar; eserler',
    '书记': 'sekreter; katip',
    '书面': 'yazılı; yazılı (garanti vb.)',
    '舒畅': 'mutlu; hiçbir endişesi olmayan',
    '疏忽': 'ihmal etmek; gözden kaçırmak; dikkatsizlik',
    '疏远': 'uzaklaşmak; soğumak',
    '束': 'bağlamak; demet; salkım için ölçü birimi',
    '束缚': 'bağlamak; kısıtlamak',
    '树立': 'kurmak; tesis etmek',
    '竖': 'dikey; dikmek; dikey çizgi',
    '数额': 'miktar; para miktarı',
    '耍': 'oynamak; hokkabazlık yapmak',
    '衰老': 'yaşlanmak; yaşlılık; zayıflamak',
    '衰退': 'düşmek; gerileme; azalmak',
    '率领': 'komuta etmek; önderlik etmek',
    '涮火锅': 'hot pot\'ta pişirmek (et, sebze vb.)',
    '双胞胎': 'ikizler',
    '爽快': 'dinç; samimi; açık sözlü',
    '水利': 'sulama; sulama tesisi',
    '水龙头': 'musluk',
    '水泥': 'çimento',
    '瞬间': 'bir göz kırpımında; anında',
    '司法': 'adli; adalet yönetimi',
    '司令': 'komutan',
    '私自': 'gizlice; izinsiz',
    '思念': 'özlemek; anmak; hasret çekmek',
    '思索': 'derin düşünmek; düşünmek',
    '思维': 'düşünce tarzı; düşünme',
    '斯文': 'zarif; kültürlü; aydın',
    '死亡': 'ölmek; ölüm',
    '四肢': 'kollar ve bacaklar; dört uzuv',
    '寺庙': 'tapınak; manastır',
    '饲养': 'yetiştirmek; beslemek (evcil hayvan)',
    '肆无忌惮': 'tamamen başıbozuk; pervasız',
    '耸': 'omuz silkmek; yükselmek; şok etmek',
    '艘': 'tekne ve gemiler için ölçü birimi',
    '苏醒': 'uyanmak; bilinci geri gelmek',
    '俗话': 'deyim; atasözü',
    '诉讼': 'dava; hukuki işlem',
    '素食': 'sebze; vejeteryan yemek',
    '素质': 'iç kalite; temel öz; karakter kalitesi',
    '塑造': 'şekillendirmek; modellemek',
    '算数': 'aritmetik; saymak',
    '随即': 'hemen; ardından',
    '随意': 'istediği gibi; keyfine göre',
    '岁月': 'bir kişinin yılları; yaşam',
    '隧道': 'tünel',
    '损坏': 'hasar vermek; zarar vermek',
    '索取': 'talep etmek; istemek',
    '索性': 'da olsa iyisi; ne olursa; dürüstçe',
    '塌': 'çökmek; yıkılmak',
    '踏实': 'pratik; gerçekçi; rahatlamak',
    '塔': 'pagoda; kule',
    '台风': 'tayfun',
    '太空': 'uzay',
    '泰斗': 'döneminin önde gelen bilgini; otorite',
    '贪婪': 'aç gözlü; tamahkar',
    '贪污': 'yolsuzluk; zimmetine geçirme',
    '摊': 'yaymak; seyyar satıcı tezgahı; kızartmak',
    '瘫痪': 'felç',
    '弹性': 'esneklik; elastikiyet',
    '坦白': 'dürüst; içten; itiraf etmek',
    '叹气': 'iç çekmek',
    '探测': 'sondaj yapmak; tespit etmek',
    '探索': 'keşfetmek; araştırmak',
    '探讨': 'araştırmak; incelemek',
    '探望': 'ziyaret etmek; gözetlemek',
    '倘若': 'eğer; şayet; durumunda',
    '掏': 'cebinden çıkarmak',
    '滔滔不绝': 'durmadan konuşmak; coşkun; sürükleyici',
    '陶瓷': 'seramik; porselen',
    '陶醉': 'sarhoş olmak (başarı veya güçle)',
    '淘汰': 'eleyerek çıkarmak; doğal seçilim; aşamalı kaldırma',
    '讨好': 'yağ çekmek; dalkavukluk etmek',
    '特长': 'güçlü yön; uzmanlık',
    '特定': 'özel; belirli; atanmış',
    '特意': 'özellikle; özel amaçla',
    '提拔': 'terfi ettirmek; yükseltmek',
    '提炼': 'özünü çıkarmak; rafine etmek',
    '提示': 'ipucu vermek; sunmak; işaret etmek',
    '提议': 'önermek; teklif etmek',
    '题材': 'konu; içerik',
    '体裁': 'edebiyat türleri',
    '体积': 'hacim; büyüklük',
    '体谅': 'empati kurmak; anlayış göstermek',
    '体面': 'onur; saygın; yüz',
    '体系': 'sistem; yapı',
    '天才': 'yetenek; deha; yetenekli',
    '天赋': 'doğal yetenek',
    '天伦之乐': 'aile mutluluğu',
    '天然气': 'doğalgaz',
    '天生': 'doğuştan; kalıtsal; doğal',
    '天堂': 'cennet; ütopya',
    '天文': 'astronomi',
    '田径': 'atletizm; koşu ve alan',
    '田野': 'tarla; açık arazi',
    '舔': 'yalamak',
    '挑剔': 'titiz; seçici',
    '条款': 'madde; sözleşme veya yasa maddesi',
    '条理': 'ardışık; düzenleme; düzenlilik',
    '条约': 'anlaşma; antlaşma',
    '调和': 'uyumlu; ahenk',
    '调剂': 'düzeltme yapmak; ayarlamak',
    '调节': 'ayarlamak; düzenlemek; uzlaştırmak',
    '调解': 'arabuluculuk; anlaşmaya getirmek',
    '调料': 'baharat; çeşni',
    '挑拨': 'kışkırtmak; fitne çıkarmak',
    '挑衅': 'kışkırtmak; meydan okuma',
    '跳跃': 'atlamak; sıçramak; zıplamak',
    '亭子': 'köşk; kiosk',
    '停泊': 'demirlemek; yanaşmak (gemi)',
    '停顿': 'durmak; ara vermek',
    '停滞': 'durma; tıkanma; çıkmaza girme',
    '挺拔': 'uzun ve dik; yüksek ve düzgün',
    '通货膨胀': 'enflasyon',
    '通缉': 'suçluyu tutuklatmak',
    '通俗': 'popüler; yaygın; günlük; sıradan',
    '通讯': 'iletişim; haber; muhabereler',
    '通用': 'ortak kullanımda; birbirinin yerine geçebilir',
    '同胞': 'vatandaş; yurttaş; hemşehri',
    '同志': 'yoldaş; dost',
    '铜': 'bakır',
    '童话': 'masal; peri masalı',
    '统筹兼顾': 'planlama yoluyla her boyutu göz önünde bulundurmak',
    '统计': 'istatistik; toplamak; hesaplamak',
    '统统': 'tamamen; büsbütün',
    '统治': 'yönetmek; hüküm sürmek',
    '投机': 'spekülasyon yapmak; fırsatçı',
    '投票': 'oy vermek; seçim',
    '投诉': 'şikayet etmek; mahkemeye başvurmak',
    '投降': 'teslim olmak; pes etmek',
    '投掷': 'fırlatmak; uzağa atmak',
    '透露': 'ifşa etmek; açığa çıkarmak',
    '秃': 'kel; küt',
    '突破': 'atlatmak; büyük başarı',
    '图案': 'desen; şekil',
    '徒弟': 'çırak; öğrenci; talebe',
    '途径': 'yol; kanal',
    '涂抹': 'karalamak; sürmek',
    '土壤': 'toprak; zemin',
    '团结': 'birleşmek; toplanmak; güçleri birleştirmek',
    '团体': 'grup; organizasyon; takım',
    '团圆': 'buluşmak; aile olarak bir araya gelmek',
    '推测': 'tahmin etmek; varsaymak',
    '推翻': 'devirmek; yıkmak',
    '推理': 'muhakeme; çıkarım',
    '推论': 'çıkarım yapmak; sonuç çıkarmak',
    '推销': 'pazarlamak; satmak',
    '吞吞吐吐': 'mırıldanmak; bir şeyleri gizler gibi konuşmak',
    '托运': 'bagaj olarak vermek; göndermek',
    '拖延': 'uzatmak; geciktirmek; ertelemek',
    '脱离': 'ayrılmak; kopmak; uzaklaşmak',
    '妥当': 'uygun; münasip; yerinde',
    '妥善': 'uygun; düzgün düzenlenmiş',
    '妥协': 'uzlaşmak; anlaşmak',
    '椭圆': 'elips; oval',
    '唾弃': 'bir kenara atmak; itmek',
    '挖掘': 'kazmak; açığa çıkarmak; keşfetmek',
    '哇': 'vay; vay be; ağlama veya şaşırma sesi',
    '娃娃': 'bebek; çocuk; oyuncak bebek',
    '瓦解': 'çökmek; dağılmak; parçalanmak',
    '歪曲': 'çarpıtmak; tahrif etmek; yanlış göstermek',
    '外表': 'dış görünüş; dışarıdan görünüm',
    '外行': 'acemi; amatör; uzman olmayan',
    '外界': 'dış dünya; harici',
    '外向': 'dışa dönük; ihracata yönelik',
    '丸': 'hap; granül',
    '完备': 'eksiksiz; tam; kusursuz',
    '完毕': 'bitirmek; tamamlamak',
    '玩弄': 'oynamak; kandırmak; kullanmak',
    '玩意儿': 'şey; oyuncak; alet',
    '顽固': 'inatçı; ısrarcı',
    '顽强': 'dayanıklı; yenilmesi zor',
    '挽回': 'kurtarmak; durumu telafi etmek',
    '挽救': 'kurtarmak; telafi etmek',
    '惋惜': 'üzülmek; acımak; pişman olmak',
    '万分': 'çok; son derece',
    '往常': 'eskiden alışılmış olduğu gibi',
    '往事': 'geçmiş olaylar; eski dönem',
    '妄想': 'boş hayal kurmak; kuruntu',
    '危机': 'kriz',
    '威风': 'haşmet; güç ve prestij',
    '威力': 'güç; korku uyandıran güç',
    '威望': 'prestij; itibar',
    '威信': 'itibar; güvenilirlik; otorite',
    '微不足道': 'ihmal edilebilir; önemsiz; söz etmeye değmez',
    '微观': 'mikroskobik; atom altı',
    '为难': 'güçlük çıkarmak; utandırılmış',
    '为期': 'belirli süre için planlanmak',
    '违背': 'ihlal etmek; karşı gelmek',
    '唯独': 'sadece; tek başına',
    '维持': 'korumak; sürdürmek',
    '维护': 'savunmak; korumak; bakımını yapmak',
    '维生素': 'vitamin',
    '伪造': 'sahte; taklit etmek; tahrif etmek',
    '蜿蜒': 'kıvrımlı; yılan gibi dolaşan',
    '婉转': 'ahenkli; nazik; dolaylı',
    '万一': 'her ihtimale karşı; olursa',
    '往返': 'gidip gelmek',
    '忘却': 'unutmak; zihinten silmek',
    '忘恩负义': 'nankör; elini ısıran köpeği beslemek',
    '网络': 'ağ; internet',
    '旺盛': 'canlı; bereketli; gelişen',
    '委托': 'emanet etmek; görevlendirmek',
    '委婉': 'nazik; yumuşak; ince',
    '卫星': 'uydu',
    '温馨': 'sıcak; samimi',
    '闻名': 'ünlü; tanınmış',
    '纹理': 'doku; tahta damarı',
    '文采': 'edebi yetenek; yazım tarzı',
    '文凭': 'diploma; belgeler',
    '文物': 'kültürel miras; tarihi eserler',
    '文献': 'literatür; belgeler; kaynaklar',
    '文雅': 'zarif; kibar; kültürlü',
    '文艺': 'edebiyat ve sanat',
    '文字': 'yazılı dil; karakterler; alfabe',
    '委员': 'komite üyesi; meclis; konsey',
    '未免': 'oldukça; biraz fazla',
    '畏惧': 'korku; kaygı',
    '喂': 'hey; beslemek; alo (telefonda)',
    '蔚蓝': 'gök mavisi; azur',
    '慰问': 'sempati belirtmek; taziyede bulunmak',
    '温带': 'ılıman kuşak',
    '温和': 'ılımlı; sıcak; ılık',
    '问世': 'yayımlanmak; çıkmak',
    '窝': 'yuva; in',
    '乌黑': 'simsiyah; zifiri siyah',
    '污蔑': 'iftira etmek; karalamak',
    '诬陷': 'tuzağa düşürmek; iftira atmak',
    '无比': 'eşsiz; benzersiz',
    '无偿': 'ücretsiz; parasız',
    '无耻': 'utanmaz; yüzsüz',
    '无动于衷': 'kayıtsız; ilgisiz',
    '无非': 'başka bir şey değil; sadece',
    '无辜': 'masum',
    '无精打采': 'hareketsiz; cesareti kırık',
    '无赖': 'serseri; aşağılık',
    '无理取闹': 'sebepsiz yere kavga çıkarmak',
    '无能为力': 'güçsüz; elinden bir şey gelmiyor',
    '无穷无尽': 'geniş ve sınırsız; sonsuz',
    '无微不至': 'her bakımdan; özenle',
    '无忧无虑': 'kaygısız ve tasasız',
    '无知': 'cehalet; bilgisizlik',
    '武器': 'silah; donanım',
    '武侠': 'şövalye; dövüş sanatları türü',
    '武装': 'silahlanmak; silahlar; donatmak',
    '侮辱': 'hakaret etmek; aşağılamak',
    '舞蹈': 'dans',
    '务必': 'mutlaka; gerekli; kesinlikle',
    '物美价廉': 'uygun fiyatlı güzel ürünler',
    '物业': 'mülk yönetimi',
    '物资': 'mal ve malzeme; emtia',
    '误差': 'fark; hata; yanlışlık',
    '误解': 'yanlış anlamak; yanlış yorumlamak',
    '夕阳': 'batan güneş; gün batımı',
    '昔日': 'eskiden; geçmişte',
    '牺牲': 'kurban vermek; fedakarlık etmek',
    '溪': 'dere; çay',
    '熄灭': 'söndürmek; sönmek',
    '膝盖': 'diz',
    '习俗': 'gelenek; adet; görenek',
    '袭击': 'sürpriz saldırı; baskın',
    '媳妇': 'gelin; oğulun eşi',
    '喜闻乐见': 'görmesi zevkli; güzel bir manzara',
    '喜悦': 'mutlu; sevinçli',
    '系列': 'seri; dizi',
    '细胞': 'hücre (biyoloji)',
    '细菌': 'bakteri; virüs; mikrop',
    '细致': 'narin; titiz; ince',
    '峡谷': 'kanyon; vadi; boğaz',
    '狭隘': 'dar; kısıtlı; dar görüşlü',
    '狭窄': 'dar',
    '霞': 'kızıl bulutlar',
    '下属': 'ast; emir altındaki',
    '先进': 'ileri (teknoloji); ilerlemek',
    '先前': 'önce; daha önce',
    '纤维': 'lif; elyaf',
    '掀起': 'kaldırmak; yükseltmek',
    '鲜明': 'parlak; belirgin; keskin',
    '闲话': 'dedikodu; konu dışı',
    '贤惠': 'erdemli ve itaatkâr (kadın için)',
    '弦': 'yay teli; çalgı aleti teli',
    '衔接': 'birleştirmek; birbirine bağlamak',
    '嫌': 'beğenmemek; şüphelenme; kırgınlık',
    '嫌疑': 'şüphe; (şüpheli) olmak',
    '显著': 'dikkate değer; belirgin; olağanüstü',
    '现场': 'olay yeri; yerinde',
    '现成': 'hazır; hazır yapılmış',
    '现状': 'mevcut durum; statüko',
    '线索': 'iz; ipucu; hikaye ipliği',
    '宪法': 'anayasa',
    '陷害': 'suçu birine yıkmak; çerçevelemek',
    '陷阱': 'tuzak; kapan',
    '陷入': 'batmak; düşmek; bir yere saplanmak',
    '馅儿': 'iç; dolma malzemesi',
    '乡镇': 'köy ve kasaba',
    '相差': 'farklı; fark',
    '相等': 'eşit olmak; denk; eşdeğer',
    '相辅相成': 'birbirini tamamlamak',
    '相应': 'uygun; ilgili',
    '镶嵌': 'kakma işi; işlemek',
    '响亮': 'yüksek sesli ve net; yankılı',
    '响应': 'yanıtlamak; cevap vermek',
    '想方设法': 'her yolu denemek; mümkün her araçla',
    '向导': 'rehber; kılavuz',
    '向来': 'her zaman; daima',
    '向往': 'özlemek; hayal etmek',
    '巷': 'çıkmaz sokak; dar sokak',
    '相声': 'güldürü diyaloğu; stand-up diyaloğu',
    '削': 'soymak; kesmek',
    '消除': 'gidermek; ortadan kaldırmak',
    '消毒': 'dezenfekte etmek; sterilize etmek',
    '消防': 'yangından korunma ve söndürme',
}

with open(DART_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

COUNT = [0]

def replace_tr(m):
    full = m.group(0)
    simp = m.group(1)
    tr_val = TR.get(simp, '')
    if not tr_val:
        return full
    COUNT[0] += 1
    tr_escaped = tr_val.replace("'", "\\'")
    return full[:-4] + f"'{tr_escaped}'],"

pattern = r"\['((?:[^'\\]|\\.)*)',\s*'(?:[^'\\]|\\.)*',\s*'(?:[^'\\]|\\.)*',\s*'(?:[^'\\]|\\.)*',\s*''\],"
result = re.sub(pattern, replace_tr, content)

with open(DART_FILE, 'w', encoding='utf-8') as f:
    f.write(result)

print(f'Done — {COUNT[0]} entries updated.')
