#!/usr/bin/env python3
"""Add Turkish translations to first 1000 HSK6 entries."""
import re

DART_FILE = r'd:\Masaustu\github\Kandao\lib\core\constants\hsk6_words.dart'

TR = {
    # A
    '挨': 'yaklaşmak; sırayla',
    '癌症': 'kanser',
    '爱不释手': 'sevdiğinden vazgeçememek',
    '爱戴': 'sevgi ve saygı göstermek',
    '暧昧': 'belirsiz; şüpheli',
    '安宁': 'huzurlu; sakin; dingin',
    '安详': 'sakin; vakur',
    '安置': 'yerleştirmek; düzenlemek',
    '按摩': 'masaj yapmak',
    '案件': 'dava; hukuki dava',
    '案例': 'vaka; örnek olay',
    '暗示': 'ima etmek; ipucu vermek',
    '昂贵': 'pahalı; değerli',
    '凹凸': 'engebeli; pürüzlü',
    '熬': 'dayanmak; kaynatmak',
    '奥秘': 'gizem; sır; derinlik',
    # B
    '巴不得': 'sabırsızlıkla beklemek; can atmak',
    '巴结': 'yağcılık yapmak; pohpohlamak',
    '扒': 'kazmak; sökmek; çıkarmak',
    '疤': 'yara izi',
    '拔苗助长': 'aceleyle işi bozmak',
    '把关': 'geçidi korumak; kontrol etmek',
    '把手': 'tutamak; kapı kolu',
    '罢工': 'grev yapmak',
    '霸道': 'zorba; despot',
    '掰': 'iki elle kırmak',
    '摆脱': 'kurtulmak; bağını koparmak',
    '败坏': 'mahvetmek; bozmak',
    '拜访': 'ziyaret etmek',
    '拜年': 'Yeni Yıl tebriğinde bulunmak',
    '拜托': 'rica etmek; lütfen',
    '颁布': 'ilan etmek; yayımlamak',
    '颁发': 'vermek; ilan etmek; ödül vermek',
    '斑': 'benek; leke; renkli nokta',
    '版本': 'baskı; versiyon; sürüm',
    '半途而废': 'yarım bırakmak; tamamlamamak',
    '扮演': 'rol oynamak; canlandırmak',
    '伴侣': 'eş; ortak; yaşam arkadaşı',
    '伴随': 'eşlik etmek; beraberinde olmak',
    '绑架': 'adam kaçırmak',
    '榜样': 'örnek; model',
    '磅': 'libre; ölçmek',
    '包庇': 'saklamak; korumak; örtbas etmek',
    '包袱': 'bohça; yük; sorun',
    '包围': 'kuşatmak; çevrelemek',
    '包装': 'ambalajlamak; paketlemek',
    '饱和': 'doyma; doygunluk',
    '饱经沧桑': 'birçok güçlük yaşamış olmak',
    '保管': 'korumak; muhafaza etmek; kesinlikle',
    '保密': 'gizli tutmak; gizlilik',
    '保姆': 'dadı; ev işçisi',
    '保守': 'tutucu; muhafazakâr; korumak',
    '保卫': 'savunmak; korumak',
    '保养': 'bakım yapmak; sağlığına dikkat etmek',
    '保障': 'güvence altına almak; teminat',
    '保重': 'kendine iyi bak',
    '报仇': 'intikam almak; öç almak',
    '报酬': 'ücret; karşılık; mükâfat',
    '报答': 'karşılık vermek; minnettarlık göstermek',
    '报复': 'misilleme yapmak; intikam',
    '报警': 'polisi aramak; alarm vermek',
    '报销': 'harcama geri almak; gider bildirmek',
    '抱负': 'hedef; hırs; özlem',
    '暴力': 'şiddet; zulüm',
    '暴露': 'ifşa etmek; açığa çıkarmak',
    '曝光': 'ışığa maruz bırakmak; açığa çıkarmak',
    '爆发': 'patlak vermek; patlamak',
    '爆炸': 'patlama; infilak',
    '卑鄙': 'alçak; aşağılık; rezil',
    '悲哀': 'keder; acı; üzüntü',
    '悲惨': 'acıklı; trajik; perişan',
    '北极': 'Kuzey Kutbu',
    '贝壳': 'deniz kabuğu; midye kabuğu',
    '备份': 'yedekleme; yedek almak',
    '备忘录': 'muhtıra; tutanak; anımsatma notu',
    '背叛': 'ihanet etmek; hain olmak',
    '背诵': 'ezbere okumak; ezbere söylemek',
    '被动': 'pasif; edilgen',
    '被告': 'sanık; davalı',
    '奔波': 'koşturmak; yorulmak; uğraşmak',
    '奔驰': 'hızla koşmak; süratle gitmek',
    '本能': 'içgüdü; doğal yetenek',
    '本钱': 'ana para; sermaye',
    '本人': 'kendim; şahsen; bizzat',
    '本身': 'kendisi; başlı başına',
    '本事': 'yetenek; beceri; kabiliyet',
    '笨拙': 'hantal; beceriksiz; sakar',
    '崩溃': 'çökmek; dağılmak; mahvolmak',
    '甭': 'gerek yok',
    '迸发': 'fışkırmak; patlak vermek',
    '蹦': 'zıplamak; sıçramak; hoplamak',
    '逼迫': 'zorlamak; mecbur etmek; baskı yapmak',
    '鼻涕': 'burun akıntısı; sümük',
    '比方': 'örnek; benzetme; mesela',
    '比喻': 'mecaz; benzetme; analoji',
    '比重': 'oran; özgül ağırlık',
    '鄙视': 'hor görmek; aşağılamak; küçümsemek',
    '闭塞': 'tıkamak; geri kalmış; ücra',
    '弊病': 'kötülük; zarar; sakınca',
    '弊端': 'kötüye kullanım; yolsuzluk',
    '臂': 'kol',
    '边疆': 'sınır bölgesi; uç bölge',
    '边界': 'sınır; hudut',
    '边境': 'sınır bölgesi; sınır hattı',
    '边缘': 'kenar; kıyı; sınır',
    '编织': 'dokumak; örgü örmek',
    '鞭策': 'teşvik etmek; dürtmek; zorlamak',
    '贬低': 'küçümsemek; aşağılamak; değer düşürmek',
    '贬义': 'olumsuz anlam; aşağılayıcı ifade',
    '扁': 'düz; yassı',
    '变故': 'beklenmedik olay; kaza',
    '变迁': 'değişim; dönüşüm; geçiş',
    '变质': 'bozulmak; dönüşmek',
    '便利': 'uygun; kolay; pratik',
    '便条': 'not; kısa not; kâğıt parçası',
    '便于': 'kolaylaştırmak; elverişli olmak',
    '遍布': 'her yere yayılmak; yaygın olmak',
    '辨认': 'tanımak; ayırt etmek; teşhis etmek',
    '辩护': 'savunmak; adına konuşmak',
    '辩解': 'açıklamak; gerekçe sunmak',
    '辩证': 'diyalektik; araştırmak',
    '辫子': 'örgü; saç örgüsü',
    '标本': 'örnek; numune',
    '标记': 'işaret; sembol; belirti',
    '标题': 'başlık; manşet; altyazı',
    '表决': 'oylama; oy vermek',
    '表态': 'tutumunu açıklamak; taraf olmak',
    '表彰': 'takdir etmek; ödüllendirmek',
    '憋': 'tutmak; nefesi tutmak; sıkmak',
    '别墅': 'villa; köşk',
    '别致': 'özgün; benzersiz; şık',
    '别扭': 'garip; doğal olmayan; zor',
    '濒临': 'eşiğinde olmak; yakın olmak',
    '冰雹': 'dolu; buz parçaları',
    '丙': 'üçüncü (sayma sırası); C; ateş',
    '并非': 'aslında değil; gerçekte değil',
    '并列': 'yan yana durmak; eşit olmak',
    '拨': 'çevirmek; kaydırmak; dürtmek',
    '波浪': 'dalga; dalgalanma',
    '波涛': 'büyük dalgalar; coşkun dalgalar',
    '剥削': 'sömürmek; istismar etmek',
    '播种': 'tohum ekmek; ekmek',
    '伯母': 'amcanın karısı; yenge',
    '博大精深': 'geniş kapsamlı ve derin',
    '博览会': 'uluslararası sergi; fuar',
    '搏斗': 'kavga etmek; boğuşmak; mücadele etmek',
    '薄弱': 'zayıf; güçsüz; kırılgan',
    '补偿': 'tazminat; telafi etmek',
    '补救': 'çaresini bulmak; düzeltmek',
    '补贴': 'sübvansiyon; yardım; ödenek',
    '捕捉': 'yakalamak; tutmak; avlamak',
    '哺乳': 'emzirmek; süt vermek',
    '不得已': 'çaresiz kalmak; başka seçenek olmamak',
    '不妨': 'zararı yok; neden olmasın',
    '不敢当': 'layık değilim; abartıyorsunuz',
    '不顾': 'aldıramamak; umursamamak; rağmen',
    '不禁': 'kendini tutamamak; dayanamamak',
    '不堪': 'dayanamamak; son derece; berbat',
    '不可思议': 'hayal edilemez; akıl almaz; inanılmaz',
    '不愧': 'layık olmak; hak etmek',
    '不料': 'beklenmedik şekilde; sürpriz olarak',
    '不免': 'kaçınılmaz; zorunlu olarak',
    '不时': 'sık sık; zaman zaman; ara sıra',
    '不惜': 'esirgemeden; çekinmeden',
    '不相上下': 'birbirine eşit; aynı seviyede',
    '不像话': 'mantıksız; saçma; yakışıksız',
    '不屑一顾': 'aşağılamak; bakmaya değmez bulmak',
    '不言而喻': 'söylemeye gerek yok; açıkça belli',
    '不由得': 'kendini tutamamak; istemeden',
    '不择手段': 'her yolu denemek; yolunu bulmak',
    '不止': 'durmadan; sadece değil; -dan fazla',
    '布告': 'ilan; duyuru; bildiri',
    '布局': 'düzen; yerleşim; düzenleme',
    '布置': 'düzenlemek; süslemek; kurmak',
    '步伐': 'adım; yürüyüş; ilerleme hızı',
    '部署': 'konuşlandırmak; dağıtmak',
    '部位': 'bölüm; yer; vücut bölgesi',
    # C
    '才干': 'yetenek; yeterlilik; kabiliyet',
    '财富': 'zenginlik; servet; hazine',
    '财务': 'mali işler; finans',
    '财政': 'devlet maliyesi; bütçe',
    '裁缝': 'terzi; dikici',
    '裁判': 'hakem; yargı; karar vermek',
    '裁员': 'işten çıkarma; personel azaltma',
    '采购': 'satın alma; tedarik',
    '采集': 'toplamak; derlemek',
    '采纳': 'kabul etmek; benimsemek',
    '彩票': 'piyango bileti',
    '参谋': 'danışman; tavsiye vermek; kurmay',
    '参照': 'referans almak; başvurmak',
    '残疾': 'engellilik; özürlülük',
    '残酷': 'zalim; acımasız; vahşi',
    '残留': 'kalmak; artık; kalıntı',
    '残忍': 'vahşi; acımasız; kıyıcı',
    '灿烂': 'parlak; muhteşem; ışıltılı',
    '仓促': 'aceleci; telaşlı',
    '仓库': 'depo; ambar',
    '苍白': 'solgun; soluk; benziz',
    '舱': 'kabin; ambar (gemi/uçak)',
    '操劳': 'çok çalışmak; aşırı çalışmak',
    '操练': 'alıştırma yapmak; talim',
    '操纵': 'kontrol etmek; manipüle etmek',
    '操作': 'çalıştırmak; işletmek; kullanmak',
    '嘈杂': 'gürültülü; patırtılı',
    '草案': 'taslak (yasa vb.)',
    '草率': 'aceleyle; özensiz; dikkatsizce',
    '侧面': 'yan; profil; yan taraf',
    '测量': 'ölçmek; ölçüm yapmak',
    '策划': 'planlamak; organize etmek',
    '策略': 'strateji; taktik; plan',
    '层出不穷': 'art arda gelmek; sürekli ortaya çıkmak',
    '层次': 'kademe; katman; sıra düzeni',
    '差别': 'fark; ayrım; farklılık',
    '插座': 'priz; elektrik soketi',
    '查获': 'suçluyu yakalamak; ele geçirmek',
    '岔': 'yol ayrımı; yan yol',
    '刹那': 'an; göz kırpma anı',
    '诧异': 'hayrete düşmek; şaşırmak',
    '柴油': 'dizel yakıt; motorin',
    '搀': 'koldan tutmak; desteklemek',
    '馋': 'obur; açgözlü; iştahlı',
    '缠绕': 'sarmak; dolaşmak; büküşmek',
    '产业': 'sektör; endüstri; mülk',
    '阐述': 'açıklamak; ele almak; detaylı anlatmak',
    '颤抖': 'titremek; sarsılmak',
    '昌盛': 'müreffeh; gelişmekte',
    '尝试': 'denemek; girişmek; teşebbüs etmek',
    '偿还': 'geri ödemek; tazmin etmek',
    '场合': 'durum; vesile; ortam',
    '场面': 'sahne; manzara; görüntü',
    '场所': 'yer; mekan; konum',
    '敞开': 'geniş açmak; serbest bırakmak',
    '畅通': 'engelsiz; akıcı; tıkansız',
    '畅销': 'çok satılan; popüler',
    '倡导': 'savunmak; öncülük etmek',
    '倡议': 'öneri; önerge; teklif',
    '钞票': 'banknot; kâğıt para',
    '超越': 'geçmek; aşmak; üstün gelmek',
    '巢穴': 'yuva; in; sığınak',
    '朝代': 'hanedan; saltanat dönemi',
    '嘲笑': 'alay etmek; küçümsemek',
    '潮流': 'akıntı; trend; akım',
    '撤退': 'geri çekilmek; ricat etmek',
    '撤销': 'iptal etmek; kaldırmak; feshetmek',
    '沉淀': 'çökelti; çökmek; birikinti',
    '沉闷': 'bunaltıcı; sıkıcı; ağır',
    '沉思': 'derin düşünce; meditasyon; tefekkür',
    '沉重': 'ağır; ciddi; bunaltıcı',
    '沉着': 'soğukkanlı; sakin',
    '陈旧': 'eski; modası geçmiş',
    '陈列': 'sergilemek; teşhir etmek',
    '陈述': 'beyan; açıklama; ifade',
    '衬托': 'vurgulamak; ön plana çıkarmak',
    '称心如意': 'tam istediği gibi; tatmin edici',
    '称号': 'unvan; isim; lakap',
    '成本': 'maliyet; üretim maliyeti',
    '成交': 'anlaşmak; işlemi tamamlamak',
    '成天': 'bütün gün; sabahtan akşama',
    '成效': 'etki; sonuç; verim',
    '成心': 'kasıtlı; bilerek yapma',
    '成员': 'üye; aza',
    '呈现': 'ortaya çıkmak; görünmek; sergilemek',
    '诚挚': 'samimi; içten; gerçek',
    '承办': 'üstlenmek; kabul etmek',
    '承包': 'taşeron olmak; ihaleyi almak',
    '承诺': 'söz vermek; taahhüt etmek',
    '城堡': 'kale; şato; hisar',
    '乘': 'binmek; kullanmak; çarpmak',
    '盛': 'içermek; doldurmak; bol',
    '惩罚': 'ceza vermek; cezalandırmak',
    '澄清': 'netleştirmek; açığa kavuşturmak',
    '橙': 'turuncu renk; portakal',
    '秤': 'terazi; baskül; kantar',
    '吃苦': 'sıkıntıya katlanmak; çile çekmek',
    '吃力': 'yorucu; zahmetli; güç',
    '迟钝': 'ağır kafalı; anlayışsız',
    '迟缓': 'yavaş; ağır; geciken',
    '迟疑': 'tereddüt etmek; duraksamak',
    '持久': 'uzun süreli; kalıcı; dayanıklı',
    '赤道': 'Ekvator',
    '赤字': 'mali açık; borç',
    '冲动': 'dürtüsel davranmak; ani; içgüdüsel',
    '冲击': 'vurmak; çarpmak; etki',
    '冲突': 'çatışma; çarpışma; anlaşmazlık',
    '充当': 'olarak görev yapmak',
    '充沛': 'bol; canlı; dinç; enerjik',
    '充实': 'dolgun; zenginleştirmek',
    '充足': 'yeterli; bol; eksiksiz',
    '重叠': 'üst üste gelmek; örtüşmek',
    '崇拜': 'tapmak; tapınmak; hayranlık duymak',
    '崇高': 'yüce; soylu; asil',
    '崇敬': 'saygı duymak; hürmet göstermek',
    '稠密': 'yoğun; sık; kalabalık',
    '筹备': 'hazırlık yapmak; organize etmek',
    '丑恶': 'çirkin; iğrenç',
    '出路': 'çıkış yolu; gelecek beklentisi',
    '出卖': 'satmak; ihanet etmek',
    '出身': 'aile geçmişi; köken',
    '出神': 'dalıp gitmek; düşünceye dalmak',
    '出息': 'gelecek vaadi; beklenti',
    '初步': 'ilk adım; ön; ilk taslak',
    '除': '-den başka; çıkarmak; bölmek',
    '处分': 'cezalandırmak; disiplin cezası',
    '处境': 'durum; çıkmaz; hal',
    '处置': 'ele almak; düzenlemek',
    '储备': 'rezerv; stok; yedek',
    '储存': 'depolamak; saklamak',
    '储蓄': 'tasarruf etmek; birikim yapmak',
    '触犯': 'ihlal etmek; karşı çıkmak',
    '川流不息': 'kesintisiz akmak; sürekli devam etmek',
    '穿越': 'geçmek; aşmak; kat etmek',
    '传达': 'iletmek; aktarmak; duyurmak',
    '传单': 'el ilanı; broşür',
    '传授': 'öğretmek; aktarmak',
    '船舶': 'gemi; tekne',
    '喘气': 'nefes nefese kalmak; soluk almak',
    '串': 'bir araya getirmek; seri; dizisi',
    '床单': 'çarşaf; yatak örtüsü',
    '创立': 'kurmak; tesis etmek',
    '创新': 'yenilik yapmak; inovasyon',
    '创业': 'iş kurmak; girişimcilik',
    '创作': 'yaratmak; özgün eser; sanat yapıtı',
    '吹牛': 'övünmek; böbürlenmek',
    '吹捧': 'pohpohlamak; aşırı övmek',
    '炊烟': 'ocak dumanı; mutfak dumanı',
    '垂直': 'dikey; dik; düşey',
    '锤': 'çekiç; tokmak',
    '纯粹': 'tamamen; saf; salt',
    '纯洁': 'temiz; saf; dürüst',
    '慈善': 'hayırseverlik; iyilikseverlik',
    '慈祥': 'şefkatli; nazik; merhametli',
    '磁带': 'kaset; manyetik bant',
    '雌雄': 'dişi ve erkek; galip ve mağlup',
    '次品': 'kusurlu ürün; ikinci sınıf',
    '次序': 'sıra; düzen; tertip',
    '伺候': 'hizmet etmek; birine bakmak',
    '刺': 'diken; batmak; sokmak',
    '从容': 'sakin; acele etmeden; rahat',
    '丛': 'küme; demet; toplu',
    '凑合': 'bir araya getirmek; idare etmek',
    '粗鲁': 'kaba; nezaketsiz; hoyrat',
    '窜': 'kaçmak; kaçıp gitmek',
    '摧残': 'tahrip etmek; yıkıp geçmek',
    '脆弱': 'kırılgan; hassas; zayıf',
    '搓': 'ovmak; bükmek',
    '磋商': 'müzakere etmek; görüşmek',
    '挫折': 'engel; hayal kırıklığı; yenilgi',
    # D
    '搭': 'kurmak; inşa etmek; binmek',
    '搭档': 'iş ortağı; birlikte çalışmak',
    '搭配': 'eşleştirmek; uydurmak',
    '达成': 'ulaşmak; anlaşmak; sağlamak',
    '答辩': 'savunmak; teze karşı savunmak',
    '答复': 'cevap vermek; yanıtlamak',
    '打包': 'paketlemek; eve götürmek için paketlemek',
    '打官司': 'mahkemeye gitmek; dava açmak',
    '打击': 'vurmak; saldırmak; mücadele etmek',
    '打架': 'kavga etmek; dövüşmek',
    '打量': 'ölçmek; değerlendirmek; süzmek',
    '打猎': 'avlanmak; ava gitmek',
    '打仗': 'savaşmak; muharebe etmek',
    '大不了': 'en kötü ihtimalle',
    '大臣': 'bakan; vezir; yüksek yetkili',
    '大伙儿': 'herkes; hepimiz',
    '大肆': 'kontrolsüzce; alenen',
    '大体': 'genel olarak; kabaca',
    '大意': 'ana fikir; özet; dikkatsiz',
    '大致': 'yaklaşık; kabaca; aşağı yukarı',
    '歹徒': 'suçlu; kötü adam; eşkıya',
    '代价': 'bedel; maliyet; fiyat',
    '代理': 'vekil; acente; temsil etmek',
    '带领': 'rehberlik etmek; öncülük etmek',
    '怠慢': 'soğuk davranmak; ihmal etmek',
    '逮捕': 'tutuklamak; gözaltına almak',
    '担保': 'garanti vermek; kefil olmak',
    '胆怯': 'korkak; ürkek; çekingen',
    '诞辰': 'doğum günü (saygın kişiler için)',
    '诞生': 'doğmak; ortaya çıkmak',
    '淡季': 'ölü sezon; durgun dönem',
    '淡水': 'tatlı su; içme suyu',
    '蛋白质': 'protein',
    '当场': 'olay yerinde; o anda',
    '当初': 'o zamanlar; başlangıçta',
    '当代': 'günümüz; çağdaş; modern dönem',
    '当面': 'yüz yüze; bizzat; doğrudan',
    '当前': 'şimdiki; mevcut; güncel',
    '当事人': 'ilgili kişi; taraf',
    '当务之急': 'en acil mesele; öncelikli iş',
    '当选': 'seçilmek; seçimi kazanmak',
    '党': 'parti; dernek; klan',
    '档案': 'dosya; kayıt; arşiv',
    '档次': 'kalite derecesi; sınıf; seviye',
    '导弹': 'güdümlü füze; balistik füze',
    '导航': 'navigasyon; rehberlik etmek',
    '导向': 'yönlendirmek; yönlendirme',
    '捣乱': 'karışıklık çıkarmak; sorun çıkarmak',
    '倒闭': 'iflas etmek; kapanmak',
    '盗窃': 'çalmak; hırsızlık etmek',
    '稻谷': 'çeltik; pirinç mahsulü',
    '得不偿失': 'kazanç kayıptan az; değmez',
    '得力': 'yetenekli; etkili',
    '得天独厚': 'doğal avantajlara sahip olmak',
    '得罪': 'gücendirmek; kırmak',
    '灯笼': 'fener; kâğıt fener',
    '登陆': 'karaya çıkmak; giriş yapmak',
    '登录': 'giriş yapmak; oturum açmak',
    '蹬': 'bastırmak; tekmelemek',
    '等候': 'beklemek; sıra beklemek',
    '等级': 'derece; rütbe; sınıf; kademe',
    '瞪': 'dikkatle bakmak; gözlerini dikmek',
    '堤坝': 'baraj; bent; set',
    '敌视': 'düşmanlık etmek; husumet beslemek',
    '抵达': 'varmak; ulaşmak',
    '抵抗': 'direnmek; karşı koymak',
    '抵制': 'boykot; reddetmek',
    '地步': 'durum; hal; boyut',
    '地势': 'arazi; topografya',
    '地质': 'jeoloji',
    '递增': 'giderek artmak; kademeli artış',
    '颠簸': 'sarsılmak; silkelenmek',
    '颠倒': 'ters yüz etmek; tersine çevirmek',
    '典礼': 'tören; merasim',
    '典型': 'tipik örnek; model',
    '点缀': 'süslemek; bezeme; son dokunuş',
    '电源': 'elektrik kaynağı; güç kaynağı',
    '垫': 'yastık; altlık; birisi için ödemek',
    '惦记': 'endişelenmek; düşünmek; özlemek',
    '奠定': 'kurmak; temelini atmak',
    '叼': 'ağzında tutmak',
    '雕刻': 'oymak; kazımak; heykel yapmak',
    '雕塑': 'heykel; büst',
    '吊': 'asmak; sarkmak; taziyede bulunmak',
    '调动': 'aktarmak; taşımak; seferber etmek',
    '跌': 'düşmek; inmek; tökezlemek',
    '丁': 'T şeklinde; küp; sağlıklı',
    '叮嘱': 'ısrarla tavsiye etmek; tekrar tekrar uyarmak',
    '盯': 'dikkatle bakmak; gözetlemek',
    '定期': 'düzenli; periyodik',
    '定义': 'tanım; tanımlamak',
    '丢人': 'yüzünü kara çıkarmak; utanç vermek',
    '丢三落四': 'dağınık; unutkan',
    '东道主': 'ev sahibi; toplantı düzenleyen',
    '东张西望': 'her tarafa bakmak; etrafı kollamak',
    '董事长': 'yönetim kurulu başkanı',
    '动荡': 'çalkantı; istikrarsızlık; kargaşa',
    '动机': 'güdü; motivasyon; niyet',
    '动静': 'hareket sesi; etkinlik',
    '动力': 'güç; kuvvet; itici güç',
    '动脉': 'atardamar',
    '动身': 'yola çıkmak; hareket etmek',
    '动手': 'çalışmaya başlamak; el atmak',
    '动态': 'gelişme; durum; eğilim',
    '动员': 'seferber etmek; harekete geçirmek',
    '冻结': 'dondurmak; bloke etmek',
    '栋': 'tavan kirişi; bina sayma kelimesi',
    '兜': 'cep; torba; sarmak',
    '陡峭': 'sarp; dik; derin',
    '斗争': 'mücadele etmek; savaşmak',
    '督促': 'denetlemek ve teşvik etmek',
    '毒品': 'uyuşturucu; zehir',
    '独裁': 'diktatörlük; otoriter yönetim',
    '堵塞': 'tıkamak; bloke etmek; trafik sıkışıklığı',
    '赌博': 'kumar oynamak',
    '杜绝': 'kökten kaldırmak; tamamen önlemek',
    '端': 'uç; baş; uç nokta; dik tutmak',
    '端午节': 'Ejder Kayığı Festivali',
    '端正': 'dürüst; düzgün; doğru',
    '短促': 'kısa süreli; anlık',
    '断定': 'sonuca varmak; kestirmek',
    '断绝': 'kesmek; koparmak; bitirmek',
    '堆积': 'yığmak; biriktirmek; yığın',
    '队伍': 'grup; ekip; takım; saf',
    '对策': 'karşı önlem; çözüm stratejisi',
    '对称': 'simetri; simetrik',
    '对付': 'başa çıkmak; idare etmek',
    '对抗': 'karşı koymak; muhalefet etmek',
    '对立': 'karşı çıkmak; zıt olmak',
    '对联': 'Çin kafiyeli yazı ikilisi',
    '对应': 'karşılık gelmek; muadil',
    '对照': 'karşılaştırmak; mukayese etmek',
    '兑现': 'çeki bozdurma; sözünü tutmak',
    '顿时': 'hemen; anında; bir anda',
    '多元化': 'çeşitlendirmek; çeşitlilik',
    '哆嗦': 'titremek; üşümek',
    '堕落': 'ahlaki düşüş; yozlaşmak',
    # E
    '额外': 'ekstra; ilave; normun dışında',
    '恶心': 'iğrenç; mide bulandırıcı',
    '恶化': 'kötüleşmek; bozulmak',
    '遏制': 'sınırlandırmak; dizginlemek',
    '恩怨': 'şikâyet; eski husumet',
    '而已': 'bu kadar; sadece bu',
    '二氧化碳': 'karbondioksit; CO2',
    # F
    '发布': 'yayınlamak; açıklamak; duyurmak',
    '发财': 'para kazanmak; zenginleşmek',
    '发呆': 'boş gözlerle bakmak; dalgın olmak',
    '发动': 'başlatmak; harekete geçirmek',
    '发觉': 'fark etmek; keşfetmek',
    '发射': 'fırlatmak; ateşlemek',
    '发誓': 'yemin etmek; söz vermek',
    '发行': 'yayımlamak; piyasaya sürmek',
    '发炎': 'iltihaplanmak; iltihap',
    '发扬': 'geliştirmek; devam ettirmek',
    '发育': 'gelişmek; büyümek; olgunlaşmak',
    '法人': 'tüzel kişi; şirket',
    '番': 'sayma kelimesi (eylemler için)',
    '凡是': 'her; hepsi; istisnasız',
    '繁华': 'kalabalık; canlı; gelişmiş',
    '繁忙': 'yoğun; meşgul; kalabalık',
    '繁体字': 'geleneksel Çince karakter',
    '繁殖': 'çoğalmak; üremek; yetiştirmek',
    '反驳': 'çürütmek; karşı çıkmak',
    '反常': 'anormal; olağandışı',
    '反感': 'hoşlanmamak; antipatik',
    '反抗': 'direnmek; isyan etmek',
    '反馈': 'geri bildirim',
    '反面': 'ters yüz; karşı taraf',
    '反射': 'yansıma; refleks',
    '反思': 'geri dönüp düşünmek; iç gözlem',
    '反问': 'retorik soru sormak',
    '反之': 'oysa; öte yandan; tersine',
    '泛滥': 'taşmak; sel basmak; yaygınlaşmak',
    '范畴': 'kategori; alan; kapsam',
    '贩卖': 'satmak; ticaret yapmak',
    '方位': 'konum; yön',
    '方言': 'lehçe; ağız; bölge dili',
    '方圆': 'çevre; yakın çevre',
    '方针': 'politika; ilke',
    '防守': 'savunmak; korumak',
    '防御': 'savunma; direnmek',
    '防止': 'önlemek; korumak',
    '防治': 'önlemek ve tedavi etmek',
    '访问': 'ziyaret etmek; mülakat yapmak',
    '纺织': 'dokumak; tekstil',
    '放大': 'büyütmek; genişletmek',
    '放射': 'radyasyon; ışıma',
    '飞禽走兽': 'kuşlar ve hayvanlar',
    '飞翔': 'uçmak; süzülmek',
    '飞跃': 'sıçramak; atlamak; büyük ilerleme',
    '非法': 'yasadışı; hukuka aykırı',
    '肥沃': 'verimli; bereketli (toprak)',
    '诽谤': 'iftira atmak; karalamak',
    '肺': 'akciğer',
    '废除': 'kaldırmak; iptal etmek',
    '废寝忘食': 'yeme içmeyi unutmak; bıkmadan çalışmak',
    '废墟': 'harabe; enkaz; yıkıntı',
    '沸腾': 'kaynamak; coşmak',
    '分辨': 'ayırt etmek; fark etmek',
    '分寸': 'ölçü; sınır; uygun davranış',
    '分红': 'kâr payı; prim vermek; temettü',
    '分解': 'ayrışmak; parçalamak',
    '分裂': 'bölünmek; ayrılmak',
    '分泌': 'salgılamak; salgı',
    '分明': 'açık; belirgin; belli',
    '分歧': 'farklılık; görüş ayrılığı',
    '分散': 'dağıtmak; yaymak; dağılmak',
    '吩咐': 'talimat vermek; söylemek',
    '坟墓': 'mezar; kabir',
    '粉末': 'toz; ince toz',
    '粉色': 'pembe renk',
    '粉碎': 'parçalamak; ezmek',
    '分量': 'ağırlık; miktar',
    '愤怒': 'kızgın; öfkeli; hiddet',
    '丰满': 'dolgun; sağlıklı; bol',
    '丰盛': 'görkemli; bol; zengin sofra',
    '丰收': 'bol hasad; bereketli yıl',
    '风暴': 'fırtına; kasırga',
    '风度': 'zarafet; şıklık; davranış biçimi',
    '风光': 'doğal manzara; güzellik',
    '风气': 'genel hava; atmosfer',
    '风趣': 'mizah; esprili; hoş',
    '风土人情': 'yöresel koşullar ve gelenekler',
    '风味': 'yöresel lezzet; tat; aroma',
    '封闭': 'kapatmak; mühürlemek',
    '封建': 'feodal; feodalizm',
    '封锁': 'abluka; kuşatmak',
    '锋利': 'keskin; sivri; yerinde',
    '逢': 'karşılaşmak; rastlamak',
    '奉献': 'adamak; vakfetmek; katkıda bulunmak',
    '否决': 'veto etmek; reddetmek',
    '夫妇': 'karı-koca; evli çift',
    '夫人': 'hanımefendi; eş; karı',
    '敷衍': 'üstünkörü yapmak; yarım yamalak',
    '服从': 'itaat etmek; uymak',
    '服气': 'ikna olmak; kabullenmek',
    '俘虏': 'esir; savaş tutuklusu',
    '符号': 'sembol; işaret; simge',
    '幅度': 'genişlik; boyut; marj',
    '辐射': 'radyasyon; ışıma',
    '福利': 'refah; sosyal yardım',
    '福气': 'şans; saadet; iyi talih',
    '抚摸': 'okşamak; sevmek; dokunmak',
    '抚养': 'yetiştirmek; büyütmek',
    '俯视': 'yukarıdan bakmak; kuş bakışı',
    '辅助': 'yardım etmek; desteklemek',
    '腐败': 'yolsuzluk; çürümüş; bozulmuş',
    '腐烂': 'çürümek; kokuşmak',
    '腐蚀': 'aşındırmak; paslanmak',
    '腐朽': 'çürük; eskimiş; çökmüş',
    '负担': 'yük; sorumluluk',
    '附和': 'onaylamak; aynı fikirde görünmek',
    '附件': 'ek; ekli dosya',
    '附属': 'bağlı; ek; filyal',
    '复活': 'diriliş; yeniden canlanmak',
    '复兴': 'rönesans; yeniden doğmak',
    '副': 'yardımcı; vekil; ikincil',
    '赋予': 'vermek; bağışlamak; donatmak',
    '富裕': 'zengin; müreffeh; varlıklı',
    '腹泻': 'ishal',
    '覆盖': 'örtmek; kapsamak',
    # G
    '改良': 'iyileştirmek; ıslah etmek',
    '钙': 'kalsiyum',
    '盖章': 'mühür basmak; damga vurmak',
    '干旱': 'kuraklık; kurumuş',
    '干扰': 'parazit yapmak; müdahale etmek',
    '干涉': 'müdahale etmek; karışmak',
    '干预': 'müdahale etmek; araya girmek',
    '尴尬': 'zor durumda kalmak; utanmak',
    '感慨': 'içli düşünceler; duygulanmak',
    '感染': 'enfeksiyon; bulaşmak',
    '干劲': 'şevk; enerji; çalışma azmi',
    '纲领': 'program; ilke; ana hat',
    '岗位': 'görev yeri; pozisyon',
    '港口': 'liman; iskele',
    '港湾': 'doğal liman; körfez',
    '杠杆': 'kaldıraç; manivela',
    '高超': 'mükemmel; üstün; muhteşem',
    '高潮': 'yüksek dalga; doruk; kulminasyon',
    '高峰': 'zirve; doruk; yoğun dönem',
    '高明': 'parlak; zeki; bilge',
    '高尚': 'asil; yüce; ince ruhlu',
    '高涨': 'yükselmek; tırmanmak; artmak',
    '稿件': 'taslak; el yazması; makale',
    '告辞': 'veda etmek; ayrılmak',
    '告诫': 'uyarmak; öğüt vermek',
    '疙瘩': 'şişlik; yumru; düğüm; sorun',
    '鸽子': 'güvercin',
    '搁': 'koymak; bir kenara bırakmak',
    '割': 'kesmek; kısmak; kopmak',
    '歌颂': 'övmek; yüceltmek; methiye',
    '革命': 'devrim; devrimci olmak',
    '格局': 'yapı; düzen; yerleşim',
    '格式': 'format; biçim; şablon',
    '隔阂': 'mesafe; yanlış anlama; engel',
    '隔离': 'ayırmak; izole etmek; karantina',
    '个体': 'birey; tek tek',
    '各抒己见': 'herkes fikrini söylemek; görüş alışverişi',
    '根深蒂固': 'köklü; derine köklenmiş',
    '根源': 'kaynak; kök; sebep',
    '跟前': 'önünde; yakında',
    '跟随': 'takip etmek; izlemek',
    '跟踪': 'takip etmek; gölge gibi peşinde',
    '更新': 'yenilemek; güncellemek',
    '更正': 'düzeltmek; tashih etmek',
    '耕地': 'tarım arazisi; sürmek',
    '工艺品': 'el işi; zanaat ürünü',
    '公安局': 'polis merkezi; emniyet müdürlüğü',
    '公道': 'adil; hakkaniyetli',
    '公告': 'duyuru; resmi ilan',
    '公关': 'halkla ilişkiler; PR',
    '公民': 'vatandaş; sivil',
    '公然': 'açıkça; alenen',
    '公认': 'genel kabul görmüş',
    '公式': 'formül; kalıp',
    '公务': 'resmi işler; kamu görevi',
    '公正': 'adil; tarafsız',
    '公证': 'noterlik; noter onayı',
    '功劳': 'katkı; hizmet; başarı',
    '功效': 'etkinlik; verim; sonuç',
    '攻击': 'saldırmak; suçlamak; hücum',
    '攻克': 'ele geçirmek; fethetmek',
    '供不应求': 'talep arzdan fazla',
    '供给': 'temin etmek; sağlamak',
    '宫殿': 'saray; imparatorluk sarayı',
    '恭敬': 'saygılı; itaatkâr; nazik',
    '巩固': 'pekiştirmek; sağlamlaştırmak',
    '共和国': 'cumhuriyet',
    '共计': 'toplam; hepsi birlikte',
    '共鸣': 'rezonans; sempati; yankı bulmak',
    '勾结': 'iş birliği yapmak; suç ortaklığı',
    '钩子': 'kanca; çengel',
    '构思': 'planlamak; taslak oluşturmak',
    '孤独': 'yalnız; ıssız; izole',
    '孤立': 'izole etmek; yalnız bırakmak',
    '姑且': 'geçici olarak; şimdilik',
    '辜负': 'hayal kırıklığı yaratmak',
    '古董': 'antika; tarihi eser',
    '古怪': 'tuhaf; acayip; garip',
    '股东': 'hissedar; ortak',
    '股份': 'hisse; pay',
    '骨干': 'omurga; temel; kilit eleman',
    '鼓动': 'kışkırtmak; motive etmek',
    '固然': 'kuşkusuz; doğru; evet ama',
    '固体': 'katı; katı cisim',
    '固有': 'özünden gelen; doğal',
    '固执': 'inatçı; dik kafalı',
    '故乡': 'memleket; doğduğu yer',
    '故障': 'arıza; teknik sorun',
    '顾虑': 'çekince; endişe; kaygı',
    '顾问': 'danışman; müşavir',
    '雇佣': 'işe almak; çalıştırmak',
    '拐杖': 'baston; koltuk değneği',
    '关怀': 'önem vermek; ilgilenmek',
    '关照': 'gözetmek; bakıp kollamak',
    '观光': 'gezi yapmak; turizm',
    '官方': 'resmi; hükümet kaynaklı',
    '管辖': 'yönetmek; denetiminde olmak',
    '贯彻': 'uygulamak; hayata geçirmek',
    '惯例': 'gelenek; alışılagelen',
    '灌溉': 'sulama; sulamak',
    '罐': 'kutu; kavanoz; tencere',
    '光彩': 'parlaklık; ışıltı; şeref',
    '光辉': 'ışıltılı; muhteşem',
    '光芒': 'ışık huzmeleri; parlaklık',
    '光荣': 'şeref; onur; onurlu',
    '广阔': 'geniş; uçsuz bucaksız',
    '归根到底': 'sonuçta; en temelde',
    '归还': 'geri vermek; iade etmek',
    '规范': 'standart; norm; standardize etmek',
    '规格': 'standart; özellik',
    '规划': 'planlama; program',
    '规章': 'yönetmelik; kural',
    '轨道': 'yörünge; rota; ray',
    '贵族': 'soylu; asil; aristokrasi',
    '跪': 'diz çökmek',
    '棍棒': 'sopa; değnek',
    '国防': 'ulusal savunma',
    '国务院': 'Devlet Konseyi',
    '果断': 'kararlı; cesur; kesin',
    '过度': 'aşırı; fazla',
    '过渡': 'geçiş; geçici',
    '过奖': 'aşırı övmek; pohpohlamak',
    '过滤': 'filtrelemek; süzmek',
    '过失': 'kusur; hata; ihmal',
    '过问': 'ilgilenmek; araya girmek',
    '过瘾': 'tatmin etmek; çok keyifli',
    '过于': 'çok fazla; aşırı',
    # H
    '嗨': 'hey; merhaba',
    '海拔': 'deniz seviyesinden yükseklik; rakım',
    '海滨': 'kıyı; sahil; plaj',
    '含糊': 'belirsiz; muğlak',
    '含义': 'zımnî anlam; anlam',
    '寒暄': 'nezaket gevezeliği; sohbet',
    '罕见': 'nadir; az rastlanır',
    '捍卫': 'savunmak; korumak',
    '行列': 'sıra; kafile; saf',
    '航空': 'havacılık; hava yolu',
    '航天': 'uzay uçuşu; uzay bilimi',
    '航行': 'seyretmek; uçmak',
    '毫米': 'milimetre',
    '毫无': 'hiç; tamamen yoksun',
    '豪迈': 'cömert; cesur; asil',
    '号召': 'çağrıda bulunmak; seferber etmek',
    '耗费': 'israf etmek; tüketmek',
    '呵': 'nefes üflemek; azarlamak',
    '合并': 'birleşmek; birleştirmek',
    '合成': 'bileşik; sentez; karışım',
    '合伙': 'ortak olmak; iş ortaklığı',
    '合算': 'değer; karlı; maliyet etkin',
    '和蔼': 'nazik; iyi huylu; sevecen',
    '和解': 'barışmak; uzlaşmak',
    '和睦': 'huzurlu ilişkiler; uyumlu',
    '和气': 'dostane; nazik; uyumlu',
    '和谐': 'ahenkli; uyumlu',
    '嘿': 'hey (dikkat çekme için)',
    '痕迹': 'iz; eser; belirti',
    '狠心': 'katı yürekli; zalim',
    '恨不得': 'dayanamamak; çok istemek',
    '横': 'yatay; enine; mantıksız',
    '哼': 'inlemek; homurdanmak',
    '轰动': 'sansasyon; yankı uyandırmak',
    '烘': 'fırında ısıtmak; kavurmak',
    '宏观': 'makro; büyük çaplı',
    '宏伟': 'büyük; heybetli; muhteşem',
    '洪水': 'sel; taşkın',
    '哄': 'kandırmak; avutmak; eğlendirmek',
    '喉咙': 'boğaz; gırtlak',
    '吼': 'bağırmak; kükreylemek',
    '后代': 'torunlar; gelecek nesiller',
    '后顾之忧': 'gerideki kaygılar; aile endişesi',
    '后勤': 'lojistik; ikmal',
    '候选': 'aday; adaylığa girme',
    '呼唤': 'seslenmek; çağırmak',
    '呼啸': 'ıslık sesi; ulumak',
    '呼吁': 'çağrıda bulunmak; ricada bulunmak',
    '忽略': 'görmezden gelmek; ihmal etmek',
    '胡乱': 'dikkatsizce; gelişigüzel',
    '胡须': 'sakal; bıyık',
    '湖泊': 'göl; göller',
    '花瓣': 'yaprak (çiçek); taç yaprağı',
    '花蕾': 'gonca; tomurcuk',
    '华丽': 'görkemli; muhteşem',
    '华侨': 'yurtdışındaki Çinli',
    '化肥': 'kimyasal gübre',
    '化石': 'fosil',
    '化验': 'laboratuvar testi',
    '化妆': 'makyaj yapmak',
    '划分': 'bölmek; sınırlara ayırmak',
    '画蛇添足': 'gereksiz eklemeler yapmak',
    '话筒': 'mikrofon; ahize',
    '欢乐': 'sevinç; neşe; mutluluk',
    '还原': 'özgün haline döndürmek',
    '环节': 'bağlantı; halka; sürecin parçası',
    '缓和': 'yumuşatmak; azaltmak',
    '患者': 'hasta; acı çeken kişi',
    '荒凉': 'ıssız; çorak; tenha',
    '荒谬': 'saçma; gülünç; absürd',
    '荒唐': 'inanılmaz; saçma',
    '皇帝': 'imparator; hükümdar',
    '皇后': 'imparatoriçe; kraliçe',
    '黄昏': 'akşam; alaca karanlık',
    '恍然大悟': 'bir anda anlamak; aydınlanmak',
    '晃': 'sallanmak; sarsmak',
    '挥霍': 'savurmak; israf etmek',
    '辉煌': 'muhteşem; görkemli; parlak',
    '回报': 'karşılık vermek; ödül',
    '回避': 'kaçınmak; çevrelemek',
    '回顾': 'geriye bakmak; gözden geçirmek',
    '回收': 'geri dönüştürmek',
    '悔恨': 'pişmanlık; acı duyma',
    '毁灭': 'mahvetmek; yıkmak; yok etmek',
    '汇报': 'rapor vermek; bildirmek',
    '会晤': 'görüşmek; toplantı',
    '贿赂': 'rüşvet vermek',
    '昏迷': 'baygın; komada olmak',
    '荤': 'et veya balık yemeği',
    '浑身': 'bütün vücud; baştan ayağa',
    '混合': 'karıştırmak; birleştirmek',
    '混乱': 'karışıklık; kaotik',
    '混淆': 'karıştırmak; bulanıklaştırmak',
    '混浊': 'bulanık; kirli; tortulu',
    '活该': 'hak etmek; cezasını bulmak',
    '活力': 'enerji; canlılık; dinamizm',
    '火箭': 'roket; füze',
    '火焰': 'alev; ateş',
    '火药': 'barut',
    '货币': 'para birimi; döviz',
    # J (first ~157 entries to reach ~1000)
    '讥笑': 'alay etmek; küçümsemek',
    '饥饿': 'açlık; kıtlık',
    '机动': 'motorlu; mobil; esnek',
    '机构': 'kuruluş; örgüt; yapı',
    '机灵': 'zeki; kurnaz; uyanık',
    '机密': 'gizli; sır',
    '机械': 'makine; mekanik; sert',
    '机遇': 'fırsat; şans; elverişli koşul',
    '机智': 'kıvrak; becerikli',
    '基地': 'üs; temel; operasyon merkezi',
    '基金': 'fon; vakıf',
    '基因': 'gen; genetik',
    '激发': 'harekete geçirmek; uyandırmak',
    '激励': 'teşvik etmek; motive etmek',
    '激情': 'tutku; şiddetli duygu; coşku',
    '及早': 'mümkün olan en kısa sürede',
    '吉祥': 'şanslı; uğurlu; mübarek',
    '级别': 'rütbe; sınıf; kademe',
    '极端': 'aşırı; uç; ekstrem',
    '极限': 'sınır; uç; limit',
    '即便': 'bile; olsa da',
    '即将': 'kısa süre içinde; yakında',
    '急功近利': 'başarı için hevesli; aceleden iş',
    '急剧': 'hızlı; ani; keskin',
    '急切': 'aceleci; sabırsız; zorunlu',
    '急于求成': 'çok hızlı başarı istemek',
    '急躁': 'sinirli; çabuk öfkelenen; sabırsız',
    '疾病': 'hastalık; rahatsızlık; illet',
    '集团': 'grup; blok; çevre',
    '嫉妒': 'kıskanmak; çekememezlik',
    '籍贯': 'ana yurt; soy yeri',
    '给予': 'vermek; sağlamak',
    '计较': 'aşırı dikkat; tartışmak',
    '记性': 'hafıza; bellek',
    '记载': 'kaydetmek; yazmak',
    '纪要': 'toplantı tutanağı; özet',
    '技巧': 'beceri; teknik; yetenek',
    '忌讳': 'tabu; yasak; kaçınmak',
    '季度': 'çeyrek; üç aylık dönem',
    '季军': 'üçüncü; bronz madalyalı',
    '迹象': 'belirti; işaret; iz',
    '继承': 'miras almak; devralmak',
    '寄托': 'emanet etmek; sığınmak',
    '寂静': 'sessizlik; sükûnet',
    '加工': 'işlemek; üretmek',
    '加剧': 'şiddetlendirmek; ağırlaştırmak',
    '夹杂': 'birbirine karışmak',
    '佳肴': 'nefis yemek; lezzet',
    '家常': 'günlük aile hayatı; ev yemeği',
    '家伙': 'adam; herif; alet',
    '家属': 'aile üyesi; bakmakla yükümlü',
    '家喻户晓': 'herkesçe bilinen; meşhur',
    '尖端': 'en yüksek zirve; uç; en gelişmiş',
    '尖锐': 'keskin; sert; derin',
    '坚定': 'kararlı; sağlam; tutarlı',
    '坚固': 'sağlam; güçlü; dayanıklı',
    '坚韧': 'dayanıklı; zorlu; güçlü',
    '坚实': 'sağlam; büyük; katı',
    '坚硬': 'sert; katı; dayanıklı',
    '艰难': 'zor; ağır; güç',
    '监督': 'denetlemek; kontrol etmek',
    '监视': 'izlemek; gözetlemek',
    '监狱': 'hapishane; cezaevi',
    '煎': 'tavada kızartmak',
    '拣': 'seçmek; ayıklamak',
    '检讨': 'özeleştiri; analiz etmek',
    '检验': 'incelemek; test etmek',
    '剪彩': 'kurdele kesmek; açılış töreni',
    '简化': 'basitleştirmek',
    '简陋': 'basit ve iptidai',
    '简体字': 'sadeleştirilmiş Çince karakter',
    '简要': 'kısa ve öz; özlü',
    '见多识广': 'deneyimli ve bilgili',
    '见解': 'görüş; fikir; anlayış',
    '见闻': 'görüp duyduğu; genel kültür',
    '见义勇为': 'doğruyu görünce cesurca davranmak',
    '间谍': 'casus; ajan',
    '间隔': 'aralık; ara; mesafe',
    '间接': 'dolaylı',
    '剑': 'kılıç',
    '健全': 'tam; sağlam; mükemmel',
    '舰艇': 'savaş gemisi',
    '践踏': 'çiğnemek; ezmek',
    '溅': 'sıçramak; fışkırmak',
    '鉴别': 'ayırt etmek; tanımak',
    '鉴定': 'değerlendirmek; tanımlamak',
    '鉴于': 'göz önüne alındığında',
    '将近': 'neredeyse; yaklaşık',
    '将就': 'mecburen kabullenmek; idare etmek',
    '将军': 'general',
    '僵硬': 'sert; kasılmış; donmuş',
    '奖励': 'ödüllendirmek',
    '奖赏': 'ödül vermek',
    '桨': 'kürek; paddle',
    '降临': 'gelmek; inmek; başına gelmek',
    '交叉': 'kesişmek; çaprazlamak',
    '交代': 'açıklamak; teslim etmek',
    '交涉': 'müzakere etmek; pazarlık etmek',
    '交易': 'ticaret; alışveriş; anlaşma',
    '娇气': 'narin; şımarık; titiz',
    '焦点': 'odak noktası; merkez',
    '焦急': 'endişeli; kaygılı; gergin',
    '角落': 'köşe; kenar',
    '侥幸': 'şansla; talihle; tesadüfen',
    '搅拌': 'karıştırmak; çevirmek',
    '缴纳': 'ödemek (vergi vb.)',
    '较量': 'yarışmak; güç denemesi',
    '教养': 'terbiye; eğitim; kültür',
    '阶层': 'sosyal tabaka; kademe',
    '皆': 'hepsi; her; tümü',
    '接连': 'arka arkaya; birbirini izleyerek',
    '揭露': 'ifşa etmek; ortaya çıkarmak',
    '节制': 'ölçülü olmak; sınırlamak',
    '节奏': 'ritim; tempo; ölçü',
    '杰出': 'olağanüstü; üstün',
    '结晶': 'kristal; kristalleşmek',
    '结局': 'son; bitiş; sonuç',
    '结算': 'hesap kapatmak; ödeme yapmak',
    '截止': 'bitiş; son gün',
    '截至': '-e kadar; belirtilen tarihe kadar',
    '竭尽全力': 'tüm çabayı göstermek',
    '解除': 'kaldırmak; görevden almak',
    '解放': 'özgürlüğe kavuşturmak',
    '解雇': 'işten çıkarmak; kovmak',
    '解剖': 'disekte etmek; anatomi',
    '解散': 'dağıtmak; feshetmek',
    '解体': 'parçalanmak; dağılmak',
    '戒备': 'tetikte olmak; savunmaya geçmek',
    '界限': 'sınır; hudut; limit',
    '借鉴': 'örnek almak; deneyimden yararlanmak',
    '借助': 'yardımını almak; kullanmak',
    '金融': 'bankacılık; finans',
    '津津有味': 'zevkle; istekle; büyük zevkle',
    '紧迫': 'acil; ivedi; çok önemli',
    '锦上添花': 'zaten güzel olan şeyi daha iyi yapmak',
    '进而': 've sonra; devam etmek',
    '进攻': 'saldırmak; taarruz etmek',
    '进化': 'evrim; evrimleşmek',
    '进展': 'ilerleme; gelişme',
    '近来': 'son zamanlarda',
    '晋升': 'terfi etmek; yükseltmek',
    '浸泡': 'ıslatmak; suda bekletmek',
    '茎': 'sap; gövde',
    '经费': 'ödenek; gider',
    '经纬': 'boylam ve enlem',
    '惊动': 'uyandırmak; telaşlandırmak',
    '惊奇': 'şaşırtmak; hayrete düşmek',
    '惊讶': 'şaşırmak; hayrete düşmek',
    '兢兢业业': 'dikkatli ve özenli; titiz çalışmak',
    '精打细算': 'dikkatli planlama ve hesap',
    '精华': 'özü; en iyi kısmı',
    '精简': 'sadeleştirmek; azaltmak',
    '精密': 'hassas; kesin; ayrıntılı',
    '精确': 'doğru; kesin; hassas',
    '精通': 'ustalaşmak; hakim olmak',
    '精心': 'büyük özene; titizlikle',
    '精益求精': 'mükemmeliyetçilik; daha iyi olmak',
    '精致': 'zarif; narin; ince',
    '井': 'kuyu',
    '颈椎': 'boyun omuru',
    '警告': 'uyarmak; ikaz etmek',
    '警惕': 'tetikte olmak; dikkatli olmak',
    '竞赛': 'yarışma; müsabaka',
}

with open(DART_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

COUNT = [0]

def replace_tr(m):
    full = m.group(0)
    simp = m.group(1)
    tr_val = TR.get(simp, '')
    if not tr_val:
        return full
    COUNT[0] += 1
    tr_escaped = tr_val.replace("'", "\\'")
    return full[:-4] + f"'{tr_escaped}'],"

pattern = r"\['((?:[^'\\]|\\.)*)',\s*'(?:[^'\\]|\\.)*',\s*'(?:[^'\\]|\\.)*',\s*'(?:[^'\\]|\\.)*',\s*''\],"
result = re.sub(pattern, replace_tr, content)

with open(DART_FILE, 'w', encoding='utf-8') as f:
    f.write(result)

print(f'Done — {COUNT[0]} entries updated.')
