# Extracts the Turkish and English landmark texts out of cities.dart into
# lib/core/constants/landmarks/landmarks_tr.dart / landmarks_en.dart so every
# landmark language pack lives in one folder (Korean comes from Gemini via
# tools/gen_ko_landmarks.py). cities.dart stays the canonical source for TR/EN.
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "lib", "core", "constants", "cities.dart")
OUT_DIR = os.path.join(ROOT, "lib", "core", "constants", "landmarks")

DSTR = r"('(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\")"

def dart_str(m):
    q = m[0]
    return m[1:-1].replace("\\" + q, q).replace("\\\\", "\\")

def parse():
    src = open(SRC, encoding="utf-8").read()
    map_m = re.search(r"kCityLandmarks\s*=\s*\{(.*)\n\};", src, re.S)
    body = map_m.group(1)
    entries = []
    for cm in re.finditer(r"'(\w+)':\s*\[", body):
        slug = cm.group(1)
        seg_start = cm.end()
        nxt = re.search(r"'\w+':\s*\[", body[seg_start:])
        seg = body[seg_start:seg_start + nxt.start()] if nxt else body[seg_start:]
        for lm in re.finditer(
                r"Landmark\(\s*icon:\s*" + DSTR +
                r".*?nameTr:\s*" + DSTR +
                r".*?nameEn:\s*" + DSTR +
                r".*?descTr:\s*" + DSTR +
                r".*?descEn:\s*" + DSTR, seg, re.S):
            entries.append({
                "key": f"{slug}/{dart_str(lm.group(1))}",
                "nameTr": dart_str(lm.group(2)),
                "nameEn": dart_str(lm.group(3)),
                "descTr": dart_str(lm.group(4)),
                "descEn": dart_str(lm.group(5)),
            })
    return entries

def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")

def write_pack(lang, name_key, desc_key, entries):
    lines = [
        f"// GENERATED by tools/gen_landmark_packs.py from cities.dart — the",
        f"// {lang.upper()} landmark text pack, keyed by '<citySlug>/<icon>'.",
        "// Edit cities.dart and regenerate; do not hand-edit entries here.",
        "",
        f"const Map<String, (String name{lang.capitalize()}, String desc{lang.capitalize()})> kLandmark{lang.capitalize()} = {{",
    ]
    for e in entries:
        lines.append(
            f"  '{e['key']}': ('{esc(e[name_key])}', '{esc(e[desc_key])}'),")
    lines.append("};")
    lines.append("")
    path = os.path.join(OUT_DIR, f"landmarks_{lang}.dart")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {path} with {len(entries)} entries")

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    entries = parse()
    print(f"parsed {len(entries)} landmarks")
    write_pack("tr", "nameTr", "descTr", entries)
    write_pack("en", "nameEn", "descEn", entries)

if __name__ == "__main__":
    main()
