# Generates lib/core/constants/ko_landmarks.dart: Korean names/descriptions
# for every city landmark, translated from the English fields in cities.dart
# via the ko-batch edge function. Keyed by '<citySlug>/<icon>'.
import json
import os
import re
import time
import urllib.request
import urllib.error

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT = "pqyceostpukueydwuiut"
FN_URL = f"https://{PROJECT}.supabase.co/functions/v1/ko-batch"
GUARD = "sinoma-ko-backfill-2026"
SRC = os.path.join(ROOT, "lib", "core", "constants", "cities.dart")
OUT = os.path.join(ROOT, "lib", "core", "constants", "landmarks",
                   "landmarks_ko.dart")

# Each model has its own free-tier quota bucket — rotate when one runs dry.
MODELS = ["gemini-flash-lite-latest", "gemini-flash-latest",
          "gemini-2.5-flash", "gemini-2.5-flash-lite"]
model_i = 0

def call_fn(prompt):
    global model_i
    for attempt in range(10):
        data = json.dumps({"prompt": prompt, "temperature": 0.2,
                           "model": MODELS[model_i % len(MODELS)]
                           }).encode("utf-8")
        req = urllib.request.Request(
            FN_URL, data=data,
            headers={"Content-Type": "application/json",
                     "x-backfill-guard": GUARD,
                     "User-Agent": "Mozilla/5.0 (sinoma-ko-landmarks)"},
            method="POST")
        try:
            with urllib.request.urlopen(req, timeout=300) as r:
                out = json.loads(r.read().decode("utf-8"))
            return json.loads(out["text"])
        except Exception as ex:
            print(f"  fn err [{MODELS[model_i % len(MODELS)]}]: {ex}",
                  flush=True)
            model_i += 1
            time.sleep(5)
    return {}

def dart_str(m):
    # Strip the surrounding quote pair and unescape.
    q = m[0]
    return m[1:-1].replace("\\" + q, q).replace("\\\\", "\\")

# A Dart string literal with either quote type.
DSTR = r"('(?:[^'\\]|\\.)*'|\"(?:[^\"\\]|\\.)*\")"

def parse():
    src = open(SRC, encoding="utf-8").read()
    # City sections inside kCityLandmarks
    map_m = re.search(r"kCityLandmarks\s*=\s*\{(.*)\n\};", src, re.S)
    body = map_m.group(1)
    entries = []
    for cm in re.finditer(r"'(\w+)':\s*\[", body):
        slug = cm.group(1)
        seg_start = cm.end()
        nxt = re.search(r"'\w+':\s*\[", body[seg_start:])
        seg = body[seg_start:seg_start + nxt.start()] if nxt else body[seg_start:]
        for lm in re.finditer(
                r"Landmark\(\s*icon:\s*" + DSTR +
                r".*?nameEn:\s*" + DSTR +
                r".*?descEn:\s*" + DSTR, seg, re.S):
            icon, name_en, desc_en = (dart_str(lm.group(1)),
                                      dart_str(lm.group(2)),
                                      dart_str(lm.group(3)))
            entries.append({"key": f"{slug}/{icon}",
                            "name": name_en, "desc": desc_en})
    return entries

PROMPT = (
    "You are a professional Korean travel-guide editor. Translate each "
    "Chinese-city landmark entry into natural Korean for a Korean audience "
    "of a language-learning app.\n"
    "- name: the Korean name of the landmark/dish/custom as Koreans actually "
    "call it (use established Korean exonyms, e.g. 자금성, 만리장성, 칭다오 맥주, "
    "훠궈; transliterate otherwise).\n"
    "- desc: one natural Korean sentence in 해요체 conveying the same fact. "
    "No translationese.\n"
    "Return ONLY JSON: {\"<key>\": {\"name\": \"...\", \"desc\": \"...\"}}\n\n"
    "Entries:\n")

def main():
    entries = parse()
    print(f"parsed {len(entries)} landmarks", flush=True)
    results = {}
    for _pass in range(4):
        todo = [e for e in entries if e["key"] not in results]
        if not todo:
            break
        for i in range(0, len(todo), 15):
            batch = todo[i:i + 15]
            lines = "\n".join(
                f"- key:{e['key']} name_en:\"{e['name']}\" desc_en:\"{e['desc']}\""
                for e in batch)
            out = call_fn(PROMPT + lines)
            for e in batch:
                v = out.get(e["key"])
                if isinstance(v, dict) and v.get("name"):
                    results[e["key"]] = (str(v["name"]).strip(),
                                         str(v.get("desc") or "").strip())
            print(f"translated {len(results)}/{len(entries)}", flush=True)
            time.sleep(4)

    def esc(s):
        return s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")

    lines = [
        "// GENERATED by tools/gen_ko_landmarks.py — Korean landmark texts,",
        "// keyed by '<citySlug>/<icon>'. Regenerate with the script; do not",
        "// hand-edit individual entries.",
        "",
        "const Map<String, (String nameKo, String descKo)> kLandmarkKo = {",
    ]
    for e in entries:
        if e["key"] in results:
            n, d = results[e["key"]]
            lines.append(f"  '{e['key']}': ('{esc(n)}', '{esc(d)}'),")
    lines.append("};")
    lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} with {len(results)} entries", flush=True)

if __name__ == "__main__":
    main()
