/// HSK Level 1 — 300 vocabulary entries.
/// Each row: [simplified, pinyin, pos, en, tr, ko]
/// pos (part of speech): verb, noun, adjective, adverb, pronoun, number,
///   classifier, auxiliary, prefix, suffix, conjunction, preposition,
///   interjection, expression
const List<List<String>> kHsk1Words = [
  ['爱',   'ài',          'verb',        'to love',                              'sevmek', '사랑하다'],
  ['八',   'bā',          'number',      'eight',                                'sekiz', '팔(8)'],
  ['爸爸', 'bàba',        'noun',        'dad',                                  'baba', '아빠'],
  ['吧',   'ba',          'auxiliary',   'suggestion/confirmation particle',      'öneri/onay partikülü', '~하지? (제안이나 추측의 어기 조사)'],
  ['白天', 'báitiān',     'noun',        'daytime',                              'gündüz', '낮'],
  ['百',   'bǎi',         'number',      'hundred',                              'yüz', '백'],
  ['半',   'bàn',         'number',      'half',                                 'yarım', '반, 절반'],
  ['包子', 'bāozi',       'noun',        'steamed stuffed bun',                  'buharda pişmiş dolma çörek', '바오쯔(중국식 찐빵)'],
  ['杯子', 'bēizi',       'noun',        'cup, glass',                           'bardak, kupa', '컵, 잔'],
  ['本',   'běn',         'classifier',  'measure word for books',               'kitaplar için sayı sözcüğü', '권 (책을 세는 단위)'],
  ['边',   'biān',        'noun',        'side',                                 'yan, kenar', '가, 옆, 쪽'],
  ['病',   'bìng',        'noun',        'illness, disease; to be ill',          'hastalık; hasta olmak', '병, 질병, 아프다'],
  ['不',   'bù',          'adverb',      'not, no',                              'değil, hayır', '아니, 안, 못'],
  ['不客气','bú kèqi',    'expression',  "you're welcome",                       'rica ederim', '천만에요'],
  ['不要', 'búyào',       'adverb',      "don't, not want",                      'yapma, istemiyorum', '하지 마라, 원하지 않다'],
  ['菜',   'cài',         'noun',        'vegetable, dish',                      'sebze, yemek', '채소, 요리, 반찬'],
  ['茶',   'chá',         'noun',        'tea',                                  'çay', '차'],
  ['唱',   'chàng',       'verb',        'to sing',                              'şarkı söylemek', '노래하다'],
  ['超市', 'chāoshì',     'noun',        'supermarket',                          'süpermarket', '슈퍼마켓'],
  ['车',   'chē',         'noun',        'vehicle, car',                         'araç, araba', '차, 자동차'],
  ['吃',   'chī',         'verb',        'to eat',                               'yemek', '먹다'],
  ['出租车','chūzūchē',   'noun',        'taxi',                                 'taksi', '택시'],
  ['穿',   'chuān',       'verb',        'to wear',                              'giymek', '입다, 신다'],
  ['打电话','dǎ diànhuà', 'expression',  'to make a phone call',                 'telefon etmek', '전화하다'],
  ['大',   'dà',          'adjective',   'big',                                  'büyük', '크다'],
  ['大家', 'dàjiā',       'pronoun',     'everyone',                             'herkes', '여러분, 모두'],
  ['大学', 'dàxué',       'noun',        'university',                           'üniversite', '대학교'],
  ['大学生','dàxuéshēng', 'noun',        'university student',                   'üniversite öğrencisi', '대학생'],
  ['到',   'dào',         'verb',        'to arrive',                            'varmak, ulaşmak', '도착하다, 이르다'],
  ['的',   'de',          'auxiliary',   'possessive/modifying particle',        'iyelik/belirtme partikülü', '~의 (관형격 조사), ~하는 (관형절 표지)'],
  ['第',   'dì',          'prefix',      'ordinal number prefix',                'sıra sayısı öneki', '제~ (서수 접두사)'],
  ['弟弟', 'dìdi',        'noun',        'younger brother',                      'küçük erkek kardeş', '남동생'],
  ['点',   'diǎn',        'classifier',  'measure word; point, dot',             'sayı sözcüğü; nokta', '시 (시간), 점, 방울'],
  ['店',   'diàn',        'noun',        'shop, store',                          'dükkan, mağaza', '가게, 상점'],
  ['电话', 'diànhuà',     'noun',        'telephone, phone call',                'telefon', '전화, 통화'],
  ['电脑', 'diànnǎo',     'noun',        'computer',                             'bilgisayar', '컴퓨터'],
  ['电视', 'diànshì',     'noun',        'television',                           'televizyon', '텔레비전'],
  ['电影', 'diànyǐng',    'noun',        'movie, film',                          'film', '영화'],
  ['电影院','diànyǐngyuàn','noun',       'cinema',                               'sinema', '영화관'],
  ['东西', 'dōngxi',      'noun',        'thing, object',                        'şey, nesne', '물건, 것'],
  ['都',   'dōu, dū',         'adverb',      'all, both',                            'hepsi, ikisi de', '모두, 다'],
  ['读',   'dú',          'verb',        'to read',                              'okumak', '읽다, 공부하다'],
  ['读书', 'dúshū',       'verb',        'to read a book',                       'kitap okumak', '독서하다, 공부하다'],
  ['对',   'duì',         'adjective',   'correct, right',                       'doğru, haklı', '맞다, 옳다'],
  ['对不起','duìbuqǐ',    'verb',        'sorry',                                'özür dilerim', '미안하다'],
  ['多',   'duō',         'adjective',   'many, much',                           'çok, fazla', '많다'],
  ['多少', 'duōshao',     'pronoun',     'how many, how much',                   'ne kadar, kaç tane', '얼마, 몇'],
  ['儿子', 'érzi',        'noun',        'son',                                  'oğul', '아들'],
  ['二',   'èr',          'number',      'two',                                  'iki', '이, 둘'],
  ['饭',   'fàn',         'noun',        'cooked rice, meal',                    'pirinç, yemek', '밥, 식사'],
  ['饭店', 'fàndiàn',     'noun',        'restaurant',                           'restoran', '식당, 호텔'],
  ['房间', 'fángjiān',    'noun',        'room',                                 'oda', '방'],
  ['非常', 'fēicháng',    'adverb',      'very, extremely',                      'çok, son derece', '매우, 아주'],
  ['飞机', 'fēijī',       'noun',        'airplane',                             'uçak', '비행기'],
  ['分',   'fēn, fèn',         'classifier',  'minute; component, part',              'dakika; bileşen', '분(시간), 나누다'],
  ['分钟', 'fēnzhōng',    'classifier',  'minute',                               'dakika', '분(시간)'],
  ['高兴', 'gāoxìng',     'adjective',   'happy, glad',                          'mutlu, sevinçli', '기쁘다, 즐겁다'],
  ['歌',   'gē',          'noun',        'song',                                 'şarkı', '노래'],
  ['哥哥', 'gēge',        'noun',        'older brother',                        'ağabey', '형, 오빠'],
  ['个',   'gè',          'classifier',  'measure word for general objects',     'genel sayı sözcüğü', '개 (일반적인 양사)'],
  ['给',   'gěi',         'verb',        'to give; to, for',                     'vermek', '주다, ~에게, ~를 위하여'],
  ['公司', 'gōngsī',      'noun',        'company',                              'şirket', '회사'],
  ['工作', 'gōngzuò',     'noun',        'work; to work',                        'iş; çalışmak', '일, 일하다'],
  ['狗',   'gǒu',         'noun',        'dog',                                  'köpek', '개'],
  ['贵',   'guì',         'adjective',   'expensive',                            'pahalı', '비싸다, 귀하다'],
  ['国',   'guó',         'noun',        'country',                              'ülke', '나라, 국가'],
  ['还',   'hái, huán',         'adverb',      'still, also; quite',                   'hâlâ, ayrıca', '아직, 또한, 오히려'],
  ['孩子', 'háizi',       'noun',        'child',                                'çocuk', '아이, 자녀'],
  ['汉语', 'Hànyǔ',       'noun',        'Chinese language',                     'Çince', '중국어'],
  ['汉字', 'Hànzì',       'noun',        'Chinese character',                    'Çin karakteri', '한자'],
  ['好',   'hǎo, hào',         'adjective',   'good; well',                           'iyi; güzel', '좋다, 잘'],
  ['好吃', 'hǎochī',      'adjective',   'delicious, tasty',                     'lezzetli', '맛있다'],
  ['好看', 'hǎokàn',      'adjective',   'good-looking',                         'güzel görünümlü', '보기 좋다, 예쁘다'],
  ['好听', 'hǎotīng',     'adjective',   'pleasant to listen to',               'kulağa güzel gelen', '듣기 좋다'],
  ['好玩儿','hǎowánr',    'adjective',   'fun, amusing',                         'eğlenceli', '재미있다'],
  ['号',   'hào',         'noun',        'number; date',                         'numara; tarih', '번호, 날짜'],
  ['喝',   'hē',          'verb',        'to drink',                             'içmek', '마시다'],
  ['和',   'hé',          'conjunction', 'and, with',                            've, ile', '과/와, ~하고'],
  ['很',   'hěn',         'adverb',      'very',                                 'çok, gayet', '매우, 아주'],
  ['后',   'hòu',         'noun',        'behind, later',                        'arkasında, sonra', '뒤, 후'],
  ['回',   'huí',         'verb',        'to return',                            'dönmek', '돌아가다, 돌아오다'],
  ['会',   'huì, kuài',         'verb',        'can, to be able to',                   'yapabilmek', '할 줄 알다, ~할 것이다'],
  ['火车', 'huǒchē',      'noun',        'train',                                'tren', '기차'],
  ['鸡蛋', 'jīdàn',       'noun',        'egg',                                  'yumurta', '달걀'],
  ['几',   'jǐ, jī',          'pronoun',     'how many, a few',                      'kaç, birkaç', '몇, 얼마'],
  ['家',   'jiā',         'noun',        'home, family',                         'ev, aile', '집, 가족'],
  ['家人', 'jiārén',      'noun',        'family member',                        'aile üyesi', '가족'],
  ['见',   'jiàn',        'verb',        'to see',                               'görmek', '보다, 만나다'],
  ['件',   'jiàn',        'classifier',  'measure word for items',               'eşya sayı sözcüğü', '(의류나 사건 등을 세는) 단위'],
  ['饺子', 'jiǎozi',      'noun',        'dumpling',                             'jiaozi (Çin mantısı)', '만두'],
  ['叫',   'jiào',        'verb',        'to be called, to call',                'adı olmak, çağırmak', '부르다, ~라고 하다'],
  ['姐姐', 'jiějie',      'noun',        'older sister',                         'abla', '언니, 누나'],
  ['今年', 'jīnnián',     'noun',        'this year',                            'bu yıl', '올해'],
  ['今天', 'jīntiān',     'noun',        'today',                                'bugün', '오늘'],
  ['九',   'jiǔ',         'number',      'nine',                                 'dokuz', '구, 아홉'],
  ['觉得', 'juéde',       'verb',        'to feel, to think',                    'hissetmek, düşünmek', '느끼다, 생각하다'],
  ['开',   'kāi',         'verb',        'to open',                              'açmak', '열다'],
  ['开车', 'kāichē',      'verb',        'to drive',                             'araba sürmek', '운전하다'],
  ['看',   'kàn',         'verb',        'to see, to look',                      'bakmak, görmek', '보다, 읽다'],
  ['看病', 'kànbìng',     'verb',        'to see a doctor',                      'doktora gitmek', '진찰받다, 병원에 가다'],
  ['看见', 'kànjiàn',     'verb',        'to see',                               'görmek', '보다, 눈에 띄다'],
  ['可以', 'kěyǐ',        'verb',        'can, may; okay, fine',                 'yapabilmek; olur', '할 수 있다, 괜찮다'],
  ['课',   'kè',          'noun',        'class, lesson',                        'ders', '수업, 과목'],
  ['口',   'kǒu',         'noun',        'mouth',                                'ağız', '입'],
  ['块',   'kuài',        'classifier',  'measure word for pieces; yuan',        'parça sayı sözcüğü; yuan', '덩어리(양사), 위안(화폐 단위)'],
  ['来',   'lái',         'verb',        'to come',                              'gelmek', '오다'],
  ['老师', 'lǎoshī',      'noun',        'teacher',                              'öğretmen', '선생님'],
  ['了',   'le, liǎo',          'auxiliary',   'completed action particle',            'tamamlanan eylem partikülü', '완료의 어기조사'],
  ['冷',   'lěng',        'adjective',   'cold',                                 'soğuk', '춥다'],
  ['里',   'lǐ',          'noun',        'inside, in',                           'içinde, içeri', '안, 속'],
  ['两',   'liǎng',       'number',      'two (for quantities)',                 'iki (miktar için)', '둘, 두 (수량)'],
  ['零',   'líng',        'number',      'zero',                                 'sıfır', '영, 0'],
  ['六',   'liù',         'number',      'six',                                  'altı', '육(6)'],
  ['妈妈', 'māma',        'noun',        'mom',                                  'anne', '엄마'],
  ['吗',   'ma',          'auxiliary',   'question particle',                    'soru partikülü', '~인가? (의문 조사)'],
  ['买',   'mǎi',         'verb',        'to buy',                               'satın almak', '사다'],
  ['卖',   'mài',         'verb',        'to sell',                              'satmak', '팔다'],
  ['忙',   'máng',        'adjective',   'busy',                                 'meşgul', '바쁘다'],
  ['猫',   'māo',         'noun',        'cat',                                  'kedi', '고양이'],
  ['没关系','méi guānxi', 'expression',  "never mind, it's okay",                'önemli değil, olsun', '관계없다, 괜찮다'],
  ['没事', 'méishì',      'expression',  "it doesn't matter",                   'önemli değil', '괜찮다, 아무 일 없다'],
  ['没有', 'méiyǒu',      'verb',        'to not have; have not',               'yok, olmamak', '없다, 가지지 않다'],
  ['妹妹', 'mèimei',      'noun',        'younger sister',                       'küçük kız kardeş', '여동생'],
  ['们',   'men',         'suffix',      'plural suffix',                        'çoğul eki', '복수 접미사'],
  ['米饭', 'mǐfàn',       'noun',        'cooked rice',                          'pişmiş pirinç', '밥'],
  ['面包', 'miànbāo',     'noun',        'bread',                                'ekmek', '빵'],
  ['面条儿','miàntiáor',  'noun',        'noodles',                              'erişte', '국수'],
  ['明年', 'míngnián',    'noun',        'next year',                            'gelecek yıl', '내년'],
  ['明天', 'míngtiān',    'noun',        'tomorrow',                             'yarın', '내일'],
  ['名字', 'míngzi',      'noun',        'name',                                 'isim, ad', '이름'],
  ['哪',   'nǎ',          'pronoun',     'which',                                'hangi', '어느'],
  ['哪个', 'nǎge',        'pronoun',     'which one',                            'hangisi', '어느 것'],
  ['哪里', 'nǎlǐ',        'pronoun',     'where',                                'nerede', '어디'],
  ['哪儿', 'nǎr',         'pronoun',     'where',                                'nerede', '어디'],
  ['哪些', 'nǎxiē',       'pronoun',     'which ones',                           'hangileri', '어느 것들'],
  ['那',   'nà',          'pronoun',     'that',                                 'o, şu', '그, 저, 그것, 저것'],
  ['那边', 'nàbiān',      'pronoun',     'over there',                           'orada, şurada', '그쪽, 저쪽'],
  ['那个', 'nàge',        'pronoun',     'that one',                             'o, şu', '그것, 저것'],
  ['那里', 'nàlǐ',        'pronoun',     'there',                                'orada', '거기, 저기'],
  ['那儿', 'nàr',         'pronoun',     'there',                                'orada', '거기, 저기'],
  ['那些', 'nàxiē',       'pronoun',     'those',                                'onlar, şunlar', '그것들, 저것들'],
  ['男',   'nán',         'adjective',   'male',                                 'erkek', '남자의, 남성의'],
  ['男朋友','nánpéngyou', 'noun',        'boyfriend',                            'erkek arkadaş', '남자친구'],
  ['呢',   'ne',          'auxiliary',   'continuation/question particle',       'soru/devam partikülü', '~은/는? (의문 조사), ~하고 있다 (진행 어기 조사)'],
  ['能',   'néng',        'verb',        'can, be able to',                      'yapabilmek', '할 수 있다, ~해도 되다'],
  ['你',   'nǐ',          'pronoun',     'you',                                  'sen', '너, 당신'],
  ['你好', 'nǐ hǎo',      'expression',  'hello',                                'merhaba', '안녕하세요'],
  ['你们', 'nǐmen',       'pronoun',     'you (plural)',                         'siz', '너희들, 당신들'],
  ['年',   'nián',        'noun',        'year',                                 'yıl', '년, 해'],
  ['您',   'nín',         'pronoun',     'you (formal)',                         'siz (saygılı)', '당신 (높임말)'],
  ['牛奶', 'niúnǎi',      'noun',        'milk',                                 'süt', '우유'],
  ['女',   'nǚ',          'adjective',   'female',                               'kadın, kız', '여자'],
  ['女儿', 'nǚér',        'noun',        'daughter',                             'kız', '딸'],
  ['女朋友','nǚpéngyou',  'noun',        'girlfriend',                           'kız arkadaş', '여자친구'],
  ['女士', 'nǚshì',       'noun',        'lady, Ms.',                            'hanım, bayan', '여사, 숙녀'],
  ['朋友', 'péngyou',     'noun',        'friend',                               'arkadaş, dost', '친구'],
  ['便宜', 'piányi',      'adjective',   'cheap',                                'ucuz', '싸다'],
  ['漂亮', 'piàoliang',   'adjective',   'beautiful',                            'güzel', '예쁘다, 아름답다'],
  ['苹果', 'píngguǒ',     'noun',        'apple',                                'elma', '사과'],
  ['七',   'qī',          'number',      'seven',                                'yedi', '칠, 일곱'],
  ['起床', 'qǐchuáng',    'verb',        'to get up',                            'kalkmak, uyanmak', '일어나다, 기상하다'],
  ['千',   'qiān',        'number',      'thousand',                             'bin', '천'],
  ['前',   'qián',        'noun',        'front, before',                        'önde, önce', '앞, 전'],
  ['钱',   'qián',        'noun',        'money',                                'para', '돈'],
  ['请',   'qǐng',        'verb',        'please; to invite',                    'lütfen; davet etmek', '청하다, 부탁하다, ~해 주십시오'],
  ['请问', 'qǐngwèn',     'expression',  'may I ask',                            'özür dilerim, bir sorum var', '말씀 좀 묻겠습니다'],
  ['去',   'qù',          'verb',        'to go',                                'gitmek', '가다'],
  ['去年', 'qùnián',      'noun',        'last year',                            'geçen yıl', '작년'],
  ['热',   'rè',          'adjective',   'hot',                                  'sıcak', '덥다, 뜨겁다'],
  ['人',   'rén',         'noun',        'person',                               'kişi, insan', '사람'],
  ['认识', 'rènshi',      'verb',        'to know, to recognize',                'tanımak', '알다, 인식하다'],
  ['日',   'rì',          'classifier',  'measure word for days; sun',           'gün sayı sözcüğü; güneş', '날, 일, 해'],
  ['三',   'sān',         'number',      'three',                                'üç', '삼, 셋'],
  ['商店', 'shāngdiàn',   'noun',        'store, shop',                          'mağaza, dükkan', '상점, 가게'],
  ['上',   'shàng',       'noun',        'up, above',                            'yukarı, üst', '위, 상'],
  ['上班', 'shàngbān',    'verb',        'to go to work',                        'işe gitmek', '출근하다'],
  ['上课', 'shàngkè',     'verb',        'to attend class',                      'derse girmek', '수업하다, 수업을 듣다'],
  ['上午', 'shàngwǔ',     'noun',        'morning',                              'sabah (09:00-12:00)', '오전'],
  ['上学', 'shàngxué',    'verb',        'to go to school',                      'okula gitmek', '등교하다, 학교에 다니다'],
  ['少',   'shǎo, shào',        'adjective',   'few, little',                          'az', '적다'],
  ['谁',   'shéi',        'pronoun',     'who',                                  'kim', '누구'],
  ['什么', 'shénme',      'pronoun',     'what',                                 'ne', '무엇, 무슨'],
  ['生病', 'shēngbìng',   'verb',        'to get sick',                          'hastalanmak', '병나다, 아프다'],
  ['十',   'shí',         'number',      'ten',                                  'on', '십, 열'],
  ['时候', 'shíhou',      'noun',        'moment, time',                         'an, zaman', '때, 시간'],
  ['时间', 'shíjiān',     'noun',        'time',                                 'zaman', '시간, 때'],
  ['事',   'shì',         'noun',        'matter, thing',                        'mesele, şey', '일, 사건'],
  ['是',   'shì',         'verb',        'to be',                                'olmak', '이다'],
  ['手机', 'shǒujī',      'noun',        'cell phone',                           'cep telefonu', '휴대전화'],
  ['书',   'shū',         'noun',        'book',                                 'kitap', '책'],
  ['书店', 'shūdiàn',     'noun',        'bookstore',                            'kitapçı', '서점'],
  ['水',   'shuǐ',        'noun',        'water',                                'su', '물'],
  ['水果', 'shuǐguǒ',     'noun',        'fruit',                                'meyve', '과일'],
  ['睡',   'shuì',        'verb',        'to sleep',                             'uyumak', '자다'],
  ['睡觉', 'shuìjiào',    'verb',        'to sleep',                             'uyumak', '자다'],
  ['说',   'shuō',        'verb',        'to speak, to say',                     'konuşmak, söylemek', '말하다'],
  ['说话', 'shuōhuà',     'verb',        'to talk',                              'konuşmak', '말하다, 이야기하다'],
  ['四',   'sì',          'number',      'four',                                 'dört', '사(4)'],
  ['岁',   'suì',         'classifier',  'measure word for age',                 'yaşında (sayı sözcüğü)', '살 (나이 단위)'],
  ['他',   'tā',          'pronoun',     'he, him',                              'o (erkek)', '그'],
  ['它',   'tā',          'pronoun',     'it',                                   'o (nesne)', '그것'],
  ['她',   'tā',          'pronoun',     'she, her',                             'o (kadın)', '그녀'],
  ['他们', 'tāmen',       'pronoun',     'they (male/mixed)',                    'onlar (erkek/karma)', '그들'],
  ['它们', 'tāmen',       'pronoun',     'they (objects)',                       'onlar (nesneler)', '그것들'],
  ['她们', 'tāmen',       'pronoun',     'they (female)',                        'onlar (kadın)', '그녀들'],
  ['太',   'tài',         'adverb',      'too, extremely',                       'çok fazla, aşırı', '너무, 대단히'],
  ['天',   'tiān',        'noun',        'day; sky',                             'gün; gökyüzü', '하늘, 날, 하루'],
  ['天气', 'tiānqì',      'noun',        'weather',                              'hava durumu', '날씨'],
  ['听',   'tīng',        'verb',        'to listen',                            'dinlemek', '듣다'],
  ['听见', 'tīngjiàn',    'verb',        'to hear',                              'duymak', '들리다'],
  ['同学', 'tóngxué',     'noun',        'classmate',                            'sınıf arkadaşı', '학우, 동창'],
  ['外',   'wài',         'noun',        'outside, exterior',                    'dışarı, dış', '밖, 외부'],
  ['外边', 'wàibian',     'noun',        'outside',                              'dışarıda', '밖, 바깥쪽'],
  ['玩',   'wán',         'verb',        'to play',                              'oynamak', '놀다, 장난하다'],
  ['晚',   'wǎn',         'adjective',   'late',                                 'geç', '늦다'],
  ['晚饭', 'wǎnfàn',      'noun',        'dinner',                               'akşam yemeği', '저녁 식사'],
  ['晚上', 'wǎnshang',    'noun',        'evening',                              'akşam', '저녁, 밤'],
  ['喂',   'wèi',         'interjection','hello (on the phone)',                 'alo', '여보세요'],
  ['问',   'wèn',         'verb',        'to ask',                               'sormak', '묻다, 질문하다'],
  ['问题', 'wèntí',       'noun',        'question, problem',                    'soru, sorun', '질문, 문제'],
  ['我',   'wǒ',          'pronoun',     'I, me',                                'ben', '나, 저'],
  ['我们', 'wǒmen',       'pronoun',     'we, us',                               'biz', '우리'],
  ['五',   'wǔ',          'number',      'five',                                 'beş', '오, 다섯'],
  ['午饭', 'wǔfàn',       'noun',        'lunch',                                'öğle yemeği', '점심'],
  ['喜欢', 'xǐhuan',      'verb',        'to like',                              'beğenmek, sevmek', '좋아하다'],
  ['下',   'xià',         'noun',        'down, below',                          'aşağı, alt', '아래, 하'],
  ['下雨', 'xià yǔ',      'expression',  'to rain',                              'yağmur yağmak', '비가 오다'],
  ['下班', 'xiàbān',      'verb',        'to get off work',                      'işten çıkmak', '퇴근하다'],
  ['下课', 'xiàkè',       'verb',        'to finish class',                      'dersten çıkmak', '수업을 마치다'],
  ['下午', 'xiàwǔ',       'noun',        'afternoon',                            'öğleden sonra', '오후'],
  ['先生', 'xiānsheng',   'noun',        'Mr., husband',                         'bay, koca', '선생, 남편'],
  ['现在', 'xiànzài',     'noun',        'now',                                  'şimdi', '현재, 지금'],
  ['想',   'xiǎng',       'verb',        'to think; to want',                    'düşünmek; istemek', '생각하다, ~하고 싶다'],
  ['小',   'xiǎo',        'adjective',   'small',                                'küçük', '작다'],
  ['小朋友','xiǎopéngyǒu','noun',        'little friend, child',                 'çocuk, küçük arkadaş', '어린이'],
  ['小时', 'xiǎoshí',     'noun',        'hour',                                 'saat', '시간'],
  ['小学', 'xiǎoxué',     'noun',        'primary school',                       'ilkokul', '초등학교'],
  ['小学生','xiǎoxuéshēng','noun',       'primary school student',               'ilkokul öğrencisi', '초등학생'],
  ['些',   'xiē',         'classifier',  'some (indefinite amount)',             'biraz, bazı', '약간, 조금 (수량)'],
  ['写',   'xiě',         'verb',        'to write',                             'yazmak', '쓰다'],
  ['谢谢', 'xièxie',      'verb',        'to thank',                             'teşekkür etmek', '감사하다, 고맙다'],
  ['新',   'xīn',         'adjective',   'new',                                  'yeni', '새롭다'],
  ['星期', 'xīngqī',      'noun',        'week',                                 'hafta', '주, 요일'],
  ['星期日','xīngqīrì',   'noun',        'Sunday',                               'Pazar', '일요일'],
  ['星期天','xīngqītiān', 'noun',        'Sunday',                               'Pazar', '일요일'],
  ['休息', 'xiūxi',       'verb',        'to rest',                              'dinlenmek', '쉬다, 휴식하다'],
  ['学',   'xué',         'verb',        'to learn, to study',                   'öğrenmek', '배우다, 공부하다'],
  ['学生', 'xuéshēng',    'noun',        'student',                              'öğrenci', '학생'],
  ['学习', 'xuéxí',       'verb',        'to study',                             'çalışmak, öğrenmek', '공부하다'],
  ['学校', 'xuéxiào',     'noun',        'school',                               'okul', '학교'],
  ['雪',   'xuě',         'noun',        'snow',                                 'kar', '눈'],
  ['要',   'yào, yāo',         'verb',        'to want, to need',                     'istemek, lazım olmak', '원하다, 필요하다, ~하려고 하다'],
  ['也',   'yě',          'adverb',      'also, too',                            'de, da', '또한, 역시'],
  ['一',   'yī',          'number',      'one',                                  'bir', '일, 하나'],
  ['衣服', 'yīfu',        'noun',        'clothes',                              'kıyafet, giysi', '옷'],
  ['医生', 'yīshēng',     'noun',        'doctor',                               'doktor', '의사'],
  ['医院', 'yīyuàn',      'noun',        'hospital',                             'hastane', '병원'],
  ['一半', 'yíbàn',       'number',      'half',                                 'yarısı', '절반, 반'],
  ['一下', 'yíxià',       'expression',  'once, a little; briefly',              'bir kere, biraz', '한번, 잠시, 조금'],
  ['椅子', 'yǐzi',        'noun',        'chair',                                'sandalye', '의자'],
  ['一点儿','yìdiǎnr',    'expression',  'a little, a bit',                      'biraz, az miktarda', '조금, 약간'],
  ['一些', 'yìxiē',       'expression',  'some, a few',                          'biraz, birkaç', '조금, 약간, 얼마간'],
  ['有',   'yǒu',         'verb',        'to have, to exist',                    'olmak, sahip olmak', '있다, 가지다'],
  ['有的', 'yǒude',       'pronoun',     'some of them',                         'bazıları', '어떤 것, 일부'],
  ['有点儿','yǒudiǎnr',   'adverb',      'a little, slightly',                   'biraz, hafifçe', '조금, 약간'],
  ['有些', 'yǒuxiē',      'pronoun',     'some, some of',                        'bazıları, biraz', '어떤, 얼마간의'],
  ['雨',   'yǔ',          'noun',        'rain',                                 'yağmur', '비'],
  ['元',   'yuán',        'classifier',  'yuan (currency)',                      'yuan (Çin para birimi)', '위안 (화폐 단위)'],
  ['月',   'yuè',         'noun',        'month; moon',                          'ay', '달, 월'],
  ['再',   'zài',         'adverb',      'again, then',                          'tekrar, yeniden', '다시, 또'],
  ['在',   'zài',         'verb',        'to be at; at; in the middle of',       '-de/-da; bulunmak', '있다, ~에(서)'],
  ['再见', 'zàijiàn',     'verb',        'goodbye',                              'hoşça kal, güle güle', '안녕히 가세요, 안녕히 계세요'],
  ['早',   'zǎo',         'adjective',   'early',                                'erken', '이르다'],
  ['早饭', 'zǎofàn',      'noun',        'breakfast',                            'kahvaltı', '아침밥'],
  ['早上', 'zǎoshang',    'noun',        'morning (early)',                      'sabah (erken)', '아침'],
  ['怎么', 'zěnme',       'pronoun',     'how',                                  'nasıl', '어떻게, 어째서'],
  ['怎么样','zěnmeyàng',  'pronoun',     'how about, what do you think',         'nasıl, ne düşünüyorsun', '어떠하다'],
  ['找',   'zhǎo',        'verb',        'to look for',                          'aramak', '찾다'],
  ['这',   'zhè',         'pronoun',     'this',                                 'bu', '이, 이것'],
  ['这边', 'zhèbiān',     'pronoun',     'here',                                 'burada', '이쪽'],
  ['这个', 'zhège',       'pronoun',     'this one',                             'bu', '이것'],
  ['这里', 'zhèlǐ',       'pronoun',     'here',                                 'burada', '여기'],
  ['这儿', 'zhèr',        'pronoun',     'here',                                 'burada', '여기'],
  ['这些', 'zhèxiē',      'pronoun',     'these',                                'bunlar', '이것들'],
  ['真',   'zhēn',        'adverb',      'really; true',                         'gerçekten; doğru', '정말, 참'],
  ['正在', 'zhèngzài',    'adverb',      'in the process of',                    '-iyor/-ıyor (şu an)', '진행 중이다, 한창 ~하고 있다'],
  ['只',   'zhǐ, zhī',         'classifier',  'measure word for animals',             'hayvan sayı sözcüğü', '마리 (동물 단위)'],
  ['知道', 'zhīdào',      'verb',        'to know',                              'bilmek', '알다'],
  ['中国', 'Zhōngguó',    'noun',        'China',                                'Çin', '중국'],
  ['中文', 'Zhōngwén',    'noun',        'Chinese language (written)',           'Çince (yazılı)', '중국어'],
  ['中午', 'zhōngwǔ',     'noun',        'noon',                                 'öğle', '정오, 낮'],
  ['中学', 'zhōngxué',    'noun',        'middle school',                        'ortaokul', '중학교'],
  ['中学生','zhōngxuéshēng','noun',      'middle school student',                'ortaokul öğrencisi', '중학생'],
  ['住',   'zhù',         'verb',        'to live, to reside',                   'yaşamak, ikamet etmek', '살다, 거주하다'],
  ['桌子', 'zhuōzi',      'noun',        'table, desk',                          'masa', '탁자, 책상'],
  ['字',   'zì',          'noun',        'character, script',                    'karakter, harf', '글자'],
  ['昨天', 'zuótiān',     'noun',        'yesterday',                            'dün', '어제'],
  ['坐',   'zuò',         'verb',        'to sit',                               'oturmak', '앉다, (탈것을) 타다'],
  ['做',   'zuò',         'verb',        'to do, to make',                       'yapmak', '하다, 만들다'],
  ['做饭', 'zuò fàn',     'expression',  'to cook',                              'yemek pişirmek', '밥을 짓다, 요리하다'],
];
