/// HSK Level 1 — 300 vocabulary entries.
/// Each row: [simplified, pinyin, pos, en, tr, ko, ja, id, vi]
/// pos (part of speech): verb, noun, adjective, adverb, pronoun, number,
///   classifier, auxiliary, prefix, suffix, conjunction, preposition,
///   interjection, expression
const List<List<String>> kHsk1Words = [
  ['爱',   'ài',          'verb',        'to love',                              'sevmek', '사랑하다', '愛する、大好きだ', 'mencintai, menyukai', 'yêu'],
  ['八',   'bā',          'number',      'eight',                                'sekiz', '팔(8)', '八', 'delapan', 'tám'],
  ['爸爸', 'bàba',        'noun',        'dad',                                  'baba', '아빠', 'お父さん', 'ayah', 'bố, cha'],
  ['吧',   'ba',          'auxiliary',   'suggestion/confirmation particle',      'öneri/onay partikülü', '~하지? (제안이나 추측의 어기 조사)', '（提案や推測を表す助詞）', 'partikel saran atau konfirmasi', 'trợ từ biểu thị sự gợi ý hoặc phỏng đoán'],
  ['白天', 'báitiān',     'noun',        'daytime',                              'gündüz', '낮', '昼間', 'siang hari', 'ban ngày'],
  ['百',   'bǎi',         'number',      'hundred',                              'yüz', '백', '百', 'ratus', 'trăm'],
  ['半',   'bàn',         'number',      'half',                                 'yarım', '반, 절반', '半分、半', 'setengah', 'một nửa, rưỡi'],
  ['包子', 'bāozi',       'noun',        'steamed stuffed bun',                  'buharda pişmiş dolma çörek', '바오쯔(중국식 찐빵)', '包子（中華まん）', 'bakpao', 'bánh bao'],
  ['杯子', 'bēizi',       'noun',        'cup, glass',                           'bardak, kupa', '컵, 잔', 'コップ、グラス', 'cangkir, gelas', 'cái cốc, cái ly'],
  ['本',   'běn',         'classifier',  'measure word for books',               'kitaplar için sayı sözcüğü', '권 (책을 세는 단위)', '冊（本の量詞）', 'kata penggolong untuk buku', 'quyển, cuốn (lượng từ cho sách)'],
  ['边',   'biān',        'noun',        'side',                                 'yan, kenar', '가, 옆, 쪽', '側、あたり', 'sisi, tepi', 'bên, phía'],
  ['病',   'bìng',        'noun',        'illness, disease; to be ill',          'hastalık; hasta olmak', '병, 질병, 아프다', '病気、病気になる', 'penyakit, sakit', 'bệnh, ốm'],
  ['不',   'bù',          'adverb',      'not, no',                              'değil, hayır', '아니, 안, 못', '1、〜ない（否定の副詞）', 'tidak, bukan', 'không'],
  ['不客气','bú kèqi',    'expression',  "you're welcome",                       'rica ederim', '천만에요', '1、どういたしまして', 'sama-sama', 'không có chi, không khách sáo'],
  ['不要', 'búyào',       'adverb',      "don't, not want",                      'yapma, istemiyorum', '하지 마라, 원하지 않다', '1、〜するな、〜しないでください、いらない', 'jangan, tidak mau', 'đừng, không muốn'],
  ['菜',   'cài',         'noun',        'vegetable, dish',                      'sebze, yemek', '채소, 요리, 반찬', '野菜、料理', 'sayur, masakan', 'rau, món ăn'],
  ['茶',   'chá',         'noun',        'tea',                                  'çay', '차', '茶、お茶', 'teh', 'trà'],
  ['唱',   'chàng',       'verb',        'to sing',                              'şarkı söylemek', '노래하다', '歌う', 'menyanyi', 'hát'],
  ['超市', 'chāoshì',     'noun',        'supermarket',                          'süpermarket', '슈퍼마켓', 'スーパーマーケット', 'swalayan, supermarket', 'siêu thị'],
  ['车',   'chē',         'noun',        'vehicle, car',                         'araç, araba', '차, 자동차', '車、乗り物', 'kendaraan, mobil', 'xe'],
  ['吃',   'chī',         'verb',        'to eat',                               'yemek', '먹다', '食べる', 'makan', 'ăn'],
  ['出租车','chūzūchē',   'noun',        'taxi',                                 'taksi', '택시', 'タクシー', 'taksi', 'xe taxi'],
  ['穿',   'chuān',       'verb',        'to wear',                              'giymek', '입다, 신다', '着る、履く', 'memakai, mengenakan', 'mặc, đeo, xỏ'],
  ['打电话','dǎ diànhuà', 'expression',  'to make a phone call',                 'telefon etmek', '전화하다', '電話をかける', 'menelepon', 'gọi điện thoại'],
  ['大',   'dà',          'adjective',   'big',                                  'büyük', '크다', '大きい', 'besar', 'lớn'],
  ['大家', 'dàjiā',       'pronoun',     'everyone',                             'herkes', '여러분, 모두', '皆さん', 'semua orang', 'mọi người'],
  ['大学', 'dàxué',       'noun',        'university',                           'üniversite', '대학교', '大学', 'universitas', 'đại học'],
  ['大学生','dàxuéshēng', 'noun',        'university student',                   'üniversite öğrencisi', '대학생', '大学生', 'mahasiswa', 'sinh viên'],
  ['到',   'dào',         'verb',        'to arrive',                            'varmak, ulaşmak', '도착하다, 이르다', '着く、到着する', 'tiba, sampai', 'đến'],
  ['的',   'de',          'auxiliary',   'possessive/modifying particle',        'iyelik/belirtme partikülü', '~의 (관형격 조사), ~하는 (관형절 표지)', '〜の（連体修飾の助詞）', 'partikel kepemilikan atau penjelas', 'trợ từ sở hữu/định ngữ'],
  ['第',   'dì',          'prefix',      'ordinal number prefix',                'sıra sayısı öneki', '제~ (서수 접두사)', '〜番目（序数を表す接頭辞）', 'prefiks penanda urutan', 'tiền tố số thứ tự'],
  ['弟弟', 'dìdi',        'noun',        'younger brother',                      'küçük erkek kardeş', '남동생', '弟', 'adik laki-laki', 'em trai'],
  ['点',   'diǎn',        'classifier',  'measure word; point, dot',             'sayı sözcüğü; nokta', '시 (시간), 점, 방울', '時（時刻）、点、少し', 'satuan waktu, titik', 'giờ, điểm, chấm'],
  ['店',   'diàn',        'noun',        'shop, store',                          'dükkan, mağaza', '가게, 상점', '店', 'toko', 'cửa hàng, tiệm'],
  ['电话', 'diànhuà',     'noun',        'telephone, phone call',                'telefon', '전화, 통화', '電話', 'telepon, panggilan telepon', 'điện thoại, cuộc gọi'],
  ['电脑', 'diànnǎo',     'noun',        'computer',                             'bilgisayar', '컴퓨터', 'コンピュータ', 'komputer', 'máy tính'],
  ['电视', 'diànshì',     'noun',        'television',                           'televizyon', '텔레비전', 'テレビ', 'televisi', 'ti vi'],
  ['电影', 'diànyǐng',    'noun',        'movie, film',                          'film', '영화', '映画', 'film', 'phim'],
  ['电影院','diànyǐngyuàn','noun',       'cinema',                               'sinema', '영화관', '映画館', 'bioskop', 'rạp chiếu phim'],
  ['东西', 'dōngxi',      'noun',        'thing, object',                        'şey, nesne', '물건, 것', '1、物、品物', 'barang, benda', 'đồ vật, vật phẩm'],
  ['都',   'dōu, dū',         'adverb',      'all, both',                            'hepsi, ikisi de', '모두, 다', 'すべて、みな、もう', 'semua, sekalian', 'đều, cả thảy'],
  ['读',   'dú',          'verb',        'to read',                              'okumak', '읽다, 공부하다', '読む、勉強する', 'membaca', 'đọc'],
  ['读书', 'dúshū',       'verb',        'to read a book',                       'kitap okumak', '독서하다, 공부하다', '読書する、勉強する', 'membaca buku, bersekolah', 'đọc sách, đi học'],
  ['对',   'duì',         'adjective',   'correct, right',                       'doğru, haklı', '맞다, 옳다', '正しい', 'benar', 'đúng'],
  ['对不起','duìbuqǐ',    'verb',        'sorry',                                'özür dilerim', '미안하다', '申し訳ない、すみません', 'minta maaf', 'xin lỗi'],
  ['多',   'duō',         'adjective',   'many, much',                           'çok, fazla', '많다', '多い', 'banyak', 'nhiều'],
  ['多少', 'duōshao',     'pronoun',     'how many, how much',                   'ne kadar, kaç tane', '얼마, 몇', 'いくつ、どれくらい', 'berapa', 'bao nhiêu'],
  ['儿子', 'érzi',        'noun',        'son',                                  'oğul', '아들', '息子', 'anak laki-laki', 'con trai'],
  ['二',   'èr',          'number',      'two',                                  'iki', '이, 둘', '1、に', 'dua', 'hai'],
  ['饭',   'fàn',         'noun',        'cooked rice, meal',                    'pirinç, yemek', '밥, 식사', 'ご飯、食事', 'nasi, makanan', 'cơm, bữa ăn'],
  ['饭店', 'fàndiàn',     'noun',        'restaurant',                           'restoran', '식당, 호텔', 'レストラン、ホテル', 'restoran, hotel', 'nhà hàng, khách sạn'],
  ['房间', 'fángjiān',    'noun',        'room',                                 'oda', '방', '部屋', 'kamar, ruangan', 'phòng'],
  ['非常', 'fēicháng',    'adverb',      'very, extremely',                      'çok, son derece', '매우, 아주', '非常に、とても', 'sangat, luar biasa', 'rất, vô cùng'],
  ['飞机', 'fēijī',       'noun',        'airplane',                             'uçak', '비행기', '飛行機', 'pesawat terbang', 'máy bay'],
  ['分',   'fēn, fèn',         'classifier',  'minute; component, part',              'dakika; bileşen', '분(시간), 나누다', '分（時間の単位）、分ける', 'menit, bagian', 'phút, phần'],
  ['分钟', 'fēnzhōng',    'classifier',  'minute',                               'dakika', '분(시간)', '分間', 'menit', 'phút'],
  ['高兴', 'gāoxìng',     'adjective',   'happy, glad',                          'mutlu, sevinçli', '기쁘다, 즐겁다', 'うれしい、楽しい', 'senang, gembira', 'vui vẻ, vui mừng'],
  ['歌',   'gē',          'noun',        'song',                                 'şarkı', '노래', '歌', 'lagu', 'bài hát'],
  ['哥哥', 'gēge',        'noun',        'older brother',                        'ağabey', '형, 오빠', '兄', 'kakak laki-laki', 'anh trai'],
  ['个',   'gè',          'classifier',  'measure word for general objects',     'genel sayı sözcüğü', '개 (일반적인 양사)', '1、個、人（一般的な量詞）', 'kata bantu bilangan untuk orang atau benda', 'cái, người (lượng từ chung)'],
  ['给',   'gěi',         'verb',        'to give; to, for',                     'vermek', '주다, ~에게, ~를 위하여', '与える、〜に、〜のために', 'memberi, kepada, untuk', 'cho, đưa, dành cho'],
  ['公司', 'gōngsī',      'noun',        'company',                              'şirket', '회사', '会社', 'perusahaan', 'công ty'],
  ['工作', 'gōngzuò',     'noun',        'work; to work',                        'iş; çalışmak', '일, 일하다', '仕事、働く', 'pekerjaan, bekerja', 'công việc, làm việc'],
  ['狗',   'gǒu',         'noun',        'dog',                                  'köpek', '개', '犬', 'anjing', 'con chó'],
  ['贵',   'guì',         'adjective',   'expensive',                            'pahalı', '비싸다, 귀하다', '高い、貴い', 'mahal', 'đắt, quý'],
  ['国',   'guó',         'noun',        'country',                              'ülke', '나라, 국가', '国', 'negara', 'nước, quốc gia'],
  ['还',   'hái, huán',         'adverb',      'still, also; quite',                   'hâlâ, ayrıca', '아직, 또한, 오히려', 'まだ、さらに、その上', 'masih, juga', 'vẫn, còn, hơn nữa'],
  ['孩子', 'háizi',       'noun',        'child',                                'çocuk', '아이, 자녀', '子供', 'anak', 'con cái, đứa trẻ'],
  ['汉语', 'Hànyǔ',       'noun',        'Chinese language',                     'Çince', '중국어', '中国語', 'bahasa Mandarin', 'tiếng Hán, tiếng Trung'],
  ['汉字', 'Hànzì',       'noun',        'Chinese character',                    'Çin karakteri', '한자', '漢字', 'aksara Tionghoa', 'chữ Hán'],
  ['好',   'hǎo, hào',         'adjective',   'good; well',                           'iyi; güzel', '좋다, 잘', '良い、元気だ', 'baik, bagus', 'tốt, hay, đẹp'],
  ['好吃', 'hǎochī',      'adjective',   'delicious, tasty',                     'lezzetli', '맛있다', '美味しい', 'enak', 'ngon'],
  ['好看', 'hǎokàn',      'adjective',   'good-looking',                         'güzel görünümlü', '보기 좋다, 예쁘다', '見栄えが良い、美しい', 'bagus, cantik, menarik', 'đẹp, ưa nhìn'],
  ['好听', 'hǎotīng',     'adjective',   'pleasant to listen to',               'kulağa güzel gelen', '듣기 좋다', '（音楽や声が）心地よい、美しい', 'merdu', 'dễ nghe, hay'],
  ['好玩儿','hǎowánr',    'adjective',   'fun, amusing',                         'eğlenceli', '재미있다', '面白い、楽しい', 'menyenangkan, seru', 'vui, thú vị'],
  ['号',   'hào',         'noun',        'number; date',                         'numara; tarih', '번호, 날짜', '番号、日', 'nomor, tanggal', 'số, ngày'],
  ['喝',   'hē',          'verb',        'to drink',                             'içmek', '마시다', '飲む', 'minum', 'uống'],
  ['和',   'hé',          'conjunction', 'and, with',                            've, ile', '과/와, ~하고', 'と、〜と', 'dan, dengan', 'và, với'],
  ['很',   'hěn',         'adverb',      'very',                                 'çok, gayet', '매우, 아주', 'とても、非常に', 'sangat', 'rất'],
  ['后',   'hòu',         'noun',        'behind, later',                        'arkasında, sonra', '뒤, 후', '後ろ、後', 'belakang, kemudian', 'sau, phía sau'],
  ['回',   'huí',         'verb',        'to return',                            'dönmek', '돌아가다, 돌아오다', '戻る、帰る', 'kembali, pulang', 'về, quay lại'],
  ['会',   'huì, kuài',         'verb',        'can, to be able to',                   'yapabilmek', '할 줄 알다, ~할 것이다', 'できる、〜するはずだ', 'dapat, bisa', 'biết, có thể'],
  ['火车', 'huǒchē',      'noun',        'train',                                'tren', '기차', '列車、汽車', 'kereta api', 'tàu hỏa'],
  ['鸡蛋', 'jīdàn',       'noun',        'egg',                                  'yumurta', '달걀', '卵、鶏卵', 'telur ayam', 'trứng gà'],
  ['几',   'jǐ, jī',          'pronoun',     'how many, a few',                      'kaç, birkaç', '몇, 얼마', 'いくつ、何人、いくつか', 'berapa, beberapa', 'mấy, vài'],
  ['家',   'jiā',         'noun',        'home, family',                         'ev, aile', '집, 가족', '家、家庭', 'rumah, keluarga', 'nhà, gia đình'],
  ['家人', 'jiārén',      'noun',        'family member',                        'aile üyesi', '가족', '家族', 'anggota keluarga', 'người nhà, thành viên gia đình'],
  ['见',   'jiàn',        'verb',        'to see',                               'görmek', '보다, 만나다', '会う、見える', 'melihat, bertemu', 'gặp, nhìn thấy'],
  ['件',   'jiàn',        'classifier',  'measure word for items',               'eşya sayı sözcüğü', '(의류나 사건 등을 세는) 단위', '〜件、〜点（事柄や衣服などを数える量詞）', 'kata penggolong untuk pakaian atau urusan', 'cái, chiếc (lượng từ)'],
  ['饺子', 'jiǎozi',      'noun',        'dumpling',                             'jiaozi (Çin mantısı)', '만두', '餃子', 'pangsit', 'sủi cảo'],
  ['叫',   'jiào',        'verb',        'to be called, to call',                'adı olmak, çağırmak', '부르다, ~라고 하다', '呼ぶ、〜という名前である', 'bernama, memanggil', 'gọi, tên là'],
  ['姐姐', 'jiějie',      'noun',        'older sister',                         'abla', '언니, 누나', '姉', 'kakak perempuan', 'chị gái'],
  ['今年', 'jīnnián',     'noun',        'this year',                            'bu yıl', '올해', '今年', 'tahun ini', 'năm nay'],
  ['今天', 'jīntiān',     'noun',        'today',                                'bugün', '오늘', '今日', 'hari ini', 'hôm nay'],
  ['九',   'jiǔ',         'number',      'nine',                                 'dokuz', '구, 아홉', '1、きゅう', 'sembilan', 'chín'],
  ['觉得', 'juéde',       'verb',        'to feel, to think',                    'hissetmek, düşünmek', '느끼다, 생각하다', '思う、感じる', 'merasa, berpendapat', 'cảm thấy, cho rằng'],
  ['开',   'kāi',         'verb',        'to open',                              'açmak', '열다', '開ける、開く', 'membuka, menyalakan', 'mở, lái (xe), bật'],
  ['开车', 'kāichē',      'verb',        'to drive',                             'araba sürmek', '운전하다', '運転する、車を運転する', 'mengemudi', 'lái xe'],
  ['看',   'kàn',         'verb',        'to see, to look',                      'bakmak, görmek', '보다, 읽다', '見る、読む、診察する', 'melihat, membaca', 'xem, nhìn, đọc'],
  ['看病', 'kànbìng',     'verb',        'to see a doctor',                      'doktora gitmek', '진찰받다, 병원에 가다', '診察を受ける、医者にかかる', 'berobat', 'khám bệnh'],
  ['看见', 'kànjiàn',     'verb',        'to see',                               'görmek', '보다, 눈에 띄다', '見える、見かける', 'melihat', 'nhìn thấy'],
  ['可以', 'kěyǐ',        'verb',        'can, may; okay, fine',                 'yapabilmek; olur', '할 수 있다, 괜찮다', 'できる、よい、かまわない', 'boleh, dapat, baik', 'có thể, được'],
  ['课',   'kè',          'noun',        'class, lesson',                        'ders', '수업, 과목', '授業、課', 'kelas, pelajaran', 'tiết học, bài học'],
  ['口',   'kǒu',         'noun',        'mouth',                                'ağız', '입', '口', 'mulut', 'miệng, cái (lượng từ)'],
  ['块',   'kuài',        'classifier',  'measure word for pieces; yuan',        'parça sayı sözcüğü; yuan', '덩어리(양사), 위안(화폐 단위)', '（塊を数える）個、元（通貨単位）', 'potong, yuan', 'miếng, đồng (đơn vị tiền tệ)'],
  ['来',   'lái',         'verb',        'to come',                              'gelmek', '오다', '来る', 'datang', 'đến'],
  ['老师', 'lǎoshī',      'noun',        'teacher',                              'öğretmen', '선생님', '先生', 'guru', 'thầy giáo, cô giáo'],
  ['了',   'le, liǎo',          'auxiliary',   'completed action particle',            'tamamlanan eylem partikülü', '완료의 어기조사', '1、〜した（完了・変化の助詞）', 'partikel penanda aspek selesai', 'trợ từ biểu thị hành động đã hoàn thành'],
  ['冷',   'lěng',        'adjective',   'cold',                                 'soğuk', '춥다', '寒い、冷たい', 'dingin', 'lạnh'],
  ['里',   'lǐ',          'noun',        'inside, in',                           'içinde, içeri', '안, 속', '中、内側', 'dalam', 'trong, bên trong'],
  ['两',   'liǎng',       'number',      'two (for quantities)',                 'iki (miktar için)', '둘, 두 (수량)', '1、2（数量を表す）', 'dua', 'hai (dùng trước lượng từ)'],
  ['零',   'líng',        'number',      'zero',                                 'sıfır', '영, 0', 'ゼロ、零', 'nol', 'không (số 0)'],
  ['六',   'liù',         'number',      'six',                                  'altı', '육(6)', '六', 'enam', 'sáu'],
  ['妈妈', 'māma',        'noun',        'mom',                                  'anne', '엄마', '母、お母さん', 'ibu', 'mẹ'],
  ['吗',   'ma',          'auxiliary',   'question particle',                    'soru partikülü', '~인가? (의문 조사)', '（疑問を表す助詞）', 'partikel tanya', 'trợ từ nghi vấn'],
  ['买',   'mǎi',         'verb',        'to buy',                               'satın almak', '사다', '1、買う', 'membeli', 'mua'],
  ['卖',   'mài',         'verb',        'to sell',                              'satmak', '팔다', '売る', 'menjual', 'bán'],
  ['忙',   'máng',        'adjective',   'busy',                                 'meşgul', '바쁘다', '忙しい', 'sibuk', 'bận'],
  ['猫',   'māo',         'noun',        'cat',                                  'kedi', '고양이', '猫', 'kucing', 'con mèo'],
  ['没关系','méi guānxi', 'expression',  "never mind, it's okay",                'önemli değil, olsun', '관계없다, 괜찮다', '構わない、大丈夫だ', 'tidak masalah, tidak apa-apa', 'không sao, không vấn đề gì'],
  ['没事', 'méishì',      'expression',  "it doesn't matter",                   'önemli değil', '괜찮다, 아무 일 없다', '大丈夫だ、何でもない', 'tidak apa-apa', 'không có gì, không sao'],
  ['没有', 'méiyǒu',      'verb',        'to not have; have not',               'yok, olmamak', '없다, 가지지 않다', '持っていない、ない', 'tidak punya, belum', 'không có'],
  ['妹妹', 'mèimei',      'noun',        'younger sister',                       'küçük kız kardeş', '여동생', '妹', 'adik perempuan', 'em gái'],
  ['们',   'men',         'suffix',      'plural suffix',                        'çoğul eki', '복수 접미사', '〜たち（人称代名詞の複数形を作る接尾辞）', 'akhiran penanda jamak', 'hậu tố chỉ số nhiều'],
  ['米饭', 'mǐfàn',       'noun',        'cooked rice',                          'pişmiş pirinç', '밥', 'ご飯、米飯', 'nasi', 'cơm'],
  ['面包', 'miànbāo',     'noun',        'bread',                                'ekmek', '빵', 'パン', 'roti', 'bánh mì'],
  ['面条儿','miàntiáor',  'noun',        'noodles',                              'erişte', '국수', '麺、うどん', 'mi', 'mì sợi'],
  ['明年', 'míngnián',    'noun',        'next year',                            'gelecek yıl', '내년', '来年', 'tahun depan', 'năm sau'],
  ['明天', 'míngtiān',    'noun',        'tomorrow',                             'yarın', '내일', '明日', 'besok', 'ngày mai'],
  ['名字', 'míngzi',      'noun',        'name',                                 'isim, ad', '이름', '名前', 'nama', 'tên'],
  ['哪',   'nǎ',          'pronoun',     'which',                                'hangi', '어느', 'どの、どちら', 'yang mana', 'nào'],
  ['哪个', 'nǎge',        'pronoun',     'which one',                            'hangisi', '어느 것', 'どれ、どちら', 'yang mana', 'cái nào'],
  ['哪里', 'nǎlǐ',        'pronoun',     'where',                                'nerede', '어디', 'どこ', 'di mana', 'đâu'],
  ['哪儿', 'nǎr',         'pronoun',     'where',                                'nerede', '어디', 'どこ', 'di mana', 'đâu'],
  ['哪些', 'nǎxiē',       'pronoun',     'which ones',                           'hangileri', '어느 것들', 'どれら、どのもの', 'yang mana saja', 'những cái nào'],
  ['那',   'nà',          'pronoun',     'that',                                 'o, şu', '그, 저, 그것, 저것', 'あれ、それ、あの、その', 'itu', 'kia'],
  ['那边', 'nàbiān',      'pronoun',     'over there',                           'orada, şurada', '그쪽, 저쪽', 'あちら、向こう', 'sebelah sana', 'phía kia, đằng kia'],
  ['那个', 'nàge',        'pronoun',     'that one',                             'o, şu', '그것, 저것', 'あれ、それ、あのもの', 'itu', 'cái kia'],
  ['那里', 'nàlǐ',        'pronoun',     'there',                                'orada', '거기, 저기', 'そこ、あそこ', 'sana', 'đằng kia, chỗ kia'],
  ['那儿', 'nàr',         'pronoun',     'there',                                'orada', '거기, 저기', 'そこ、あそこ', 'sana', 'đằng kia, chỗ kia'],
  ['那些', 'nàxiē',       'pronoun',     'those',                                'onlar, şunlar', '그것들, 저것들', 'あれら、それら', 'itu (jamak)', 'những cái kia'],
  ['男',   'nán',         'adjective',   'male',                                 'erkek', '남자의, 남성의', '男の', 'laki-laki', 'nam'],
  ['男朋友','nánpéngyou', 'noun',        'boyfriend',                            'erkek arkadaş', '남자친구', '彼氏', 'pacar laki-laki', 'bạn trai'],
  ['呢',   'ne',          'auxiliary',   'continuation/question particle',       'soru/devam partikülü', '~은/는? (의문 조사), ~하고 있다 (진행 어기 조사)', '（疑問や継続を表す助詞）', 'partikel penegas atau tanya', 'trợ từ biểu thị sự tiếp diễn hoặc nghi vấn'],
  ['能',   'néng',        'verb',        'can, be able to',                      'yapabilmek', '할 수 있다, ~해도 되다', 'できる、〜してもよい', 'dapat, bisa', 'có thể'],
  ['你',   'nǐ',          'pronoun',     'you',                                  'sen', '너, 당신', 'あなた、君', 'kamu, Anda', 'bạn, anh, chị'],
  ['你好', 'nǐ hǎo',      'expression',  'hello',                                'merhaba', '안녕하세요', 'こんにちは', 'halo', 'xin chào'],
  ['你们', 'nǐmen',       'pronoun',     'you (plural)',                         'siz', '너희들, 당신들', 'あなたたち、君たち', 'kalian', 'các bạn, các anh, các chị'],
  ['年',   'nián',        'noun',        'year',                                 'yıl', '년, 해', '年', 'tahun', 'năm'],
  ['您',   'nín',         'pronoun',     'you (formal)',                         'siz (saygılı)', '당신 (높임말)', 'あなた（敬称）', 'Anda (bentuk hormat)', 'ngài, ông, bà (từ tôn xưng)'],
  ['牛奶', 'niúnǎi',      'noun',        'milk',                                 'süt', '우유', '牛乳', 'susu sapi', 'sữa bò'],
  ['女',   'nǚ',          'adjective',   'female',                               'kadın, kız', '여자', '女性の', 'perempuan', 'nữ, con gái'],
  ['女儿', 'nǚér',        'noun',        'daughter',                             'kız', '딸', '娘', 'anak perempuan', 'con gái'],
  ['女朋友','nǚpéngyou',  'noun',        'girlfriend',                           'kız arkadaş', '여자친구', 'ガールフレンド、彼女', 'pacar perempuan', 'bạn gái'],
  ['女士', 'nǚshì',       'noun',        'lady, Ms.',                            'hanım, bayan', '여사, 숙녀', '女性、〜さん', 'nona, nyonya', 'quý bà, bà, cô'],
  ['朋友', 'péngyou',     'noun',        'friend',                               'arkadaş, dost', '친구', '友達', 'teman', 'bạn, bạn bè'],
  ['便宜', 'piányi',      'adjective',   'cheap',                                'ucuz', '싸다', '安い', 'murah', 'rẻ'],
  ['漂亮', 'piàoliang',   'adjective',   'beautiful',                            'güzel', '예쁘다, 아름답다', '美しい、きれいだ', 'cantik, indah', 'đẹp'],
  ['苹果', 'píngguǒ',     'noun',        'apple',                                'elma', '사과', 'リンゴ', 'apel', 'táo'],
  ['七',   'qī',          'number',      'seven',                                'yedi', '칠, 일곱', '1、なな', 'tujuh', 'bảy'],
  ['起床', 'qǐchuáng',    'verb',        'to get up',                            'kalkmak, uyanmak', '일어나다, 기상하다', '起床する、起きる', 'bangun tidur', 'thức dậy'],
  ['千',   'qiān',        'number',      'thousand',                             'bin', '천', '千', 'ribu', 'nghìn, ngàn'],
  ['前',   'qián',        'noun',        'front, before',                        'önde, önce', '앞, 전', '前、前方', 'depan, sebelum', 'trước'],
  ['钱',   'qián',        'noun',        'money',                                'para', '돈', '金、金銭', 'uang', 'tiền'],
  ['请',   'qǐng',        'verb',        'please; to invite',                    'lütfen; davet etmek', '청하다, 부탁하다, ~해 주십시오', '請う、〜してください、招待する', 'silakan, mengundang', 'mời, xin'],
  ['请问', 'qǐngwèn',     'expression',  'may I ask',                            'özür dilerim, bir sorum var', '말씀 좀 묻겠습니다', 'お尋ねしますが、ちょっとお聞きしますが', 'boleh saya tanya', 'xin hỏi'],
  ['去',   'qù',          'verb',        'to go',                                'gitmek', '가다', '行く', 'pergi', 'đi'],
  ['去年', 'qùnián',      'noun',        'last year',                            'geçen yıl', '작년', '去年', 'tahun lalu', 'năm ngoái'],
  ['热',   'rè',          'adjective',   'hot',                                  'sıcak', '덥다, 뜨겁다', '暑い、熱い', 'panas', 'nóng'],
  ['人',   'rén',         'noun',        'person',                               'kişi, insan', '사람', '1、人', 'orang', 'người'],
  ['认识', 'rènshi',      'verb',        'to know, to recognize',                'tanımak', '알다, 인식하다', '知っている、面識がある', 'mengenal', 'quen biết, nhận ra'],
  ['日',   'rì',          'classifier',  'measure word for days; sun',           'gün sayı sözcüğü; güneş', '날, 일, 해', '日（日付）、太陽', 'hari, matahari', 'ngày, mặt trời'],
  ['三',   'sān',         'number',      'three',                                'üç', '삼, 셋', '1、さん', 'tiga', 'ba'],
  ['商店', 'shāngdiàn',   'noun',        'store, shop',                          'mağaza, dükkan', '상점, 가게', '店、商店', 'toko', 'cửa hàng'],
  ['上',   'shàng',       'noun',        'up, above',                            'yukarı, üst', '위, 상', '1、上、上の方', 'atas', 'trên, phía trên'],
  ['上班', 'shàngbān',    'verb',        'to go to work',                        'işe gitmek', '출근하다', '1、出勤する、仕事に行く', 'bekerja', 'đi làm'],
  ['上课', 'shàngkè',     'verb',        'to attend class',                      'derse girmek', '수업하다, 수업을 듣다', '1、授業に出る、授業をする', 'mengikuti pelajaran, mengajar', 'lên lớp, vào học'],
  ['上午', 'shàngwǔ',     'noun',        'morning',                              'sabah (09:00-12:00)', '오전', '1、午前', 'pagi', 'buổi sáng'],
  ['上学', 'shàngxué',    'verb',        'to go to school',                      'okula gitmek', '등교하다, 학교에 다니다', '1、登校する、学校に通う', 'bersekolah', 'đi học'],
  ['少',   'shǎo, shào',        'adjective',   'few, little',                          'az', '적다', '少ない', 'sedikit, kurang', 'ít'],
  ['谁',   'shéi',        'pronoun',     'who',                                  'kim', '누구', 'だれ', 'siapa', 'ai'],
  ['什么', 'shénme',      'pronoun',     'what',                                 'ne', '무엇, 무슨', '1、何', 'apa', 'gì'],
  ['生病', 'shēngbìng',   'verb',        'to get sick',                          'hastalanmak', '병나다, 아프다', '病気になる', 'sakit', 'bị ốm, mắc bệnh'],
  ['十',   'shí',         'number',      'ten',                                  'on', '십, 열', '十', 'sepuluh', 'mười'],
  ['时候', 'shíhou',      'noun',        'moment, time',                         'an, zaman', '때, 시간', '時、時分', 'saat, waktu', 'lúc, thời điểm'],
  ['时间', 'shíjiān',     'noun',        'time',                                 'zaman', '시간, 때', '時間', 'waktu', 'thời gian'],
  ['事',   'shì',         'noun',        'matter, thing',                        'mesele, şey', '일, 사건', '1、事、用事', 'perkara, urusan', 'việc, sự việc'],
  ['是',   'shì',         'verb',        'to be',                                'olmak', '이다', '〜である', 'adalah', 'là'],
  ['手机', 'shǒujī',      'noun',        'cell phone',                           'cep telefonu', '휴대전화', '携帯電話', 'telepon genggam, ponsel', 'điện thoại di động'],
  ['书',   'shū',         'noun',        'book',                                 'kitap', '책', '1、本', 'buku', 'sách'],
  ['书店', 'shūdiàn',     'noun',        'bookstore',                            'kitapçı', '서점', '1、書店、本屋', 'toko buku', 'hiệu sách'],
  ['水',   'shuǐ',        'noun',        'water',                                'su', '물', '水', 'air', 'nước'],
  ['水果', 'shuǐguǒ',     'noun',        'fruit',                                'meyve', '과일', '果物', 'buah', 'hoa quả, trái cây'],
  ['睡',   'shuì',        'verb',        'to sleep',                             'uyumak', '자다', '眠る、寝る', 'tidur', 'ngủ'],
  ['睡觉', 'shuìjiào',    'verb',        'to sleep',                             'uyumak', '자다', '眠る、就寝する', 'tidur', 'ngủ'],
  ['说',   'shuō',        'verb',        'to speak, to say',                     'konuşmak, söylemek', '말하다', '話す、言う', 'berbicara, mengatakan', 'nói'],
  ['说话', 'shuōhuà',     'verb',        'to talk',                              'konuşmak', '말하다, 이야기하다', '話す、しゃべる', 'berbicara', 'nói chuyện'],
  ['四',   'sì',          'number',      'four',                                 'dört', '사(4)', '四', 'empat', 'bốn'],
  ['岁',   'suì',         'classifier',  'measure word for age',                 'yaşında (sayı sözcüğü)', '살 (나이 단위)', '〜歳（年齢の単位）', 'tahun (usia)', 'tuổi'],
  ['他',   'tā',          'pronoun',     'he, him',                              'o (erkek)', '그', '彼', 'dia, ia', 'anh ấy, ông ấy, nó'],
  ['它',   'tā',          'pronoun',     'it',                                   'o (nesne)', '그것', 'それ', 'ia, itu (benda/hewan)', 'nó'],
  ['她',   'tā',          'pronoun',     'she, her',                             'o (kadın)', '그녀', '彼女', 'dia (perempuan)', 'cô ấy, bà ấy'],
  ['他们', 'tāmen',       'pronoun',     'they (male/mixed)',                    'onlar (erkek/karma)', '그들', '彼ら', 'mereka', 'họ, các anh ấy'],
  ['它们', 'tāmen',       'pronoun',     'they (objects)',                       'onlar (nesneler)', '그것들', 'それら', 'mereka (benda/hewan)', 'chúng nó'],
  ['她们', 'tāmen',       'pronoun',     'they (female)',                        'onlar (kadın)', '그녀들', '彼女たち', 'mereka (perempuan)', 'các cô ấy, các bà ấy'],
  ['太',   'tài',         'adverb',      'too, extremely',                       'çok fazla, aşırı', '너무, 대단히', 'あまりに、非常に', 'terlalu, sangat', 'quá, lắm'],
  ['天',   'tiān',        'noun',        'day; sky',                             'gün; gökyüzü', '하늘, 날, 하루', '空、日', 'hari, langit', 'ngày, trời'],
  ['天气', 'tiānqì',      'noun',        'weather',                              'hava durumu', '날씨', '天気', 'cuaca', 'thời tiết'],
  ['听',   'tīng',        'verb',        'to listen',                            'dinlemek', '듣다', '聞く', 'mendengar, mendengarkan', 'nghe'],
  ['听见', 'tīngjiàn',    'verb',        'to hear',                              'duymak', '들리다', '聞こえる', 'terdengar', 'nghe thấy'],
  ['同学', 'tóngxué',     'noun',        'classmate',                            'sınıf arkadaşı', '학우, 동창', '同級生、クラスメート', 'teman sekelas', 'bạn học'],
  ['外',   'wài',         'noun',        'outside, exterior',                    'dışarı, dış', '밖, 외부', '外、外部', 'luar', 'ngoài'],
  ['外边', 'wàibian',     'noun',        'outside',                              'dışarıda', '밖, 바깥쪽', '外、外側', 'bagian luar', 'bên ngoài'],
  ['玩',   'wán',         'verb',        'to play',                              'oynamak', '놀다, 장난하다', '遊ぶ', 'bermain', 'chơi'],
  ['晚',   'wǎn',         'adjective',   'late',                                 'geç', '늦다', '遅い', 'terlambat, malam', 'muộn, trễ'],
  ['晚饭', 'wǎnfàn',      'noun',        'dinner',                               'akşam yemeği', '저녁 식사', '晩ごはん', 'makan malam', 'bữa tối'],
  ['晚上', 'wǎnshang',    'noun',        'evening',                              'akşam', '저녁, 밤', '晩、夜', 'malam hari', 'buổi tối'],
  ['喂',   'wèi',         'interjection','hello (on the phone)',                 'alo', '여보세요', 'もしもし', 'halo', 'a lô'],
  ['问',   'wèn',         'verb',        'to ask',                               'sormak', '묻다, 질문하다', '聞く、尋ねる', 'bertanya', 'hỏi'],
  ['问题', 'wèntí',       'noun',        'question, problem',                    'soru, sorun', '질문, 문제', '問題、質問', 'pertanyaan, masalah', 'câu hỏi, vấn đề'],
  ['我',   'wǒ',          'pronoun',     'I, me',                                'ben', '나, 저', '私', 'saya, aku', 'tôi, tao, mình'],
  ['我们', 'wǒmen',       'pronoun',     'we, us',                               'biz', '우리', '私たち', 'kami, kita', 'chúng tôi, chúng ta'],
  ['五',   'wǔ',          'number',      'five',                                 'beş', '오, 다섯', '1、ご', 'lima', 'năm'],
  ['午饭', 'wǔfàn',       'noun',        'lunch',                                'öğle yemeği', '점심', '昼食', 'makan siang', 'bữa trưa'],
  ['喜欢', 'xǐhuan',      'verb',        'to like',                              'beğenmek, sevmek', '좋아하다', '好きだ', 'suka', 'thích'],
  ['下',   'xià',         'noun',        'down, below',                          'aşağı, alt', '아래, 하', '1、下、下の方', 'bawah', 'dưới, phía dưới'],
  ['下雨', 'xià yǔ',      'expression',  'to rain',                              'yağmur yağmak', '비가 오다', '1、雨が降る', 'hujan', 'mưa, đổ mưa'],
  ['下班', 'xiàbān',      'verb',        'to get off work',                      'işten çıkmak', '퇴근하다', '1、退勤する、仕事が終わる', 'pulang kerja', 'tan làm'],
  ['下课', 'xiàkè',       'verb',        'to finish class',                      'dersten çıkmak', '수업을 마치다', '1、授業が終わる', 'selesai pelajaran', 'tan học, hết giờ học'],
  ['下午', 'xiàwǔ',       'noun',        'afternoon',                            'öğleden sonra', '오후', '1、午後', 'sore', 'buổi chiều'],
  ['先生', 'xiānsheng',   'noun',        'Mr., husband',                         'bay, koca', '선생, 남편', '先生、〜さん、夫', 'tuan, suami', 'ông, tiên sinh, chồng'],
  ['现在', 'xiànzài',     'noun',        'now',                                  'şimdi', '현재, 지금', '今、現在', 'sekarang', 'bây giờ'],
  ['想',   'xiǎng',       'verb',        'to think; to want',                    'düşünmek; istemek', '생각하다, ~하고 싶다', '思う、〜したい', 'berpikir, ingin, merindukan', 'nghĩ, muốn, nhớ'],
  ['小',   'xiǎo',        'adjective',   'small',                                'küçük', '작다', '小さい', 'kecil', 'nhỏ, bé'],
  ['小朋友','xiǎopéngyǒu','noun',        'little friend, child',                 'çocuk, küçük arkadaş', '어린이', '子供、坊や', 'anak kecil', 'trẻ nhỏ, bé'],
  ['小时', 'xiǎoshí',     'noun',        'hour',                                 'saat', '시간', '時間', 'jam', 'tiếng đồng hồ'],
  ['小学', 'xiǎoxué',     'noun',        'primary school',                       'ilkokul', '초등학교', '小学校', 'sekolah dasar', 'trường tiểu học'],
  ['小学生','xiǎoxuéshēng','noun',       'primary school student',               'ilkokul öğrencisi', '초등학생', '小学生', 'murid sekolah dasar', 'học sinh tiểu học'],
  ['些',   'xiē',         'classifier',  'some (indefinite amount)',             'biraz, bazı', '약간, 조금 (수량)', '1、いくらかの、いくつかの', 'beberapa', 'một vài, một ít'],
  ['写',   'xiě',         'verb',        'to write',                             'yazmak', '쓰다', '書く', 'menulis', 'viết'],
  ['谢谢', 'xièxie',      'verb',        'to thank',                             'teşekkür etmek', '감사하다, 고맙다', '感謝する、ありがとう', 'berterima kasih', 'cảm ơn'],
  ['新',   'xīn',         'adjective',   'new',                                  'yeni', '새롭다', '新しい', 'baru', 'mới'],
  ['星期', 'xīngqī',      'noun',        'week',                                 'hafta', '주, 요일', '週', 'minggu, pekan', 'tuần'],
  ['星期日','xīngqīrì',   'noun',        'Sunday',                               'Pazar', '일요일', '日曜日', 'hari Minggu', 'chủ nhật'],
  ['星期天','xīngqītiān', 'noun',        'Sunday',                               'Pazar', '일요일', '日曜日', 'hari Minggu', 'chủ nhật'],
  ['休息', 'xiūxi',       'verb',        'to rest',                              'dinlenmek', '쉬다, 휴식하다', '休む、休息する', 'beristirahat', 'nghỉ ngơi'],
  ['学',   'xué',         'verb',        'to learn, to study',                   'öğrenmek', '배우다, 공부하다', '学ぶ、習う', 'belajar', 'học'],
  ['学生', 'xuéshēng',    'noun',        'student',                              'öğrenci', '학생', '学生', 'pelajar, murid', 'học sinh'],
  ['学习', 'xuéxí',       'verb',        'to study',                             'çalışmak, öğrenmek', '공부하다', '勉強する、学習する', 'belajar', 'học tập'],
  ['学校', 'xuéxiào',     'noun',        'school',                               'okul', '학교', '学校', 'sekolah', 'trường học'],
  ['雪',   'xuě',         'noun',        'snow',                                 'kar', '눈', '雪', 'salju', 'tuyết'],
  ['要',   'yào, yāo',         'verb',        'to want, to need',                     'istemek, lazım olmak', '원하다, 필요하다, ~하려고 하다', 'ほしい、〜するつもりだ、必要だ', 'ingin, perlu, akan', 'muốn, cần'],
  ['也',   'yě',          'adverb',      'also, too',                            'de, da', '또한, 역시', '1、〜も、また', 'juga', 'cũng'],
  ['一',   'yī',          'number',      'one',                                  'bir', '일, 하나', '1、いち', 'satu', 'một'],
  ['衣服', 'yīfu',        'noun',        'clothes',                              'kıyafet, giysi', '옷', '服、衣服', 'pakaian, baju', 'quần áo'],
  ['医生', 'yīshēng',     'noun',        'doctor',                               'doktor', '의사', '医者、医師', 'dokter', 'bác sĩ'],
  ['医院', 'yīyuàn',      'noun',        'hospital',                             'hastane', '병원', '病院', 'rumah sakit', 'bệnh viện'],
  ['一半', 'yíbàn',       'number',      'half',                                 'yarısı', '절반, 반', '1、半分', 'setengah', 'một nửa'],
  ['一下', 'yíxià',       'expression',  'once, a little; briefly',              'bir kere, biraz', '한번, 잠시, 조금', '1、ちょっと、一回', 'sebentar, sekali', 'một chút, một lát'],
  ['椅子', 'yǐzi',        'noun',        'chair',                                'sandalye', '의자', '椅子', 'kursi', 'cái ghế'],
  ['一点儿','yìdiǎnr',    'expression',  'a little, a bit',                      'biraz, az miktarda', '조금, 약간', '1、少し、ちょっと', 'sedikit', 'một chút, một ít'],
  ['一些', 'yìxiē',       'expression',  'some, a few',                          'biraz, birkaç', '조금, 약간, 얼마간', '1、いくらか、少し', 'beberapa, sedikit', 'một vài, một ít'],
  ['有',   'yǒu',         'verb',        'to have, to exist',                    'olmak, sahip olmak', '있다, 가지다', 'ある、持っている', 'mempunyai, ada', 'có'],
  ['有的', 'yǒude',       'pronoun',     'some of them',                         'bazıları', '어떤 것, 일부', 'あるもの、一部のもの', 'beberapa di antaranya', 'có cái, một số'],
  ['有点儿','yǒudiǎnr',   'adverb',      'a little, slightly',                   'biraz, hafifçe', '조금, 약간', '少し、ちょっと', 'sedikit', 'một chút, hơi'],
  ['有些', 'yǒuxiē',      'pronoun',     'some, some of',                        'bazıları, biraz', '어떤, 얼마간의', 'いくらか、少し', 'beberapa', 'một vài, một số'],
  ['雨',   'yǔ',          'noun',        'rain',                                 'yağmur', '비', '雨', 'hujan', 'mưa'],
  ['元',   'yuán',        'classifier',  'yuan (currency)',                      'yuan (Çin para birimi)', '위안 (화폐 단위)', '元（中国の通貨単位）', 'yuan', 'nhân dân tệ (đơn vị tiền tệ)'],
  ['月',   'yuè',         'noun',        'month; moon',                          'ay', '달, 월', '月（暦）、月（天体）', 'bulan', 'tháng, trăng'],
  ['再',   'zài',         'adverb',      'again, then',                          'tekrar, yeniden', '다시, 또', 'また、さらに', 'lagi, kemudian', 'lại, nữa'],
  ['在',   'zài',         'verb',        'to be at; at; in the middle of',       '-de/-da; bulunmak', '있다, ~에(서)', '〜にいる、〜にある、〜で（動作の進行）', 'berada di, di, sedang', 'ở, đang'],
  ['再见', 'zàijiàn',     'verb',        'goodbye',                              'hoşça kal, güle güle', '안녕히 가세요, 안녕히 계세요', 'さようなら', 'sampai jumpa', 'tạm biệt'],
  ['早',   'zǎo',         'adjective',   'early',                                'erken', '이르다', '早い', 'awal, pagi', 'sớm'],
  ['早饭', 'zǎofàn',      'noun',        'breakfast',                            'kahvaltı', '아침밥', '朝ごはん', 'sarapan', 'bữa sáng'],
  ['早上', 'zǎoshang',    'noun',        'morning (early)',                      'sabah (erken)', '아침', '朝', 'pagi hari', 'buổi sáng'],
  ['怎么', 'zěnme',       'pronoun',     'how',                                  'nasıl', '어떻게, 어째서', 'どのように、どうして', 'bagaimana', 'thế nào, làm sao'],
  ['怎么样','zěnmeyàng',  'pronoun',     'how about, what do you think',         'nasıl, ne düşünüyorsun', '어떠하다', 'どうですか、いかがですか', 'bagaimana, bagaimana menurutmu', 'thế nào, ra sao'],
  ['找',   'zhǎo',        'verb',        'to look for',                          'aramak', '찾다', '探す、求める', 'mencari', 'tìm, kiếm'],
  ['这',   'zhè',         'pronoun',     'this',                                 'bu', '이, 이것', 'これ、この', 'ini', 'này'],
  ['这边', 'zhèbiān',     'pronoun',     'here',                                 'burada', '이쪽', 'こちら、こっち', 'sini', 'phía này'],
  ['这个', 'zhège',       'pronoun',     'this one',                             'bu', '이것', 'これ、このもの', 'ini', 'cái này'],
  ['这里', 'zhèlǐ',       'pronoun',     'here',                                 'burada', '여기', 'ここ', 'sini', 'đây'],
  ['这儿', 'zhèr',        'pronoun',     'here',                                 'burada', '여기', 'ここ', 'sini', 'đây'],
  ['这些', 'zhèxiē',      'pronoun',     'these',                                'bunlar', '이것들', 'これら', 'ini (jamak)', 'những cái này'],
  ['真',   'zhēn',        'adverb',      'really; true',                         'gerçekten; doğru', '정말, 참', '本当に、実に', 'sungguh, benar', 'thật, thực sự'],
  ['正在', 'zhèngzài',    'adverb',      'in the process of',                    '-iyor/-ıyor (şu an)', '진행 중이다, 한창 ~하고 있다', 'ちょうど〜している（進行の副詞）', 'sedang', 'đang'],
  ['只',   'zhǐ, zhī',         'classifier',  'measure word for animals',             'hayvan sayı sözcüğü', '마리 (동물 단위)', '（動物を数える）匹', 'kata penggolong untuk hewan', 'con (lượng từ)'],
  ['知道', 'zhīdào',      'verb',        'to know',                              'bilmek', '알다', '知っている、わかる', 'tahu, mengetahui', 'biết'],
  ['中国', 'Zhōngguó',    'noun',        'China',                                'Çin', '중국', '1、中国', 'Tiongkok', 'Trung Quốc'],
  ['中文', 'Zhōngwén',    'noun',        'Chinese language (written)',           'Çince (yazılı)', '중국어', '1、中国語（書き言葉）', 'bahasa Mandarin', 'tiếng Trung'],
  ['中午', 'zhōngwǔ',     'noun',        'noon',                                 'öğle', '정오, 낮', '1、正午、昼', 'siang', 'buổi trưa'],
  ['中学', 'zhōngxué',    'noun',        'middle school',                        'ortaokul', '중학교', '1、中学校', 'sekolah menengah', 'trung học'],
  ['中学生','zhōngxuéshēng','noun',      'middle school student',                'ortaokul öğrencisi', '중학생', '1、中学生', 'siswa sekolah menengah', 'học sinh trung học'],
  ['住',   'zhù',         'verb',        'to live, to reside',                   'yaşamak, ikamet etmek', '살다, 거주하다', '住む、居住する', 'tinggal, menetap', 'ở, cư trú'],
  ['桌子', 'zhuōzi',      'noun',        'table, desk',                          'masa', '탁자, 책상', 'テーブル、机', 'meja', 'cái bàn'],
  ['字',   'zì',          'noun',        'character, script',                    'karakter, harf', '글자', '文字', 'aksara, huruf', 'chữ'],
  ['昨天', 'zuótiān',     'noun',        'yesterday',                            'dün', '어제', '昨日', 'kemarin', 'hôm qua'],
  ['坐',   'zuò',         'verb',        'to sit',                               'oturmak', '앉다, (탈것을) 타다', '座る、乗る', 'duduk', 'ngồi'],
  ['做',   'zuò',         'verb',        'to do, to make',                       'yapmak', '하다, 만들다', 'する、作る', 'mengerjakan, membuat', 'làm'],
  ['做饭', 'zuò fàn',     'expression',  'to cook',                              'yemek pişirmek', '밥을 짓다, 요리하다', '料理を作る、炊事をする', 'memasak', 'nấu cơm'],
];
