/// HSK Level 2 — 198 unique vocabulary entries (200 list entries, 2 duplicates merged).
/// Each row: [simplified, pinyin, pos, en, tr, ko, ja, id]
const List<List<String>> kHsk2Words = [
  ['啊',     'a',            'auxiliary',   'ah, oh',                                          'ah, oh', '아, 어 (감탄사)', 'ああ、あっ（感嘆詞）、〜よ、〜ね（文末助詞）', 'ah, oh'],
  ['爱好',   'àihào',        'verb',        'to like; hobby',                                  'beğenmek; hobi', '좋아하다, 취미', '趣味、好む', 'hobi, menyukai'],
  ['白色',   'báisè',        'noun',        'white',                                           'beyaz', '흰색', '白、白色', 'warna putih'],
  ['班',     'bān',          'noun',        'class, team',                                     'sınıf, takım', '반, 조', 'クラス、チーム', 'kelas, kelompok'],
  ['帮',     'bāng',         'verb',        'to help',                                         'yardım etmek', '돕다', '助ける、手伝う', 'membantu'],
  ['帮忙',   'bāngmáng',     'verb',        'to help',                                         'yardım etmek', '돕다, 거들다', '手伝う', 'menolong, bantuan'],
  ['包',     'bāo',          'noun',        'to wrap; bag',                                    'sarmak; çanta', '싸다; 가방', '包む、袋、バッグ', 'membungkus, tas'],
  ['本子',   'běnzi',        'noun',        'notebook',                                        'defter', '공책', 'ノート', 'buku catatan'],
  ['比',     'bǐ',           'preposition', 'than; to compare',                                'daha; karşılaştırmak', '~보다, 비교하다', '〜より（比較の基準を示す）', 'daripada, dibandingkan dengan'],
  ['笔',     'bǐ',           'noun',        'pen',                                             'kalem', '펜, 필기구', 'ペン、筆記用具', 'pena, alat tulis'],
  ['别',     'bié',          'adverb',      "don't",                                           'yapma', '헤어지다, 떠나다', '別れる', 'berpisah, meninggalkan'],
  ['不错',   'búcuò',        'adjective',   'not bad, pretty good',                            'fena değil, oldukça iyi', '좋다, 괜찮다', '悪くない、なかなか良い', 'lumayan, tidak buruk'],
  ['不好意思','bù hǎoyìsi',  'expression',  'sorry, embarrassed',                              'özür dilerim, utanmak', '미안하다, 부끄럽다, 민망하다', 'すみません、恥ずかしい', 'maaf, malu'],
  ['长',     'cháng, zhǎng',        'adjective',   'long',                                            'uzun', '긴', '長い', 'panjang'],
  ['车站',   'chēzhàn',      'noun',        'station',                                         'istasyon', '정류장, 역', '駅、停留所', 'stasiun, halte'],
  ['出',     'chū',          'verb',        'to go out, to leave',                             'dışarı çıkmak, ayrılmak', '나가다, 나오다', '出る、出す', 'keluar'],
  ['出国',   'chūguó',       'verb',        'to go abroad',                                    'yurt dışına çıkmak', '출국하다, 해외로 나가다', '外国へ行く、出国する', 'pergi ke luar negeri'],
  ['出来',   'chūlái',       'verb',        'to come out',                                     'dışarı çıkmak', '나오다', '出てくる', 'datang keluar'],
  ['出门',   'chūmén',       'verb',        'to go out',                                       'dışarı çıkmak', '외출하다, 집에서 나가다', '外出する、出かける', 'keluar rumah'],
  ['出去',   'chūqù',        'verb',        'to go out',                                       'dışarı gitmek', '나가다', '外へ出る', 'pergi keluar'],
  ['床',     'chuáng',       'noun',        'bed',                                             'yatak', '침대', 'ベッド', 'tempat tidur'],
  ['词',     'cí',           'noun',        'word, term',                                      'kelime, terim', '단어, 말', '単語、言葉', 'kata, istilah'],
  ['次',     'cì',           'classifier',  'measure word for times or occasions',              'kez, defa', '번 (횟수나 차례를 세는 말)', '（回数を数える）回', 'kali'],
  ['从',     'cóng',         'preposition', 'from',                                            '-den, -dan', '~로부터, ~에서', '〜から', 'dari'],
  ['从小',   'cóngxiǎo',    'adverb',      'from childhood',                                  'çocukluktan beri', '어릴 때부터', '幼い頃から', 'sejak kecil'],
  ['错',     'cuò',          'adjective',   'wrong, mistaken',                                 'yanlış, hatalı', '틀린, 잘못된', '間違っている、誤りだ', 'salah, keliru'],
  ['打',     'dǎ',           'verb',        'to hit, to play, to make',                        'vurmak, oynamak', '치다, 때리다, 하다, 걸다', '打つ、叩く、する（スポーツなど）', 'memukul, bermain, membuat'],
  ['打车',   'dǎchē',        'verb',        'to take a taxi',                                  'taksi tutmak', '택시를 잡다, 택시를 타다', 'タクシーを拾う', 'naik taksi'],
  ['打开',   'dǎkāi',        'verb',        'to open',                                         'açmak', '열다, 펴다', '開ける', 'membuka'],
  ['但',     'dàn',          'conjunction', 'but, however',                                    'ama, fakat', '그러나, 하지만', 'しかし、だが', 'tetapi, namun'],
  ['但是',   'dànshì',       'conjunction', 'but, however',                                    'ama, fakat', '그러나, 하지만', 'しかし、だが', 'tetapi, namun'],
  ['得',     'de, dé, děi',           'auxiliary',   'particle indicating degree or manner',             'derece veya tarz bildiren partikül', '~하게 (정도를 나타냄), ~해야 한다 (의무)', '（動詞・形容詞の後で程度や結果を表す助詞）', 'partikel penanda derajat atau cara'],
  ['地',     'de, dì',           'auxiliary',   'particle modifying adjective into adverb',         'sıfatı zarfa dönüştüren partikül', '~하게 (형용사를 부사로 만드는 조사)', '（形容詞を副詞化する助詞）〜に', 'partikel pembentuk keterangan'],
  ['等',     'děng',         'verb',        'to wait',                                         'beklemek', '기다리다, 등등', '待つ、〜など', 'menunggu, dan sebagainya'],
  ['地铁',   'dìtiě',        'noun',        'subway, metro',                                   'metro', '지하철', '地下鉄', 'kereta bawah tanah, metro'],
  ['点',     'diǎn',         'verb',        'to order; point, dot',                            'sipariş etmek; nokta', '시 (시간), 점, 방울', '時（時刻）、点、少し', 'satuan waktu, titik'],
  ['懂',     'dǒng',         'verb',        'to understand',                                   'anlamak', '이해하다, 알다', 'わかる、理解する', 'mengerti, paham'],
  ['动',     'dòng',         'verb',        'to move, to act',                                 'hareket etmek', '움직이다, 행동하다', '動く、動かす', 'bergerak, beraksi'],
  ['饭馆',   'fànguǎn',      'noun',        'restaurant',                                      'restoran', '식당', 'レストラン、食堂', 'restoran, rumah makan'],
  ['飞',     'fēi',          'verb',        'to fly',                                          'uçmak', '날다', '飛ぶ', 'terbang'],
  ['高',     'gāo',          'adjective',   'tall, high',                                      'uzun boylu, yüksek', '높은, 키가 큰', '高い', 'tinggi'],
  ['高中',   'gāozhōng',     'noun',        'high school',                                     'lise', '고등학교', '高校', 'sekolah menengah atas'],
  ['告诉',   'gàosu',        'verb',        'to tell',                                         'söylemek, anlatmak', '알리다, 말하다', '告げる、教える', 'memberitahu'],
  ['个子',   'gèzi',         'noun',        'height, stature',                                 'boy, endam', '키, 골격', '背丈、体格', 'tinggi badan, perawakan'],
  ['跟',     'gēn',          'preposition', 'with; and',                                       'ile; ve', '~와, ~과 (전치사)', '〜と、〜に', 'dengan, dan'],
  ['公交车', 'gōngjiāochē',  'noun',        'bus',                                             'otobüs', '버스', 'バス', 'bus'],
  ['过',     'guò',          'verb',        'to pass, to cross; past experience particle',      'geçmek; geçmiş deneyim partikülü', '지나다, 건너다; 경험을 나타내는 조사', '過ぎる、渡る、経験を表す助詞', 'melewati, melampaui, partikel pengalaman'],
  ['过来',   'guòlái',       'verb',        'to come over',                                    'yaklaşmak, gelmek', '이리 오다', '来る、こちらへ来る', 'datang ke sini'],
  ['过年',   'guònián',      'verb',        'to celebrate the New Year',                       'Yeni Yıl kutlamak', '설날을 보내다', '正月を祝う', 'merayakan tahun baru'],
  ['过去',   'guòqù',        'verb',        'to go over',                                      'oraya gitmek', '지나가다', '行く、過ぎ去る', 'pergi ke sana, berlalu'],
  ['还是',   'háishi',       'adverb',      'still; or',                                       'hâlâ; ya da', '여전히; 혹은', 'やはり、あるいは', 'masih, atau'],
  ['黑色',   'hēisè',        'noun',        'black',                                           'siyah', '검은색', '黒色', 'warna hitam'],
  ['红茶',   'hóngchá',      'noun',        'black tea',                                       'siyah çay', '홍차', '紅茶', 'teh hitam'],
  ['红色',   'hóngsè',       'noun',        'red',                                             'kırmızı', '붉은색', '赤、赤色', 'warna merah'],
  ['后面',   'hòumiàn',      'noun',        'behind, back',                                    'arka, geri', '뒤', '後ろ、背後', 'belakang'],
  ['花',     'huā',          'verb',        'to spend (money or time); flower',                'harcamak (para/zaman); çiçek', '쓰다 (돈, 시간), 꽃', '費やす、花', 'menghabiskan, bunga'],
  ['画',     'huà',          'verb',        'to draw, to paint; painting',                     'çizmek, resim yapmak; resim', '그리다, 그림', '描く、絵', 'menggambar, melukis, lukisan'],
  ['坏',     'huài',         'adjective',   'bad, broken',                                     'kötü, bozuk', '나쁘다, 고장 나다', '悪い、壊れている', 'buruk, rusak'],
  ['回来',   'huílái',       'verb',        'to come back',                                    'geri dönmek', '돌아오다', '帰ってくる、戻ってくる', 'datang kembali'],
  ['回去',   'huíqù',        'verb',        'to go back',                                      'geri gitmek', '돌아가다', '帰る、戻る', 'kembali, pulang'],
  ['机场',   'jīchǎng',      'noun',        'airport',                                         'havalimanı', '공항', '空港', 'bandara'],
  ['机票',   'jīpiào',       'noun',        'airplane ticket',                                 'uçak bileti', '항공권', '航空券', 'tiket pesawat'],
  ['记得',   'jìde',         'verb',        'to remember',                                     'hatırlamak', '기억하다, 기억나다', '覚えている', 'ingat'],
  ['间',     'jiān, jiàn',         'classifier',  'measure word for rooms',                          'oda sayı sözcüğü', '~의 (방을 세는 단위)', '（部屋を数える）室', 'kata penggolong untuk ruangan'],
  ['教',     'jiāo, jiào',         'verb',        'to teach',                                        'öğretmek', '가르치다', '教える', 'mengajar'],
  ['教室',   'jiàoshì',      'noun',        'classroom',                                       'sınıf', '교실', '教室', 'ruang kelas'],
  ['介绍',   'jièshào',      'verb',        'to introduce',                                    'tanıtmak', '소개하다', '紹介する', 'memperkenalkan'],
  ['进',     'jìn',          'verb',        'to enter',                                        'girmek', '들어가다', '入る', 'masuk'],
  ['近',     'jìn',          'adjective',   'near, close',                                     'yakın', '가깝다', '近い', 'dekat'],
  ['进来',   'jìnlái',       'verb',        'to come in',                                      'içeri girmek', '안으로 들어오다', '入ってくる', 'masuk ke sini'],
  ['进去',   'jìnqù',        'verb',        'to go in',                                        'içeri gitmek', '안으로 들어가다', '入っていく', 'masuk ke sana'],
  ['经常',   'jīngcháng',    'adverb',      'often',                                           'sık sık, çoğunlukla', '자주, 늘', 'よく、しばしば', 'sering'],
  ['酒店',   'jiǔdiàn',      'noun',        'hotel',                                           'otel', '호텔', 'ホテル', 'hotel'],
  ['就',     'jiù',          'adverb',      'just, then',                                      'hemen, o zaman', '곧, 바로, 겨우, 단지', 'すぐに、そのまま、〜さえすれば', 'hanya, lalu, segera'],
  ['咖啡',   'kāfēi',        'noun',        'coffee',                                          'kahve', '커피', 'コーヒー', 'kopi'],
  ['开始',   'kāishǐ',       'verb',        'to start; beginning',                             'başlamak; başlangıç', '시작하다, 개시하다', '始める、始まる、開始', 'mulai, permulaan'],
  ['开学',   'kāixué',       'verb',        'school starts',                                   'okul başlamak', '개학하다', '新学期が始まる', 'masuk sekolah, mulai semester'],
  ['考',     'kǎo',          'verb',        'to test, to take an exam',                        'sınav yapmak', '시험하다, 시험을 보다', '試験を受ける、調べる', 'menguji, menempuh ujian'],
  ['考试',   'kǎoshì',       'verb',        'to take an exam; exam',                           'sınava girmek; sınav', '시험, 시험을 보다', '試験を受ける、試験', 'ujian, menempuh ujian'],
  ['可能',   'kěnéng',       'adjective',   'possible; may',                                   'mümkün; olabilir', '가능하다; ~일지도 모르다', '可能だ、〜かもしれない', 'mungkin, dapat'],
  ['裤子',   'kùzi',         'noun',        'pants',                                           'pantolon', '바지', 'ズボン', 'celana'],
  ['快',     'kuài',         'adjective',   'fast; soon',                                      'hızlı; yakında', '빠르다, 곧', '速い、すぐだ', 'cepat, segera'],
  ['快乐',   'kuàilè',       'adjective',   'happy, joyful',                                   'mutlu, neşeli', '즐겁다, 행복하다', '楽しい、うれしい', 'bahagia, gembira'],
  ['快要',   'kuàiyào',      'adverb',      'soon, almost',                                    'yakında, neredeyse', '곧, 머지않아', 'もうすぐ、今にも〜しそうだ', 'hampir, segera'],
  ['篮球',   'lánqiú',       'noun',        'basketball',                                      'basketbol', '농구', 'バスケットボール', 'bola basket'],
  ['累',     'lèi, lěi',          'adjective',   'tired; to tire',                                  'yorgun; yormak', '피곤하다, 지치다', '疲れる', 'lelah, melelahkan'],
  ['离',     'lí',           'verb',        'to leave, to be away from',                       'ayrılmak, uzakta olmak', '떠나다, 떨어지다', '離れる、〜から（距離）', 'meninggalkan, berjarak dari'],
  ['里面',   'lǐmiàn',       'noun',        'inside',                                          'içeri, içinde', '안, 내부', '中', 'dalam, bagian dalam'],
  ['楼',     'lóu',          'noun',        'building, floor',                                 'bina, kat', '건물, 층', '建物、階', 'gedung, lantai'],
  ['路',     'lù',           'noun',        'road, path',                                      'yol', '길', '道', 'jalan'],
  ['路上',   'lùshang',      'noun',        'on the road',                                     'yolda', '길 위에서', '道中、途中で', 'di jalan'],
  ['旅游',   'lǚyóu',        'verb',        'to travel',                                       'seyahat etmek', '여행하다', '旅行する', 'berwisata, bepergian'],
  ['绿茶',   'lǜchá',        'noun',        'green tea',                                       'yeşil çay', '녹차', '緑茶', 'teh hijau'],
  ['绿色',   'lǜsè',         'noun',        'green',                                           'yeşil', '초록색', '緑、緑色', 'warna hijau'],
  ['慢',     'màn',          'adjective',   'slow',                                            'yavaş', '느리다', '遅い', 'lambat'],
  ['没意思', 'méi yìsi',     'adjective',   'boring, uninteresting',                           'sıkıcı, ilginç değil', '재미없는, 지루한', 'つまらない、面白くない', 'membosankan, tidak menarik'],
  ['每',     'měi',          'pronoun',     'every, each',                                     'her, her biri', '매, 모든', '毎〜、どの〜も', 'setiap'],
  ['门',     'mén',          'noun',        'door, gate',                                      'kapı', '문', '戸、門', 'pintu, gerbang'],
  ['门口',   'ménkǒu',       'noun',        'doorway, entrance',                               'kapı önü, giriş', '문 입구, 출입구', '入り口、玄関先', 'pintu masuk, pelataran'],
  ['门票',   'ménpiào',      'noun',        'ticket',                                          'giriş bileti', '입장권, 표', '入場券、チケット', 'tiket masuk'],
  ['面',     'miàn',         'noun',        'side, aspect',                                    'taraf, yön', '면, 쪽, 얼굴', '面、側面', 'sisi, aspek, permukaan'],
  ['名',     'míng',         'classifier',  'measure word for people; name',                   'kişi sayı sözcüğü; isim', '~의 (사람을 세는 단위); 이름', '（人を数える）〜名、名前', 'orang (kata penggolong), nama'],
  ['拿',     'ná',           'verb',        'to take, to hold',                                'almak, tutmak', '가지다, 잡다, 쥐다', '持つ、取る', 'mengambil, memegang'],
  ['那么',   'nàme',         'conjunction', 'so, then',                                        'öyleyse, o zaman', '그렇게, 그러면', 'それなら、そんなに', 'begitu, kalau begitu'],
  ['那样',   'nàyàng',       'pronoun',     'like that',                                       'böyle, öyle', '그렇게, 저런 모양', 'あのように、ああだ', 'seperti itu, begitu'],
  ['奶茶',   'nǎichá',       'noun',        'milk tea',                                        'sütlü çay', '밀크티', 'ミルクティー', 'teh susu'],
  ['奶奶',   'nǎinai',       'noun',        'grandmother',                                     'büyükanne (baba tarafı)', '할머니', 'おばあさん（父方の祖母）', 'nenek'],
  ['男孩儿', 'nánháir',      'noun',        'boy',                                             'erkek çocuk', '남자아이', '男の子', 'anak laki-laki'],
  ['鸟',     'niǎo',         'noun',        'bird',                                            'kuş', '새', '鳥', 'burung'],
  ['女孩儿', 'nǚháir',       'noun',        'girl',                                            'kız çocuk', '여자아이', '女の子、少女', 'gadis, anak perempuan'],
  ['旁边',   'pángbiān',     'noun',        'side',                                            'yan, yanı', '옆, 곁', 'そば、わき', 'samping, sisi'],
  ['跑',     'pǎo',          'verb',        'to run',                                          'koşmak', '달리다', '走る', 'berlari'],
  ['跑步',   'pǎobù',        'verb',        'to run, jogging',                                 'koşmak, jogging yapmak', '달리기, 달리다', '走る、ジョギングする', 'berlari, joging'],
  ['票',     'piào',         'noun',        'ticket',                                          'bilet', '표', 'チケット、切符', 'tiket'],
  ['妻子',   'qīzi',         'noun',        'wife',                                            'eş (kadın)', '아내', '妻', 'istri'],
  ['起来',   'qǐlái',        'verb',        'to get up, to stand up',                          'kalkmak, ayağa kalkmak', '일어나다, 올라가다', '起きる、立ち上がる', 'bangun, berdiri'],
  ['前面',   'qiánmiàn',     'noun',        'front',                                           'ön', '앞', '前、前方', 'depan'],
  ['晴',     'qíng',         'adjective',   'sunny, clear',                                    'güneşli, açık', '맑다', '晴れる', 'cerah'],
  ['球',     'qiú',          'noun',        'ball, sphere',                                    'top', '공, 구', 'ボール、球', 'bola'],
  ['让',     'ràng',         'verb',        'to let, to allow',                                'izin vermek, bırakmak', '시키다, 허락하다', '〜させる、譲る', 'membiarkan, mengizinkan'],
  ['肉',     'ròu',          'noun',        'meat',                                            'et', '고기', '肉', 'daging'],
  ['商场',   'shāngchǎng',   'noun',        'shopping mall',                                   'alışveriş merkezi', '쇼핑몰', 'ショッピングモール、デパート', 'pusat perbelanjaan, mal'],
  ['上来',   'shànglái',     'verb',        'to come up',                                      'yukarı çıkmak', '올라오다', '上がってくる', 'datang ke atas'],
  ['上面',   'shàngmiàn',    'noun',        'above, top',                                      'üstünde, üzeri', '위, 위쪽', '上、表面', 'atas'],
  ['上去',   'shàngqù',      'verb',        'to go up',                                        'yukarı çıkmak', '올라가다', '上がる', 'naik'],
  ['上网',   'shàngwǎng',    'verb',        'to go online',                                    'internete girmek', '인터넷을 하다', 'インターネットをする', 'berselancar di internet'],
  ['身体',   'shēntǐ',       'noun',        'body',                                            'vücut, beden', '몸', '体、健康', 'tubuh, badan'],
  ['生日',   'shēngrì',      'noun',        'birthday',                                        'doğum günü', '생일', '誕生日', 'hari ulang tahun'],
  ['时',     'shí',          'noun',        'time, moment',                                    'zaman, an', '때, 시기, 시간', '時、時間', 'waktu, saat'],
  ['事情',   'shìqing',      'noun',        'matter, affair',                                  'konu, mesele', '일, 사건, 사정', '事、用事', 'hal, urusan'],
  ['手',     'shǒu',         'noun',        'hand',                                            'el', '손', '手', 'tangan'],
  ['手表',   'shǒubiǎo',     'noun',        'watch, wristwatch',                               'kol saati', '손목시계', '腕時計', 'jam tangan'],
  ['书包',   'shūbāo',       'noun',        'backpack, schoolbag',                             'sırt çantası, okul çantası', '책가방', 'かばん、ランドセル', 'tas sekolah'],
  ['舒服',   'shūfu',        'adjective',   'comfortable',                                     'rahat, konforlu', '편안하다, 안락하다', '気持ちいい、快適だ', 'nyaman, segar'],
  ['送',     'sòng',         'verb',        'to give, to send, to see off',                    'vermek, göndermek, uğurlamak', '보내다, 주다, 배웅하다', '送る、贈る、見送る', 'memberi, mengirim, mengantar'],
  ['虽然',   'suīrán',       'conjunction', 'although',                                        'her ne kadar, -se de', '비록 ~이지만', '〜だけれども、〜とはいえ', 'meskipun, walaupun'],
  ['所以',   'suǒyǐ',        'conjunction', 'so, therefore',                                   'bu yüzden, bu nedenle', '그래서, 따라서', 'だから、そのために', 'jadi, oleh karena itu'],
  ['疼',     'téng',         'adjective',   'painful, sore',                                   'ağrılı, sızlayan', '아프다, 쓰리다', '痛い', 'sakit, nyeri'],
  ['踢',     'tī',           'verb',        'to kick',                                         'tekmelemek', '차다', '蹴る', 'menendang'],
  ['题',     'tí',           'noun',        'question, problem, topic',                        'soru, sorun, konu', '문제, 과제', '問題、課題、テーマ', 'pertanyaan, masalah, topik'],
  ['条',     'tiáo',         'classifier',  'measure word for long thin objects',               'uzun ince nesneler için sayı sözcüğü', '개 (사물 분류사)', '（細長いものを数える）本', 'kata penggolong untuk benda panjang dan tipis'],
  ['跳舞',   'tiàowǔ',       'verb',        'to dance',                                        'dans etmek', '춤추다', '踊る', 'menari'],
  ['头',     'tóu',          'noun',        'head',                                            'baş', '~ (명사 뒤에 붙는 접미사)', '（名詞の後に付く接尾辞）', 'akhiran kata benda'],
  ['外国',   'wàiguó',       'noun',        'foreign country',                                 'yabancı ülke', '외국', '外国', 'luar negeri'],
  ['外面',   'wàimiàn',      'noun',        'outside',                                         'dışarı, dışı', '바깥', '外、外部', 'luar'],
  ['完',     'wán',          'verb',        'to finish',                                       'bitirmek, tamamlamak', '끝내다, 마치다', '終える、終わる', 'selesai, habis'],
  ['万',     'wàn',          'number',      'ten thousand',                                    'on bin', '만', '万', 'sepuluh ribu'],
  ['往',     'wǎng',         'preposition', 'toward',                                          'doğru, -e doğru', '~쪽으로, ~을 향해', '〜へ、〜の方へ', 'ke, menuju'],
  ['网上',   'wǎngshang',    'noun',        'online',                                          'çevrimiçi, internette', '온라인상의', 'ネット上、オンライン', 'daring, internet'],
  ['忘',     'wàng',         'verb',        'to forget',                                       'unutmak', '잊다, 잊어버리다', '忘れる', 'lupa'],
  ['位',     'wèi',          'classifier',  'measure word for people (polite)',                 'kişi sayı sözcüğü (saygılı)', '~의 (높임 접두사)', '（人に対する敬称の）〜名、〜方', 'orang (kata penggolong sopan)'],
  ['为什么', 'wèi shénme',   'adverb',      'why',                                             'neden, niçin', '왜', 'なぜ、どうして', 'mengapa'],
  ['希望',   'xīwàng',       'verb',        'to hope',                                         'ummak, umut etmek', '희망하다, 바라다', '望む、願う', 'berharap, harapan'],
  ['洗',     'xǐ',           'verb',        'to wash',                                         'yıkamak', '씻다', '洗う', 'mencuci'],
  ['洗手间', 'xǐshǒujiān',   'noun',        'restroom, toilet',                                'tuvalet, banyo', '화장실', 'トイレ、洗面所', 'kamar kecil, toilet'],
  ['下来',   'xiàlái',       'verb',        'to come down',                                    'aşağı inmek', '내려오다', '下りてくる', 'datang ke bawah'],
  ['下面',   'xiàmiàn',      'noun',        'below, under',                                    'altında, aşağısı', '아래, 밑', '下、下部', 'bawah'],
  ['下去',   'xiàqù',        'verb',        'to go down',                                      'aşağı inmek', '내려가다', '下りる', 'turun'],
  ['小孩儿', 'xiǎoháir',     'noun',        'child, little kid',                               'çocuk, küçük çocuk', '아이', '子供', 'anak, anak kecil'],
  ['小时候', 'xiǎoshíhou',   'noun',        'childhood',                                       'çocukluk', '어릴 때, 어린 시절', '子供のころ', 'masa kecil'],
  ['笑',     'xiào',         'verb',        'to laugh, to smile',                              'gülmek', '웃다', '笑う、微笑む', 'tertawa, tersenyum'],
  ['姓',     'xìng',         'noun',        'surname',                                         'soyadı', '성씨', '姓、名字', 'nama keluarga, marga'],
  ['姓名',   'xìngmíng',     'noun',        'full name',                                       'tam ad soyadı', '성명', '氏名、フルネーム', 'nama lengkap'],
  ['颜色',   'yánsè',        'noun',        'color',                                           'renk', '색깔', '色', 'warna'],
  ['眼睛',   'yǎnjing',      'noun',        'eye',                                             'göz', '눈', '目', 'mata'],
  ['药',     'yào',          'noun',        'medicine, drug',                                  'ilaç', '약', '薬', 'obat'],
  ['药店',   'yàodiàn',      'noun',        'pharmacy',                                        'eczane', '약국', '薬局', 'apotek'],
  ['爷爷',   'yéye',         'noun',        'grandfather',                                     'büyükbaba (baba tarafı)', '할아버지', '祖父', 'kakek'],
  ['一会儿', 'yíhuìr',       'adverb',      'a while, a moment; soon',                         'bir süre, biraz; yakında', '잠시, 잠깐', '少しの間、しばらく、まもなく', 'sebentar, sesaat'],
  ['已经',   'yǐjīng',       'adverb',      'already',                                         'zaten, çoktan', '이미, 벌써', 'すでに、もう', 'sudah'],
  ['一起',   'yìqǐ',         'adverb',      'together',                                        'birlikte', '함께, 같이', '一緒に', 'bersama-sama'],
  ['意思',   'yìsi',         'noun',        'meaning, idea',                                   'anlam, fikir', '뜻, 의미, 생각', '意味、考え、面白み', 'arti, makna, maksud'],
  ['阴',     'yīn',          'adjective',   'cloudy',                                          'bulutlu', '흐린', '曇っている', 'mendung, redup'],
  ['因为',   'yīnwèi',       'conjunction', 'because',                                         'çünkü', '왜냐하면, ~때문에', '〜なので、〜だから', 'karena'],
  ['游',     'yóu',          'verb',        'to swim',                                         'yüzmek', '헤엄치다', '泳ぐ', 'berenang'],
  ['游泳',   'yóuyǒng',      'verb',        'to swim',                                         'yüzmek', '수영하다', '泳ぐ、水泳', 'berenang'],
  ['有意思', 'yǒu yìsi',     'adjective',   'interesting, enjoyable',                          'ilginç, eğlenceli', '재미있다, 흥미롭다', '面白い、興味深い', 'menarik'],
  ['有时',   'yǒushí',       'adverb',      'sometimes',                                       'bazen', '때때로, 가끔', '時々', 'terkadang'],
  ['右',     'yòu',          'noun',        'right',                                           'sağ', '오른쪽', '右、右側', 'kanan'],
  ['右边',   'yòubian',      'noun',        'right side',                                      'sağ taraf', '오른쪽', '右側、右の方', 'sebelah kanan'],
  ['鱼',     'yú',           'noun',        'fish',                                            'balık', '물고기', '魚', 'ikan'],
  ['远',     'yuǎn',         'adjective',   'far',                                             'uzak', '멀다', '遠い', 'jauh'],
  ['运动',   'yùndòng',      'verb',        'to exercise; sports',                             'spor yapmak; spor', '운동하다, 스포츠', '運動する、スポーツ', 'berolahraga, olahraga'],
  ['站',     'zhàn',         'noun',        'station, stop',                                   'durak, istasyon', '정거장, 서다', '駅、停留所', 'stasiun, halte'],
  ['丈夫',   'zhàngfu',      'noun',        'husband',                                         'koca, eş (erkek)', '남편', '夫、主人', 'suami'],
  ['这么',   'zhème',        'pronoun',     'so, such, like this',                             'bu kadar, böyle', '이렇게, 이토록', 'こんなに、これほど', 'begitu, sedemikian'],
  ['这样',   'zhèyàng',      'pronoun',     'like this, so',                                   'böyle, bu şekilde', '이렇게, 이런 모양', 'このように、こうだ', 'seperti ini, begini'],
  ['着',     'zhe, zháo, zhuó',          'auxiliary',   'particle indicating ongoing action',               'devam eden eylem bildiren partikül', '고 (동작의 지속), 닿다, 얻다, 잡다', '（動作の持続を表す助詞）、（結果・到達を表す）〜に触れる、〜に達する', 'partikel aspek untuk tindakan yang sedang berlangsung, menyentuh'],
  ['正',     'zhèng, zhēng',        'adverb',      'just, exactly, right',                            'tam, tam olarak', '막, 바로, 꼭', 'ちょうど、まさに', 'tepat, pas'],
  ['周',     'zhōu',         'noun',        'week',                                            'hafta', '주', '週、一週間', 'pekan, minggu'],
  ['准备',   'zhǔnbèi',      'verb',        'to prepare',                                      'hazırlanmak, hazırlamak', '준비하다', '準備する、用意する', 'menyiapkan, bersiap'],
  ['自己',   'zìjǐ',         'pronoun',     'oneself',                                         'kendisi, kendi başına', '자기, 자신', '自分、自身', 'sendiri'],
  ['走',     'zǒu',          'verb',        'to walk',                                         'yürümek', '가다, 걷다', '歩く、行く', 'berjalan, pergi'],
  ['走路',   'zǒulù',        'verb',        'to walk',                                         'yürümek', '걷다', '歩く', 'berjalan kaki'],
  ['足球',   'zúqiú',        'noun',        'soccer, football',                                'futbol', '축구', 'サッカー', 'sepak bola'],
  ['最',     'zuì',          'adverb',      'most, -est',                                      'en', '가장, 제일', '最も、一番', 'paling, ter-'],
  ['左',     'zuǒ',          'noun',        'left',                                            'sol', '왼쪽', '左', 'kiri'],
  ['左边',   'zuǒbian',      'noun',        'left side',                                       'sol taraf', '왼쪽', '左側', 'sebelah kiri'],
];
