/// HSK Level 2 — 198 unique vocabulary entries (200 list entries, 2 duplicates merged).
/// Each row: [simplified, pinyin, pos, en, tr]
const List<List<String>> kHsk2Words = [
  ['啊',     'a',            'auxiliary',   'ah, oh',                                          'ah, oh'],
  ['爱好',   'àihào',        'verb',        'to like; hobby',                                  'beğenmek; hobi'],
  ['白色',   'báisè',        'noun',        'white',                                           'beyaz'],
  ['班',     'bān',          'noun',        'class, team',                                     'sınıf, takım'],
  ['帮',     'bāng',         'verb',        'to help',                                         'yardım etmek'],
  ['帮忙',   'bāngmáng',     'verb',        'to help',                                         'yardım etmek'],
  ['包',     'bāo',          'noun',        'to wrap; bag',                                    'sarmak; çanta'],
  ['本子',   'běnzi',        'noun',        'notebook',                                        'defter'],
  ['比',     'bǐ',           'preposition', 'than; to compare',                                'daha; karşılaştırmak'],
  ['笔',     'bǐ',           'noun',        'pen',                                             'kalem'],
  ['别',     'bié',          'adverb',      "don't",                                           'yapma'],
  ['不错',   'búcuò',        'adjective',   'not bad, pretty good',                            'fena değil, oldukça iyi'],
  ['不好意思','bù hǎoyìsi',  'expression',  'sorry, embarrassed',                              'özür dilerim, utanmak'],
  ['长',     'cháng',        'adjective',   'long',                                            'uzun'],
  ['车站',   'chēzhàn',      'noun',        'station',                                         'istasyon'],
  ['出',     'chū',          'verb',        'to go out, to leave',                             'dışarı çıkmak, ayrılmak'],
  ['出国',   'chūguó',       'verb',        'to go abroad',                                    'yurt dışına çıkmak'],
  ['出来',   'chūlái',       'verb',        'to come out',                                     'dışarı çıkmak'],
  ['出门',   'chūmén',       'verb',        'to go out',                                       'dışarı çıkmak'],
  ['出去',   'chūqù',        'verb',        'to go out',                                       'dışarı gitmek'],
  ['床',     'chuáng',       'noun',        'bed',                                             'yatak'],
  ['词',     'cí',           'noun',        'word, term',                                      'kelime, terim'],
  ['次',     'cì',           'classifier',  'measure word for times or occasions',              'kez, defa'],
  ['从',     'cóng',         'preposition', 'from',                                            '-den, -dan'],
  ['从小',   'cóngxiǎo',    'adverb',      'from childhood',                                  'çocukluktan beri'],
  ['错',     'cuò',          'adjective',   'wrong, mistaken',                                 'yanlış, hatalı'],
  ['打',     'dǎ',           'verb',        'to hit, to play, to make',                        'vurmak, oynamak'],
  ['打车',   'dǎchē',        'verb',        'to take a taxi',                                  'taksi tutmak'],
  ['打开',   'dǎkāi',        'verb',        'to open',                                         'açmak'],
  ['但',     'dàn',          'conjunction', 'but, however',                                    'ama, fakat'],
  ['但是',   'dànshì',       'conjunction', 'but, however',                                    'ama, fakat'],
  ['得',     'de',           'auxiliary',   'particle indicating degree or manner',             'derece veya tarz bildiren partikül'],
  ['地',     'de',           'auxiliary',   'particle modifying adjective into adverb',         'sıfatı zarfa dönüştüren partikül'],
  ['等',     'děng',         'verb',        'to wait',                                         'beklemek'],
  ['地铁',   'dìtiě',        'noun',        'subway, metro',                                   'metro'],
  ['点',     'diǎn',         'verb',        'to order; point, dot',                            'sipariş etmek; nokta'],
  ['懂',     'dǒng',         'verb',        'to understand',                                   'anlamak'],
  ['动',     'dòng',         'verb',        'to move, to act',                                 'hareket etmek'],
  ['饭馆',   'fànguǎn',      'noun',        'restaurant',                                      'restoran'],
  ['飞',     'fēi',          'verb',        'to fly',                                          'uçmak'],
  ['高',     'gāo',          'adjective',   'tall, high',                                      'uzun boylu, yüksek'],
  ['高中',   'gāozhōng',     'noun',        'high school',                                     'lise'],
  ['告诉',   'gàosu',        'verb',        'to tell',                                         'söylemek, anlatmak'],
  ['个子',   'gèzi',         'noun',        'height, stature',                                 'boy, endam'],
  ['跟',     'gēn',          'preposition', 'with; and',                                       'ile; ve'],
  ['公交车', 'gōngjiāochē',  'noun',        'bus',                                             'otobüs'],
  ['过',     'guò',          'verb',        'to pass, to cross; past experience particle',      'geçmek; geçmiş deneyim partikülü'],
  ['过来',   'guòlái',       'verb',        'to come over',                                    'yaklaşmak, gelmek'],
  ['过年',   'guònián',      'verb',        'to celebrate the New Year',                       'Yeni Yıl kutlamak'],
  ['过去',   'guòqù',        'verb',        'to go over',                                      'oraya gitmek'],
  ['还是',   'háishi',       'adverb',      'still; or',                                       'hâlâ; ya da'],
  ['黑色',   'hēisè',        'noun',        'black',                                           'siyah'],
  ['红茶',   'hóngchá',      'noun',        'black tea',                                       'siyah çay'],
  ['红色',   'hóngsè',       'noun',        'red',                                             'kırmızı'],
  ['后面',   'hòumiàn',      'noun',        'behind, back',                                    'arka, geri'],
  ['花',     'huā',          'verb',        'to spend (money or time); flower',                'harcamak (para/zaman); çiçek'],
  ['画',     'huà',          'verb',        'to draw, to paint; painting',                     'çizmek, resim yapmak; resim'],
  ['坏',     'huài',         'adjective',   'bad, broken',                                     'kötü, bozuk'],
  ['回来',   'huílái',       'verb',        'to come back',                                    'geri dönmek'],
  ['回去',   'huíqù',        'verb',        'to go back',                                      'geri gitmek'],
  ['机场',   'jīchǎng',      'noun',        'airport',                                         'havalimanı'],
  ['机票',   'jīpiào',       'noun',        'airplane ticket',                                 'uçak bileti'],
  ['记得',   'jìde',         'verb',        'to remember',                                     'hatırlamak'],
  ['间',     'jiān',         'classifier',  'measure word for rooms',                          'oda sayı sözcüğü'],
  ['教',     'jiāo',         'verb',        'to teach',                                        'öğretmek'],
  ['教室',   'jiàoshì',      'noun',        'classroom',                                       'sınıf'],
  ['介绍',   'jièshào',      'verb',        'to introduce',                                    'tanıtmak'],
  ['进',     'jìn',          'verb',        'to enter',                                        'girmek'],
  ['近',     'jìn',          'adjective',   'near, close',                                     'yakın'],
  ['进来',   'jìnlái',       'verb',        'to come in',                                      'içeri girmek'],
  ['进去',   'jìnqù',        'verb',        'to go in',                                        'içeri gitmek'],
  ['经常',   'jīngcháng',    'adverb',      'often',                                           'sık sık, çoğunlukla'],
  ['酒店',   'jiǔdiàn',      'noun',        'hotel',                                           'otel'],
  ['就',     'jiù',          'adverb',      'just, then',                                      'hemen, o zaman'],
  ['咖啡',   'kāfēi',        'noun',        'coffee',                                          'kahve'],
  ['开始',   'kāishǐ',       'verb',        'to start; beginning',                             'başlamak; başlangıç'],
  ['开学',   'kāixué',       'verb',        'school starts',                                   'okul başlamak'],
  ['考',     'kǎo',          'verb',        'to test, to take an exam',                        'sınav yapmak'],
  ['考试',   'kǎoshì',       'verb',        'to take an exam; exam',                           'sınava girmek; sınav'],
  ['可能',   'kěnéng',       'adjective',   'possible; may',                                   'mümkün; olabilir'],
  ['裤子',   'kùzi',         'noun',        'pants',                                           'pantolon'],
  ['快',     'kuài',         'adjective',   'fast; soon',                                      'hızlı; yakında'],
  ['快乐',   'kuàilè',       'adjective',   'happy, joyful',                                   'mutlu, neşeli'],
  ['快要',   'kuàiyào',      'adverb',      'soon, almost',                                    'yakında, neredeyse'],
  ['篮球',   'lánqiú',       'noun',        'basketball',                                      'basketbol'],
  ['累',     'lèi',          'adjective',   'tired; to tire',                                  'yorgun; yormak'],
  ['离',     'lí',           'verb',        'to leave, to be away from',                       'ayrılmak, uzakta olmak'],
  ['里面',   'lǐmiàn',       'noun',        'inside',                                          'içeri, içinde'],
  ['楼',     'lóu',          'noun',        'building, floor',                                 'bina, kat'],
  ['路',     'lù',           'noun',        'road, path',                                      'yol'],
  ['路上',   'lùshang',      'noun',        'on the road',                                     'yolda'],
  ['旅游',   'lǚyóu',        'verb',        'to travel',                                       'seyahat etmek'],
  ['绿茶',   'lǜchá',        'noun',        'green tea',                                       'yeşil çay'],
  ['绿色',   'lǜsè',         'noun',        'green',                                           'yeşil'],
  ['慢',     'màn',          'adjective',   'slow',                                            'yavaş'],
  ['没意思', 'méi yìsi',     'adjective',   'boring, uninteresting',                           'sıkıcı, ilginç değil'],
  ['每',     'měi',          'pronoun',     'every, each',                                     'her, her biri'],
  ['门',     'mén',          'noun',        'door, gate',                                      'kapı'],
  ['门口',   'ménkǒu',       'noun',        'doorway, entrance',                               'kapı önü, giriş'],
  ['门票',   'ménpiào',      'noun',        'ticket',                                          'giriş bileti'],
  ['面',     'miàn',         'noun',        'side, aspect',                                    'taraf, yön'],
  ['名',     'míng',         'classifier',  'measure word for people; name',                   'kişi sayı sözcüğü; isim'],
  ['拿',     'ná',           'verb',        'to take, to hold',                                'almak, tutmak'],
  ['那么',   'nàme',         'conjunction', 'so, then',                                        'öyleyse, o zaman'],
  ['那样',   'nàyàng',       'pronoun',     'like that',                                       'böyle, öyle'],
  ['奶茶',   'nǎichá',       'noun',        'milk tea',                                        'sütlü çay'],
  ['奶奶',   'nǎinai',       'noun',        'grandmother',                                     'büyükanne (baba tarafı)'],
  ['男孩儿', 'nánháir',      'noun',        'boy',                                             'erkek çocuk'],
  ['鸟',     'niǎo',         'noun',        'bird',                                            'kuş'],
  ['女孩儿', 'nǚháir',       'noun',        'girl',                                            'kız çocuk'],
  ['旁边',   'pángbiān',     'noun',        'side',                                            'yan, yanı'],
  ['跑',     'pǎo',          'verb',        'to run',                                          'koşmak'],
  ['跑步',   'pǎobù',        'verb',        'to run, jogging',                                 'koşmak, jogging yapmak'],
  ['票',     'piào',         'noun',        'ticket',                                          'bilet'],
  ['妻子',   'qīzi',         'noun',        'wife',                                            'eş (kadın)'],
  ['起来',   'qǐlái',        'verb',        'to get up, to stand up',                          'kalkmak, ayağa kalkmak'],
  ['前面',   'qiánmiàn',     'noun',        'front',                                           'ön'],
  ['晴',     'qíng',         'adjective',   'sunny, clear',                                    'güneşli, açık'],
  ['球',     'qiú',          'noun',        'ball, sphere',                                    'top'],
  ['让',     'ràng',         'verb',        'to let, to allow',                                'izin vermek, bırakmak'],
  ['肉',     'ròu',          'noun',        'meat',                                            'et'],
  ['商场',   'shāngchǎng',   'noun',        'shopping mall',                                   'alışveriş merkezi'],
  ['上来',   'shànglái',     'verb',        'to come up',                                      'yukarı çıkmak'],
  ['上面',   'shàngmiàn',    'noun',        'above, top',                                      'üstünde, üzeri'],
  ['上去',   'shàngqù',      'verb',        'to go up',                                        'yukarı çıkmak'],
  ['上网',   'shàngwǎng',    'verb',        'to go online',                                    'internete girmek'],
  ['身体',   'shēntǐ',       'noun',        'body',                                            'vücut, beden'],
  ['生日',   'shēngrì',      'noun',        'birthday',                                        'doğum günü'],
  ['时',     'shí',          'noun',        'time, moment',                                    'zaman, an'],
  ['事情',   'shìqing',      'noun',        'matter, affair',                                  'konu, mesele'],
  ['手',     'shǒu',         'noun',        'hand',                                            'el'],
  ['手表',   'shǒubiǎo',     'noun',        'watch, wristwatch',                               'kol saati'],
  ['书包',   'shūbāo',       'noun',        'backpack, schoolbag',                             'sırt çantası, okul çantası'],
  ['舒服',   'shūfu',        'adjective',   'comfortable',                                     'rahat, konforlu'],
  ['送',     'sòng',         'verb',        'to give, to send, to see off',                    'vermek, göndermek, uğurlamak'],
  ['虽然',   'suīrán',       'conjunction', 'although',                                        'her ne kadar, -se de'],
  ['所以',   'suǒyǐ',        'conjunction', 'so, therefore',                                   'bu yüzden, bu nedenle'],
  ['疼',     'téng',         'adjective',   'painful, sore',                                   'ağrılı, sızlayan'],
  ['踢',     'tī',           'verb',        'to kick',                                         'tekmelemek'],
  ['题',     'tí',           'noun',        'question, problem, topic',                        'soru, sorun, konu'],
  ['条',     'tiáo',         'classifier',  'measure word for long thin objects',               'uzun ince nesneler için sayı sözcüğü'],
  ['跳舞',   'tiàowǔ',       'verb',        'to dance',                                        'dans etmek'],
  ['头',     'tóu',          'noun',        'head',                                            'baş'],
  ['外国',   'wàiguó',       'noun',        'foreign country',                                 'yabancı ülke'],
  ['外面',   'wàimiàn',      'noun',        'outside',                                         'dışarı, dışı'],
  ['完',     'wán',          'verb',        'to finish',                                       'bitirmek, tamamlamak'],
  ['万',     'wàn',          'number',      'ten thousand',                                    'on bin'],
  ['往',     'wǎng',         'preposition', 'toward',                                          'doğru, -e doğru'],
  ['网上',   'wǎngshang',    'noun',        'online',                                          'çevrimiçi, internette'],
  ['忘',     'wàng',         'verb',        'to forget',                                       'unutmak'],
  ['位',     'wèi',          'classifier',  'measure word for people (polite)',                 'kişi sayı sözcüğü (saygılı)'],
  ['为什么', 'wèi shénme',   'adverb',      'why',                                             'neden, niçin'],
  ['希望',   'xīwàng',       'verb',        'to hope',                                         'ummak, umut etmek'],
  ['洗',     'xǐ',           'verb',        'to wash',                                         'yıkamak'],
  ['洗手间', 'xǐshǒujiān',   'noun',        'restroom, toilet',                                'tuvalet, banyo'],
  ['下来',   'xiàlái',       'verb',        'to come down',                                    'aşağı inmek'],
  ['下面',   'xiàmiàn',      'noun',        'below, under',                                    'altında, aşağısı'],
  ['下去',   'xiàqù',        'verb',        'to go down',                                      'aşağı inmek'],
  ['小孩儿', 'xiǎoháir',     'noun',        'child, little kid',                               'çocuk, küçük çocuk'],
  ['小时候', 'xiǎoshíhou',   'noun',        'childhood',                                       'çocukluk'],
  ['笑',     'xiào',         'verb',        'to laugh, to smile',                              'gülmek'],
  ['姓',     'xìng',         'noun',        'surname',                                         'soyadı'],
  ['姓名',   'xìngmíng',     'noun',        'full name',                                       'tam ad soyadı'],
  ['颜色',   'yánsè',        'noun',        'color',                                           'renk'],
  ['眼睛',   'yǎnjing',      'noun',        'eye',                                             'göz'],
  ['药',     'yào',          'noun',        'medicine, drug',                                  'ilaç'],
  ['药店',   'yàodiàn',      'noun',        'pharmacy',                                        'eczane'],
  ['爷爷',   'yéye',         'noun',        'grandfather',                                     'büyükbaba (baba tarafı)'],
  ['一会儿', 'yíhuìr',       'adverb',      'a while, a moment; soon',                         'bir süre, biraz; yakında'],
  ['已经',   'yǐjīng',       'adverb',      'already',                                         'zaten, çoktan'],
  ['一起',   'yìqǐ',         'adverb',      'together',                                        'birlikte'],
  ['意思',   'yìsi',         'noun',        'meaning, idea',                                   'anlam, fikir'],
  ['阴',     'yīn',          'adjective',   'cloudy',                                          'bulutlu'],
  ['因为',   'yīnwèi',       'conjunction', 'because',                                         'çünkü'],
  ['游',     'yóu',          'verb',        'to swim',                                         'yüzmek'],
  ['游泳',   'yóuyǒng',      'verb',        'to swim',                                         'yüzmek'],
  ['有意思', 'yǒu yìsi',     'adjective',   'interesting, enjoyable',                          'ilginç, eğlenceli'],
  ['有时',   'yǒushí',       'adverb',      'sometimes',                                       'bazen'],
  ['右',     'yòu',          'noun',        'right',                                           'sağ'],
  ['右边',   'yòubian',      'noun',        'right side',                                      'sağ taraf'],
  ['鱼',     'yú',           'noun',        'fish',                                            'balık'],
  ['远',     'yuǎn',         'adjective',   'far',                                             'uzak'],
  ['运动',   'yùndòng',      'verb',        'to exercise; sports',                             'spor yapmak; spor'],
  ['站',     'zhàn',         'noun',        'station, stop',                                   'durak, istasyon'],
  ['丈夫',   'zhàngfu',      'noun',        'husband',                                         'koca, eş (erkek)'],
  ['这么',   'zhème',        'pronoun',     'so, such, like this',                             'bu kadar, böyle'],
  ['这样',   'zhèyàng',      'pronoun',     'like this, so',                                   'böyle, bu şekilde'],
  ['着',     'zhe',          'auxiliary',   'particle indicating ongoing action',               'devam eden eylem bildiren partikül'],
  ['正',     'zhèng',        'adverb',      'just, exactly, right',                            'tam, tam olarak'],
  ['周',     'zhōu',         'noun',        'week',                                            'hafta'],
  ['准备',   'zhǔnbèi',      'verb',        'to prepare',                                      'hazırlanmak, hazırlamak'],
  ['自己',   'zìjǐ',         'pronoun',     'oneself',                                         'kendisi, kendi başına'],
  ['走',     'zǒu',          'verb',        'to walk',                                         'yürümek'],
  ['走路',   'zǒulù',        'verb',        'to walk',                                         'yürümek'],
  ['足球',   'zúqiú',        'noun',        'soccer, football',                                'futbol'],
  ['最',     'zuì',          'adverb',      'most, -est',                                      'en'],
  ['左',     'zuǒ',          'noun',        'left',                                            'sol'],
  ['左边',   'zuǒbian',      'noun',        'left side',                                       'sol taraf'],
];
