/// HSK Level 3 — ~494 unique vocabulary entries (500 list entries, ~6 duplicates deduplicated).
/// Each row: [simplified, pinyin, pos, en, tr]
const List<List<String>> kHsk3Words = [
  ['阿姨','āyí','noun','aunt','hala, teyze'],
  ['矮','ǎi','adjective','short','kısa boylu'],
  ['爱人','àiren','noun','spouse','eş'],
  ['安静','ānjìng','adjective','quiet','sessiz, sakin'],
  ['安全','ānquán','adjective','safe','güvenli'],
  ['把','bǎ','classifier','measure word for handles; object-fronting particle','saplı nesneler sayı sözcüğü'],
  ['搬','bān','verb','to move, to carry','taşımak'],
  ['班级','bānjí','noun','class, grade','sınıf'],
  ['搬家','bānjiā','verb','to move house','ev taşımak'],
  ['办','bàn','verb','to do, to handle','yapmak, halletmek'],
  ['办法','bànfǎ','noun','way, solution','yol, çözüm'],
  ['办公室','bàngōngshì','noun','office','ofis'],
  ['半天','bàntiān','number-classifier','half a day, a long time','yarım gün, uzun zaman'],
  ['帮助','bāngzhù','verb','to help','yardım etmek'],
  ['饱','bǎo','adjective','full','tok'],
  ['报纸','bàozhǐ','noun','newspaper','gazete'],
  ['北','běi','noun','north','kuzey'],
  ['北方','běifāng','noun','north','kuzey'],
  ['被','bèi','preposition','by','tarafından'],
  ['笔记','bǐjì','noun','notes','not'],
  ['比较','bǐjiào','adverb','to compare; quite, relatively; than','karşılaştırmak; oldukça'],
  ['笔记本','bǐjìběn','noun','notebook','defter'],
  ['比如','bǐrú','verb','for example','örneğin'],
  ['比赛','bǐsài','verb','to compete; game, match','yarışmak; maç'],
  ['必须','bìxū','adverb','must','zorunlu olmak'],
  ['变','biàn','verb','to change, to become','değişmek'],
  ['遍','biàn','classifier','measure word for actions','eylemler için sayı sözcüğü (kez)'],
  ['变成','biànchéng','verb','to become, to turn into','olmak, dönüşmek'],
  ['变化','biànhuà','verb','to change; change','değişmek; değişim'],
  ['表演','biǎoyǎn','verb','to perform, to act','sahne almak, oynamak'],
  ['别的','biéde','pronoun','other','diğer'],
  ['别人','biérén','pronoun','other people','başkaları'],
  ['宾馆','bīnguǎn','noun','hotel','otel'],
  ['冰','bīng','noun','ice; (to freeze)','buz; (donmak)'],
  ['冰激凌','bīngjīlíng','noun','ice cream','dondurma'],
  ['冰箱','bīngxiāng','noun','refrigerator','buzdolabı'],
  ['病人','bìngrén','noun','patient','hasta'],
  ['不但','búdàn','conjunction','not only','sadece değil'],
  ['不见','bújiàn','verb','to disappear, to not see','kaybolmak, görmemek'],
  ['不用','búyòng','adverb','need not','gerek yok'],
  ['不同','bùtóng','adjective','different','farklı'],
  ['不久','bùjiǔ','adjective','soon, not long after','kısa süre sonra'],
  ['不行','bùxíng','adjective','not allowed; not good','olmaz; iyi değil'],
  ['才','cái','adverb','just, only','ancak, yalnızca'],
  ['菜单','càidān','noun','menu','menü'],
  ['参加','cānjiā','verb','to join, to attend','katılmak'],
  ['草','cǎo','noun','grass','çimen, ot'],
  ['草地','cǎodì','noun','grassland','çayırlık, ot, çimen'],
  ['层','céng','classifier','measure word for layer, floor','kat sayı sözcüğü'],
  ['查','chá','verb','to check','kontrol etmek'],
  ['差','chà','adjective','bad, poor; to lack','kötü, yetersiz'],
  ['差不多','chàbuduō','adverb','almost, similar; nearly','hemen hemen, yaklaşık'],
  ['尝','cháng','verb','to taste','tatmak'],
  ['常','cháng','adverb','often, frequent','sık sık'],
  ['常见','chángjiàn','adjective','common','yaygın'],
  ['常用','chángyòng','adjective','commonly used','sık kullanılan'],
  ['常常','chángcháng','adverb','often','sık sık'],
  ['衬衫','chènshān','noun','shirt','gömlek'],
  ['成绩','chéngjì','noun','score, grade, achievement','not, derece, başarı'],
  ['城市','chéngshì','noun','city','şehir'],
  ['迟到','chídào','verb','to be late','geç kalmak'],
  ['出发','chūfā','verb','to set out, to leave','yola çıkmak'],
  ['出生','chūshēng','verb','to be born','doğmak'],
  ['出院','chūyuàn','verb','to be discharged from hospital','taburcu olmak'],
  ['初中','chūzhōng','noun','junior high school','ortaokul'],
  ['除了','chúle','preposition','except, besides','-den başka, dışında'],
  ['船','chuán','noun','boat','tekne, gemi'],
  ['春天','chūntiān','noun','spring','ilkbahar'],
  ['词典','cídiǎn','noun','dictionary','sözlük'],
  ['聪明','cōngmíng','adjective','smart, clever','zeki, akıllı'],
  ['打扫','dǎsǎo','verb','to clean','temizlemek'],
  ['打算','dǎsuàn','verb','to plan, intend; plan','planlamak; plan'],
  ['大概','dàgài','adverb','probably, approximately; general','muhtemelen; genel'],
  ['大人','dàren','noun','adult','yetişkin'],
  ['大小','dàxiǎo','noun','size','boyut, beden'],
  ['大熊猫','dàxióngmāo','noun','giant panda','dev panda'],
  ['大衣','dàyī','noun','coat','palto'],
  ['带','dài','verb','to bring, to take; (belt)','getirmek, almak; (kemer)'],
  ['担心','dānxīn','verb','to worry','endişelenmek'],
  ['蛋糕','dàngāo','noun','cake','pasta'],
  ['当然','dāngrán','adverb','of course','tabii ki, elbette'],
  ['到处','dàochù','adverb','everywhere','her yerde'],
  ['得到','dédào','verb','to get, to obtain','elde etmek'],
  ['得分','défēn','verb','to score; score','puan almak; puan'],
  ['的话','dehuà','auxiliary','particle after condition clause, if...','koşul partikülü, eğer...'],
  ['灯','dēng','noun','lamp, light','lamba, ışık'],
  ['地点','dìdiǎn','noun','place, location','yer, konum'],
  ['地方','dìfang','noun','place','yer'],
  ['地图','dìtú','noun','map','harita'],
  ['电','diàn','noun','electricity; (to give an electric shock)','elektrik; (elektrik çarpmak)'],
  ['电梯','diàntī','noun','elevator','asansör'],
  ['电子书','diànzǐshū','noun','e-book','e-kitap'],
  ['丢','diū','verb','to lose, to throw away','kaybetmek, atmak'],
  ['东','dōng','noun','east','doğu'],
  ['东北','dōngběi','noun','northeast','kuzeydoğu'],
  ['东方','dōngfāng','noun','east','doğu'],
  ['东南','dōngnán','noun','southeast','güneydoğu'],
  ['冬天','dōngtiān','noun','winter','kış'],
  ['懂得','dǒngde','verb','to understand','anlamak'],
  ['动物','dòngwù','noun','animal','hayvan'],
  ['动物园','dòngwùyuán','noun','zoo','hayvanat bahçesi'],
  ['短','duǎn','adjective','short','kısa'],
  ['短裤','duǎnkù','noun','shorts','şort'],
  ['段','duàn','classifier','measure word for segment, paragraph','bölüm, paragraf sayı sözcüğü'],
  ['锻炼','duànliàn','verb','to exercise','egzersiz yapmak'],
  ['对话','duìhuà','noun','dialogue, conversation','diyalog, konuşma'],
  ['饿','è','adjective','hungry','aç'],
  ['而且','érqiě','conjunction','and, moreover','ayrıca, üstelik'],
  ['耳朵','ěrduo','noun','ear','kulak'],
  ['耳机','ěrjī','noun','earphone','kulaklık'],
  ['发','fā','verb','to send, to issue','göndermek, yayımlamak'],
  ['发烧','fāshāo','verb','to have a fever','ateş çıkmak'],
  ['发生','fāshēng','verb','to happen','olmak, meydana gelmek'],
  ['发现','fāxiàn','verb','to find, to discover','bulmak, keşfetmek'],
  ['发展','fāzhǎn','verb','to develop','gelişmek'],
  ['方便','fāngbiàn','adjective','convenient','uygun, pratik'],
  ['方便面','fāngbiànmiàn','noun','instant noodles','hazır noodle'],
  ['方法','fāngfǎ','noun','method','yöntem'],
  ['方向','fāngxiàng','noun','direction','yön'],
  ['房子','fángzi','noun','house','ev'],
  ['放','fàng','verb','to put, to place','koymak, yerleştirmek'],
  ['放假','fàngjià','verb','to have a holiday','tatile çıkmak'],
  ['放心','fàngxīn','verb','to relax, to feel at ease','rahatlamak'],
  ['放学','fàngxué','verb','school is over','okul bitmek'],
  ['分开','fēnkāi','verb','to separate','ayrılmak, ayırmak'],
  ['风','fēng','noun','wind','rüzgar'],
  ['封','fēng','classifier','measure word for letters; (to seal)','mektup sayı sözcüğü; (mühürlemek)'],
  ['夫妻','fūqī','noun','husband and wife','karı koca'],
  ['服务','fúwù','verb','to serve','hizmet etmek'],
  ['附近','fùjìn','noun','nearby','yakın çevrede'],
  ['复习','fùxí','verb','to review','tekrar etmek'],
  ['该','gāi','verb','should','-meli'],
  ['干净','gānjìng','adjective','clean','temiz'],
  ['感兴趣','gǎn xìngqù','verb','to be interested in','ilgi duymak'],
  ['感到','gǎndào','verb','to feel','hissetmek'],
  ['感冒','gǎnmào','noun','cold; to catch a cold','soğuk algınlığı; soğuk almak'],
  ['干','gàn','verb','to do, to work','yapmak, çalışmak'],
  ['刚','gāng','adverb','just, just now','hemen, az önce'],
  ['刚才','gāngcái','noun','just now','az önce'],
  ['刚刚','gānggāng','adverb','just now, a moment ago','az önce, biraz önce'],
  ['高铁','gāotiě','noun','high-speed rail','hızlı tren'],
  ['根据','gēnjù','preposition','according to; to base on; (basis)','-e göre; dayanmak; (temel)'],
  ['更','gèng','adverb','more','daha'],
  ['公斤','gōngjīn','classifier','kilogram','kilogram'],
  ['公园','gōngyuán','noun','park','park'],
  ['工作日','gōngzuòrì','noun','workday','iş günü'],
  ['故事','gùshi','noun','story','hikaye'],
  ['刮','guā','verb','to scrape, to blow','kazımak, esmek'],
  ['关','guān','verb','to close, to turn off; pass','kapatmak; geçit'],
  ['关机','guānjī','verb','to turn off device','cihazı kapatmak'],
  ['关系','guānxì','noun','relationship; (to relate)','ilişki; (ilgili olmak)'],
  ['关心','guānxīn','verb','to care about, to be concerned','önemsemek, ilgilenmek'],
  ['关于','guānyú','preposition','about, regarding','hakkında'],
  ['关注','guānzhù','verb','to pay attention to, to follow','ilgi göstermek, takip etmek'],
  ['国家','guójiā','noun','country','ülke'],
  ['过节','guòjié','verb','to celebrate a festival','bayram kutlamak'],
  ['海','hǎi','noun','sea','deniz'],
  ['害怕','hàipà','verb','to be afraid','korkmak'],
  ['好多','hǎoduō','adjective','many, a lot','çok, bir sürü'],
  ['好久','hǎojiǔ','adjective','a long time','uzun zaman'],
  ['好像','hǎoxiàng','adverb','to seem, as if; perhaps','gibi görünmek; belki'],
  ['号码','hàomǎ','noun','number, code','numara, kod'],
  ['河','hé','noun','river','nehir'],
  ['合适','héshì','adjective','suitable','uygun'],
  ['黑板','hēibǎn','noun','blackboard','kara tahta'],
  ['红绿灯','hónglǜdēng','noun','traffic light','trafik ışığı'],
  ['后来','hòulái','noun','later, afterwards','sonradan'],
  ['后年','hòunián','noun','the year after next','öbür yıl'],
  ['后天','hòutiān','noun','the day after tomorrow','öbür gün'],
  ['护照','hùzhào','noun','passport','pasaport'],
  ['花园','huāyuán','noun','garden','bahçe'],
  ['画家','huàjiā','noun','painter, artist','ressam, sanatçı'],
  ['欢迎','huānyíng','verb','to welcome','karşılamak'],
  ['还','huán','verb','to return, to give back','geri vermek'],
  ['环境','huánjìng','noun','environment','çevre, ortam'],
  ['换','huàn','verb','to exchange, to change','değiştirmek'],
  ['黄色','huángsè','noun','yellow','sarı'],
  ['回答','huídá','verb','to answer','cevap vermek'],
  ['会','huì','noun','meeting','toplantı'],
  ['会议','huìyì','noun','meeting','toplantı'],
  ['或','huò','conjunction','or; (perhaps, maybe)','ya da; (belki)'],
  ['或者','huòzhě','conjunction','or','ya da'],
  ['鸡','jī','noun','chicken','tavuk'],
  ['几乎','jīhū','adverb','almost','neredeyse'],
  ['机会','jīhuì','noun','opportunity','fırsat'],
  ['极','jí','adverb','extremely','son derece'],
  ['急','jí','adjective','urgent; (to worry)','acil; (endişelenmek)'],
  ['记','jì','verb','to remember','hatırlamak'],
  ['季','jì','noun','season','mevsim'],
  ['季节','jìjié','noun','season','mevsim'],
  ['加','jiā','verb','to add','eklemek'],
  ['假期','jiàqī','noun','vacation','tatil'],
  ['坚持','jiānchí','verb','to persist','ısrar etmek, devam etmek'],
  ['检查','jiǎnchá','verb','to check, to inspect','kontrol etmek, incelemek'],
  ['简单','jiǎndān','adjective','simple','basit'],
  ['检票','jiǎnpiào','verb','ticket checking','bilet kontrol etmek'],
  ['健康','jiànkāng','adjective','healthy','sağlıklı'],
  ['见面','jiànmiàn','verb','to meet','buluşmak'],
  ['讲','jiǎng','verb','to speak, to talk','konuşmak, anlatmak'],
  ['角','jiǎo','classifier','measure word for fractions, angle, currency','para, açı sayı sözcüğü'],
  ['脚','jiǎo','noun','foot','ayak'],
  ['接','jiē','verb','to pick up, to receive','karşılamak, almak'],
  ['街','jiē','noun','street','cadde, sokak'],
  ['节','jié','classifier','measure word for segments, lessons; festival','bölüm, ders sayı sözcüğü; festival'],
  ['结婚','jiéhūn','verb','to marry','evlenmek'],
  ['节目','jiémù','noun','program','program'],
  ['节日','jiérì','noun','festival','festival, bayram'],
  ['结束','jiéshù','verb','to end','bitmek, sona ermek'],
  ['解决','jiějué','verb','to solve','çözmek'],
  ['姐妹','jiěmèi','noun','sister','kız kardeş'],
  ['借','jiè','verb','to borrow','ödünç almak'],
  ['斤','jīn','classifier','catty (500g)','jin (500g ağırlık birimi)'],
  ['经过','jīngguò','verb','to pass; process','geçmek; süreç'],
  ['经理','jīnglǐ','noun','manager','müdür'],
  ['久','jiǔ','adjective','long (time)','uzun (süre)'],
  ['酒','jiǔ','noun','alcohol','alkol, içki'],
  ['旧','jiù','adjective','old','eski'],
  ['句','jù','classifier','measure word of sentence','cümle sayı sözcüğü'],
  ['句子','jùzi','noun','sentence','cümle'],
  ['决定','juédìng','verb','to decide; decision','karar vermek; karar'],
  ['卡','kǎ','noun','card','kart'],
  ['开花','kāihuā','verb','to bloom','çiçek açmak'],
  ['开会','kāihuì','verb','to have a meeting','toplantı yapmak'],
  ['开机','kāijī','verb','to turn on device','cihazı açmak'],
  ['开心','kāixīn','adjective','happy','mutlu, neşeli'],
  ['看来','kànlái','verb','it seems, it appears','görünüşe göre'],
  ['可','kě','conjunction','but; (yet)','ama; (henüz)'],
  ['渴','kě','adjective','thirsty','susamış'],
  ['可爱','kě\'ài','adjective','lovely','sevimli'],
  ['可是','kěshì','conjunction','but','ama, fakat'],
  ['刻','kè','classifier','quarter; to carve','çeyrek saat; (oymak)'],
  ['课本','kèběn','noun','textbook','ders kitabı'],
  ['客人','kèrén','noun','guest','misafir'],
  ['课文','kèwén','noun','text','metin, okuma parçası'],
  ['空调','kōngtiáo','noun','air conditioner','klima'],
  ['哭','kū','verb','to cry','ağlamak'],
  ['筷子','kuàizi','noun','chopsticks','yemek çubukları'],
  ['矿泉水','kuàngquánshuǐ','noun','mineral water','maden suyu'],
  ['来自','láizì','verb','to come from','-den gelmek'],
  ['蓝','lán','adjective','blue','mavi'],
  ['老','lǎo','adjective','old, aged; (always, constantly)','yaşlı; (her zaman)'],
  ['老人','lǎorén','noun','elderly person','yaşlı kişi'],
  ['离开','líkāi','verb','to leave','ayrılmak'],
  ['礼物','lǐwù','noun','gift','hediye'],
  ['历史','lìshǐ','noun','history','tarih'],
  ['脸','liǎn','noun','face','yüz'],
  ['练','liàn','verb','to practice','alıştırma yapmak'],
  ['练习','liànxí','verb','to practice; exercise','alıştırma yapmak; alıştırma'],
  ['凉快','liángkuai','adjective','cool','serin, ferah'],
  ['辆','liàng','classifier','measure word for vehicles','araç sayı sözcüğü'],
  ['聊','liáo','verb','to chat','sohbet etmek'],
  ['聊天儿','liáotiānr','verb','to chat','sohbet etmek'],
  ['了解','liǎojiě','verb','to understand','anlamak, bilmek'],
  ['邻居','línjū','noun','neighbor','komşu'],
  ['留学','liúxué','verb','to study abroad','yurt dışında okumak'],
  ['留学生','liúxuéshēng','noun','overseas student','yurt dışı öğrencisi'],
  ['楼梯','lóutī','noun','stairs','merdiven'],
  ['路边','lùbiān','noun','roadside','yol kenarı'],
  ['路口','lùkǒu','noun','intersection','kavşak'],
  ['马','mǎ','noun','horse','at'],
  ['马路','mǎlù','noun','road','yol, cadde'],
  ['马上','mǎshàng','adverb','immediately','hemen'],
  ['满意','mǎnyì','verb','satisfied','memnun olmak'],
  ['毛','máo','classifier','measure word for money (0.1 yuan); (hair)','para sayı sözcüğü; (kıl, tüy)'],
  ['米','mǐ','classifier','meter','metre'],
  ['面前','miànqián','noun','in front of','önünde'],
  ['明白','míngbai','adjective','to understand; clear','anlamak; açık'],
  ['名单','míngdān','noun','name list','isim listesi'],
  ['名人','míngrén','noun','famous person','ünlü kişi'],
  ['南','nán','noun','south','güney'],
  ['难','nán','adjective','difficult; (to make difficult)','zor; (zorlaştırmak)'],
  ['南方','nánfāng','noun','south','güney'],
  ['难过','nánguò','adjective','sad','üzgün'],
  ['难看','nánkàn','adjective','ugly','çirkin'],
  ['男人','nánrén','noun','man','adam, erkek'],
  ['男生','nánshēng','noun','boy student','erkek öğrenci'],
  ['难题','nántí','noun','difficult problem','zor problem'],
  ['难听','nántīng','adjective','unpleasant to hear','kulak tırmalayan'],
  ['年级','niánjí','noun','grade','sınıf (yıl bazlı)'],
  ['年轻','niánqīng','adjective','young','genç'],
  ['牛','niú','noun','cow; (awesome)','inek; (harika)'],
  ['努力','nǔlì','adjective','to work hard; hardworking','çok çalışmak; çalışkan'],
  ['女人','nǚrén','noun','woman','kadın'],
  ['女生','nǚshēng','noun','girl student','kız öğrenci'],
  ['爬','pá','verb','to climb','tırmanmak'],
  ['怕','pà','verb','to fear; (perhaps)','korkmak; (belki)'],
  ['拍照','pāizhào','verb','to take a photo','fotoğraf çekmek'],
  ['盘子','pánzi','noun','plate','tabak'],
  ['胖','pàng','adjective','fat','şişman'],
  ['啤酒','píjiǔ','noun','beer','bira'],
  ['平时','píngshí','noun','usually','genellikle'],
  ['瓶子','píngzi','noun','bottle','şişe'],
  ['骑','qí','verb','to ride','binmek (bisiklet/at)'],
  ['奇怪','qíguài','adjective','strange','tuhaf, garip'],
  ['其实','qíshí','adverb','actually','aslında'],
  ['其他','qítā','pronoun','other','diğerleri'],
  ['起','qǐ','verb','to rise, to get up; (measure word for events)','kalkmak; (olay sayı sözcüğü)'],
  ['起飞','qǐfēi','verb','to take off','havalanmak'],
  ['汽车','qìchē','noun','car','araba'],
  ['铅笔','qiānbǐ','noun','pencil','kurşun kalem'],
  ['前年','qiánnián','noun','the year before last','iki yıl önce'],
  ['前天','qiántiān','noun','the day before yesterday','önceki gün'],
  ['清楚','qīngchu','adjective','clear, obvious; to understand','net, açık; anlamak'],
  ['请假','qǐngjià','verb','to ask for leave','izin istemek'],
  ['请客','qǐngkè','verb','to invite guests, to treat someone','misafir davet etmek, ısmarlamak'],
  ['秋天','qiūtiān','noun','autumn','sonbahar'],
  ['球场','qiúchǎng','noun','sports field, court','spor sahası, kort'],
  ['裙子','qúnzi','noun','skirt','etek'],
  ['然后','ránhòu','conjunction','then, afterwards','sonra'],
  ['热情','rèqíng','adjective','enthusiastic','coşkulu, sıcakkanlı'],
  ['认得','rènde','verb','to recognize, to know','tanımak'],
  ['认为','rènwéi','verb','to think, to consider','düşünmek, saymak'],
  ['认真','rènzhēn','adjective','serious, earnest','ciddi, özenli'],
  ['容易','róngyì','adjective','easy','kolay'],
  ['如果','rúguǒ','conjunction','if','eğer'],
  ['伞','sǎn','noun','umbrella','şemsiye'],
  ['扫','sǎo','verb','to sweep','süpürmek'],
  ['沙发','shāfā','noun','sofa','kanepe'],
  ['山','shān','noun','mountain','dağ'],
  ['上衣','shàngyī','noun','jacket, top garment','ceket, üst giysi'],
  ['勺子','sháozi','noun','spoon','kaşık'],
  ['身边','shēnbiān','noun','by one\'s side','yanında'],
  ['身高','shēngāo','noun','height','boy uzunluğu'],
  ['声','shēng','noun','sound, voice; measure word for sounds','ses; ses sayı sözcüğü'],
  ['生活','shēnghuó','noun','life; to live','yaşam; yaşamak'],
  ['生气','shēngqì','verb','to get angry','kızmak, sinirlenmek'],
  ['声音','shēngyīn','noun','sound','ses'],
  ['市','shì','noun','city','şehir (idari)'],
  ['试','shì','verb','to try','denemek'],
  ['室','shì','noun','room','oda'],
  ['世界','shìjiè','noun','world','dünya'],
  ['收','shōu','verb','to receive','almak'],
  ['收到','shōudào','verb','to receive','teslim almak'],
  ['受','shòu','verb','to receive, to be affected','almak, etkilenmek'],
  ['瘦','shòu','adjective','thin, slim','ince, zayıf'],
  ['受到','shòudào','verb','to receive, to be subjected to','almak, maruz kalmak'],
  ['叔叔','shūshu','noun','uncle','amca'],
  ['树','shù','noun','tree','ağaç'],
  ['数学','shùxué','noun','mathematics','matematik'],
  ['刷','shuā','verb','to brush, to scrub','fırçalamak'],
  ['双','shuāng','classifier','pair, measure word for pairs','çift sayı sözcüğü'],
  ['水平','shuǐpíng','noun','level, standard','seviye, standart'],
  ['司机','sījī','noun','driver','sürücü'],
  ['四季','sìjì','noun','four seasons','dört mevsim'],
  ['太阳','tàiyáng','noun','sun','güneş'],
  ['糖','táng','noun','candy, sugar','şeker'],
  ['特别','tèbié','adverb','special; particularly','özel; özellikle'],
  ['提高','tígāo','verb','to raise, to improve','yükseltmek, geliştirmek'],
  ['体育','tǐyù','noun','physical education','beden eğitimi'],
  ['体育馆','tǐyùguǎn','noun','gymnasium','spor salonu'],
  ['甜','tián','adjective','sweet','tatlı'],
  ['跳','tiào','verb','to jump','zıplamak, atlamak'],
  ['听说','tīngshuō','verb','to hear said','duyduğuna göre'],
  ['挺','tǐng','adverb','quite, rather; (to endure)','oldukça; (katlanmak)'],
  ['同事','tóngshì','noun','colleague','iş arkadaşı'],
  ['同意','tóngyì','verb','to agree','katılmak, onaylamak'],
  ['头发','tóufa','noun','hair','saç'],
  ['突然','tūrán','adjective','sudden','ani'],
  ['图书馆','túshūguǎn','noun','library','kütüphane'],
  ['腿','tuǐ','noun','leg','bacak'],
  ['外地','wàidì','noun','other place','başka şehir/yer'],
  ['外卖','wàimài','noun','takeaway; to order takeout','paket servis; paket sipariş etmek'],
  ['外语','wàiyǔ','noun','foreign language','yabancı dil'],
  ['完成','wánchéng','verb','to complete','tamamlamak'],
  ['碗','wǎn','noun','bowl','kase'],
  ['晚点','wǎndiǎn','verb','to be late','geç kalmak'],
  ['晚会','wǎnhuì','noun','evening party','gece partisi'],
  ['网球','wǎngqiú','noun','tennis','tenis'],
  ['网站','wǎngzhàn','noun','website','web sitesi'],
  ['忘记','wàngjì','verb','to forget','unutmak'],
  ['为','wèi','preposition','for, because of, to','için, -den dolayı'],
  ['为了','wèile','preposition','in order to','-mek için'],
  ['卫生间','wèishēngjiān','noun','bathroom, restroom','banyo, tuvalet'],
  ['文化','wénhuà','noun','culture','kültür'],
  ['屋子','wūzi','noun','room, house','oda, ev'],
  ['西','xī','noun','west','batı'],
  ['西北','xīběi','noun','northwest','kuzeybatı'],
  ['西方','xīfāng','noun','west','batı'],
  ['西瓜','xīguā','noun','watermelon','karpuz'],
  ['西南','xīnán','noun','southwest','güneybatı'],
  ['习惯','xíguàn','verb','to be used to; habit','alışmak; alışkanlık'],
  ['喜爱','xǐ\'ài','verb','to like, to love','sevmek, beğenmek'],
  ['洗衣机','xǐyījī','noun','washing machine','çamaşır makinesi'],
  ['洗澡','xǐzǎo','verb','to take a bath','banyo yapmak'],
  ['夏天','xiàtiān','noun','summer','yaz'],
  ['先','xiān','adverb','first, before','önce'],
  ['香蕉','xiāngjiāo','noun','banana','muz'],
  ['相信','xiāngxìn','verb','to believe','inanmak'],
  ['箱子','xiāngzi','noun','box, case','kutu, bavul'],
  ['向','xiàng','preposition','toward, to; to face','-e doğru; yönelmek'],
  ['像','xiàng','verb','to resemble, to be like; (as if)','benzemek; (sanki)'],
  ['相机','xiàngjī','noun','camera','fotoğraf makinesi'],
  ['小区','xiǎoqū','noun','residential community','konut sitesi'],
  ['小心','xiǎoxīn','adjective','to be careful; careful','dikkatli olmak; dikkatli'],
  ['校园','xiàoyuán','noun','campus','kampüs'],
  ['校长','xiàozhǎng','noun','principal, headmaster','okul müdürü'],
  ['鞋','xié','noun','shoe','ayakkabı'],
  ['心里','xīnlǐ','noun','heart, mind','kalpte, içinde'],
  ['新年','xīnnián','noun','New Year','Yeni Yıl'],
  ['新闻','xīnwén','noun','news','haber'],
  ['新鲜','xīnxiān','adjective','fresh','taze'],
  ['信','xìn','verb','to believe; letter','inanmak; mektup'],
  ['信用卡','xìnyòngkǎ','noun','credit card','kredi kartı'],
  ['行','xíng','adjective','okay, permissible; to go','tamam, caiz; gitmek'],
  ['行李','xíngli','noun','luggage','bagaj'],
  ['兴趣','xìngqù','noun','interest','ilgi, merak'],
  ['休假','xiūjià','verb','to take a holiday','tatile çıkmak'],
  ['需要','xūyào','verb','to need; need','ihtiyaç duymak; ihtiyaç'],
  ['选','xuǎn','verb','to choose','seçmek'],
  ['选择','xuǎnzé','verb','to choose','seçmek'],
  ['学期','xuéqī','noun','semester','dönem'],
  ['牙','yá','noun','tooth','diş'],
  ['牙刷','yáshuā','noun','toothbrush','diş fırçası'],
  ['羊','yáng','noun','sheep','koyun'],
  ['养','yǎng','verb','to raise, to keep','beslemek, yetiştirmek'],
  ['要求','yāoqiú','verb','to demand; requirement','talep etmek; gereksinim'],
  ['页','yè','classifier','measure word for page','sayfa sayı sözcüğü'],
  ['一定','yídìng','adverb','certain; certainly','kesin; kesinlikle'],
  ['一共','yígòng','adverb','altogether, in total','toplamda, hepsi birden'],
  ['一块儿','yíkuàir','adverb','the same place; together','birlikte'],
  ['一样','yíyàng','adjective','same','aynı'],
  ['以后','yǐhòu','noun','later, after','sonra, -den sonra'],
  ['以前','yǐqián','noun','before','önce, -den önce'],
  ['以上','yǐshàng','noun','above, more than','yukarıda, fazla'],
  ['以外','yǐwài','noun','except, besides','dışında, haricinde'],
  ['以为','yǐwéi','verb','to think, to believe','sanmak'],
  ['以下','yǐxià','noun','below, less than','aşağıda, az'],
  ['一般','yìbān','adjective','general, ordinary','genel, sıradan'],
  ['一边','yìbiān','adverb','at the same time','aynı zamanda, -ken'],
  ['一直','yìzhí','adverb','always, straight','hep, doğruca'],
  ['音乐','yīnyuè','noun','music','müzik'],
  ['银行','yínháng','noun','bank','banka'],
  ['银行卡','yínhángkǎ','noun','bank card','banka kartı'],
  ['饮料','yǐnliào','noun','beverage','içecek'],
  ['应该','yīnggāi','verb','should, ought to','-meli, -malı'],
  ['影响','yǐngxiǎng','verb','to affect; influence','etkilemek; etki'],
  ['用','yòng','verb','to use','kullanmak'],
  ['邮件','yóujiàn','noun','mail','posta, e-posta'],
  ['游客','yóukè','noun','tourist','turist'],
  ['游戏','yóuxì','noun','game','oyun'],
  ['邮箱','yóuxiāng','noun','mailbox','posta kutusu'],
  ['有关','yǒuguān','verb','to have to do with; concerning','ilgili olmak; hakkında'],
  ['有名','yǒumíng','adjective','famous','ünlü'],
  ['有用','yǒuyòng','adjective','useful','faydalı'],
  ['又','yòu','adverb','again, also','yine, tekrar'],
  ['羽毛球','yǔmáoqiú','noun','badminton','badminton'],
  ['语言','yǔyán','noun','language','dil'],
  ['雨衣','yǔyī','noun','raincoat','yağmurluk'],
  ['遇到','yùdào','verb','to encounter','karşılaşmak'],
  ['遇见','yùjiàn','verb','to meet','rastlamak'],
  ['园','yuán','noun','garden','bahçe'],
  ['员','yuán','suffix','suffix for person with a certain job','belirli bir iş kişisi eki'],
  ['愿意','yuànyì','verb','willing','istekli olmak, razı olmak'],
  ['越','yuè','adverb','more, increasingly','giderek daha fazla'],
  ['月亮','yuèliang','noun','moon','ay'],
  ['运动会','yùndònghuì','noun','sports meet','spor müsabakası'],
  ['运动员','yùndòngyuán','noun','athlete','sporcu'],
  ['咱们','zánmen','pronoun','we (inclusive)','biz (dahili)'],
  ['脏','zāng','adjective','dirty','kirli'],
  ['怎么办','zěnmebàn','verb','what to do','ne yapalım'],
  ['怎样','zěnyàng','pronoun','how','nasıl'],
  ['张','zhāng','classifier','measure word for flat objects; to open','düz nesneler sayı sözcüğü; açmak'],
  ['着急','zháojí','adjective','anxious','endişeli, telaşlı'],
  ['照','zhào','verb','to shine, to photograph','parlatmak, fotoğraf çekmek'],
  ['照顾','zhàogù','verb','to take care of','bakmak, ilgilenmek'],
  ['照片','zhàopiàn','noun','photo','fotoğraf'],
  ['照相','zhàoxiàng','verb','to take a picture','fotoğraf çekmek'],
  ['直到','zhídào','verb','until','-e kadar'],
  ['只','zhǐ','adverb','only, merely','yalnızca, sadece'],
  ['纸','zhǐ','noun','paper','kağıt'],
  ['只能','zhǐnéng','adverb','can only','yalnızca yapabilmek'],
  ['只是','zhǐshì','adverb','only, merely; but','yalnızca; ama'],
  ['只要','zhǐyào','conjunction','as long as','-diği sürece'],
  ['只有','zhǐyǒu','conjunction','only if','yalnızca eğer'],
  ['中','zhōng','noun','middle','orta'],
  ['中间','zhōngjiān','noun','middle, between','arasında, ortada'],
  ['终于','zhōngyú','adverb','finally','sonunda'],
  ['种','zhǒng','classifier','measure word for kinds','tür sayı sözcüğü'],
  ['重要','zhòngyào','adjective','important','önemli'],
  ['周末','zhōumò','noun','weekend','hafta sonu'],
  ['主要','zhǔyào','adjective','main','ana, esas'],
  ['注意','zhùyì','verb','to pay attention to','dikkat etmek'],
  ['住院','zhùyuàn','verb','to be hospitalized','hastaneye yatmak'],
  ['字典','zìdiǎn','noun','dictionary','sözlük'],
  ['自行车','zìxíngchē','noun','bicycle','bisiklet'],
  ['子','zi','suffix','noun suffix','isim eki'],
  ['总','zǒng','adverb','always, invariably; (total, overall)','her zaman; (toplam)'],
  ['总是','zǒngshì','adverb','always','her zaman'],
  ['嘴','zuǐ','noun','mouth','ağız'],
  ['最好','zuìhǎo','adverb','best','en iyi, mümkünse'],
  ['最后','zuìhòu','noun','last, final','son'],
  ['最近','zuìjìn','noun','recently','son zamanlarda'],
  ['做客','zuòkè','verb','to be a guest','misafir olmak'],
  ['作业','zuòyè','noun','homework','ödev'],
];
