/// HSK Level 3 — ~494 unique vocabulary entries (500 list entries, ~6 duplicates deduplicated).
/// Each row: [simplified, pinyin, pos, en, tr, ko]
const List<List<String>> kHsk3Words = [
  ['阿姨','āyí','noun','aunt','hala, teyze', '이모, 숙모, 아줌마'],
  ['矮','ǎi','adjective','short','kısa boylu', '키가 작다'],
  ['爱人','àiren','noun','spouse','eş', '애인, 배우자'],
  ['安静','ānjìng','adjective','quiet','sessiz, sakin', '조용하다'],
  ['安全','ānquán','adjective','safe','güvenli', '안전하다'],
  ['把','bǎ','classifier','measure word for handles; object-fronting particle','saplı nesneler sayı sözcüğü', '~을/를 (목적어 앞으로 도치시키는 조사)'],
  ['搬','bān','verb','to move, to carry','taşımak', '옮기다, 이사하다'],
  ['班级','bānjí','noun','class, grade','sınıf', '반, 학급'],
  ['搬家','bānjiā','verb','to move house','ev taşımak', '이사하다'],
  ['办','bàn','verb','to do, to handle','yapmak, halletmek', '하다, 처리하다'],
  ['办法','bànfǎ','noun','way, solution','yol, çözüm', '방법, 해결책'],
  ['办公室','bàngōngshì','noun','office','ofis', '사무실'],
  ['半天','bàntiān','number-classifier','half a day, a long time','yarım gün, uzun zaman', '반나절, 오래'],
  ['帮助','bāngzhù','verb','to help','yardım etmek', '돕다'],
  ['饱','bǎo','adjective','full','tok', '배부르다'],
  ['报纸','bàozhǐ','noun','newspaper','gazete', '신문'],
  ['北','běi','noun','north','kuzey', '북쪽'],
  ['北方','běifāng','noun','north','kuzey', '북방'],
  ['被','bèi','preposition','by','tarafından', '~에 의해 (피동), ~에게'],
  ['笔记','bǐjì','noun','notes','not', '필기, 메모'],
  ['比较','bǐjiào','adverb','to compare; quite, relatively; than','karşılaştırmak; oldukça', '비교하다, 상당히'],
  ['笔记本','bǐjìběn','noun','notebook','defter', '노트, 노트북'],
  ['比如','bǐrú','verb','for example','örneğin', '예를 들면'],
  ['比赛','bǐsài','verb','to compete; game, match','yarışmak; maç', '시합하다, 경기하다'],
  ['必须','bìxū','adverb','must','zorunlu olmak', '반드시 ~해야 하다'],
  ['变','biàn','verb','to change, to become','değişmek', '변하다, 바뀌다'],
  ['遍','biàn','classifier','measure word for actions','eylemler için sayı sözcüğü (kez)', '~번 (동작 횟수)'],
  ['变成','biànchéng','verb','to become, to turn into','olmak, dönüşmek', '~으로 변하다, ~이 되다'],
  ['变化','biànhuà','verb','to change; change','değişmek; değişim', '변화하다; 변화'],
  ['表演','biǎoyǎn','verb','to perform, to act','sahne almak, oynamak', '공연하다, 연기하다'],
  ['别的','biéde','pronoun','other','diğer', '다른'],
  ['别人','biérén','pronoun','other people','başkaları', '다른 사람'],
  ['宾馆','bīnguǎn','noun','hotel','otel', '호텔'],
  ['冰','bīng','noun','ice; (to freeze)','buz; (donmak)', '얼음, 얼다'],
  ['冰激凌','bīngjīlíng','noun','ice cream','dondurma', '아이스크림'],
  ['冰箱','bīngxiāng','noun','refrigerator','buzdolabı', '냉장고'],
  ['病人','bìngrén','noun','patient','hasta', '환자'],
  ['不但','búdàn','conjunction','not only','sadece değil', '~일 뿐만 아니라'],
  ['不见','bújiàn','verb','to disappear, to not see','kaybolmak, görmemek', '사라지다, 보이지 않다'],
  ['不用','búyòng','adverb','need not','gerek yok', '~할 필요가 없다'],
  ['不同','bùtóng','adjective','different','farklı', '다른, 같지 않은'],
  ['不久','bùjiǔ','adjective','soon, not long after','kısa süre sonra', '머지않아, 곧'],
  ['不行','bùxíng','adjective','not allowed; not good','olmaz; iyi değil', '안 된다, 좋지 않다'],
  ['才','cái','adverb','just, only','ancak, yalnızca', '재능, 능력'],
  ['菜单','càidān','noun','menu','menü', '메뉴'],
  ['参加','cānjiā','verb','to join, to attend','katılmak', '참하다, 참가하다'],
  ['草','cǎo','noun','grass','çimen, ot', '풀'],
  ['草地','cǎodì','noun','grassland','çayırlık, ot, çimen', '잔디밭'],
  ['层','céng','classifier','measure word for layer, floor','kat sayı sözcüğü', '층, 단계'],
  ['查','chá','verb','to check','kontrol etmek', '조사하다, 찾다'],
  ['差','chà, chā, chāi','adjective','bad, poor; to lack','kötü, yetersiz', '나쁘다, 부족하다'],
  ['差不多','chàbuduō','adverb','almost, similar; nearly','hemen hemen, yaklaşık', '거의, 비슷하다'],
  ['尝','cháng','verb','to taste','tatmak', '맛보다'],
  ['常','cháng','adverb','often, frequent','sık sık', '자주'],
  ['常见','chángjiàn','adjective','common','yaygın', '흔한'],
  ['常用','chángyòng','adjective','commonly used','sık kullanılan', '자주 쓰이는'],
  ['常常','chángcháng','adverb','often','sık sık', '자주'],
  ['衬衫','chènshān','noun','shirt','gömlek', '셔츠, 블라우스'],
  ['成绩','chéngjì','noun','score, grade, achievement','not, derece, başarı', '성적, 결과, 성과'],
  ['城市','chéngshì','noun','city','şehir', '도시'],
  ['迟到','chídào','verb','to be late','geç kalmak', '지각하다'],
  ['出发','chūfā','verb','to set out, to leave','yola çıkmak', '출발하다'],
  ['出生','chūshēng','verb','to be born','doğmak', '태어나다'],
  ['出院','chūyuàn','verb','to be discharged from hospital','taburcu olmak', '퇴원하다'],
  ['初中','chūzhōng','noun','junior high school','ortaokul', '중학교'],
  ['除了','chúle','preposition','except, besides','-den başka, dışında', '~을/를 제외하고, ~ 외에'],
  ['船','chuán','noun','boat','tekne, gemi', '배'],
  ['春天','chūntiān','noun','spring','ilkbahar', '봄'],
  ['词典','cídiǎn','noun','dictionary','sözlük', '사전'],
  ['聪明','cōngmíng','adjective','smart, clever','zeki, akıllı', '똑똑하다, 영리하다'],
  ['打扫','dǎsǎo','verb','to clean','temizlemek', '청소하다'],
  ['打算','dǎsuàn','verb','to plan, intend; plan','planlamak; plan', '계획하다, ~할 작정이다; 계획'],
  ['大概','dàgài','adverb','probably, approximately; general','muhtemelen; genel', '대략, 아마; 일반적인'],
  ['大人','dàren','noun','adult','yetişkin', '어른'],
  ['大小','dàxiǎo','noun','size','boyut, beden', '크기'],
  ['大熊猫','dàxióngmāo','noun','giant panda','dev panda', '팬더'],
  ['大衣','dàyī','noun','coat','palto', '코트, 외투'],
  ['带','dài','verb','to bring, to take; (belt)','getirmek, almak; (kemer)', '가지고 가다, 데리고 가다'],
  ['担心','dānxīn','verb','to worry','endişelenmek', '걱정하다'],
  ['蛋糕','dàngāo','noun','cake','pasta', '케이크'],
  ['当然','dāngrán','adverb','of course','tabii ki, elbette', '물론'],
  ['到处','dàochù','adverb','everywhere','her yerde', '도처에, 곳곳에'],
  ['得到','dédào','verb','to get, to obtain','elde etmek', '얻다, 받다'],
  ['得分','défēn','verb','to score; score','puan almak; puan', '득점하다'],
  ['的话','dehuà','auxiliary','particle after condition clause, if...','koşul partikülü, eğer...', '~라면 (가정절 뒤에 쓰여)'],
  ['灯','dēng','noun','lamp, light','lamba, ışık', '등, 불'],
  ['地点','dìdiǎn','noun','place, location','yer, konum', '장소, 지점'],
  ['地方','dìfang','noun','place','yer', '곳, 장소'],
  ['地图','dìtú','noun','map','harita', '지도'],
  ['电','diàn','noun','electricity; (to give an electric shock)','elektrik; (elektrik çarpmak)', '전기, 전압'],
  ['电梯','diàntī','noun','elevator','asansör', '엘리베이터'],
  ['电子书','diànzǐshū','noun','e-book','e-kitap', '전자책'],
  ['丢','diū','verb','to lose, to throw away','kaybetmek, atmak', '잃다, 버리다'],
  ['东','dōng','noun','east','doğu', '동쪽'],
  ['东北','dōngběi','noun','northeast','kuzeydoğu', '동북쪽'],
  ['东方','dōngfāng','noun','east','doğu', '동방, 동쪽'],
  ['东南','dōngnán','noun','southeast','güneydoğu', '동남쪽'],
  ['冬天','dōngtiān','noun','winter','kış', '겨울'],
  ['懂得','dǒngde','verb','to understand','anlamak', '이해하다, 알다'],
  ['动物','dòngwù','noun','animal','hayvan', '동물'],
  ['动物园','dòngwùyuán','noun','zoo','hayvanat bahçesi', '동물원'],
  ['短','duǎn','adjective','short','kısa', '짧다'],
  ['短裤','duǎnkù','noun','shorts','şort', '반바지'],
  ['段','duàn','classifier','measure word for segment, paragraph','bölüm, paragraf sayı sözcüğü', '단, 토막, 구간'],
  ['锻炼','duànliàn','verb','to exercise','egzersiz yapmak', '운동하다, 단련하다'],
  ['对话','duìhuà','noun','dialogue, conversation','diyalog, konuşma', '대화'],
  ['饿','è','adjective','hungry','aç', '배고프다'],
  ['而且','érqiě','conjunction','and, moreover','ayrıca, üstelik', '~일 뿐만 아니라, 게다가'],
  ['耳朵','ěrduo','noun','ear','kulak', '귀'],
  ['耳机','ěrjī','noun','earphone','kulaklık', '이어폰'],
  ['发','fā, fà','verb','to send, to issue','göndermek, yayımlamak', '보내다, 발송하다, (머리를) 풀다'],
  ['发烧','fāshāo','verb','to have a fever','ateş çıkmak', '열이 나다, 발열하다'],
  ['发生','fāshēng','verb','to happen','olmak, meydana gelmek', '발생하다, 일어나다'],
  ['发现','fāxiàn','verb','to find, to discover','bulmak, keşfetmek', '발견하다'],
  ['发展','fāzhǎn','verb','to develop','gelişmek', '발전하다'],
  ['方便','fāngbiàn','adjective','convenient','uygun, pratik', '편리하다, 알맞다'],
  ['方便面','fāngbiànmiàn','noun','instant noodles','hazır noodle', '인스턴트 라면'],
  ['方法','fāngfǎ','noun','method','yöntem', '방법, 방식'],
  ['方向','fāngxiàng','noun','direction','yön', '방향, 방면'],
  ['房子','fángzi','noun','house','ev', '집'],
  ['放','fàng','verb','to put, to place','koymak, yerleştirmek', '놓다, 두다'],
  ['放假','fàngjià','verb','to have a holiday','tatile çıkmak', '휴가를 보내다, 방학하다'],
  ['放心','fàngxīn','verb','to relax, to feel at ease','rahatlamak', '안심하다'],
  ['放学','fàngxué','verb','school is over','okul bitmek', '하교하다'],
  ['分开','fēnkāi','verb','to separate','ayrılmak, ayırmak', '나누다, 헤어지다'],
  ['风','fēng','noun','wind','rüzgar', '바람'],
  ['封','fēng','classifier','measure word for letters; (to seal)','mektup sayı sözcüğü; (mühürlemek)', '통(편지 봉투), 봉하다'],
  ['夫妻','fūqī','noun','husband and wife','karı koca', '부부'],
  ['服务','fúwù','verb','to serve','hizmet etmek', '서비스하다, 봉사하다'],
  ['附近','fùjìn','noun','nearby','yakın çevrede', '부근, 근처'],
  ['复习','fùxí','verb','to review','tekrar etmek', '복습하다'],
  ['该','gāi','verb','should','-meli', '해야 한다'],
  ['干净','gānjìng','adjective','clean','temiz', '깨끗하다'],
  ['感兴趣','gǎn xìngqù','verb','to be interested in','ilgi duymak', '흥미를 느끼다'],
  ['感到','gǎndào','verb','to feel','hissetmek', '느끼다'],
  ['感冒','gǎnmào','noun','cold; to catch a cold','soğuk algınlığı; soğuk almak', '감기; 감기에 걸리다'],
  ['干','gān, gàn','verb','to do, to work','yapmak, çalışmak', '하다, 마르다'],
  ['刚','gāng','adverb','just, just now','hemen, az önce', '막, 방금'],
  ['刚才','gāngcái','noun','just now','az önce', '방금 전'],
  ['刚刚','gānggāng','adverb','just now, a moment ago','az önce, biraz önce', '방금, للتو'],
  ['高铁','gāotiě','noun','high-speed rail','hızlı tren', '고속철도'],
  ['根据','gēnjù','preposition','according to; to base on; (basis)','-e göre; dayanmak; (temel)', '~에 의하면, ~을 근거로'],
  ['更','gèng, gēng','adverb','more','daha', '더, 더욱'],
  ['公斤','gōngjīn','classifier','kilogram','kilogram', '킬로그램'],
  ['公园','gōngyuán','noun','park','park', '공원'],
  ['工作日','gōngzuòrì','noun','workday','iş günü', '평일'],
  ['故事','gùshi','noun','story','hikaye', '이야기, 옛날 이야기'],
  ['刮','guā','verb','to scrape, to blow','kazımak, esmek', '긁다, 불다'],
  ['关','guān','verb','to close, to turn off; pass','kapatmak; geçit', '닫다, 끄다; 관문'],
  ['关机','guānjī','verb','to turn off device','cihazı kapatmak', '기기를 끄다'],
  ['关系','guānxì','noun','relationship; (to relate)','ilişki; (ilgili olmak)', '관계; 관련되다'],
  ['关心','guānxīn','verb','to care about, to be concerned','önemsemek, ilgilenmek', '관심을 가지다, 걱정하다'],
  ['关于','guānyú','preposition','about, regarding','hakkında', '~에 관하여, ~에 대하여'],
  ['关注','guānzhù','verb','to pay attention to, to follow','ilgi göstermek, takip etmek', '주목하다, 관심을 기울이다'],
  ['国家','guójiā','noun','country','ülke', '국가, 나라'],
  ['过节','guòjié','verb','to celebrate a festival','bayram kutlamak', '명절을 쇠다'],
  ['海','hǎi','noun','sea','deniz', '바다'],
  ['害怕','hàipà','verb','to be afraid','korkmak', '두려워하다'],
  ['好多','hǎoduō','adjective','many, a lot','çok, bir sürü', '많음'],
  ['好久','hǎojiǔ','adjective','a long time','uzun zaman', '오랫동안'],
  ['好像','hǎoxiàng','adverb','to seem, as if; perhaps','gibi görünmek; belki', '마치 ~인 듯하다, ~인 것 같다; 아마'],
  ['号码','hàomǎ','noun','number, code','numara, kod', '번호, 코드'],
  ['河','hé','noun','river','nehir', '강'],
  ['合适','héshì','adjective','suitable','uygun', '적합하다, 알맞다'],
  ['黑板','hēibǎn','noun','blackboard','kara tahta', '칠판'],
  ['红绿灯','hónglǜdēng','noun','traffic light','trafik ışığı', '신호등'],
  ['后来','hòulái','noun','later, afterwards','sonradan', '나중에, 이후에'],
  ['后年','hòunián','noun','the year after next','öbür yıl', '내후년'],
  ['后天','hòutiān','noun','the day after tomorrow','öbür gün', '모레'],
  ['护照','hùzhào','noun','passport','pasaport', '여권'],
  ['花园','huāyuán','noun','garden','bahçe', '화원, 정원'],
  ['画家','huàjiā','noun','painter, artist','ressam, sanatçı', '화가'],
  ['欢迎','huānyíng','verb','to welcome','karşılamak', '환영하다, 맞이하다'],
  ['还','hái, huán','verb','to return, to give back','geri vermek', '아직, 또한, 오히려'],
  ['环境','huánjìng','noun','environment','çevre, ortam', '환경'],
  ['换','huàn','verb','to exchange, to change','değiştirmek', '갈다, 바꾸다'],
  ['黄色','huángsè','noun','yellow','sarı', '노란색'],
  ['回答','huídá','verb','to answer','cevap vermek', '대답하다'],
  ['会','huì, kuài','noun','meeting','toplantı', '할 줄 알다, ~할 것이다'],
  ['会议','huìyì','noun','meeting','toplantı', '회의'],
  ['或','huò','conjunction','or; (perhaps, maybe)','ya da; (belki)', '혹은, 또는; 아마'],
  ['或者','huòzhě','conjunction','or','ya da', '혹은, 또는'],
  ['鸡','jī','noun','chicken','tavuk', '닭'],
  ['几乎','jīhū','adverb','almost','neredeyse', '거의'],
  ['机会','jīhuì','noun','opportunity','fırsat', '기회'],
  ['极','jí','adverb','extremely','son derece', '매우, 아주'],
  ['急','jí','adjective','urgent; (to worry)','acil; (endişelenmek)', '급하다, 초조하다'],
  ['记','jì','verb','to remember','hatırlamak', '기억하다, 기록하다'],
  ['季','jì','noun','season','mevsim', '계절'],
  ['季节','jìjié','noun','season','mevsim', '계절'],
  ['加','jiā','verb','to add','eklemek', '더하다, 보태다'],
  ['假期','jiàqī','noun','vacation','tatil', '휴가, 방학'],
  ['坚持','jiānchí','verb','to persist','ısrar etmek, devam etmek', '고집하다, 견지하다'],
  ['检查','jiǎnchá','verb','to check, to inspect','kontrol etmek, incelemek', '검사하다, 점검하다'],
  ['简单','jiǎndān','adjective','simple','basit', '간단하다, 단순하다'],
  ['检票','jiǎnpiào','verb','ticket checking','bilet kontrol etmek', '표를 검사하다'],
  ['健康','jiànkāng','adjective','healthy','sağlıklı', '건강하다'],
  ['见面','jiànmiàn','verb','to meet','buluşmak', '만나다'],
  ['讲','jiǎng','verb','to speak, to talk','konuşmak, anlatmak', '말하다, 이야기하다'],
  ['角','jiǎo','classifier','measure word for fractions, angle, currency','para, açı sayı sözcüğü', '각도; (화폐 단위) 각, 센트'],
  ['脚','jiǎo','noun','foot','ayak', '발'],
  ['接','jiē','verb','to pick up, to receive','karşılamak, almak', '받다, 맞이하다'],
  ['街','jiē','noun','street','cadde, sokak', '거리'],
  ['节','jié','classifier','measure word for segments, lessons; festival','bölüm, ders sayı sözcüğü; festival', '마디, 절, 단락; 명절'],
  ['结婚','jiéhūn','verb','to marry','evlenmek', '결혼하다'],
  ['节目','jiémù','noun','program','program', '프로그램, 종목'],
  ['节日','jiérì','noun','festival','festival, bayram', '명절, 축제'],
  ['结束','jiéshù','verb','to end','bitmek, sona ermek', '끝나다, 마치다'],
  ['解决','jiějué','verb','to solve','çözmek', '해결하다'],
  ['姐妹','jiěmèi','noun','sister','kız kardeş', '자매'],
  ['借','jiè','verb','to borrow','ödünç almak', '빌리다'],
  ['斤','jīn','classifier','catty (500g)','jin (500g ağırlık birimi)', '근 (무게 단위)'],
  ['经过','jīngguò','verb','to pass; process','geçmek; süreç', '지나가다; 거치다'],
  ['经理','jīnglǐ','noun','manager','müdür', '지배인, 매니저'],
  ['久','jiǔ','adjective','long (time)','uzun (süre)', '오랜 (시간)'],
  ['酒','jiǔ','noun','alcohol','alkol, içki', '술'],
  ['旧','jiù','adjective','old','eski', '낡다, 오래되다'],
  ['句','jù','classifier','measure word of sentence','cümle sayı sözcüğü', '~구 (단위)'],
  ['句子','jùzi','noun','sentence','cümle', '문장'],
  ['决定','juédìng','verb','to decide; decision','karar vermek; karar', '결정하다, 결정'],
  ['卡','kǎ','noun','card','kart', '카드'],
  ['开花','kāihuā','verb','to bloom','çiçek açmak', '꽃이 피다'],
  ['开会','kāihuì','verb','to have a meeting','toplantı yapmak', '회의하다'],
  ['开机','kāijī','verb','to turn on device','cihazı açmak', '기기를 켜다'],
  ['开心','kāixīn','adjective','happy','mutlu, neşeli', '기쁘다'],
  ['看来','kànlái','verb','it seems, it appears','görünüşe göre', '보아하니, ~인 것 같다'],
  ['可','kě','conjunction','but; (yet)','ama; (henüz)', '그러나; (결과를 나타냄)'],
  ['渴','kě','adjective','thirsty','susamış', '목마르다'],
  ['可爱','kě\'ài','adjective','lovely','sevimli', '귀엽다'],
  ['可是','kěshì','conjunction','but','ama, fakat', '그러나'],
  ['刻','kè','classifier','quarter; to carve','çeyrek saat; (oymak)', '1/4시간, 새기다'],
  ['课本','kèběn','noun','textbook','ders kitabı', '교과서'],
  ['客人','kèrén','noun','guest','misafir', '손님'],
  ['课文','kèwén','noun','text','metin, okuma parçası', '교과서 본문'],
  ['空调','kōngtiáo','noun','air conditioner','klima', '에어컨'],
  ['哭','kū','verb','to cry','ağlamak', '울다'],
  ['筷子','kuàizi','noun','chopsticks','yemek çubukları', '젓가락'],
  ['矿泉水','kuàngquánshuǐ','noun','mineral water','maden suyu', '광천수, 생수'],
  ['来自','láizì','verb','to come from','-den gelmek', '출신이다, ~에서 오다'],
  ['蓝','lán','adjective','blue','mavi', '파란색의'],
  ['老','lǎo','adjective','old, aged; (always, constantly)','yaşlı; (her zaman)', '늙은, 오래된; 늘, 항상'],
  ['老人','lǎorén','noun','elderly person','yaşlı kişi', '노인'],
  ['离开','líkāi','verb','to leave','ayrılmak', '떠나다, 벗어나다'],
  ['礼物','lǐwù','noun','gift','hediye', '선물'],
  ['历史','lìshǐ','noun','history','tarih', '역사'],
  ['脸','liǎn','noun','face','yüz', '얼굴'],
  ['练','liàn','verb','to practice','alıştırma yapmak', '연습하다'],
  ['练习','liànxí','verb','to practice; exercise','alıştırma yapmak; alıştırma', '연습하다; 연습 문제'],
  ['凉快','liángkuai','adjective','cool','serin, ferah', '시원하다'],
  ['辆','liàng','classifier','measure word for vehicles','araç sayı sözcüğü', '~량 (탈것 수사)'],
  ['聊','liáo','verb','to chat','sohbet etmek', '이야기하다, 담소를 나누다'],
  ['聊天儿','liáotiānr','verb','to chat','sohbet etmek', '이야기하다, 담소를 나누다'],
  ['了解','liǎojiě','verb','to understand','anlamak, bilmek', '이해하다, 알다'],
  ['邻居','línjū','noun','neighbor','komşu', '이웃'],
  ['留学','liúxué','verb','to study abroad','yurt dışında okumak', '유학하다'],
  ['留学生','liúxuéshēng','noun','overseas student','yurt dışı öğrencisi', '유학생'],
  ['楼梯','lóutī','noun','stairs','merdiven', '계단'],
  ['路边','lùbiān','noun','roadside','yol kenarı', '길가'],
  ['路口','lùkǒu','noun','intersection','kavşak', '교차로'],
  ['马','mǎ','noun','horse','at', '말'],
  ['马路','mǎlù','noun','road','yol, cadde', '길, 도로'],
  ['马上','mǎshàng','adverb','immediately','hemen', '곧, 즉시'],
  ['满意','mǎnyì','verb','satisfied','memnun olmak', '만족하다'],
  ['毛','máo','classifier','measure word for money (0.1 yuan); (hair)','para sayı sözcüğü; (kıl, tüy)', '털, (화폐 단위) 모'],
  ['米','mǐ','classifier','meter','metre', '미터'],
  ['面前','miànqián','noun','in front of','önünde', '~의 면전, ~ 앞'],
  ['明白','míngbai','adjective','to understand; clear','anlamak; açık', '분명하다, 이해하다'],
  ['名单','míngdān','noun','name list','isim listesi', '명단'],
  ['名人','míngrén','noun','famous person','ünlü kişi', '유명인'],
  ['南','nán','noun','south','güney', '남쪽'],
  ['难','nán, nàn','adjective','difficult; (to make difficult)','zor; (zorlaştırmak)', '어렵다, 힘들다'],
  ['南方','nánfāng','noun','south','güney', '남방'],
  ['难过','nánguò','adjective','sad','üzgün', '슬프다, 괴롭다'],
  ['难看','nánkàn','adjective','ugly','çirkin', '보기 싫다, 추하다, 못생기다'],
  ['男人','nánrén','noun','man','adam, erkek', '남자'],
  ['男生','nánshēng','noun','boy student','erkek öğrenci', '남자아이, 남학생'],
  ['难题','nántí','noun','difficult problem','zor problem', '어려운 문제, 난제'],
  ['难听','nántīng','adjective','unpleasant to hear','kulak tırmalayan', '듣기 싫다, 불쾌하다'],
  ['年级','niánjí','noun','grade','sınıf (yıl bazlı)', '학년'],
  ['年轻','niánqīng','adjective','young','genç', '젊다'],
  ['牛','niú','noun','cow; (awesome)','inek; (harika)', '소, (속어) 대단하다'],
  ['努力','nǔlì','adjective','to work hard; hardworking','çok çalışmak; çalışkan', '노력하다, 노력하는'],
  ['女人','nǚrén','noun','woman','kadın', '여자'],
  ['女生','nǚshēng','noun','girl student','kız öğrenci', '여자아이, 여학생'],
  ['爬','pá','verb','to climb','tırmanmak', '기어가다, 오르다'],
  ['怕','pà','verb','to fear; (perhaps)','korkmak; (belki)', '두려워하다, 걱정하다'],
  ['拍照','pāizhào','verb','to take a photo','fotoğraf çekmek', '사진을 찍다'],
  ['盘子','pánzi','noun','plate','tabak', '접시'],
  ['胖','pàng','adjective','fat','şişman', '뚱뚱하다'],
  ['啤酒','píjiǔ','noun','beer','bira', '맥주'],
  ['平时','píngshí','noun','usually','genellikle', '평소'],
  ['瓶子','píngzi','noun','bottle','şişe', '병'],
  ['骑','qí','verb','to ride','binmek (bisiklet/at)', '타다'],
  ['奇怪','qíguài','adjective','strange','tuhaf, garip', '이상하다, 기묘하다'],
  ['其实','qíshí','adverb','actually','aslında', '실은, 사실은'],
  ['其他','qítā','pronoun','other','diğerleri', '기타의, 다른'],
  ['起','qǐ','verb','to rise, to get up; (measure word for events)','kalkmak; (olay sayı sözcüğü)', '일어나다, 발생하다; (사건) 횟수'],
  ['起飞','qǐfēi','verb','to take off','havalanmak', '이륙하다'],
  ['汽车','qìchē','noun','car','araba', '자동차'],
  ['铅笔','qiānbǐ','noun','pencil','kurşun kalem', '연필'],
  ['前年','qiánnián','noun','the year before last','iki yıl önce', '재작년'],
  ['前天','qiántiān','noun','the day before yesterday','önceki gün', '그저께'],
  ['清楚','qīngchu','adjective','clear, obvious; to understand','net, açık; anlamak', '분명하다, 명확하다, 분명히 알다'],
  ['请假','qǐngjià','verb','to ask for leave','izin istemek', '휴가를 신청하다'],
  ['请客','qǐngkè','verb','to invite guests, to treat someone','misafir davet etmek, ısmarlamak', '손님을 대접하다, 한턱내다'],
  ['秋天','qiūtiān','noun','autumn','sonbahar', '가을'],
  ['球场','qiúchǎng','noun','sports field, court','spor sahası, kort', '운동장, 구장'],
  ['裙子','qúnzi','noun','skirt','etek', '치마'],
  ['然后','ránhòu','conjunction','then, afterwards','sonra', '그러고 나서, 그런 다음'],
  ['热情','rèqíng','adjective','enthusiastic','coşkulu, sıcakkanlı', '열정적이다'],
  ['认得','rènde','verb','to recognize, to know','tanımak', '알아보다, 알다'],
  ['认为','rènwéi','verb','to think, to consider','düşünmek, saymak', '여기다, 생각하다'],
  ['认真','rènzhēn','adjective','serious, earnest','ciddi, özenli', '진지한, 성실한'],
  ['容易','róngyì','adjective','easy','kolay', '쉽다'],
  ['如果','rúguǒ','conjunction','if','eğer', '~라면, 만약'],
  ['伞','sǎn','noun','umbrella','şemsiye', '우산'],
  ['扫','sǎo, sào','verb','to sweep','süpürmek', '쓸다, 청소하다'],
  ['沙发','shāfā','noun','sofa','kanepe', '소파'],
  ['山','shān','noun','mountain','dağ', '산'],
  ['上衣','shàngyī','noun','jacket, top garment','ceket, üst giysi', '상의'],
  ['勺子','sháozi','noun','spoon','kaşık', '숟가락'],
  ['身边','shēnbiān','noun','by one\'s side','yanında', '곁, 곁에'],
  ['身高','shēngāo','noun','height','boy uzunluğu', '키'],
  ['声','shēng','noun','sound, voice; measure word for sounds','ses; ses sayı sözcüğü', '소리, 목소리; (소리의) 회수'],
  ['生活','shēnghuó','noun','life; to live','yaşam; yaşamak', '생활, 삶, 살다'],
  ['生气','shēngqì','verb','to get angry','kızmak, sinirlenmek', '화나다, 성내다'],
  ['声音','shēngyīn','noun','sound','ses', '소리, 음성'],
  ['市','shì','noun','city','şehir (idari)', '시'],
  ['试','shì','verb','to try','denemek', '시도하다, 시험하다'],
  ['室','shì','noun','room','oda', '방'],
  ['世界','shìjiè','noun','world','dünya', '세계'],
  ['收','shōu','verb','to receive','almak', '받다, 거두다'],
  ['收到','shōudào','verb','to receive','teslim almak', '받다'],
  ['受','shòu','verb','to receive, to be affected','almak, etkilenmek', '받다, 당하다'],
  ['瘦','shòu','adjective','thin, slim','ince, zayıf', '마르다, 야위다'],
  ['受到','shòudào','verb','to receive, to be subjected to','almak, maruz kalmak', '받다, 당하다'],
  ['叔叔','shūshu','noun','uncle','amca', '아저씨'],
  ['树','shù','noun','tree','ağaç', '나무'],
  ['数学','shùxué','noun','mathematics','matematik', '수학'],
  ['刷','shuā','verb','to brush, to scrub','fırçalamak', '솔질하다, 닦다'],
  ['双','shuāng','classifier','pair, measure word for pairs','çift sayı sözcüğü', '~쌍 (단위)'],
  ['水平','shuǐpíng','noun','level, standard','seviye, standart', '수준, 실력'],
  ['司机','sījī','noun','driver','sürücü', '운전사'],
  ['四季','sìjì','noun','four seasons','dört mevsim', '사계절'],
  ['太阳','tàiyáng','noun','sun','güneş', '태양'],
  ['糖','táng','noun','candy, sugar','şeker', '사탕, 설탕'],
  ['特别','tèbié','adverb','special; particularly','özel; özellikle', '특별히, 특히'],
  ['提高','tígāo','verb','to raise, to improve','yükseltmek, geliştirmek', '높이다, 향상시키다'],
  ['体育','tǐyù','noun','physical education','beden eğitimi', '체육'],
  ['体育馆','tǐyùguǎn','noun','gymnasium','spor salonu', '체육관'],
  ['甜','tián','adjective','sweet','tatlı', '달다'],
  ['跳','tiào','verb','to jump','zıplamak, atlamak', '뛰다, 뛰어넘다'],
  ['听说','tīngshuō','verb','to hear said','duyduğuna göre', '듣다 이르다, 소문이 나다'],
  ['挺','tǐng','adverb','quite, rather; (to endure)','oldukça; (katlanmak)', '꽤, 아주; 견디다'],
  ['同事','tóngshì','noun','colleague','iş arkadaşı', '동료'],
  ['同意','tóngyì','verb','to agree','katılmak, onaylamak', '동의하다'],
  ['头发','tóufa','noun','hair','saç', '머리카락'],
  ['突然','tūrán','adjective','sudden','ani', '갑자기'],
  ['图书馆','túshūguǎn','noun','library','kütüphane', '도서관'],
  ['腿','tuǐ','noun','leg','bacak', '다리'],
  ['外地','wàidì','noun','other place','başka şehir/yer', '타지, 다른 지역'],
  ['外卖','wàimài','noun','takeaway; to order takeout','paket servis; paket sipariş etmek', '포장 음식, 배달 음식; 배달 음식을 주문하다'],
  ['外语','wàiyǔ','noun','foreign language','yabancı dil', '외국어'],
  ['完成','wánchéng','verb','to complete','tamamlamak', '완성하다'],
  ['碗','wǎn','noun','bowl','kase', '사발, 그릇'],
  ['晚点','wǎndiǎn','verb','to be late','geç kalmak', '늦어지다, 지연되다'],
  ['晚会','wǎnhuì','noun','evening party','gece partisi', '야회, 저녁 파티'],
  ['网球','wǎngqiú','noun','tennis','tenis', '테니스'],
  ['网站','wǎngzhàn','noun','website','web sitesi', '웹사이트'],
  ['忘记','wàngjì','verb','to forget','unutmak', '잊다'],
  ['为','wèi, wéi','preposition','for, because of, to','için, -den dolayı', '~을 위하여, ~을 위해'],
  ['为了','wèile','preposition','in order to','-mek için', '~을/를 위하여, ~을/를 위해서'],
  ['卫生间','wèishēngjiān','noun','bathroom, restroom','banyo, tuvalet', '화장실'],
  ['文化','wénhuà','noun','culture','kültür', '문화'],
  ['屋子','wūzi','noun','room, house','oda, ev', '방, 집'],
  ['西','xī','noun','west','batı', '서쪽'],
  ['西北','xīběi','noun','northwest','kuzeybatı', '서북쪽'],
  ['西方','xīfāng','noun','west','batı', '서방, 서양'],
  ['西瓜','xīguā','noun','watermelon','karpuz', '수박'],
  ['西南','xīnán','noun','southwest','güneybatı', '서남쪽'],
  ['习惯','xíguàn','verb','to be used to; habit','alışmak; alışkanlık', '습관이 되다, 익숙해지다'],
  ['喜爱','xǐ\'ài','verb','to like, to love','sevmek, beğenmek', '좋아하다, 사랑하다'],
  ['洗衣机','xǐyījī','noun','washing machine','çamaşır makinesi', '세탁기'],
  ['洗澡','xǐzǎo','verb','to take a bath','banyo yapmak', '목욕하다'],
  ['夏天','xiàtiān','noun','summer','yaz', '여름'],
  ['先','xiān','adverb','first, before','önce', '먼저, 우선'],
  ['香蕉','xiāngjiāo','noun','banana','muz', '바나나'],
  ['相信','xiāngxìn','verb','to believe','inanmak', '믿다, 신뢰하다'],
  ['箱子','xiāngzi','noun','box, case','kutu, bavul', '상자, 가방'],
  ['向','xiàng','preposition','toward, to; to face','-e doğru; yönelmek', '~을 향하여, ~에게; ~을 향하다'],
  ['像','xiàng','verb','to resemble, to be like; (as if)','benzemek; (sanki)', '닮다, 비슷하다; 마치 ~처럼'],
  ['相机','xiàngjī','noun','camera','fotoğraf makinesi', '카메라'],
  ['小区','xiǎoqū','noun','residential community','konut sitesi', '주택 단지'],
  ['小心','xiǎoxīn','adjective','to be careful; careful','dikkatli olmak; dikkatli', '조심하다, 조심스러운'],
  ['校园','xiàoyuán','noun','campus','kampüs', '캠퍼스, 교정'],
  ['校长','xiàozhǎng','noun','principal, headmaster','okul müdürü', '교장'],
  ['鞋','xié','noun','shoe','ayakkabı', '신발'],
  ['心里','xīnlǐ','noun','heart, mind','kalpte, içinde', '마음속'],
  ['新年','xīnnián','noun','New Year','Yeni Yıl', '신년, 새해'],
  ['新闻','xīnwén','noun','news','haber', '뉴스, 소식'],
  ['新鲜','xīnxiān','adjective','fresh','taze', '신선하다, 새롭다'],
  ['信','xìn','verb','to believe; letter','inanmak; mektup', '믿다, 편지'],
  ['信用卡','xìnyòngkǎ','noun','credit card','kredi kartı', '신용카드'],
  ['行','xíng, háng','adjective','okay, permissible; to go','tamam, caiz; gitmek', '줄, 열; (화폐 단위) 각'],
  ['行李','xíngli','noun','luggage','bagaj', '수하물, 짐'],
  ['兴趣','xìngqù','noun','interest','ilgi, merak', '흥미, 관심'],
  ['休假','xiūjià','verb','to take a holiday','tatile çıkmak', '휴가를 내다, 휴가를 보내다'],
  ['需要','xūyào','verb','to need; need','ihtiyaç duymak; ihtiyaç', '필요하다, 요구하다'],
  ['选','xuǎn','verb','to choose','seçmek', '선택하다, 고르다'],
  ['选择','xuǎnzé','verb','to choose','seçmek', '선택하다'],
  ['学期','xuéqī','noun','semester','dönem', '학기'],
  ['牙','yá','noun','tooth','diş', '이'],
  ['牙刷','yáshuā','noun','toothbrush','diş fırçası', '칫솔'],
  ['羊','yáng','noun','sheep','koyun', '양'],
  ['养','yǎng','verb','to raise, to keep','beslemek, yetiştirmek', '기르다, 양육하다'],
  ['要求','yāoqiú','verb','to demand; requirement','talep etmek; gereksinim', '요구하다; 요구, 요청'],
  ['页','yè','classifier','measure word for page','sayfa sayı sözcüğü', '~쪽, 페이지'],
  ['一定','yídìng','adverb','certain; certainly','kesin; kesinlikle', '반드시, 꼭'],
  ['一共','yígòng','adverb','altogether, in total','toplamda, hepsi birden', '모두, 전부'],
  ['一块儿','yíkuàir','adverb','the same place; together','birlikte', '함께, 같이'],
  ['一样','yíyàng','adjective','same','aynı', '같은'],
  ['以后','yǐhòu','noun','later, after','sonra, -den sonra', '이후, 뒤에'],
  ['以前','yǐqián','noun','before','önce, -den önce', '이전, 전에'],
  ['以上','yǐshàng','noun','above, more than','yukarıda, fazla', '이상, ~ 이상'],
  ['以外','yǐwài','noun','except, besides','dışında, haricinde', '~을/를 제외하고, ~ 외에'],
  ['以为','yǐwéi','verb','to think, to believe','sanmak', '착각하다, 여기다'],
  ['以下','yǐxià','noun','below, less than','aşağıda, az', '이하, ~ 이하'],
  ['一般','yìbān','adjective','general, ordinary','genel, sıradan', '일반적인, 보통의'],
  ['一边','yìbiān','adverb','at the same time','aynı zamanda, -ken', '~하면서 동시에'],
  ['一直','yìzhí','adverb','always, straight','hep, doğruca', '쭉, 계속'],
  ['音乐','yīnyuè','noun','music','müzik', '음악'],
  ['银行','yínháng','noun','bank','banka', '은행'],
  ['银行卡','yínhángkǎ','noun','bank card','banka kartı', '은행 카드'],
  ['饮料','yǐnliào','noun','beverage','içecek', '음료'],
  ['应该','yīnggāi','verb','should, ought to','-meli, -malı', '해야 한다'],
  ['影响','yǐngxiǎng','verb','to affect; influence','etkilemek; etki', '영향을 미치다'],
  ['用','yòng','verb','to use','kullanmak', '사용하다'],
  ['邮件','yóujiàn','noun','mail','posta, e-posta', '우편물'],
  ['游客','yóukè','noun','tourist','turist', '관광객'],
  ['游戏','yóuxì','noun','game','oyun', '게임, 유희'],
  ['邮箱','yóuxiāng','noun','mailbox','posta kutusu', '우편함'],
  ['有关','yǒuguān','verb','to have to do with; concerning','ilgili olmak; hakkında', '관련되다, ~에 관한'],
  ['有名','yǒumíng','adjective','famous','ünlü', '유명하다, 이름나다'],
  ['有用','yǒuyòng','adjective','useful','faydalı', '유용하다, 쓸모 있다'],
  ['又','yòu','adverb','again, also','yine, tekrar', '또, 다시'],
  ['羽毛球','yǔmáoqiú','noun','badminton','badminton', '배드민턴'],
  ['语言','yǔyán','noun','language','dil', '언어'],
  ['雨衣','yǔyī','noun','raincoat','yağmurluk', '우비, 비옷'],
  ['遇到','yùdào','verb','to encounter','karşılaşmak', '만나다, 부닥치다'],
  ['遇见','yùjiàn','verb','to meet','rastlamak', '만나다'],
  ['园','yuán','noun','garden','bahçe', '동산, 정원'],
  ['员','yuán','suffix','suffix for person with a certain job','belirli bir iş kişisi eki', '~원 (직책 접미사)'],
  ['愿意','yuànyì','verb','willing','istekli olmak, razı olmak', '원하다, 기꺼이 ~하다'],
  ['越','yuè','adverb','more, increasingly','giderek daha fazla', '점점 더'],
  ['月亮','yuèliang','noun','moon','ay', '달'],
  ['运动会','yùndònghuì','noun','sports meet','spor müsabakası', '운동회'],
  ['运动员','yùndòngyuán','noun','athlete','sporcu', '운동선수'],
  ['咱们','zánmen','pronoun','we (inclusive)','biz (dahili)', '우리 (화자 포함)'],
  ['脏','zāng, zàng','adjective','dirty','kirli', '더러운'],
  ['怎么办','zěnmebàn','verb','what to do','ne yapalım', '어떻게 하다'],
  ['怎样','zěnyàng','pronoun','how','nasıl', '어떻게'],
  ['张','zhāng','classifier','measure word for flat objects; to open','düz nesneler sayı sözcüğü; açmak', '장(평평한 물건), 펴다'],
  ['着急','zháojí','adjective','anxious','endişeli, telaşlı', '조급하다, 안달하다'],
  ['照','zhào','verb','to shine, to photograph','parlatmak, fotoğraf çekmek', '비추다, 사진을 찍다'],
  ['照顾','zhàogù','verb','to take care of','bakmak, ilgilenmek', '돌보다, 보살피다'],
  ['照片','zhàopiàn','noun','photo','fotoğraf', '사진'],
  ['照相','zhàoxiàng','verb','to take a picture','fotoğraf çekmek', '사진을 찍다'],
  ['直到','zhídào','verb','until','-e kadar', '~까지 이르다'],
  ['只','zhǐ, zhī','adverb','only, merely','yalnızca, sadece', '마리 (동물 단위)'],
  ['纸','zhǐ','noun','paper','kağıt', '종이'],
  ['只能','zhǐnéng','adverb','can only','yalnızca yapabilmek', '~할 수밖에 없다'],
  ['只是','zhǐshì','adverb','only, merely; but','yalnızca; ama', '단지, 다만; 그러나'],
  ['只要','zhǐyào','conjunction','as long as','-diği sürece', '~하기만 하면'],
  ['只有','zhǐyǒu','conjunction','only if','yalnızca eğer', '~해야만'],
  ['中','zhōng, zhòng','noun','middle','orta', '중간, 가운데'],
  ['中间','zhōngjiān','noun','middle, between','arasında, ortada', '중간, 가운데'],
  ['终于','zhōngyú','adverb','finally','sonunda', '마침내, 드디어'],
  ['种','zhǒng, zhòng','classifier','measure word for kinds','tür sayı sözcüğü', '1. 종류 2. 심다, 재배하다'],
  ['重要','zhòngyào','adjective','important','önemli', '중요한'],
  ['周末','zhōumò','noun','weekend','hafta sonu', '주말'],
  ['主要','zhǔyào','adjective','main','ana, esas', '주요한, 주된'],
  ['注意','zhùyì','verb','to pay attention to','dikkat etmek', '주의하다, 주목하다'],
  ['住院','zhùyuàn','verb','to be hospitalized','hastaneye yatmak', '입원하다'],
  ['字典','zìdiǎn','noun','dictionary','sözlük', '자전, 사전'],
  ['自行车','zìxíngchē','noun','bicycle','bisiklet', '자전거'],
  ['子','zi','suffix','noun suffix','isim eki', '명사 뒤에 붙어 사물이나 사람을 나타내는 접미사'],
  ['总','zǒng','adverb','always, invariably; (total, overall)','her zaman; (toplam)', '언제나, 늘; 총, 합계'],
  ['总是','zǒngshì','adverb','always','her zaman', '언제나, 늘'],
  ['嘴','zuǐ','noun','mouth','ağız', '입'],
  ['最好','zuìhǎo','adverb','best','en iyi, mümkünse', '가장 좋은, 제일 좋은'],
  ['最后','zuìhòu','noun','last, final','son', '최후의, 마지막'],
  ['最近','zuìjìn','noun','recently','son zamanlarda', '최근에'],
  ['做客','zuòkè','verb','to be a guest','misafir olmak', '손님으로 가다, 방문하다'],
  ['作业','zuòyè','noun','homework','ödev', '과제, 숙제'],
];
