/// HSK Level 3 — ~494 unique vocabulary entries (500 list entries, ~6 duplicates deduplicated).
/// Each row: [simplified, pinyin, pos, en, tr, ko, ja, id, vi, th, ru, es, pt]
const List<List<String>> kHsk3Words = [
  ['阿姨','āyí','noun','aunt','hala, teyze', '이모, 숙모, 아줌마', 'おばさん、叔母', 'bibi, tante', 'dì, cô, bác', 'น้า, ป้า', 'тётя', 'la tía', 'a tia'],
  ['矮','ǎi','adjective','short','kısa boylu', '키가 작다', '（背が）低い', 'pendek', 'thấp', 'เตี้ย', 'низкий (о росте)', 'bajo', 'baixo'],
  ['爱人','àiren','noun','spouse','eş', '애인, 배우자', '配偶者、夫、妻', 'pasangan, suami atau istri', 'vợ hoặc chồng, người yêu', 'คู่สมรส, สามีหรือภรรยา', 'супруг, супруга', 'el cónyuge, la pareja', 'o cônjuge, o esposo, a esposa'],
  ['安静','ānjìng','adjective','quiet','sessiz, sakin', '조용하다', '静かだ', 'tenang, sunyi', 'yên tĩnh, lặng lẽ', 'เงียบ, สงบ', 'тихий, спокойный', 'tranquilo, silencioso', 'tranquilo, silencioso'],
  ['安全','ānquán','adjective','safe','güvenli', '안전하다', '安全だ', 'aman', 'an toàn', 'ปลอดภัย', 'безопасный', 'seguro', 'seguro'],
  ['把','bǎ','classifier','measure word for handles; object-fronting particle','saplı nesneler sayı sözcüğü', '~을/를 (목적어 앞으로 도치시키는 조사)', '（取っ手のあるものを数える）〜本、〜把、動作の対象を導く助詞', 'kata penggolong benda bergagang, partikel penanda objek', 'lượng từ (vật có tay cầm), giới từ (đánh dấu tân ngữ)', 'คำลักษณนามของสิ่งที่มีด้ามจับ, คำช่วยหน้ากรรมเพื่อเน้นการกระทำ', 'счётное слово для предметов с ручкой, показатель объекта', 'clasificador para objetos con mango, partícula de preposición de objeto', 'classificador para objetos com cabo, partícula de marcação de objeto'],
  ['搬','bān','verb','to move, to carry','taşımak', '옮기다, 이사하다', '運ぶ、移動させる', 'memindahkan, mengangkut', 'chuyển, dời', 'ย้าย, ขนย้าย', 'передвигать, переносить', 'mover, trasladar', 'mover, carregar'],
  ['班级','bānjí','noun','class, grade','sınıf', '반, 학급', 'クラス、学級', 'kelas', 'lớp học', 'ชั้นเรียน, ระดับชั้น', 'класс, группа', 'la clase, el curso', 'a turma, a classe'],
  ['搬家','bānjiā','verb','to move house','ev taşımak', '이사하다', '引っ越す', 'pindah rumah', 'chuyển nhà', 'ย้ายบ้าน', 'переезжать', 'mudarse', 'mudar-se'],
  ['办','bàn','verb','to do, to handle','yapmak, halletmek', '하다, 처리하다', '処理する、行う', 'melakukan, mengurus', 'làm, xử lý', 'ทำ, จัดการ', 'делать, оформлять/оформить', 'hacer, gestionar', 'fazer, tratar de'],
  ['办法','bànfǎ','noun','way, solution','yol, çözüm', '방법, 해결책', '方法、手段', 'cara, solusi', 'cách, phương pháp', 'วิธี, หนทางแก้ไข', 'способ, решение', 'el método, la solución', 'o método, a solução'],
  ['办公室','bàngōngshì','noun','office','ofis', '사무실', 'オフィス、事務室', 'kantor', 'văn phòng', 'สำนักงาน', 'офис, кабинет', 'la oficina', 'o escritório'],
  ['半天','bàntiān','number-classifier','half a day, a long time','yarım gün, uzun zaman', '반나절, 오래', '半日、長い時間', 'setengah hari, waktu yang lama', 'nửa ngày, một lúc lâu', 'ครึ่งวัน, เป็นเวลานาน', 'полдня, долгое время', 'medio día, mucho tiempo', 'meio dia, muito tempo'],
  ['帮助','bāngzhù','verb','to help','yardım etmek', '돕다', '助ける、手伝う', 'membantu', 'giúp đỡ', 'ช่วยเหลือ', 'помогать/помочь', 'ayudar', 'ajudar'],
  ['饱','bǎo','adjective','full','tok', '배부르다', '満腹だ、十分だ', 'kenyang', 'no', 'อิ่ม', 'сытый', 'satisfecho, lleno', 'satisfeito, cheio'],
  ['报纸','bàozhǐ','noun','newspaper','gazete', '신문', '新聞', 'surat kabar, koran', 'báo, tờ báo', 'หนังสือพิมพ์', 'газета', 'el periódico', 'o jornal'],
  ['北','běi','noun','north','kuzey', '북쪽', '北', 'utara', 'phía bắc', 'ทิศเหนือ', 'север', 'el norte', 'o norte'],
  ['北方','běifāng','noun','north','kuzey', '북방', '北方、北の方', 'utara', 'phương bắc', 'ทางเหนือ', 'север', 'el norte', 'o norte'],
  ['被','bèi','preposition','by','tarafından', '~에 의해 (피동), ~에게', '〜に（受身を表す前置詞）', 'oleh', 'bị, được', 'โดย (คำบุพบทแสดงกรรม)', 'предлог пассивного залога', 'por', 'por (agente da passiva)'],
  ['笔记','bǐjì','noun','notes','not', '필기, 메모', 'ノート、メモ', 'catatan', 'ghi chú, bút ký', 'บันทึก, จดบันทึก', 'заметки, записи', 'los apuntes', 'as anotações'],
  ['比较','bǐjiào','adverb','to compare; quite, relatively; than','karşılaştırmak; oldukça', '비교하다, 상당히', '比較する、比較的、〜より', 'membandingkan, relatif, cukup', 'so sánh, tương đối, khá', 'เปรียบเทียบ, ค่อนข้าง', 'сравнивать, сравнительно, довольно', 'comparar, relativamente, bastante', 'comparar, relativamente'],
  ['笔记本','bǐjìběn','noun','notebook','defter', '노트, 노트북', 'ノート（帳）、ノートパソコン', 'buku catatan', 'sổ tay, máy tính xách tay', 'สมุดบันทึก', 'блокнот, тетрадь', 'el cuaderno', 'o caderno'],
  ['比如','bǐrú','verb','for example','örneğin', '예를 들면', '例えば', 'seperti, misalnya', 'ví dụ, chẳng hạn', 'เช่น, ยกตัวอย่างเช่น', 'например', 'por ejemplo', 'por exemplo'],
  ['比赛','bǐsài','verb','to compete; game, match','yarışmak; maç', '시합하다, 경기하다', '試合する、競技する、試合', 'bertanding, pertandingan', 'thi đấu, cuộc thi', 'แข่งขัน, การแข่งขัน', 'соревноваться, соревнование, матч', 'competir, el partido, la competición', 'competir, a competição, a partida'],
  ['必须','bìxū','adverb','must','zorunlu olmak', '반드시 ~해야 하다', '必ず、どうしても', 'harus, wajib', 'phải, bắt buộc', 'ต้อง', 'должен, необходимо', 'deber, tener que', 'precisar, ter de'],
  ['变','biàn','verb','to change, to become','değişmek', '변하다, 바뀌다', '変わる、変化する', 'berubah, menjadi', 'thay đổi, biến đổi', 'เปลี่ยน, เปลี่ยนแปลง', 'меняться, становиться', 'cambiar, convertirse', 'mudar, tornar-se'],
  ['遍','biàn','classifier','measure word for actions','eylemler için sayı sözcüğü (kez)', '~번 (동작 횟수)', '（動作の回数を数える助数詞）', 'kali', 'lần, lượt', 'รอบ, ครั้ง (ลักษณนามสำหรับจำนวนครั้งที่ทำ)', 'раз (счетное слово для действий)', 'clasificador para acciones (vez)', 'classificador para ações'],
  ['变成','biànchéng','verb','to become, to turn into','olmak, dönüşmek', '~으로 변하다, ~이 되다', '〜になる、変わる', 'menjadi', 'trở thành, biến thành', 'กลายเป็น', 'превращаться, становиться', 'convertirse en, transformarse en', 'tornar-se, transformar-se'],
  ['变化','biànhuà','verb','to change; change','değişmek; değişim', '변화하다; 변화', '変化する、変化', 'berubah, perubahan', 'thay đổi, biến hóa', 'การเปลี่ยนแปลง, เปลี่ยนแปลง', 'изменение, меняться', 'cambiar, el cambio', 'mudar, a mudança'],
  ['表演','biǎoyǎn','verb','to perform, to act','sahne almak, oynamak', '공연하다, 연기하다', '演じる、演技する、演奏する', 'mempertunjukkan, tampil', 'biểu diễn', 'แสดง', 'выступать, исполнять', 'actuar, representar', 'apresentar, atuar'],
  ['别的','biéde','pronoun','other','diğer', '다른', 'ほかの', 'lainnya', 'khác', 'อื่น, อย่างอื่น', 'другой, иной', 'otro', 'outro'],
  ['别人','biérén','pronoun','other people','başkaları', '다른 사람', '他人、ほかの人', 'orang lain', 'người khác', 'คนอื่น', 'другие (люди), посторонние', 'los demás, otra persona', 'outras pessoas, o próximo'],
  ['宾馆','bīnguǎn','noun','hotel','otel', '호텔', 'ホテル', 'hotel', 'khách sạn', 'โรงแรม', 'гостиница, отель', 'el hotel', 'o hotel'],
  ['冰','bīng','noun','ice; (to freeze)','buz; (donmak)', '얼음, 얼다', '氷、凍る', 'es, membekukan', 'băng, đá, đóng băng', 'น้ำแข็ง, ทำให้เป็นน้ำแข็ง', 'лёд', 'el hielo', 'o gelo, congelar'],
  ['冰激凌','bīngjīlíng','noun','ice cream','dondurma', '아이스크림', 'アイスクリーム', 'es krim', 'kem', 'ไอศกรีม', 'мороженое', 'el helado', 'o sorvete'],
  ['冰箱','bīngxiāng','noun','refrigerator','buzdolabı', '냉장고', '冷蔵庫', 'kulkas, lemari es', 'tủ lạnh', 'ตู้เย็น', 'холодильник', 'el refrigerador, la nevera', 'a geladeira'],
  ['病人','bìngrén','noun','patient','hasta', '환자', '病人、患者', 'pasien, orang sakit', 'bệnh nhân', 'คนไข้, ผู้ป่วย', 'больной, пациент', 'el paciente', 'o paciente'],
  ['不但','búdàn','conjunction','not only','sadece değil', '~일 뿐만 아니라', '〜だけでなく', 'tidak hanya', 'không những', 'ไม่เพียงแต่', 'не только', 'no solo', 'não apenas'],
  ['不见','bújiàn','verb','to disappear, to not see','kaybolmak, görmemek', '사라지다, 보이지 않다', '見えなくなる、姿を消す', 'hilang, tidak terlihat', 'biến mất, không thấy', 'หายไป, ไม่พบ', 'исчезнуть, пропасть', 'desaparecer, no ver', 'desaparecer, não ver'],
  ['不用','búyòng','adverb','need not','gerek yok', '~할 필요가 없다', '〜する必要はない', 'tidak perlu', 'không cần', 'ไม่ต้อง', 'не нужно, не стоит', 'no necesitar, no hacer falta', 'não precisar'],
  ['不同','bùtóng','adjective','different','farklı', '다른, 같지 않은', '異なる、違う', 'berbeda', 'khác biệt', 'แตกต่าง, ไม่เหมือนกัน', 'различный, другой', 'diferente, distinto', 'diferente'],
  ['不久','bùjiǔ','adjective','soon, not long after','kısa süre sonra', '머지않아, 곧', 'まもなく、間もなく', 'tidak lama lagi, segera', 'không lâu, chẳng bao lâu', 'ไม่นาน', 'недолго, вскоре', 'pronto, poco después', 'em breve, pouco tempo depois'],
  ['不行','bùxíng','adjective','not allowed; not good','olmaz; iyi değil', '안 된다, 좋지 않다', 'だめだ、いけない', 'tidak boleh, tidak bisa', 'không được, không xong', 'ไม่ได้, ไม่ไหว', 'нельзя, не годится', 'no permitido, no estar bien', 'inviável, não permitido, não dar certo'],
  ['才','cái','adverb','just, only','ancak, yalnızca', '재능, 능력', '才能、能力', 'bakat, kemampuan', 'tài năng, năng lực', 'ความสามารถ, พรสวรรค์', 'талант, способности', 'el talento, la capacidad', 'o talento, a habilidade'],
  ['菜单','càidān','noun','menu','menü', '메뉴', 'メニュー、献立表', 'daftar menu', 'thực đơn', 'เมนู, รายการอาหาร', 'меню', 'el menú, la carta', 'o cardápio'],
  ['参加','cānjiā','verb','to join, to attend','katılmak', '참하다, 참가하다', '参加する、加わる', 'mengikuti, menghadiri', 'tham gia, dự', 'เข้าร่วม, ร่วม', 'участвовать, принимать участие', 'participar, asistir', 'participar, comparecer'],
  ['草','cǎo','noun','grass','çimen, ot', '풀', '草', 'rumput', 'cỏ', 'หญ้า', 'трава', 'la hierba', 'a grama'],
  ['草地','cǎodì','noun','grassland','çayırlık, ot, çimen', '잔디밭', '草地、芝生', 'padang rumput', 'bãi cỏ', 'สนามหญ้า', 'лужайка, газон', 'el césped, la pradera', 'o gramado'],
  ['层','céng','classifier','measure word for layer, floor','kat sayı sözcüğü', '층, 단계', '層、階', 'kata penggolong untuk lapisan atau lantai', 'lượng từ (tầng, lớp)', 'ชั้น (ลักษณนามของชั้นหรือระดับ)', 'счётное слово для этажей и слоёв', 'clasificador para pisos o capas', 'classificador para andares ou camadas'],
  ['查','chá','verb','to check','kontrol etmek', '조사하다, 찾다', '調べる、検査する', 'memeriksa, mengecek', 'tra, kiểm tra', 'ตรวจสอบ, ค้นหา', 'проверять, наводить справки', 'consultar, verificar, comprobar', 'verificar, consultar, pesquisar'],
  ['差','chà, chā, chāi','adjective','bad, poor; to lack','kötü, yetersiz', '나쁘다, 부족하다', '悪い、不足する、違う', 'buruk, kurang, selisih', 'kém, thiếu, sai lệch', 'แย่, ขาด, ไม่ดี', 'плохой, недоставать, не хватать', 'malo, deficiente, faltar', 'ruim, inferior, faltar'],
  ['差不多','chàbuduō','adverb','almost, similar; nearly','hemen hemen, yaklaşık', '거의, 비슷하다', 'ほとんど、大体', 'hampir, kurang lebih', 'gần như, xấp xỉ', 'เกือบจะ, พอๆ กัน, ใกล้เคียงกัน', 'почти, примерно, одинаковый', 'casi, aproximadamente', 'quase, semelhante'],
  ['尝','cháng','verb','to taste','tatmak', '맛보다', '味わう、試食する', 'mencicipi, mencoba', 'nếm, thưởng thức', 'ชิม, ลิ้มรส', 'пробовать на вкус', 'probar', 'provar, experimentar'],
  ['常','cháng','adverb','often, frequent','sık sık', '자주', '常に、よく', 'sering', 'thường, thường xuyên', 'บ่อย, เป็นประจำ', 'часто', 'frecuentemente', 'frequentemente'],
  ['常见','chángjiàn','adjective','common','yaygın', '흔한', 'よく見かける、ありふれた', 'umum, lumrah', 'thường gặp', 'ที่พบเห็นได้บ่อย', 'распространённый, обычный', 'común, habitual', 'comum, habitual'],
  ['常用','chángyòng','adjective','commonly used','sık kullanılan', '자주 쓰이는', '常用する', 'lazim digunakan, umum', 'thường dùng', 'ที่ใช้บ่อย', 'общеупотребительный', 'de uso común', 'de uso comum'],
  ['常常','chángcháng','adverb','often','sık sık', '자주', 'よく、しばしば', 'sering', 'thường xuyên', 'บ่อยๆ', 'часто', 'a menudo', 'frequentemente'],
  ['衬衫','chènshān','noun','shirt','gömlek', '셔츠, 블라우스', 'シャツ、ワイシャツ', 'kemeja', 'áo sơ mi', 'เสื้อเชิ้ต', 'рубашка', 'la camisa', 'a camisa'],
  ['成绩','chéngjì','noun','score, grade, achievement','not, derece, başarı', '성적, 결과, 성과', '成績、成果', 'nilai, prestasi', 'thành tích, điểm số', 'คะแนน, ผลการเรียน, ผลงาน', 'успеваемость, результат, достижение', 'el resultado, la nota, el logro', 'a nota, o resultado, o desempenho'],
  ['城市','chéngshì','noun','city','şehir', '도시', '都市、都会', 'kota', 'thành phố', 'เมือง', 'город', 'la ciudad', 'a cidade'],
  ['迟到','chídào','verb','to be late','geç kalmak', '지각하다', '遅刻する', 'terlambat', 'đến muộn, trễ giờ', 'มาสาย', 'опаздывать', 'llegar tarde', 'atrasar-se'],
  ['出发','chūfā','verb','to set out, to leave','yola çıkmak', '출발하다', '出発する', 'berangkat', 'xuất phát, khởi hành', 'ออกเดินทาง', 'отправляться/отправиться, выезжать/выехать', 'partir, salir', 'partir, sair'],
  ['出生','chūshēng','verb','to be born','doğmak', '태어나다', '生まれる', 'lahir', 'sinh ra, chào đời', 'เกิด', 'родиться', 'nacer', 'nascer'],
  ['出院','chūyuàn','verb','to be discharged from hospital','taburcu olmak', '퇴원하다', '退院する', 'keluar rumah sakit', 'xuất viện', 'ออกจากโรงพยาบาล', 'выписываться/выписаться из больницы', 'recibir el alta médica', 'receber alta hospitalar'],
  ['初中','chūzhōng','noun','junior high school','ortaokul', '중학교', '中学校', 'sekolah menengah pertama', 'trung học cơ sở', 'มัธยมศึกษาตอนต้น', 'средняя школа (первая ступень)', 'la escuela secundaria básica', 'o ensino fundamental II'],
  ['除了','chúle','preposition','except, besides','-den başka, dışında', '~을/를 제외하고, ~ 외에', '〜を除いて、〜のほかに', 'kecuali, selain', 'ngoài ra, ngoại trừ', 'นอกจาก, ยกเว้น', 'кроме, помимо', 'además de, excepto', 'exceto, além de'],
  ['船','chuán','noun','boat','tekne, gemi', '배', '船', 'kapal, perahu', 'thuyền, tàu', 'เรือ', 'лодка, судно, корабль', 'el barco', 'o barco'],
  ['春天','chūntiān','noun','spring','ilkbahar', '봄', '春', 'musim semi', 'mùa xuân', 'ฤดูใบไม้ผลิ', 'весна', 'la primavera', 'a primavera'],
  ['词典','cídiǎn','noun','dictionary','sözlük', '사전', '辞書', 'kamus', 'từ điển', 'พจนานุกรม', 'словарь', 'el diccionario', 'o dicionário'],
  ['聪明','cōngmíng','adjective','smart, clever','zeki, akıllı', '똑똑하다, 영리하다', '賢い、利口だ', 'cerdas, pandai', 'thông minh', 'ฉลาด', 'умный, сообразительный', 'inteligente, listo', 'inteligente, esperto'],
  ['打扫','dǎsǎo','verb','to clean','temizlemek', '청소하다', '掃除する', 'membersihkan', 'quét dọn, dọn dẹp', 'ทำความสะอาด, ปัดกวาด', 'убирать/убрать', 'limpiar', 'limpar, varrer'],
  ['打算','dǎsuàn','verb','to plan, intend; plan','planlamak; plan', '계획하다, ~할 작정이다; 계획', '計画する、つもりだ、計画', 'berencana, rencana', 'dự định, kế hoạch', 'วางแผน, ตั้งใจ, แผนการ', 'планировать, намереваться, план', 'planear, tener la intención, el plan', 'planejar, o plano'],
  ['大概','dàgài','adverb','probably, approximately; general','muhtemelen; genel', '대략, 아마; 일반적인', 'だいたい、おおよそ、おそらく', 'kira-kira, mungkin, umum', 'đại khái, khoảng chừng, có lẽ', 'อาจจะ, ประมาณ, โดยทั่วไป', 'примерно, вероятно', 'probablemente, aproximadamente, general', 'provavelmente, aproximadamente, geral'],
  ['大人','dàren','noun','adult','yetişkin', '어른', '大人、成人', 'orang dewasa', 'người lớn', 'ผู้ใหญ่', 'взрослый', 'el adulto', 'o adulto'],
  ['大小','dàxiǎo','noun','size','boyut, beden', '크기', '大きさ', 'ukuran', 'kích thước, lớn nhỏ', 'ขนาด', 'размер', 'el tamaño', 'o tamanho'],
  ['大熊猫','dàxióngmāo','noun','giant panda','dev panda', '팬더', 'ジャイアントパンダ', 'panda raksasa', 'gấu trúc lớn', 'หมีแพนด้า', 'большая панда', 'el panda gigante', 'o panda-gigante'],
  ['大衣','dàyī','noun','coat','palto', '코트, 외투', 'コート', 'mantel', 'áo khoác', 'เสื้อโค้ต', 'пальто', 'el abrigo', 'o casaco'],
  ['带','dài','verb','to bring, to take; (belt)','getirmek, almak; (kemer)', '가지고 가다, 데리고 가다', '持っていく、連れて行く', 'membawa, mengajak', 'mang, đem, dẫn theo', 'นำ, พา, พกพา', 'брать с собой, приносить', 'llevar, traer', 'trazer, levar'],
  ['担心','dānxīn','verb','to worry','endişelenmek', '걱정하다', '心配する', 'khawatir, cemas', 'lo lắng', 'กังวล, เป็นห่วง', 'беспокоиться, волноваться', 'preocuparse', 'preocupar-se'],
  ['蛋糕','dàngāo','noun','cake','pasta', '케이크', 'ケーキ', 'kue', 'bánh kem, bánh ngọt', 'เค้ก', 'торт, пирожное', 'el pastel, la tarta', 'o bolo'],
  ['当然','dāngrán','adverb','of course','tabii ki, elbette', '물론', '当然だ、もちろん', 'tentu, tentu saja', 'đương nhiên, tất nhiên', 'แน่นอน, อย่างแน่นอน', 'конечно, разумеется', 'por supuesto, naturalmente', 'naturalmente, claro'],
  ['到处','dàochù','adverb','everywhere','her yerde', '도처에, 곳곳에', 'いたるところ、あちこち', 'di mana-mana', 'khắp nơi', 'ทุกหนทุกแห่ง', 'везде, повсюду', 'por todas partes', 'em toda parte, por toda parte'],
  ['得到','dédào','verb','to get, to obtain','elde etmek', '얻다, 받다', '手に入れる、得る', 'mendapatkan, memperoleh', 'đạt được, nhận được', 'ได้รับ, ได้มา', 'получать/получить', 'obtener, conseguir', 'obter, conseguir'],
  ['得分','défēn','verb','to score; score','puan almak; puan', '득점하다', '得点する、得点', 'mencetak skor, skor', 'ghi điểm, điểm số', 'ทำคะแนน, คะแนน', 'набирать очки, счёт', 'anotar, marcar puntos', 'pontuar, marcar pontos'],
  ['的话','dehuà','auxiliary','particle after condition clause, if...','koşul partikülü, eğer...', '~라면 (가정절 뒤에 쓰여)', '〜ならば、〜としたら（仮定を表す助詞）', 'partikel penanda pengandaian', 'trợ từ đặt sau mệnh đề điều kiện (nếu)', 'คำแสดงเงื่อนไข (ใช้หลังประโยคเงื่อนไข)', 'частица, оформляющая условие (если)', 'partícula condicional', 'partícula condicional (se)'],
  ['灯','dēng','noun','lamp, light','lamba, ışık', '등, 불', '明かり、ランプ、電灯', 'lampu', 'đèn', 'โคมไฟ, หลอดไฟ', 'лампа, светильник', 'la lámpara, la luz', 'a lâmpada, a luz'],
  ['地点','dìdiǎn','noun','place, location','yer, konum', '장소, 지점', '地点、場所', 'tempat, lokasi', 'địa điểm, vị trí', 'สถานที่, จุดที่ตั้ง', 'местоположение, пункт', 'el lugar, la ubicación', 'o local, o ponto'],
  ['地方','dìfang','noun','place','yer', '곳, 장소', '場所、ところ', 'tempat, daerah', 'nơi chốn, địa phương', 'สถานที่, ที่', 'место', 'el lugar, el sitio', 'o lugar, o local'],
  ['地图','dìtú','noun','map','harita', '지도', '地図', 'peta', 'bản đồ', 'แผนที่', 'карта', 'el mapa', 'o mapa'],
  ['电','diàn','noun','electricity; (to give an electric shock)','elektrik; (elektrik çarpmak)', '전기, 전압', '電気、電報', 'listrik', 'điện', 'ไฟฟ้า', 'электричество', 'la electricidad', 'a eletricidade'],
  ['电梯','diàntī','noun','elevator','asansör', '엘리베이터', 'エレベーター', 'lift', 'thang máy', 'ลิฟต์', 'лифт', 'el ascensor', 'o elevador'],
  ['电子书','diànzǐshū','noun','e-book','e-kitap', '전자책', '電子書籍', 'buku elektronik', 'sách điện tử', 'หนังสืออิเล็กทรอนิกส์', 'электронная книга', 'el libro electrónico', 'o e-book'],
  ['丢','diū','verb','to lose, to throw away','kaybetmek, atmak', '잃다, 버리다', '失くす、捨てる', 'kehilangan, membuang', 'mất, vứt bỏ', 'ทำหาย, ทิ้ง', 'терять, бросать', 'perder, tirar', 'perder, jogar fora'],
  ['东','dōng','noun','east','doğu', '동쪽', '東', 'timur', 'phía đông', 'ทิศตะวันออก', 'восток', 'el este', 'o leste'],
  ['东北','dōngběi','noun','northeast','kuzeydoğu', '동북쪽', '北東', 'timur laut', 'đông bắc', 'ทิศตะวันออกเฉียงเหนือ', 'северо-восток', 'el noreste', 'o nordeste'],
  ['东方','dōngfāng','noun','east','doğu', '동방, 동쪽', '東方、東', 'timur', 'phương đông', 'ทิศตะวันออก', 'восток', 'el oriente, el este', 'o oriente, o leste'],
  ['东南','dōngnán','noun','southeast','güneydoğu', '동남쪽', '南東', 'tenggara', 'đông nam', 'ทิศตะวันออกเฉียงใต้', 'юго-восток', 'el sureste', 'o sudeste'],
  ['冬天','dōngtiān','noun','winter','kış', '겨울', '冬', 'musim dingin', 'mùa đông', 'ฤดูหนาว', 'зима', 'el invierno', 'o inverno'],
  ['懂得','dǒngde','verb','to understand','anlamak', '이해하다, 알다', 'わかる、理解する', 'mengerti, memahami', 'hiểu, biết', 'เข้าใจ, รู้เรื่อง', 'понимать/понять', 'entender, comprender', 'entender, compreender'],
  ['动物','dòngwù','noun','animal','hayvan', '동물', '動物', 'hewan, binatang', 'động vật', 'สัตว์', 'животное', 'el animal', 'o animal'],
  ['动物园','dòngwùyuán','noun','zoo','hayvanat bahçesi', '동물원', '動物園', 'kebun binatang', 'vườn bách thú', 'สวนสัตว์', 'зоопарк', 'el zoológico', 'o zoológico'],
  ['短','duǎn','adjective','short','kısa', '짧다', '短い', 'pendek', 'ngắn', 'สั้น', 'короткий', 'corto', 'curto'],
  ['短裤','duǎnkù','noun','shorts','şort', '반바지', 'ショートパンツ、半ズボン', 'celana pendek', 'quần đùi, quần soóc', 'กางเกงขาสั้น', 'шорты', 'los pantalones cortos', 'o short'],
  ['段','duàn','classifier','measure word for segment, paragraph','bölüm, paragraf sayı sözcüğü', '단, 토막, 구간', '（時間・空間の）一区切り、部分', 'bagian, ruas, paragraf', 'đoạn, khúc', 'ช่วง, ตอน, ท่อน', 'отрезок, часть, период', 'segmento, parte, párrafo', 'classificador para segmentos, trechos ou períodos'],
  ['锻炼','duànliàn','verb','to exercise','egzersiz yapmak', '운동하다, 단련하다', '鍛える、運動する', 'berolahraga, melatih', 'rèn luyện, tập luyện', 'ออกกำลังกาย, ฝึกฝน', 'тренироваться, заниматься физическими упражнениями', 'hacer ejercicio, entrenar', 'exercitar-se, treinar'],
  ['对话','duìhuà','noun','dialogue, conversation','diyalog, konuşma', '대화', '対話、会話', 'dialog, percakapan', 'đối thoại, hội thoại', 'บทสนทนา, การสนทนา', 'диалог, беседа', 'el diálogo, la conversación', 'o diálogo, a conversa'],
  ['饿','è','adjective','hungry','aç', '배고프다', '空腹だ、ひもじい', 'lapar', 'đói', 'หิว', 'голодный', 'hambriento', 'faminto'],
  ['而且','érqiě','conjunction','and, moreover','ayrıca, üstelik', '~일 뿐만 아니라, 게다가', 'その上、さらに、また', 'lagipula, dan lagi', 'hơn nữa, vả lại', 'อีกทั้ง, ยิ่งไปกว่านั้น', 'к тому же, а также', 'además, y también', 'e, além disso'],
  ['耳朵','ěrduo','noun','ear','kulak', '귀', '耳', 'telinga', 'tai', 'หู', 'ухо', 'la oreja', 'a orelha'],
  ['耳机','ěrjī','noun','earphone','kulaklık', '이어폰', 'イヤホン、ヘッドホン', 'alat dengar, fon kepala', 'tai nghe', 'หูฟัง', 'наушники', 'los auriculares', 'o fone de ouvido'],
  ['发','fā, fà','verb','to send, to issue','göndermek, yayımlamak', '보내다, 발송하다, (머리를) 풀다', '送る、発する', 'mengirim, mengeluarkan', 'phát, gửi', 'ส่ง, ออก, แจกจ่าย', 'отправлять, выпускать', 'enviar, emitir', 'enviar, emitir'],
  ['发烧','fāshāo','verb','to have a fever','ateş çıkmak', '열이 나다, 발열하다', '熱を出す、発熱する', 'demam', 'sốt', 'เป็นไข้, มีไข้', 'температурить, иметь жар', 'tener fiebre', 'ter febre'],
  ['发生','fāshēng','verb','to happen','olmak, meydana gelmek', '발생하다, 일어나다', '起こる、発生する', 'terjadi', 'xảy ra, phát sinh', 'เกิดขึ้น', 'происходить, случаться', 'suceder, ocurrir', 'acontecer, ocorrer'],
  ['发现','fāxiàn','verb','to find, to discover','bulmak, keşfetmek', '발견하다', '見つける、発見する', 'menemukan, mendapati', 'phát hiện, tìm ra', 'พบ, ค้นพบ', 'находить, обнаруживать', 'encontrar, descubrir', 'descobrir, notar'],
  ['发展','fāzhǎn','verb','to develop','gelişmek', '발전하다', '発展する', 'berkembang, mengembangkan', 'phát triển', 'พัฒนา', 'развивать, развиваться', 'desarrollar', 'desenvolver'],
  ['方便','fāngbiàn','adjective','convenient','uygun, pratik', '편리하다, 알맞다', '便利だ、都合がよい', 'praktis, nyaman', 'thuận tiện, tiện lợi', 'สะดวก', 'удобный', 'conveniente, cómodo', 'conveniente, prático'],
  ['方便面','fāngbiànmiàn','noun','instant noodles','hazır noodle', '인스턴트 라면', 'インスタントラーメン', 'mi instan', 'mì ăn liền', 'บะหมี่กึ่งสำเร็จรูป', 'лапша быстрого приготовления', 'los fideos instantáneos', 'o macarrão instantâneo'],
  ['方法','fāngfǎ','noun','method','yöntem', '방법, 방식', '方法、やり方', 'metode, cara', 'phương pháp, cách thức', 'วิธี, วิธีการ', 'метод, способ', 'el método, la manera', 'o método, a maneira'],
  ['方向','fāngxiàng','noun','direction','yön', '방향, 방면', '方向、方角', 'arah', 'phương hướng', 'ทิศทาง', 'направление', 'la dirección, el rumbo', 'a direção, o sentido'],
  ['房子','fángzi','noun','house','ev', '집', '家、建物', 'rumah', 'nhà, căn nhà', 'บ้าน, อาคาร', 'дом, квартира', 'la casa', 'a casa'],
  ['放','fàng','verb','to put, to place','koymak, yerleştirmek', '놓다, 두다', '置く、放す', 'meletakkan, menaruh', 'đặt, để', 'วาง, ปล่อย', 'класть, ставить', 'poner, colocar', 'pôr, colocar'],
  ['放假','fàngjià','verb','to have a holiday','tatile çıkmak', '휴가를 보내다, 방학하다', '休みになる', 'berlibur', 'nghỉ lễ, nghỉ phép', 'หยุดเรียน, หยุดงาน', 'уходить на каникулы/отпуск', 'tener vacaciones', 'entrar de férias'],
  ['放心','fàngxīn','verb','to relax, to feel at ease','rahatlamak', '안심하다', '安心する', 'tenang, tidak khawatir', 'yên tâm', 'วางใจ, สบายใจ', 'успокаиваться, не волноваться', 'tranquilizarse, estar tranquilo', 'tranquilizar-se, ficar sossegado'],
  ['放学','fàngxué','verb','school is over','okul bitmek', '하교하다', '授業が終わる、下校する', 'pulang sekolah', 'tan học', 'เลิกเรียน', 'заканчивать занятия', 'terminar las clases', 'terminar a aula'],
  ['分开','fēnkāi','verb','to separate','ayrılmak, ayırmak', '나누다, 헤어지다', '分かれる、分ける', 'memisahkan, berpisah', 'chia tách, chia tay', 'แยกจากกัน', 'разделять/разделить, расставаться/расстаться', 'separar, separarse', 'separar, separar-se'],
  ['风','fēng','noun','wind','rüzgar', '바람', '風', 'angin', 'gió', 'ลม', 'ветер', 'el viento', 'o vento'],
  ['封','fēng','classifier','measure word for letters; (to seal)','mektup sayı sözcüğü; (mühürlemek)', '통(편지 봉투), 봉하다', '（手紙などを数える）通', 'kata penggolong untuk surat', 'lượng từ (thư từ), niêm phong', 'ฉบับ (ลักษณนามของจดหมาย), ผนึก', 'счётное слово для писем', 'clasificador para cartas', 'classificador para cartas'],
  ['夫妻','fūqī','noun','husband and wife','karı koca', '부부', '夫婦', 'suami istri', 'vợ chồng', 'สามีภรรยา', 'супруги', 'el matrimonio, los esposos', 'o casal'],
  ['服务','fúwù','verb','to serve','hizmet etmek', '서비스하다, 봉사하다', 'サービスする、奉仕する', 'melayani, layanan', 'phục vụ', 'บริการ', 'обслуживать, служить', 'servir, prestar servicio', 'servir, prestar serviço'],
  ['附近','fùjìn','noun','nearby','yakın çevrede', '부근, 근처', '付近、近く', 'sekitar, dekat', 'gần, khu vực lân cận', 'บริเวณใกล้เคียง, แถวนี้', 'окрестности, поблизости', 'la cercanía, los alrededores', 'a vizinhança, as redondezas'],
  ['复习','fùxí','verb','to review','tekrar etmek', '복습하다', '復習する', 'mengulang pelajaran', 'ôn tập', 'ทบทวน', 'повторять (пройденный материал)', 'repasar, revisar', 'revisar'],
  ['该','gāi','verb','should','-meli', '해야 한다', '〜すべきだ、当然〜だ', 'seharusnya, patut', 'nên, đáng', 'ควร, สมควร', 'следовать, должен', 'deber', 'dever'],
  ['干净','gānjìng','adjective','clean','temiz', '깨끗하다', 'きれいだ、清潔だ', 'bersih', 'sạch sẽ', 'สะอาด', 'чистый', 'limpio', 'limpo'],
  ['感兴趣','gǎn xìngqù','verb','to be interested in','ilgi duymak', '흥미를 느끼다', '興味がある', 'tertarik', 'có hứng thú', 'สนใจ', 'интересоваться', 'interesarse', 'interessar-se'],
  ['感到','gǎndào','verb','to feel','hissetmek', '느끼다', '感じる', 'merasa', 'cảm thấy', 'รู้สึก', 'чувствовать, ощущать', 'sentir, sentirse', 'sentir'],
  ['感冒','gǎnmào','noun','cold; to catch a cold','soğuk algınlığı; soğuk almak', '감기; 감기에 걸리다', '風邪、風邪をひく', 'pilek, masuk angin', 'cảm cúm, bị cảm', 'เป็นหวัด, โรคหวัด', 'простуда, простудиться', 'el resfriado, resfriarse', 'o resfriado, resfriar-se'],
  ['干','gān, gàn','verb','to do, to work','yapmak, çalışmak', '하다, 마르다', 'する、やる、乾いている', '1) mengerjakan, melakukan; 2) kering', 'làm, khô', 'ทำ, แห้ง', 'делать, работать; сухой', 'hacer, trabajar, seco', 'fazer, trabalhar, seco'],
  ['刚','gāng','adverb','just, just now','hemen, az önce', '막, 방금', 'たった今、ちょうど', 'baru saja', 'vừa, mới', 'เพิ่งจะ', 'только что', 'acabar de, recién', 'acabar de, recém'],
  ['刚才','gāngcái','noun','just now','az önce', '방금 전', 'さっき、先ほど', 'tadi', 'vừa nãy, lúc nãy', 'เมื่อสักครู่', 'только что', 'hace un momento', 'o momento anterior, agora mesmo'],
  ['刚刚','gānggāng','adverb','just now, a moment ago','az önce, biraz önce', '방금, للتو', 'たった今、ちょうど', 'baru saja', 'vừa mới, vừa nãy', 'เพิ่งจะ, เมื่อสักครู่', 'только что', 'hace un momento, recién', 'agora mesmo, há pouco'],
  ['高铁','gāotiě','noun','high-speed rail','hızlı tren', '고속철도', '高速鉄道', 'kereta cepat', 'tàu cao tốc', 'รถไฟความเร็วสูง', 'высокоскоростная железная дорога', 'el tren de alta velocidad', 'o trem de alta velocidade'],
  ['根据','gēnjù','preposition','according to; to base on; (basis)','-e göre; dayanmak; (temel)', '~에 의하면, ~을 근거로', '〜に基づいて、根拠', 'berdasarkan, dasar', 'căn cứ, dựa theo', 'ตามที่, อ้างอิงจาก, พื้นฐาน', 'согласно, на основании, основание', 'según, basarse en', 'conforme, basear-se em'],
  ['更','gèng, gēng','adverb','more','daha', '더, 더욱', 'さらに、もっと', 'lebih', 'hơn, càng', 'ยิ่งขึ้น, กว่า', 'ещё более, больше', 'más', 'mais'],
  ['公斤','gōngjīn','classifier','kilogram','kilogram', '킬로그램', 'キログラム', 'kilogram', 'ki-lô-gam', 'กิโลกรัม', 'килограмм', 'el kilogramo', 'o quilograma'],
  ['公园','gōngyuán','noun','park','park', '공원', '公園', 'taman', 'công viên', 'สวนสาธารณะ', 'парк', 'el parque', 'o parque'],
  ['工作日','gōngzuòrì','noun','workday','iş günü', '평일', '平日、勤務日', 'hari kerja', 'ngày làm việc', 'วันทำงาน', 'рабочий день', 'el día laborable', 'o dia útil'],
  ['故事','gùshi','noun','story','hikaye', '이야기, 옛날 이야기', '物語、昔話', 'cerita, kisah', 'câu chuyện, truyện', 'เรื่องราว, นิทาน', 'история, рассказ', 'el cuento, la historia', 'a história'],
  ['刮','guā','verb','to scrape, to blow','kazımak, esmek', '긁다, 불다', 'こする、削る、（風が）吹く', 'mengikis, bertiup', 'cạo, thổi', 'ขูด, พัด', 'скрести, дуть (о ветре)', 'raspar, soplar', 'raspar, soprar'],
  ['关','guān','verb','to close, to turn off; pass','kapatmak; geçit', '닫다, 끄다; 관문', '閉める、切る、関所', 'menutup, mematikan', 'đóng, tắt', 'ปิด, ด่าน', 'закрывать, выключать', 'cerrar, apagar', 'fechar, desligar'],
  ['关机','guānjī','verb','to turn off device','cihazı kapatmak', '기기를 끄다', '電源を切る', 'mematikan perangkat', 'tắt máy', 'ปิดเครื่อง', 'выключать устройство', 'apagar (un dispositivo)', 'desligar o aparelho'],
  ['关系','guānxì','noun','relationship; (to relate)','ilişki; (ilgili olmak)', '관계; 관련되다', '関係', 'hubungan, kaitan', 'quan hệ', 'ความสัมพันธ์, เกี่ยวข้อง', 'отношение, связь', 'la relación, el vínculo', 'o relacionamento, a relação'],
  ['关心','guānxīn','verb','to care about, to be concerned','önemsemek, ilgilenmek', '관심을 가지다, 걱정하다', '関心を持つ、気にかける', 'peduli, memperhatikan', 'quan tâm', 'ห่วงใย, ใส่ใจ', 'заботиться, проявлять интерес', 'preocuparse por, interesarse por', 'preocupar-se, interessar-se'],
  ['关于','guānyú','preposition','about, regarding','hakkında', '~에 관하여, ~에 대하여', '〜について', 'tentang, mengenai', 'về, đối với', 'เกี่ยวกับ', 'о, относительно, касательно', 'sobre, acerca de', 'sobre, a respeito de'],
  ['关注','guānzhù','verb','to pay attention to, to follow','ilgi göstermek, takip etmek', '주목하다, 관심을 기울이다', '注目する、関心を寄せる', 'memperhatikan, mengikuti', 'chú ý, quan tâm', 'ติดตาม, ให้ความสนใจ', 'следить, уделять внимание', 'prestar atención, seguir', 'prestar atenção, acompanhar'],
  ['国家','guójiā','noun','country','ülke', '국가, 나라', '国、国家', 'negara', 'quốc gia, đất nước', 'ประเทศ', 'страна, государство', 'el país', 'o país'],
  ['过节','guòjié','verb','to celebrate a festival','bayram kutlamak', '명절을 쇠다', '祭日を祝う', 'merayakan hari raya', 'ăn tết, đón lễ', 'ฉลองเทศกาล', 'праздновать, отмечать праздник', 'celebrar una festividad', 'celebrar um feriado'],
  ['海','hǎi','noun','sea','deniz', '바다', '海', 'laut', 'biển', 'ทะเล', 'море', 'el mar', 'o mar'],
  ['害怕','hàipà','verb','to be afraid','korkmak', '두려워하다', '怖がる', 'takut', 'sợ hãi, lo sợ', 'กลัว', 'бояться, пугаться', 'temer, tener miedo', 'ter medo, recear'],
  ['好多','hǎoduō','adjective','many, a lot','çok, bir sürü', '많음', 'たくさん、多くの', 'banyak', 'nhiều', 'มากมาย', 'много', 'mucho, muchos', 'muito, bastante'],
  ['好久','hǎojiǔ','adjective','a long time','uzun zaman', '오랫동안', '長い間、久しい', 'lama', 'lâu, rất lâu', 'นาน', 'долгое время', 'mucho tiempo', 'muito tempo'],
  ['好像','hǎoxiàng','adverb','to seem, as if; perhaps','gibi görünmek; belki', '마치 ~인 듯하다, ~인 것 같다; 아마', '〜のようだ、〜らしい', 'sepertinya, tampaknya', 'dường như, hình như', 'ดูเหมือนว่า, คล้ายกับ', 'казаться, по-видимому', 'parecer, al parecer, como si', 'parecer, como se'],
  ['号码','hàomǎ','noun','number, code','numara, kod', '번호, 코드', '番号', 'nomor', 'số, mã số', 'หมายเลข, เบอร์', 'номер', 'el número', 'o número'],
  ['河','hé','noun','river','nehir', '강', '川', 'sungai', 'sông', 'แม่น้ำ', 'река', 'el río', 'o rio'],
  ['合适','héshì','adjective','suitable','uygun', '적합하다, 알맞다', '適当だ、ふさわしい', 'cocok, sesuai', 'thích hợp, phù hợp', 'เหมาะสม, พอดี', 'подходящий, соответствующий', 'adecuado, apropiado', 'adequado, apropriado'],
  ['黑板','hēibǎn','noun','blackboard','kara tahta', '칠판', '黒板', 'papan tulis', 'bảng đen', 'กระดานดำ', 'классная доска', 'la pizarra', 'o quadro-negro'],
  ['红绿灯','hónglǜdēng','noun','traffic light','trafik ışığı', '신호등', '信号機', 'lampu lalu lintas', 'đèn giao thông', 'สัญญาณไฟจราจร', 'светофор', 'el semáforo', 'o semáforo'],
  ['后来','hòulái','noun','later, afterwards','sonradan', '나중에, 이후에', 'その後、あとで', 'kemudian, setelah itu', 'sau này, về sau', 'ภายหลัง, ต่อมา', 'потом, впоследствии', 'después, más tarde', 'mais tarde, posteriormente'],
  ['后年','hòunián','noun','the year after next','öbür yıl', '내후년', '再来年', 'dua tahun lagi', 'năm kia', 'ปีมะรืน', 'послеследующий год', 'el año después del próximo', 'depois de dois anos'],
  ['后天','hòutiān','noun','the day after tomorrow','öbür gün', '모레', '明後日', 'lusa', 'ngày kia', 'มะรืนนี้', 'послезавтра', 'pasado mañana', 'depois de amanhã'],
  ['护照','hùzhào','noun','passport','pasaport', '여권', 'パスポート', 'paspor', 'hộ chiếu', 'หนังสือเดินทาง', 'паспорт', 'el pasaporte', 'o passaporte'],
  ['花园','huāyuán','noun','garden','bahçe', '화원, 정원', '庭、庭園', 'taman', 'vườn hoa', 'สวนดอกไม้', 'сад', 'el jardín', 'o jardim'],
  ['画家','huàjiā','noun','painter, artist','ressam, sanatçı', '화가', '画家', 'pelukis', 'họa sĩ', 'จิตรกร, ศิลปินวาดภาพ', 'художник', 'el pintor, el artista', 'o pintor, o artista'],
  ['欢迎','huānyíng','verb','to welcome','karşılamak', '환영하다, 맞이하다', '歓迎する', 'menyambut, selamat datang', 'hoan nghênh, chào mừng', 'ยินดีต้อนรับ', 'приветствовать, добро пожаловать', 'dar la bienvenida, recibir', 'dar as boas-vindas'],
  ['还','hái, huán','verb','to return, to give back','geri vermek', '아직, 또한, 오히려', 'まだ、さらに、その上', 'masih, juga', 'vẫn, còn, hơn nữa', 'ยัง, อีก, นอกจากนี้', 'ещё, также', 'todavía, aún, además', 'ainda, também'],
  ['环境','huánjìng','noun','environment','çevre, ortam', '환경', '環境', 'lingkungan', 'môi trường', 'สภาพแวดล้อม', 'окружающая среда, обстановка', 'el medio ambiente, el entorno', 'o ambiente'],
  ['换','huàn','verb','to exchange, to change','değiştirmek', '갈다, 바꾸다', '交換する、替える', 'menukar, mengganti', 'đổi, thay đổi', 'เปลี่ยน, แลกเปลี่ยน', 'менять, обменивать', 'cambiar, intercambiar', 'trocar, mudar'],
  ['黄色','huángsè','noun','yellow','sarı', '노란색', '黄色', 'kuning', 'màu vàng', 'สีเหลือง', 'жёлтый цвет', 'el amarillo', 'o amarelo'],
  ['回答','huídá','verb','to answer','cevap vermek', '대답하다', '答える、回答する', 'menjawab', 'trả lời, đáp lại', 'ตอบ', 'отвечать/ответить', 'responder, contestar', 'responder'],
  ['会','huì, kuài','noun','meeting','toplantı', '할 줄 알다, ~할 것이다', 'できる、〜するはずだ', 'dapat, bisa', 'biết, có thể', 'เป็น, สามารถ, จะ', 'уметь, мочь, быть в состоянии', 'saber, poder, ser capaz de', 'saber, conseguir, poder'],
  ['会议','huìyì','noun','meeting','toplantı', '회의', '会議', 'rapat, pertemuan', 'hội nghị, cuộc họp', 'การประชุม', 'собрание, совещание', 'la reunión, la conferencia', 'a reunião'],
  ['或','huò','conjunction','or; (perhaps, maybe)','ya da; (belki)', '혹은, 또는; 아마', 'あるいは、または', 'atau', 'hoặc, có lẽ', 'หรือ', 'или', 'o', 'ou'],
  ['或者','huòzhě','conjunction','or','ya da', '혹은, 또는', 'あるいは、または', 'atau', 'hoặc, hoặc là', 'หรือ, หรือไม่ก็', 'или', 'o', 'ou'],
  ['鸡','jī','noun','chicken','tavuk', '닭', '鶏', 'ayam', 'gà', 'ไก่', 'курица', 'el pollo', 'a galinha, o frango'],
  ['几乎','jīhū','adverb','almost','neredeyse', '거의', 'ほとんど、あやうく', 'hampir', 'gần như, suýt nữa', 'เกือบจะ', 'почти, едва не', 'casi', 'quase'],
  ['机会','jīhuì','noun','opportunity','fırsat', '기회', '機会、チャンス', 'kesempatan, peluang', 'cơ hội', 'โอกาส', 'возможность, шанс', 'la oportunidad', 'a oportunidade'],
  ['极','jí','adverb','extremely','son derece', '매우, 아주', '極めて、非常に', 'sangat, sekali', 'cực kỳ, rất', 'อย่างยิ่ง, ที่สุด', 'чрезвычайно, крайне', 'extremadamente', 'extremamente'],
  ['急','jí','adjective','urgent; (to worry)','acil; (endişelenmek)', '급하다, 초조하다', '急ぐ、焦る、差し迫った', 'mendesak, cemas, terburu-buru', 'gấp, vội vàng, lo lắng', 'รีบ, ร้อนใจ, ด่วน', 'срочный, беспокоиться', 'urgente, impaciente', 'urgente, impaciente'],
  ['记','jì','verb','to remember','hatırlamak', '기억하다, 기록하다', '覚える、記録する', 'mengingat, mencatat', 'ghi nhớ, ghi chép', 'จำ, จด', 'помнить, записывать', 'recordar, anotar', 'lembrar, memorizar, anotar'],
  ['季','jì','noun','season','mevsim', '계절', '季節', 'musim', 'mùa', 'ฤดู', 'сезон, время года', 'la estación', 'a estação'],
  ['季节','jìjié','noun','season','mevsim', '계절', '季節', 'musim', 'mùa, thời tiết', 'ฤดูกาล', 'сезон, время года', 'la estación', 'a estação'],
  ['加','jiā','verb','to add','eklemek', '더하다, 보태다', '加える、足す', 'menambah', 'thêm, cộng', 'บวก, เพิ่ม', 'добавлять/добавить, прибавлять/прибавить', 'añadir, sumar', 'adicionar, somar'],
  ['假期','jiàqī','noun','vacation','tatil', '휴가, 방학', '休暇、休日', 'masa liburan', 'kỳ nghỉ', 'วันหยุด, ช่วงปิดเทอม', 'каникулы, отпуск', 'las vacaciones', 'as férias'],
  ['坚持','jiānchí','verb','to persist','ısrar etmek, devam etmek', '고집하다, 견지하다', '堅持する、やり抜く', 'bertahan, bersikeras', 'kiên trì, giữ vững', 'ยืนหยัด, ยืนกราน', 'настаивать, упорствовать', 'persistir, insistir', 'persistir, insistir'],
  ['检查','jiǎnchá','verb','to check, to inspect','kontrol etmek, incelemek', '검사하다, 점검하다', '検査する、点検する', 'memeriksa, menginspeksi', 'kiểm tra', 'ตรวจสอบ, ตรวจตรา', 'проверять, осматривать', 'inspeccionar, examinar, revisar', 'inspecionar, examinar'],
  ['简单','jiǎndān','adjective','simple','basit', '간단하다, 단순하다', '簡単だ、単純だ', 'sederhana, simpel', 'đơn giản', 'ง่าย, เรียบง่าย', 'простой, несложный', 'simple, sencillo', 'simples'],
  ['检票','jiǎnpiào','verb','ticket checking','bilet kontrol etmek', '표를 검사하다', '改札する', 'memeriksa tiket', 'kiểm soát vé', 'ตรวจตั๋ว', 'проверять билеты', 'revisar los billetes', 'verificar bilhetes'],
  ['健康','jiànkāng','adjective','healthy','sağlıklı', '건강하다', '健康だ', 'sehat', 'khỏe mạnh', 'สุขภาพดี, แข็งแรง', 'здоровый', 'saludable, sano', 'saudável'],
  ['见面','jiànmiàn','verb','to meet','buluşmak', '만나다', '会う、面会する', 'bertemu', 'gặp mặt', 'พบหน้า, พบปะ', 'встречаться', 'reunirse, encontrarse', 'encontrar-se'],
  ['讲','jiǎng','verb','to speak, to talk','konuşmak, anlatmak', '말하다, 이야기하다', '話す、説明する', 'berbicara, menceritakan', 'nói, giảng giải', 'พูด, บรรยาย, อธิบาย', 'говорить, рассказывать', 'hablar, explicar', 'falar, contar, explicar'],
  ['角','jiǎo','classifier','measure word for fractions, angle, currency','para, açı sayı sözcüğü', '각도; (화폐 단위) 각, 센트', '（通貨単位の）角、隅、角', 'sudut, satuan mata uang', 'đơn vị tiền tệ (hào), góc', 'มุม, หน่วยเงินจีน (1 ใน 10 ของหยวน)', 'цзяо (денежная единица), угол', 'clasificador para fracciones, ángulo, unidad monetaria', 'classificador para frações, ângulo, unidade monetária'],
  ['脚','jiǎo','noun','foot','ayak', '발', '足（足首から先）', 'kaki', 'bàn chân', 'เท้า', 'стопа, нога', 'el pie', 'o pé'],
  ['接','jiē','verb','to pick up, to receive','karşılamak, almak', '받다, 맞이하다', '受け取る、迎えに行く', 'menjemput, menerima', 'đón, tiếp nhận', 'รับ, ไปรับ', 'встречать, принимать', 'recibir, recoger', 'receber, buscar'],
  ['街','jiē','noun','street','cadde, sokak', '거리', '通り、街路', 'jalan', 'phố, đường', 'ถนน', 'улица', 'la calle', 'a rua'],
  ['节','jié','classifier','measure word for segments, lessons; festival','bölüm, ders sayı sözcüğü; festival', '마디, 절, 단락; 명절', '（授業などの）コマ、節、祝日', 'ruas, bab, festival', 'đơn vị đo đoạn/tiết học, ngày lễ', 'ข้อ, บท, เทศกาล', 'счётное слово для уроков или отрезков; праздник', 'clasificador para segmentos o lecciones, festividad', 'classificador para seções ou aulas, feriado'],
  ['结婚','jiéhūn','verb','to marry','evlenmek', '결혼하다', '結婚する', 'menikah', 'kết hôn', 'แต่งงาน', 'вступать в брак, жениться', 'casarse', 'casar-se'],
  ['节目','jiémù','noun','program','program', '프로그램, 종목', '番組、演目', 'program, acara', 'chương trình', 'รายการ', 'программа, номер', 'el programa', 'o programa'],
  ['节日','jiérì','noun','festival','festival, bayram', '명절, 축제', '祝日、祭日', 'hari raya, perayaan', 'ngày lễ, lễ hội', 'เทศกาล, วันหยุดนักขัตฤกษ์', 'праздник', 'la festividad, el día festivo', 'o feriado, a festividade'],
  ['结束','jiéshù','verb','to end','bitmek, sona ermek', '끝나다, 마치다', '終わる、終える', 'berakhir, menyelesaikan', 'kết thúc', 'จบ, สิ้นสุด', 'заканчивать, завершать', 'terminar, finalizar', 'terminar, encerrar'],
  ['解决','jiějué','verb','to solve','çözmek', '해결하다', '解決する', 'menyelesaikan, memecahkan', 'giải quyết', 'แก้ไข, จัดการ', 'решать, разрешать (проблему)', 'resolver, solucionar', 'resolver, solucionar'],
  ['姐妹','jiěmèi','noun','sister','kız kardeş', '자매', '姉妹', 'saudara perempuan', 'chị em', 'พี่น้องหญิง', 'сестры', 'la hermana', 'a irmã'],
  ['借','jiè','verb','to borrow','ödünç almak', '빌리다', '借りる、貸す', 'meminjam, meminjamkan', 'mượn, vay', 'ยืม, ให้ยืม', 'занимать, одалживать', 'pedir prestado, prestar', 'pegar emprestado, emprestar'],
  ['斤','jīn','classifier','catty (500g)','jin (500g ağırlık birimi)', '근 (무게 단위)', '斤（重さの単位、500グラム）', 'kati (satuan berat 500 gram)', 'cân (đơn vị đo lường, 500g)', 'ชั่ง (หน่วยวัดน้ำหนักเท่ากับ 500 กรัม)', 'цзинь (мера веса, 500 г)', 'el jin (unidad de peso equivalente a 500 gramos)', 'classificador para peso (500g)'],
  ['经过','jīngguò','verb','to pass; process','geçmek; süreç', '지나가다; 거치다', '通る、経過する、過程', 'melewati, melalui, proses', 'đi qua, trải qua, quá trình', 'ผ่าน, กระบวนการ', 'проходить через; процесс', 'pasar, el proceso', 'passar, o processo'],
  ['经理','jīnglǐ','noun','manager','müdür', '지배인, 매니저', 'マネージャー、支配人', 'manajer', 'giám đốc, quản lý', 'ผู้จัดการ', 'менеджер, управляющий', 'el gerente, el director', 'o gerente'],
  ['久','jiǔ','adjective','long (time)','uzun (süre)', '오랜 (시간)', '長い（時間）', 'lama', 'lâu', 'นาน', 'долгий, длительный', 'largo (tiempo)', 'longo'],
  ['酒','jiǔ','noun','alcohol','alkol, içki', '술', '酒', 'minuman keras, alkohol', 'rượu', 'เหล้า, เครื่องดื่มแอลกอฮอล์', 'алкоголь, спиртное', 'el alcohol, la bebida alcohólica', 'a bebida alcoólica'],
  ['旧','jiù','adjective','old','eski', '낡다, 오래되다', '古い、旧式の', 'lama, bekas', 'cũ', 'เก่า', 'старый, подержанный', 'viejo, usado', 'velho, usado'],
  ['句','jù','classifier','measure word of sentence','cümle sayı sözcüğü', '~구 (단위)', '（文を数える）文', 'kata penggolong untuk kalimat', 'câu (lượng từ)', 'ประโยค (ลักษณนาม)', 'счётное слово для предложений', 'clasificador para oraciones', 'classificador para frases'],
  ['句子','jùzi','noun','sentence','cümle', '문장', '文', 'kalimat', 'câu', 'ประโยค', 'предложение', 'la oración, la frase', 'a frase'],
  ['决定','juédìng','verb','to decide; decision','karar vermek; karar', '결정하다, 결정', '決める、決定', 'memutuskan, keputusan', 'quyết định', 'ตัดสินใจ, การตัดสินใจ', 'решать/решить, решение', 'decidir, la decisión', 'decidir, a decisão'],
  ['卡','kǎ','noun','card','kart', '카드', 'カード', 'kartu', 'thẻ', 'บัตร', 'карточка', 'la tarjeta', 'o cartão'],
  ['开花','kāihuā','verb','to bloom','çiçek açmak', '꽃이 피다', '花が咲く', 'berbunga', 'nở hoa', 'ออกดอก, บาน', 'цвести, расцветать', 'florecer', 'florescer'],
  ['开会','kāihuì','verb','to have a meeting','toplantı yapmak', '회의하다', '会議をする', 'rapat, mengadakan rapat', 'họp, mở cuộc họp', 'ประชุม', 'проводить собрание, заседать', 'reunirse, tener una reunión', 'reunir-se'],
  ['开机','kāijī','verb','to turn on device','cihazı açmak', '기기를 켜다', '電源を入れる', 'menyalakan perangkat', 'mở máy, khởi động máy', 'เปิดเครื่อง', 'включать устройство', 'encender un dispositivo', 'ligar o aparelho'],
  ['开心','kāixīn','adjective','happy','mutlu, neşeli', '기쁘다', '楽しい、うれしい', 'senang, bahagia', 'vui vẻ', 'ดีใจ, มีความสุข', 'весёлый, радостный', 'feliz, alegre', 'feliz, alegre'],
  ['看来','kànlái','verb','it seems, it appears','görünüşe göre', '보아하니, ~인 것 같다', '〜のようだ、〜と見える', 'tampaknya, kelihatannya', 'xem ra, có vẻ như', 'ดูเหมือนว่า', 'по-видимому, кажется', 'parecer', 'parecer'],
  ['可','kě','conjunction','but; (yet)','ama; (henüz)', '그러나; (결과를 나타냄)', 'しかし、だが', 'tetapi', 'nhưng, mà', 'แต่, ทว่า', 'но, однако', 'pero, sin embargo', 'mas, porém'],
  ['渴','kě','adjective','thirsty','susamış', '목마르다', '喉が渇く', 'haus', 'khát', 'หิวน้ำ', 'испытывающий жажду', 'sediento', 'sedento'],
  ['可爱','kě\'ài','adjective','lovely','sevimli', '귀엽다', 'かわいい', 'lucu, menggemaskan', 'đáng yêu, dễ thương', 'น่ารัก', 'милый, прелестный', 'encantador, adorable', 'adorável, gracioso'],
  ['可是','kěshì','conjunction','but','ama, fakat', '그러나', 'しかし、だが', 'tetapi', 'nhưng, nhưng mà', 'แต่, ทว่า', 'но, однако', 'pero, sin embargo', 'mas, porém'],
  ['刻','kè','classifier','quarter; to carve','çeyrek saat; (oymak)', '1/4시간, 새기다', '15分、刻む', 'seperempat jam, mengukir', 'khắc, khắc (15 phút)', 'หนึ่งในสี่ของชั่วโมง, แกะสลัก', 'четверть часа', 'el cuarto de hora, grabar', 'o quarto de hora, esculpir'],
  ['课本','kèběn','noun','textbook','ders kitabı', '교과서', '教科書', 'buku teks', 'sách giáo khoa', 'หนังสือเรียน', 'учебник', 'el libro de texto', 'o livro didático'],
  ['客人','kèrén','noun','guest','misafir', '손님', '客', 'tamu', 'khách', 'แขก, ผู้มาเยือน', 'гость', 'el invitado, el huésped', 'o convidado, o hóspede'],
  ['课文','kèwén','noun','text','metin, okuma parçası', '교과서 본문', '本文、テキスト', 'teks pelajaran', 'bài khóa', 'บทเรียน', 'текст (учебный)', 'el texto', 'o texto'],
  ['空调','kōngtiáo','noun','air conditioner','klima', '에어컨', 'エアコン', 'penyejuk udara', 'máy điều hòa', 'เครื่องปรับอากาศ', 'кондиционер', 'el aire acondicionado', 'o ar-condicionado'],
  ['哭','kū','verb','to cry','ağlamak', '울다', '泣く', 'menangis', 'khóc', 'ร้องไห้', 'плакать', 'llorar', 'chorar'],
  ['筷子','kuàizi','noun','chopsticks','yemek çubukları', '젓가락', '箸', 'sumpit', 'đũa', 'ตะเกียบ', 'палочки для еды', 'los palillos', 'o hashi'],
  ['矿泉水','kuàngquánshuǐ','noun','mineral water','maden suyu', '광천수, 생수', 'ミネラルウォーター', 'air mineral', 'nước khoáng', 'น้ำแร่', 'минеральная вода', 'el agua mineral', 'a água mineral'],
  ['来自','láizì','verb','to come from','-den gelmek', '출신이다, ~에서 오다', '〜から来る、〜出身である', 'berasal dari', 'đến từ', 'มาจาก', 'происходить из, быть родом из', 'provenir de, venir de', 'vir de, ser originário de'],
  ['蓝','lán','adjective','blue','mavi', '파란색의', '青い', 'biru', 'xanh lam', 'สีฟ้า, สีน้ำเงิน', 'синий, голубой', 'azul', 'azul'],
  ['老','lǎo','adjective','old, aged; (always, constantly)','yaşlı; (her zaman)', '늙은, 오래된; 늘, 항상', '年をとった、老いた、いつも', 'tua, lama, selalu', 'già, cũ, luôn luôn', 'แก่, เก่า, ตลอดเวลา', 'старый, пожилой', 'viejo, antiguo', 'velho, antigo'],
  ['老人','lǎorén','noun','elderly person','yaşlı kişi', '노인', '老人、高齢者', 'orang tua, lansia', 'người già, người cao tuổi', 'คนชรา, ผู้สูงอายุ', 'пожилой человек, старик', 'el anciano, la persona mayor', 'o idoso'],
  ['离开','líkāi','verb','to leave','ayrılmak', '떠나다, 벗어나다', '離れる、去る', 'pergi, meninggalkan', 'rời khỏi', 'จากไป, ออกจาก', 'уходить, покидать', 'partir, salir', 'partir, sair'],
  ['礼物','lǐwù','noun','gift','hediye', '선물', '贈り物、プレゼント', 'hadiah, kado', 'quà tặng', 'ของขวัญ', 'подарок', 'el regalo', 'o presente'],
  ['历史','lìshǐ','noun','history','tarih', '역사', '歴史', 'sejarah', 'lịch sử', 'ประวัติศาสตร์', 'история', 'la historia', 'a história'],
  ['脸','liǎn','noun','face','yüz', '얼굴', '顔', 'wajah, muka', 'khuôn mặt', 'ใบหน้า', 'лицо', 'la cara', 'o rosto'],
  ['练','liàn','verb','to practice','alıştırma yapmak', '연습하다', '練習する、鍛える', 'berlatih', 'luyện, tập', 'ฝึก, ฝึกฝน', 'тренироваться, упражняться', 'practicar', 'praticar'],
  ['练习','liànxí','verb','to practice; exercise','alıştırma yapmak; alıştırma', '연습하다; 연습 문제', '練習する、練習', 'berlatih, latihan', 'luyện tập, bài tập', 'ฝึกฝน, แบบฝึกหัด', 'упражняться, тренироваться; упражнение', 'practicar, el ejercicio', 'praticar, o exercício'],
  ['凉快','liángkuai','adjective','cool','serin, ferah', '시원하다', '涼しい', 'sejuk', 'mát mẻ', 'เย็นสบาย', 'прохладный', 'fresco', 'fresco'],
  ['辆','liàng','classifier','measure word for vehicles','araç sayı sözcüğü', '~량 (탈것 수사)', '（車両を数える助数詞）', 'kata penggolong untuk kendaraan', 'chiếc (lượng từ cho xe cộ)', 'คัน (ลักษณนามสำหรับยานพาหนะ)', 'счетное слово для транспортных средств', 'clasificador para vehículos', 'classificador para veículos'],
  ['聊','liáo','verb','to chat','sohbet etmek', '이야기하다, 담소를 나누다', 'おしゃべりする、雑談する', 'mengobrol', 'trò chuyện, tán gẫu', 'คุย, สนทนา', 'болтать, беседовать', 'charlar, conversar', 'conversar'],
  ['聊天儿','liáotiānr','verb','to chat','sohbet etmek', '이야기하다, 담소를 나누다', 'おしゃべりする、雑談する', 'mengobrol', 'trò chuyện, tán gẫu', 'คุยเล่น, สนทนา', 'болтать, беседовать', 'charlar, conversar', 'conversar, bater papo'],
  ['了解','liǎojiě','verb','to understand','anlamak, bilmek', '이해하다, 알다', '理解する、把握する', 'memahami, mengerti', 'hiểu, hiểu rõ', 'เข้าใจ', 'понимать/понять, узнавать/узнать', 'comprender, entender', 'entender, compreender'],
  ['邻居','línjū','noun','neighbor','komşu', '이웃', '隣人、近所の人', 'tetangga', 'hàng xóm', 'เพื่อนบ้าน', 'сосед', 'el vecino', 'o vizinho'],
  ['留学','liúxué','verb','to study abroad','yurt dışında okumak', '유학하다', '留学する', 'belajar di luar negeri', 'du học', 'เรียนต่อต่างประเทศ', 'учиться за границей', 'estudiar en el extranjero', 'estudar no exterior'],
  ['留学生','liúxuéshēng','noun','overseas student','yurt dışı öğrencisi', '유학생', '留学生', 'pelajar asing', 'du học sinh', 'นักเรียนต่างชาติ', 'студент-иностранец', 'el estudiante extranjero', 'o estudante estrangeiro'],
  ['楼梯','lóutī','noun','stairs','merdiven', '계단', '階段', 'tangga', 'cầu thang', 'บันได', 'лестница', 'la escalera', 'a escada'],
  ['路边','lùbiān','noun','roadside','yol kenarı', '길가', '道端', 'tepi jalan', 'ven đường, lề đường', 'ริมถนน', 'обочина, край дороги', 'la orilla del camino, el borde de la carretera', 'a beira da estrada, o acostamento'],
  ['路口','lùkǒu','noun','intersection','kavşak', '교차로', '交差点', 'persimpangan jalan', 'ngã ba, ngã tư, giao lộ', 'ทางแยก', 'перекресток', 'el cruce, la intersección', 'o cruzamento, a esquina'],
  ['马','mǎ','noun','horse','at', '말', '馬', 'kuda', 'ngựa', 'ม้า', 'лошадь', 'el caballo', 'o cavalo'],
  ['马路','mǎlù','noun','road','yol, cadde', '길, 도로', '道路、車道', 'jalan raya', 'đường cái, đường phố', 'ถนน', 'дорога, улица', 'la carretera, la calle', 'a rua, a estrada'],
  ['马上','mǎshàng','adverb','immediately','hemen', '곧, 즉시', 'すぐに、直ちに', 'segera, langsung', 'ngay lập tức', 'ทันที, เดี๋ยวนี้', 'сейчас же, немедленно', 'inmediatamente', 'imediatamente, logo'],
  ['满意','mǎnyì','verb','satisfied','memnun olmak', '만족하다', '満足する', 'puas', 'hài lòng, mãn nguyện', 'พอใจ', 'быть довольным, удовлетворенный', 'estar satisfecho', 'estar satisfeito'],
  ['毛','máo','classifier','measure word for money (0.1 yuan); (hair)','para sayı sözcüğü; (kıl, tüy)', '털, (화폐 단위) 모', '毛、10分の1元', 'satuan mata uang (sepersepuluh yuan), bulu', 'hào (đơn vị tiền tệ, 0.1 tệ)', 'เหมา (หน่วยเงินจีนเท่ากับ 1/10 หยวน), ขน', 'мао (денежная единица, 1/10 юаня)', 'el mao (unidad monetaria equivalente a 0,1 yuan)', 'classificador para moeda (0,1 yuan)'],
  ['米','mǐ','classifier','meter','metre', '미터', 'メートル', 'meter', 'mét', 'เมตร', 'метр', 'el metro', 'o metro'],
  ['面前','miànqián','noun','in front of','önünde', '~의 면전, ~ 앞', '目の前', 'di depan', 'trước mặt', 'ต่อหน้า, ข้างหน้า', 'перед, в присутствии', 'la parte delantera, la presencia', 'a frente, a presença'],
  ['明白','míngbai','adjective','to understand; clear','anlamak; açık', '분명하다, 이해하다', 'わかる、はっきりしている', 'paham, jelas', 'hiểu, rõ ràng', 'เข้าใจ, ชัดเจน', 'понимать, ясный, понятный', 'claro, comprensible', 'claro, compreensível'],
  ['名单','míngdān','noun','name list','isim listesi', '명단', '名簿', 'daftar nama', 'danh sách', 'รายชื่อ', 'список имён', 'la lista de nombres', 'a lista de nomes'],
  ['名人','míngrén','noun','famous person','ünlü kişi', '유명인', '有名人', 'orang terkenal', 'người nổi tiếng', 'คนดัง, ผู้มีชื่อเสียง', 'знаменитость, известный человек', 'la persona famosa, el personaje célebre', 'a celebridade, a pessoa famosa'],
  ['南','nán','noun','south','güney', '남쪽', '南', 'selatan', 'phía nam', 'ทิศใต้', 'юг', 'el sur', 'o sul'],
  ['难','nán, nàn','adjective','difficult; (to make difficult)','zor; (zorlaştırmak)', '어렵다, 힘들다', '難しい、困難だ', 'sulit, sukar', 'khó', 'ยาก, ลำบาก', 'трудный, сложный', 'difícil', 'difícil'],
  ['南方','nánfāng','noun','south','güney', '남방', '南方、南の方', 'selatan', 'phương nam', 'ทางใต้', 'юг', 'el sur', 'o sul'],
  ['难过','nánguò','adjective','sad','üzgün', '슬프다, 괴롭다', '悲しい、つらい', 'sedih, susah hati', 'buồn bã, đau lòng', 'เสียใจ, เศร้าโศก', 'грустный, огорчённый', 'triste, apenado', 'triste, infeliz'],
  ['难看','nánkàn','adjective','ugly','çirkin', '보기 싫다, 추하다, 못생기다', '見苦しい、醜い', 'jelek, buruk rupa', 'xấu xí, khó coi', 'น่าเกลียด, ดูไม่ดี', 'некрасивый, уродливый', 'feo', 'feio'],
  ['男人','nánrén','noun','man','adam, erkek', '남자', '男、男性', 'pria', 'đàn ông', 'ผู้ชาย', 'мужчина', 'el hombre', 'o homem'],
  ['男生','nánshēng','noun','boy student','erkek öğrenci', '남자아이, 남학생', '男子学生', 'siswa laki-laki', 'nam sinh', 'นักเรียนชาย', 'студент, школьник', 'el alumno, el estudiante', 'o estudante, o aluno'],
  ['难题','nántí','noun','difficult problem','zor problem', '어려운 문제, 난제', '難問、難題', 'masalah sulit', 'vấn đề khó, nan đề', 'ปัญหาที่ยาก, โจทย์ยาก', 'трудная задача, сложная проблема', 'el problema difícil', 'o problema difícil, o desafio'],
  ['难听','nántīng','adjective','unpleasant to hear','kulak tırmalayan', '듣기 싫다, 불쾌하다', '聞き苦しい、耳障りだ', 'sumbang, tidak enak didengar', 'khó nghe', 'ฟังไม่รื่นหู, ฟังไม่เพราะ', 'неприятный на слух, противный', 'desagradable al oído', 'desagradável ao ouvido'],
  ['年级','niánjí','noun','grade','sınıf (yıl bazlı)', '학년', '学年', 'tingkat, kelas', 'khối, lớp', 'ชั้นปี, ระดับชั้น', 'класс, курс', 'el curso, el grado', 'o ano escolar, a série'],
  ['年轻','niánqīng','adjective','young','genç', '젊다', '若い', 'muda', 'trẻ, trẻ tuổi', 'อายุน้อย, หนุ่มสาว', 'молодой', 'joven', 'jovem'],
  ['牛','niú','noun','cow; (awesome)','inek; (harika)', '소, (속어) 대단하다', '牛、すごい', 'sapi', 'bò', 'วัว', 'корова, бык', 'la vaca', 'o boi, a vaca'],
  ['努力','nǔlì','adjective','to work hard; hardworking','çok çalışmak; çalışkan', '노력하다, 노력하는', '努力する、一生懸命だ', 'rajin, berusaha keras', 'nỗ lực, cố gắng', 'พยายาม, ขยัน', 'старательный, усердно', 'esforzarse, trabajador', 'esforçado, esforçar-se'],
  ['女人','nǚrén','noun','woman','kadın', '여자', '女、女性', 'wanita, perempuan', 'phụ nữ, đàn bà', 'ผู้หญิง', 'женщина', 'la mujer', 'a mulher'],
  ['女生','nǚshēng','noun','girl student','kız öğrenci', '여자아이, 여학생', '女子学生', 'siswi, mahasiswi', 'nữ sinh', 'นักเรียนหญิง', 'студентка, ученица', 'la estudiante, la alumna', 'a estudante'],
  ['爬','pá','verb','to climb','tırmanmak', '기어가다, 오르다', '登る、這う', 'memanjat, merangkak', 'leo, bò', 'ปีน, คลาน', 'ползать, взбираться', 'trepar, escalar', 'subir, escalar'],
  ['怕','pà','verb','to fear; (perhaps)','korkmak; (belki)', '두려워하다, 걱정하다', '恐れる、怖い、ひょっとして', 'takut, khawatir', 'sợ, e rằng', 'กลัว, เกรงว่า', 'бояться, опасаться', 'temer, tener miedo', 'temer, recear'],
  ['拍照','pāizhào','verb','to take a photo','fotoğraf çekmek', '사진을 찍다', '写真を撮る', 'memotret, berfoto', 'chụp ảnh', 'ถ่ายรูป', 'фотографировать', 'fotografiar, sacar una foto', 'fotografar'],
  ['盘子','pánzi','noun','plate','tabak', '접시', '皿', 'piring', 'cái đĩa', 'จาน', 'тарелка', 'el plato', 'o prato'],
  ['胖','pàng','adjective','fat','şişman', '뚱뚱하다', '太っている', 'gemuk', 'béo, mập', 'อ้วน', 'толстый, полный', 'gordo', 'gordo'],
  ['啤酒','píjiǔ','noun','beer','bira', '맥주', 'ビール', 'bir', 'bia', 'เบียร์', 'пиво', 'la cerveza', 'a cerveja'],
  ['平时','píngshí','noun','usually','genellikle', '평소', '平素、普段', 'biasanya, hari-hari biasa', 'ngày thường, lúc bình thường', 'เวลาปกติ, ยามปกติ', 'обычное время, будни', 'el tiempo habitual, normalmente', 'o tempo habitual, o dia a dia'],
  ['瓶子','píngzi','noun','bottle','şişe', '병', '瓶', 'botol', 'cái chai', 'ขวด', 'бутылка', 'la botella', 'a garrafa'],
  ['骑','qí','verb','to ride','binmek (bisiklet/at)', '타다', '乗る（馬や自転車などに）', 'menunggang, mengendarai', 'cưỡi, đi (xe)', 'ขี่', 'ехать верхом, ехать на велосипеде', 'montar', 'montar, andar de'],
  ['奇怪','qíguài','adjective','strange','tuhaf, garip', '이상하다, 기묘하다', '奇妙だ、変だ', 'aneh, ganjil', 'kỳ lạ, lạ lùng', 'แปลก, ประหลาด', 'странный, удивительный', 'extraño, raro', 'estranho'],
  ['其实','qíshí','adverb','actually','aslında', '실은, 사실은', '実は、実際は', 'sebenarnya', 'thực ra', 'ที่จริงแล้ว, ความจริง', 'на самом деле, фактически', 'en realidad, de hecho', 'na verdade, na realidade'],
  ['其他','qítā','pronoun','other','diğerleri', '기타의, 다른', 'その他', 'lainnya', 'khác', 'อื่น ๆ', 'другой, остальной', 'otro', 'outro'],
  ['起','qǐ','verb','to rise, to get up; (measure word for events)','kalkmak; (olay sayı sözcüğü)', '일어나다, 발생하다; (사건) 횟수', '起きる、立ち上がる、（出来事の回数を数える）', 'bangun, bangkit', 'đứng dậy, khởi đầu', 'ลุกขึ้น, เริ่มต้น, ครั้ง (ลักษณนาม)', 'вставать, подниматься', 'levantarse, ascender', 'levantar-se, erguer-se, classificador para eventos'],
  ['起飞','qǐfēi','verb','to take off','havalanmak', '이륙하다', '離陸する', 'lepas landas', 'cất cánh', 'บินขึ้น, ออกเดินทาง', 'взлетать', 'despegar', 'decolar'],
  ['汽车','qìchē','noun','car','araba', '자동차', '自動車、車', 'mobil', 'ô tô, xe hơi', 'รถยนต์', 'автомобиль, машина', 'el coche, el automóvil', 'o carro'],
  ['铅笔','qiānbǐ','noun','pencil','kurşun kalem', '연필', '鉛筆', 'pensil', 'bút chì', 'ดินสอ', 'карандаш', 'el lápiz', 'o lápis'],
  ['前年','qiánnián','noun','the year before last','iki yıl önce', '재작년', '一昨年', 'dua tahun lalu', 'năm kia', 'ปีกลายก่อน', 'позапрошлый год', 'anteaño', 'anteontem (ano)'],
  ['前天','qiántiān','noun','the day before yesterday','önceki gün', '그저께', '一昨日', 'kemarin lusa', 'hôm kia', 'เมื่อวานซืน', 'позавчера', 'anteayer', 'anteontem'],
  ['清楚','qīngchu','adjective','clear, obvious; to understand','net, açık; anlamak', '분명하다, 명확하다, 분명히 알다', 'はっきりしている、明瞭だ、よくわかっている', 'jelas, paham', 'rõ ràng, hiểu rõ', 'ชัดเจน, เข้าใจ', 'ясный, отчетливый, понимать', 'claro, evidente, entender', 'claro, nítido, compreensível'],
  ['请假','qǐngjià','verb','to ask for leave','izin istemek', '휴가를 신청하다', '休暇を願い出る', 'meminta izin tidak masuk', 'xin nghỉ', 'ลาหยุด', 'отпрашиваться (с работы, учебы)', 'pedir permiso, solicitar licencia', 'pedir licença, pedir dispensa'],
  ['请客','qǐngkè','verb','to invite guests, to treat someone','misafir davet etmek, ısmarlamak', '손님을 대접하다, 한턱내다', '客を招く、ごちそうする', 'menjamu tamu, mentraktir', 'mời khách, đãi khách', 'เลี้ยงแขก, เป็นเจ้ามือ', 'угощать, приглашать гостей', 'invitar, convidar', 'convidar, pagar uma refeição'],
  ['秋天','qiūtiān','noun','autumn','sonbahar', '가을', '秋', 'musim gugur', 'mùa thu', 'ฤดูใบไม้ร่วง', 'осень', 'el otoño', 'o outono'],
  ['球场','qiúchǎng','noun','sports field, court','spor sahası, kort', '운동장, 구장', '球技場、グラウンド', 'lapangan olahraga', 'sân bóng', 'สนามกีฬากลางแจ้ง', 'спортивная площадка, стадион', 'el campo de deportes, la cancha', 'a quadra, o campo'],
  ['裙子','qúnzi','noun','skirt','etek', '치마', 'スカート、ワンピース', 'rok', 'váy', 'กระโปรง', 'юбка', 'la falda', 'a saia'],
  ['然后','ránhòu','conjunction','then, afterwards','sonra', '그러고 나서, 그런 다음', 'それから、その後', 'kemudian, setelah itu', 'sau đó', 'จากนั้น, หลังจากนั้น', 'затем, после этого', 'luego, después', 'então, depois, em seguida'],
  ['热情','rèqíng','adjective','enthusiastic','coşkulu, sıcakkanlı', '열정적이다', '熱心だ、親切だ、情熱的だ', 'antusias, ramah', 'nhiệt tình', 'กระตือรือร้น, มีน้ำใจ', 'горячий, радушный, отзывчивый', 'entusiasta, cordial', 'entusiasta, caloroso'],
  ['认得','rènde','verb','to recognize, to know','tanımak', '알아보다, 알다', '見覚えがある、知っている', 'mengenali, mengenal', 'nhận ra, quen biết', 'จำได้, รู้จัก', 'узнавать, быть знакомым', 'reconocer, conocer', 'reconhecer, conhecer'],
  ['认为','rènwéi','verb','to think, to consider','düşünmek, saymak', '여기다, 생각하다', '思う、考える', 'menganggap, berpendapat', 'cho rằng, nghĩ rằng', 'คิดว่า, เห็นว่า', 'полагать, считать', 'pensar, considerar', 'achar, considerar, pensar'],
  ['认真','rènzhēn','adjective','serious, earnest','ciddi, özenli', '진지한, 성실한', '真面目だ、真剣だ', 'serius, bersungguh-sungguh', 'nghiêm túc, cẩn thận', 'จริงจัง, เอาจริงเอาจัง', 'серьезный, добросовестный', 'serio, concienzudo', 'sério, consciencioso'],
  ['容易','róngyì','adjective','easy','kolay', '쉽다', '易しい、簡単だ', 'mudah, gampang', 'dễ dàng', 'ง่าย', 'лёгкий, нетрудный', 'fácil', 'fácil'],
  ['如果','rúguǒ','conjunction','if','eğer', '~라면, 만약', 'もし〜ならば', 'jika, kalau', 'nếu, nếu như', 'ถ้า, หาก', 'если', 'si', 'se'],
  ['伞','sǎn','noun','umbrella','şemsiye', '우산', '傘', 'payung', 'ô, dù', 'ร่ม', 'зонт', 'el paraguas', 'o guarda-chuva'],
  ['扫','sǎo, sào','verb','to sweep','süpürmek', '쓸다, 청소하다', '掃く、掃除する', 'menyapu', 'quét', 'กวาด', 'мести, подметать', 'barrer', 'varrer'],
  ['沙发','shāfā','noun','sofa','kanepe', '소파', 'ソファ', 'sofa', 'ghế sô pha', 'โซฟา', 'диван', 'el sofá', 'o sofá'],
  ['山','shān','noun','mountain','dağ', '산', '山', 'gunung', 'núi', 'ภูเขา', 'гора', 'la montaña', 'a montanha'],
  ['上衣','shàngyī','noun','jacket, top garment','ceket, üst giysi', '상의', '上着', 'baju atasan, jaket', 'áo khoác, áo trên', 'เสื้อตัวบน, เสื้อแจ็กเก็ต', 'верхняя одежда, куртка', 'la chaqueta, la prenda superior', 'a jaqueta, a blusa'],
  ['勺子','sháozi','noun','spoon','kaşık', '숟가락', 'スプーン、さじ', 'sendok', 'cái thìa, cái muỗng', 'ช้อน', 'ложка', 'la cuchara', 'a colher'],
  ['身边','shēnbiān','noun','by one\'s side','yanında', '곁, 곁에', '身の回り、そば', 'sisi, samping', 'bên cạnh', 'ข้างกาย', 'рядом, под рукой', 'el lado, el entorno inmediato', 'ao lado, perto de si'],
  ['身高','shēngāo','noun','height','boy uzunluğu', '키', '身長', 'tinggi badan', 'chiều cao', 'ส่วนสูง', 'рост (человека)', 'la estatura', 'a estatura, a altura'],
  ['声','shēng','noun','sound, voice; measure word for sounds','ses; ses sayı sözcüğü', '소리, 목소리; (소리의) 회수', '声、音、（音の）数え方', 'suara, bunyi, kata penggolong untuk bunyi', 'tiếng, âm thanh; lượng từ cho âm thanh', 'เสียง, ลักษณนามของเสียง', 'звук, голос; сч. сл. для звуков', 'el sonido, la voz, clasificador para sonidos', 'o som, a voz, classificador para sons'],
  ['生活','shēnghuó','noun','life; to live','yaşam; yaşamak', '생활, 삶, 살다', '生活、暮らし、生活する', 'kehidupan, hidup', 'cuộc sống, sinh sống', 'ชีวิต, การใช้ชีวิต', 'жизнь, жить', 'la vida, vivir', 'a vida, viver'],
  ['生气','shēngqì','verb','to get angry','kızmak, sinirlenmek', '화나다, 성내다', '怒る、腹を立てる', 'marah', 'giận, tức giận', 'โกรธ', 'сердиться, злиться', 'enfadarse, enojarse', 'ficar com raiva, zangar-se'],
  ['声音','shēngyīn','noun','sound','ses', '소리, 음성', '音、声', 'suara, bunyi', 'âm thanh, tiếng nói', 'เสียง', 'звук, голос', 'el sonido, la voz', 'o som, a voz'],
  ['市','shì','noun','city','şehir (idari)', '시', '市、都市', 'kota', 'thành phố', 'เมือง, เทศบาล', 'город', 'la ciudad', 'a cidade'],
  ['试','shì','verb','to try','denemek', '시도하다, 시험하다', '試す', 'mencoba, menguji', 'thử', 'ลอง, ทดสอบ', 'пробовать, пытаться', 'probar, intentar', 'tentar, experimentar'],
  ['室','shì','noun','room','oda', '방', '部屋', 'ruangan', 'phòng', 'ห้อง', 'комната, помещение', 'la habitación, la sala', 'o cômodo, a sala'],
  ['世界','shìjiè','noun','world','dünya', '세계', '世界', 'dunia', 'thế giới', 'โลก', 'мир', 'el mundo', 'o mundo'],
  ['收','shōu','verb','to receive','almak', '받다, 거두다', '受け取る、収める', 'menerima, memungut', 'thu, nhận', 'รับ, เก็บ', 'принимать, получать', 'recibir, aceptar', 'receber, aceitar'],
  ['收到','shōudào','verb','to receive','teslim almak', '받다', '受け取る、届く', 'menerima', 'nhận được', 'ได้รับ', 'получать/получить', 'recibir', 'receber'],
  ['受','shòu','verb','to receive, to be affected','almak, etkilenmek', '받다, 당하다', '受ける、被る', 'menerima, mengalami', 'nhận, chịu', 'ได้รับ, รับ', 'получать, подвергаться', 'recibir, sufrir', 'receber, sofrer'],
  ['瘦','shòu','adjective','thin, slim','ince, zayıf', '마르다, 야위다', '痩せている', 'kurus, ramping', 'gầy, ốm', 'ผอม', 'худой, стройный', 'delgado', 'magro'],
  ['受到','shòudào','verb','to receive, to be subjected to','almak, maruz kalmak', '받다, 당하다', '受ける、被る', 'menerima, mendapatkan', 'nhận được, chịu sự', 'ได้รับ', 'получать, быть подверженным', 'recibir, ser objeto de', 'receber, ser submetido a'],
  ['叔叔','shūshu','noun','uncle','amca', '아저씨', 'おじ（父の弟）、おじさん', 'paman', 'chú', 'อา, ลุง', 'дядя', 'el tío', 'o tio'],
  ['树','shù','noun','tree','ağaç', '나무', '木', 'pohon', 'cây', 'ต้นไม้', 'дерево', 'el árbol', 'a árvore'],
  ['数学','shùxué','noun','mathematics','matematik', '수학', '数学', 'matematika', 'toán học', 'คณิตศาสตร์', 'математика', 'las matemáticas', 'a matemática'],
  ['刷','shuā','verb','to brush, to scrub','fırçalamak', '솔질하다, 닦다', '磨く、洗う、刷毛で塗る', 'menyikat, menggosok', 'chải, cọ, quẹt', 'แปรง, ขัด', 'чистить, драить', 'cepillar, fregar', 'escovar, esfregar'],
  ['双','shuāng','classifier','pair, measure word for pairs','çift sayı sözcüğü', '~쌍 (단위)', '一対の、二つの（対になるものを数える）', 'pasang', 'đôi, cặp', 'คู่', 'пара', 'par', 'par'],
  ['水平','shuǐpíng','noun','level, standard','seviye, standart', '수준, 실력', 'レベル、水準', 'tingkat, taraf', 'trình độ, mức độ', 'ระดับ, มาตรฐาน', 'уровень, стандарт', 'el nivel, el estándar', 'o nível, o padrão'],
  ['司机','sījī','noun','driver','sürücü', '운전사', '運転手', 'sopir', 'tài xế, lái xe', 'คนขับรถ', 'водитель, шофёр', 'el conductor, el chófer', 'o motorista'],
  ['四季','sìjì','noun','four seasons','dört mevsim', '사계절', '四季', 'empat musim', 'bốn mùa', 'สี่ฤดู', 'четыре времени года', 'las cuatro estaciones', 'as quatro estações'],
  ['太阳','tàiyáng','noun','sun','güneş', '태양', '太陽', 'matahari', 'mặt trời', 'ดวงอาทิตย์', 'солнце', 'el sol', 'o sol'],
  ['糖','táng','noun','candy, sugar','şeker', '사탕, 설탕', '砂糖、飴', 'gula, permen', 'đường, kẹo', 'น้ำตาล, ลูกอม', 'сахар, конфета', 'el azúcar, el caramelo', 'o açúcar, o doce'],
  ['特别','tèbié','adverb','special; particularly','özel; özellikle', '특별히, 특히', '特別な、格別な、特に', 'khusus, istimewa, sangat', 'đặc biệt, vô cùng', 'พิเศษ, เป็นพิเศษ', 'особенный, особенно', 'especial, particularmente', 'especial, particularmente'],
  ['提高','tígāo','verb','to raise, to improve','yükseltmek, geliştirmek', '높이다, 향상시키다', '高める、向上させる', 'meningkatkan, menaikkan', 'nâng cao, cải thiện', 'ยกระดับ, ปรับปรุงให้ดีขึ้น', 'повышать/повысить, улучшать/улучшить', 'elevar, mejorar', 'elevar, melhorar'],
  ['体育','tǐyù','noun','physical education','beden eğitimi', '체육', '体育', 'pendidikan jasmani, olahraga', 'thể dục, thể thao', 'พลศึกษา', 'физкультура, спорт', 'la educación física', 'a educação física'],
  ['体育馆','tǐyùguǎn','noun','gymnasium','spor salonu', '체육관', '体育館', 'gedung olahraga, gimnasium', 'nhà thi đấu, nhà thể chất', 'โรงยิม, อาคารพลศึกษา', 'спортивный зал, спорткомплекс', 'el gimnasio', 'o ginásio'],
  ['甜','tián','adjective','sweet','tatlı', '달다', '甘い', 'manis', 'ngọt', 'หวาน', 'сладкий', 'dulce', 'doce'],
  ['跳','tiào','verb','to jump','zıplamak, atlamak', '뛰다, 뛰어넘다', '跳ぶ、跳ねる', 'melompat', 'nhảy', 'กระโดด, เต้น', 'прыгать', 'saltar', 'pular, saltar'],
  ['听说','tīngshuō','verb','to hear said','duyduğuna göre', '듣다 이르다, 소문이 나다', '〜だと聞く、〜だそうだ', 'mendengar kabar', 'nghe nói', 'ได้ยินมาว่า', 'слышать, по слухам', 'oír decir, enterarse', 'ouvir dizer'],
  ['挺','tǐng','adverb','quite, rather; (to endure)','oldukça; (katlanmak)', '꽤, 아주; 견디다', 'かなり、非常に、耐える', 'cukup, lumayan', 'khá, rất', 'ค่อนข้าง, มาก', 'весьма, довольно', 'bastante, muy', 'bastante, muito'],
  ['同事','tóngshì','noun','colleague','iş arkadaşı', '동료', '同僚', 'rekan kerja', 'đồng nghiệp', 'เพื่อนร่วมงาน', 'коллега, сослуживец', 'el colega, el compañero de trabajo', 'o colega'],
  ['同意','tóngyì','verb','to agree','katılmak, onaylamak', '동의하다', '同意する、賛成する', 'setuju', 'đồng ý', 'เห็นด้วย, ตกลง', 'соглашаться', 'estar de acuerdo, consentir', 'concordar'],
  ['头发','tóufa','noun','hair','saç', '머리카락', '髪の毛', 'rambut', 'tóc', 'ผม', 'волосы', 'el cabello', 'o cabelo'],
  ['突然','tūrán','adjective','sudden','ani', '갑자기', '突然の、急な', 'tiba-tiba, mendadak', 'đột nhiên, bất ngờ', 'กะทันหัน, ฉับพลัน', 'внезапный, неожиданный', 'repentino', 'repentino'],
  ['图书馆','túshūguǎn','noun','library','kütüphane', '도서관', '図書館', 'perpustakaan', 'thư viện', 'ห้องสมุด', 'библиотека', 'la biblioteca', 'a biblioteca'],
  ['腿','tuǐ','noun','leg','bacak', '다리', '脚（足の付け根から足首まで）', 'kaki', 'chân', 'ขา', 'нога', 'la pierna', 'a perna'],
  ['外地','wàidì','noun','other place','başka şehir/yer', '타지, 다른 지역', '他郷、よその土地', 'daerah lain, luar kota', 'nơi khác, địa phương khác', 'ต่างถิ่น, ต่างจังหวัด', 'другая местность', 'otro lugar, fuera de la localidad', 'outro lugar, fora da cidade'],
  ['外卖','wàimài','noun','takeaway; to order takeout','paket servis; paket sipariş etmek', '포장 음식, 배달 음식; 배달 음식을 주문하다', '出前、テイクアウト、出前を頼む', 'makanan pesan antar', 'đồ ăn mang về, dịch vụ giao đồ ăn', 'อาหารสั่งกลับบ้าน, สั่งอาหารกลับบ้าน', 'еда навынос', 'la comida para llevar', 'a comida para viagem, pedir comida'],
  ['外语','wàiyǔ','noun','foreign language','yabancı dil', '외국어', '外国語', 'bahasa asing', 'ngoại ngữ', 'ภาษาต่างประเทศ', 'иностранный язык', 'el idioma extranjero', 'a língua estrangeira'],
  ['完成','wánchéng','verb','to complete','tamamlamak', '완성하다', '完成する', 'menyelesaikan, menuntaskan', 'hoàn thành', 'เสร็จ, ทำให้สำเร็จ', 'завершать/завершить, выполнять/выполнить', 'completar, terminar', 'concluir, completar'],
  ['碗','wǎn','noun','bowl','kase', '사발, 그릇', '茶碗、椀', 'mangkuk', 'cái bát, cái chén', 'ชาม', 'чашка, пиала', 'el cuenco', 'a tigela'],
  ['晚点','wǎndiǎn','verb','to be late','geç kalmak', '늦어지다, 지연되다', '（乗り物が）遅れる', 'terlambat', 'trễ giờ, chậm giờ', 'ล่าช้า, มาสาย', 'опаздывать (о транспорте)', 'retrasarse', 'atrasar'],
  ['晚会','wǎnhuì','noun','evening party','gece partisi', '야회, 저녁 파티', '夜のパーティー、夕べの集い', 'pesta malam, perayaan malam', 'tiệc tối, dạ hội', 'งานเลี้ยงตอนเย็น', 'вечер, праздничный вечер', 'la fiesta nocturna, la velada', 'a festa noturna, a celebração'],
  ['网球','wǎngqiú','noun','tennis','tenis', '테니스', 'テニス', 'tenis', 'quần vợt', 'เทนนิส', 'теннис', 'el tenis', 'o tênis'],
  ['网站','wǎngzhàn','noun','website','web sitesi', '웹사이트', 'ウェブサイト', 'situs web', 'trang web', 'เว็บไซต์', 'веб-сайт', 'el sitio web', 'o site'],
  ['忘记','wàngjì','verb','to forget','unutmak', '잊다', '忘れる', 'melupakan', 'quên', 'ลืม', 'забывать/забыть', 'olvidar', 'esquecer'],
  ['为','wèi, wéi','preposition','for, because of, to','için, -den dolayı', '~을 위하여, ~을 위해', '〜のために', 'untuk, demi', 'vì, cho', 'เพื่อ, สำหรับ', 'ради, для, в пользу', 'por, para, en beneficio de', 'para, por causa de'],
  ['为了','wèile','preposition','in order to','-mek için', '~을/를 위하여, ~을/를 위해서', '〜のために', 'demi, untuk', 'để, vì', 'เพื่อ, สำหรับ', 'для того чтобы, ради', 'para, con el fin de', 'para, a fim de'],
  ['卫生间','wèishēngjiān','noun','bathroom, restroom','banyo, tuvalet', '화장실', 'トイレ、洗面所', 'kamar mandi, toilet', 'nhà vệ sinh', 'ห้องน้ำ', 'туалет, ванная комната', 'el baño, el aseo', 'o banheiro'],
  ['文化','wénhuà','noun','culture','kültür', '문화', '文化', 'budaya', 'văn hóa', 'วัฒนธรรม', 'культура', 'la cultura', 'a cultura'],
  ['屋子','wūzi','noun','room, house','oda, ev', '방, 집', '部屋、家', 'kamar, rumah', 'phòng, căn nhà', 'ห้อง, บ้าน', 'комната, дом', 'la habitación, la casa', 'o quarto, a casa'],
  ['西','xī','noun','west','batı', '서쪽', '西', 'barat', 'phía tây', 'ทิศตะวันตก', 'запад', 'el oeste', 'o oeste'],
  ['西北','xīběi','noun','northwest','kuzeybatı', '서북쪽', '北西', 'barat laut', 'tây bắc', 'ทิศตะวันตกเฉียงเหนือ', 'северо-запад', 'el noroeste', 'o noroeste'],
  ['西方','xīfāng','noun','west','batı', '서방, 서양', '西洋、西方', 'barat', 'phương tây', 'ตะวันตก', 'Запад', 'el occidente', 'o ocidente'],
  ['西瓜','xīguā','noun','watermelon','karpuz', '수박', 'スイカ', 'semangka', 'dưa hấu', 'แตงโม', 'арбуз', 'la sandía', 'a melancia'],
  ['西南','xīnán','noun','southwest','güneybatı', '서남쪽', '南西', 'barat daya', 'tây nam', 'ทิศตะวันตกเฉียงใต้', 'юго-запад', 'el suroeste', 'o sudoeste'],
  ['习惯','xíguàn','verb','to be used to; habit','alışmak; alışkanlık', '습관이 되다, 익숙해지다', '慣れる、習慣', 'terbiasa, kebiasaan', 'quen, thói quen', 'เคยชิน, นิสัย', 'привыкать/привыкнуть, привычка', 'acostumbrarse a, el hábito', 'acostumar-se, hábito'],
  ['喜爱','xǐ\'ài','verb','to like, to love','sevmek, beğenmek', '좋아하다, 사랑하다', '好む、愛する', 'menyukai, mencintai', 'yêu thích, ưa thích', 'ชอบ, รัก', 'любить, обожать', 'amar, gustar', 'amar, gostar'],
  ['洗衣机','xǐyījī','noun','washing machine','çamaşır makinesi', '세탁기', '洗濯機', 'mesin cuci', 'máy giặt', 'เครื่องซักผ้า', 'стиральная машина', 'la lavadora', 'a máquina de lavar'],
  ['洗澡','xǐzǎo','verb','to take a bath','banyo yapmak', '목욕하다', '風呂に入る、入浴する', 'mandi', 'tắm rửa', 'อาบน้ำ', 'принимать ванну, мыться', 'bañarse, ducharse', 'tomar banho'],
  ['夏天','xiàtiān','noun','summer','yaz', '여름', '夏', 'musim panas', 'mùa hè', 'ฤดูร้อน', 'лето', 'el verano', 'o verão'],
  ['先','xiān','adverb','first, before','önce', '먼저, 우선', '先に、まず', 'terlebih dahulu, duluan', 'trước', 'ก่อน', 'сначала, прежде', 'primero, antes', 'primeiro, antes'],
  ['香蕉','xiāngjiāo','noun','banana','muz', '바나나', 'バナナ', 'pisang', 'chuối', 'กล้วย', 'банан', 'el plátano', 'a banana'],
  ['相信','xiāngxìn','verb','to believe','inanmak', '믿다, 신뢰하다', '信じる', 'percaya, meyakini', 'tin tưởng, tin', 'เชื่อ, เชื่อถือ', 'верить, доверять', 'creer', 'acreditar'],
  ['箱子','xiāngzi','noun','box, case','kutu, bavul', '상자, 가방', '箱、スーツケース', 'kotak, peti, koper', 'cái thùng, cái hòm, vali', 'กล่อง, หีบ, กระเป๋าเดินทาง', 'ящик, чемодан', 'la caja, la maleta', 'a caixa, a mala'],
  ['向','xiàng','preposition','toward, to; to face','-e doğru; yönelmek', '~을 향하여, ~에게; ~을 향하다', '〜の方へ、〜に向かって', 'ke arah, kepada', 'hướng về, đối với', 'ทาง, ไปทาง, ต่อ', 'к, в направлении; по направлению к', 'hacia, a', 'em direção a, para'],
  ['像','xiàng','verb','to resemble, to be like; (as if)','benzemek; (sanki)', '닮다, 비슷하다; 마치 ~처럼', '似ている、〜のようだ', 'menyerupai, seperti', 'giống, như là', 'เหมือน, คล้าย', 'походить, напоминать', 'parecerse a, ser como', 'assemelhar-se, parecer'],
  ['相机','xiàngjī','noun','camera','fotoğraf makinesi', '카메라', 'カメラ', 'kamera', 'máy ảnh', 'กล้องถ่ายรูป', 'фотоаппарат', 'la cámara', 'a câmera'],
  ['小区','xiǎoqū','noun','residential community','konut sitesi', '주택 단지', '団地、住宅街', 'kompleks perumahan', 'khu dân cư', 'หมู่บ้านจัดสรร, ชุมชนที่พักอาศัย', 'жилой квартал, жилой комплекс', 'el complejo residencial', 'o condomínio residencial'],
  ['小心','xiǎoxīn','adjective','to be careful; careful','dikkatli olmak; dikkatli', '조심하다, 조심스러운', '注意深い、気をつける', 'hati-hati, cermat', 'cẩn thận', 'ระมัดระวัง, รอบคอบ', 'осторожный, бережный', 'cuidadoso, tener cuidado', 'cuidadoso, ter cuidado'],
  ['校园','xiàoyuán','noun','campus','kampüs', '캠퍼스, 교정', 'キャンパス、校庭', 'kampus', 'khuôn viên trường, trường học', 'วิทยาเขต, บริเวณโรงเรียน', 'кампус, территория учебного заведения', 'el campus', 'o campus'],
  ['校长','xiàozhǎng','noun','principal, headmaster','okul müdürü', '교장', '校長、学長', 'kepala sekolah, rektor', 'hiệu trưởng', 'อาจารย์ใหญ่, อธิการบดี', 'директор школы, ректор', 'el director, el rector', 'o diretor, o reitor'],
  ['鞋','xié','noun','shoe','ayakkabı', '신발', '靴', 'sepatu', 'giày', 'รองเท้า', 'обувь, туфли', 'el zapato', 'o sapato'],
  ['心里','xīnlǐ','noun','heart, mind','kalpte, içinde', '마음속', '心、胸中', 'hati, pikiran, batin', 'trong lòng, tâm trí', 'ในใจ, จิตใจ', 'душа, сердце, мысли', 'el corazón, la mente', 'o coração, a mente'],
  ['新年','xīnnián','noun','New Year','Yeni Yıl', '신년, 새해', '新年、正月', 'tahun baru', 'năm mới', 'ปีใหม่', 'Новый год', 'el Año Nuevo', 'o ano-novo'],
  ['新闻','xīnwén','noun','news','haber', '뉴스, 소식', 'ニュース、新聞', 'berita', 'tin tức, thời sự', 'ข่าว', 'новости', 'la noticia, las noticias', 'a notícia'],
  ['新鲜','xīnxiān','adjective','fresh','taze', '신선하다, 새롭다', '新鮮だ、新しい', 'segar, baru', 'tươi, tươi mới', 'สด, ใหม่', 'свежий', 'fresco', 'fresco'],
  ['信','xìn','verb','to believe; letter','inanmak; mektup', '믿다, 편지', '信じる、手紙', 'percaya, surat', 'tin, thư', 'เชื่อ, จดหมาย', 'верить, письмо', 'creer, la carta', 'acreditar, a carta'],
  ['信用卡','xìnyòngkǎ','noun','credit card','kredi kartı', '신용카드', 'クレジットカード', 'kartu kredit', 'thẻ tín dụng', 'บัตรเครดิต', 'кредитная карта', 'la tarjeta de crédito', 'o cartão de crédito'],
  ['行','xíng, háng','adjective','okay, permissible; to go','tamam, caiz; gitmek', '줄, 열; (화폐 단위) 각', '列、行', 'baris, deret', 'hàng, dòng', 'แถว, บรรทัด', 'ряд, линия', 'la línea, la fila', 'a linha, a fila'],
  ['行李','xíngli','noun','luggage','bagaj', '수하물, 짐', '荷物、手荷物', 'bagasi, barang bawaan', 'hành lý', 'สัมภาระ', 'багаж', 'el equipaje', 'a bagagem'],
  ['兴趣','xìngqù','noun','interest','ilgi, merak', '흥미, 관심', '興味', 'minat, ketertarikan', 'hứng thú, sở thích', 'ความสนใจ', 'интерес', 'el interés', 'o interesse'],
  ['休假','xiūjià','verb','to take a holiday','tatile çıkmak', '휴가를 내다, 휴가를 보내다', '休暇を取る', 'berlibur, cuti', 'nghỉ phép', 'ลาหยุด, พักร้อน', 'отдыхать в отпуске, брать отпуск', 'tomar vacaciones', 'tirar férias'],
  ['需要','xūyào','verb','to need; need','ihtiyaç duymak; ihtiyaç', '필요하다, 요구하다', '必要とする、必要', 'memerlukan, kebutuhan', 'cần, nhu cầu', 'ต้องการ, จำเป็นต้อง', 'нуждаться, требоваться; нужда, потребность', 'necesitar, la necesidad', 'precisar, a necessidade'],
  ['选','xuǎn','verb','to choose','seçmek', '선택하다, 고르다', '選ぶ', 'memilih', 'chọn, lựa chọn', 'เลือก', 'выбирать, избирать', 'elegir, escoger', 'escolher, selecionar'],
  ['选择','xuǎnzé','verb','to choose','seçmek', '선택하다', '選ぶ、選択する', 'memilih, pilihan', 'lựa chọn', 'เลือก, การเลือก', 'выбирать, выбор', 'elegir, seleccionar', 'escolher, optar'],
  ['学期','xuéqī','noun','semester','dönem', '학기', '学期', 'semester', 'học kỳ', 'ภาคการศึกษา', 'семестр', 'el semestre, el trimestre', 'o semestre'],
  ['牙','yá','noun','tooth','diş', '이', '歯', 'gigi', 'răng', 'ฟัน', 'зуб', 'el diente', 'o dente'],
  ['牙刷','yáshuā','noun','toothbrush','diş fırçası', '칫솔', '歯ブラシ', 'sikat gigi', 'bàn chải đánh răng', 'แปรงสีฟัน', 'зубная щетка', 'el cepillo de dientes', 'a escova de dentes'],
  ['羊','yáng','noun','sheep','koyun', '양', '羊', 'domba, kambing', 'con cừu, con dê', 'แกะ', 'овца', 'la oveja', 'a ovelha'],
  ['养','yǎng','verb','to raise, to keep','beslemek, yetiştirmek', '기르다, 양육하다', '飼う、育てる', 'memelihara, merawat', 'nuôi', 'เลี้ยง', 'выращивать, содержать', 'criar, mantener', 'criar, cuidar'],
  ['要求','yāoqiú','verb','to demand; requirement','talep etmek; gereksinim', '요구하다; 요구, 요청', '要求する、求める、要求', 'menuntut, permintaan', 'yêu cầu', 'เรียกร้อง, ข้อกำหนด', 'требовать; требование', 'exigir, requerir', 'exigir, a exigência'],
  ['页','yè','classifier','measure word for page','sayfa sayı sözcüğü', '~쪽, 페이지', 'ページ（枚数を数える単位）', 'halaman', 'trang', 'หน้า (ลักษณนามของกระดาษหรือหนังสือ)', 'счётное слово для страниц', 'clasificador para páginas', 'classificador para páginas'],
  ['一定','yídìng','adverb','certain; certainly','kesin; kesinlikle', '반드시, 꼭', '必ず、決まった', 'pasti, tentu', 'nhất định, chắc chắn', 'แน่นอน, ต้อง', 'непременно, обязательно', 'cierto, ciertamente, sin falta', 'certo, certamente'],
  ['一共','yígòng','adverb','altogether, in total','toplamda, hepsi birden', '모두, 전부', '合計で、全部で', 'seluruhnya, total', 'tổng cộng', 'ทั้งหมด, รวมแล้ว', 'всего, в общей сложности', 'en total', 'ao todo, no total'],
  ['一块儿','yíkuàir','adverb','the same place; together','birlikte', '함께, 같이', '一緒に、同じ場所で', 'bersama-sama', 'cùng nhau', 'ด้วยกัน', 'вместе', 'juntos', 'junto, no mesmo lugar'],
  ['一样','yíyàng','adjective','same','aynı', '같은', '同じだ', 'sama', 'giống nhau', 'เหมือนกัน', 'одинаковый', 'igual', 'igual, mesmo'],
  ['以后','yǐhòu','noun','later, after','sonra, -den sonra', '이후, 뒤에', '以後、あと、〜の後', 'setelahnya, kemudian', 'sau này, sau', 'หลังจาก, ต่อไป', 'потом, после', 'después, más tarde', 'depois, mais tarde'],
  ['以前','yǐqián','noun','before','önce, -den önce', '이전, 전에', '以前、前', 'sebelumnya, dahulu', 'trước đây, trước', 'ก่อน, แต่ก่อน', 'раньше, до', 'antes, anteriormente', 'antes'],
  ['以上','yǐshàng','noun','above, more than','yukarıda, fazla', '이상, ~ 이상', '以上、〜より上', 'di atas, lebih dari', 'trở lên, trên', 'ข้างบน, มากกว่า', 'выше, свыше', 'lo anterior, más de', 'acima, mais de'],
  ['以外','yǐwài','noun','except, besides','dışında, haricinde', '~을/를 제외하고, ~ 외에', '以外、〜のほか', 'selain, di luar', 'ngoài ra, ngoại trừ', 'นอกจาก, ยกเว้น', 'кроме, помимо', 'fuera de, excepto', 'exceto, além de'],
  ['以为','yǐwéi','verb','to think, to believe','sanmak', '착각하다, 여기다', '〜だと思い込む', 'mengira, menyangka', 'cho là, tưởng là', 'คิดว่า, เข้าใจว่า', 'полагать, считать', 'creer, pensar (erróneamente)', 'achar, acreditar'],
  ['以下','yǐxià','noun','below, less than','aşağıda, az', '이하, ~ 이하', '以下、〜より下', 'di bawah, kurang dari', 'trở xuống, dưới', 'ข้างล่าง, น้อยกว่า', 'ниже, менее', 'lo siguiente, menos de', 'abaixo, menos de'],
  ['一般','yìbān','adjective','general, ordinary','genel, sıradan', '일반적인, 보통의', '一般的な、普通の', 'umum, biasa', 'bình thường, phổ thông', 'ทั่วไป, ธรรมดา', 'обычный, средний', 'general, ordinario, corriente', 'geral, comum, ordinário'],
  ['一边','yìbiān','adverb','at the same time','aynı zamanda, -ken', '~하면서 동시에', '〜しながら', 'sambil', 'vừa... vừa...', 'พลาง, ในขณะเดียวกัน', 'одновременно', 'a la vez, al mismo tiempo', 'ao mesmo tempo'],
  ['一直','yìzhí','adverb','always, straight','hep, doğruca', '쭉, 계속', 'ずっと、まっすぐ', 'selalu, lurus terus', 'luôn luôn, thẳng', 'ตลอด, ตรงไป', 'всегда, прямо', 'siempre, continuamente, recto', 'sempre, direto, continuamente'],
  ['音乐','yīnyuè','noun','music','müzik', '음악', '音楽', 'musik', 'âm nhạc', 'ดนตรี, เพลง', 'музыка', 'la música', 'a música'],
  ['银行','yínháng','noun','bank','banka', '은행', '銀行', 'bank', 'ngân hàng', 'ธนาคาร', 'банк', 'el banco', 'o banco'],
  ['银行卡','yínhángkǎ','noun','bank card','banka kartı', '은행 카드', 'キャッシュカード', 'kartu bank', 'thẻ ngân hàng', 'บัตรธนาคาร', 'банковская карта', 'la tarjeta bancaria', 'o cartão bancário'],
  ['饮料','yǐnliào','noun','beverage','içecek', '음료', '飲み物、飲料', 'minuman', 'đồ uống, thức uống', 'เครื่องดื่ม', 'напиток', 'la bebida', 'a bebida'],
  ['应该','yīnggāi','verb','should, ought to','-meli, -malı', '해야 한다', '〜すべきだ、〜はずだ', 'seharusnya, patut', 'nên, cần phải', 'ควร, น่าจะ', 'следовать, быть должным', 'deber', 'dever'],
  ['影响','yǐngxiǎng','verb','to affect; influence','etkilemek; etki', '영향을 미치다', '影響する、影響', 'mempengaruhi, dampak', 'ảnh hưởng', 'ส่งผลกระทบ, อิทธิพล', 'влиять, воздействовать', 'afectar, influir', 'afetar, influenciar'],
  ['用','yòng','verb','to use','kullanmak', '사용하다', '使う、用いる', 'menggunakan', 'dùng, sử dụng', 'ใช้', 'использовать, пользоваться', 'usar, utilizar', 'usar, utilizar'],
  ['邮件','yóujiàn','noun','mail','posta, e-posta', '우편물', '郵便、メール', 'surat, surel', 'thư từ, email', 'ไปรษณีย์, อีเมล', 'почта, письмо', 'el correo, el mensaje', 'a correspondência, o e-mail'],
  ['游客','yóukè','noun','tourist','turist', '관광객', '観光客、旅行者', 'wisatawan', 'khách du lịch', 'นักท่องเที่ยว', 'турист', 'el turista', 'o turista'],
  ['游戏','yóuxì','noun','game','oyun', '게임, 유희', 'ゲーム、遊び', 'permainan', 'trò chơi, game', 'เกม', 'игра', 'el juego', 'o jogo'],
  ['邮箱','yóuxiāng','noun','mailbox','posta kutusu', '우편함', '郵便受け、メールボックス', 'kotak surat, alamat surel', 'hộp thư', 'ตู้ไปรษณีย์, กล่องจดหมาย', 'почтовый ящик', 'el buzón, la dirección de correo electrónico', 'a caixa de correio'],
  ['有关','yǒuguān','verb','to have to do with; concerning','ilgili olmak; hakkında', '관련되다, ~에 관한', '関係がある、関連する', 'berhubungan, terkait', 'liên quan', 'เกี่ยวข้อง', 'иметь отношение, касаться', 'relacionarse con, concerniente a', 'relacionar-se, concernente'],
  ['有名','yǒumíng','adjective','famous','ünlü', '유명하다, 이름나다', '有名だ', 'terkenal, ternama', 'nổi tiếng', 'มีชื่อเสียง', 'известный, знаменитый', 'famoso, célebre', 'famoso'],
  ['有用','yǒuyòng','adjective','useful','faydalı', '유용하다, 쓸모 있다', '役に立つ、有益だ', 'berguna, bermanfaat', 'có ích, hữu dụng', 'มีประโยชน์', 'полезный', 'útil', 'útil'],
  ['又','yòu','adverb','again, also','yine, tekrar', '또, 다시', 'また、さらに', 'lagi, juga', 'lại, cũng', 'อีก, อีกครั้ง, ทั้ง...ทั้ง...', 'снова, опять, к тому же', 'otra vez, además', 'novamente, também'],
  ['羽毛球','yǔmáoqiú','noun','badminton','badminton', '배드민턴', 'バドミントン', 'bulu tangkis', 'cầu lông', 'แบดมินตัน', 'бадминтон', 'el bádminton', 'o badminton'],
  ['语言','yǔyán','noun','language','dil', '언어', '言語', 'bahasa', 'ngôn ngữ', 'ภาษา', 'язык', 'el idioma, la lengua', 'a língua, o idioma'],
  ['雨衣','yǔyī','noun','raincoat','yağmurluk', '우비, 비옷', 'レインコート、雨合羽', 'jas hujan', 'áo mưa', 'เสื้อกันฝน', 'дождевик', 'el impermeable', 'a capa de chuva'],
  ['遇到','yùdào','verb','to encounter','karşılaşmak', '만나다, 부닥치다', '出くわす、遭遇する', 'bertemu, menjumpai', 'gặp, bắt gặp', 'พบ, เจอ', 'встречать, сталкиваться', 'encontrarse con, hallar', 'encontrar, deparar-se com'],
  ['遇见','yùjiàn','verb','to meet','rastlamak', '만나다', '出会う', 'bertemu', 'gặp gỡ', 'พบเจอ, ประสบ', 'встречать, видеться', 'encontrarse, conocer', 'encontrar, conhecer'],
  ['园','yuán','noun','garden','bahçe', '동산, 정원', '庭、園', 'taman, kebun', 'vườn, công viên', 'สวน', 'сад, парк', 'el jardín, el parque', 'o jardim'],
  ['员','yuán','suffix','suffix for person with a certain job','belirli bir iş kişisi eki', '~원 (직책 접미사)', '〜員（人を示す接尾辞）', 'akhiran untuk profesi atau anggota', 'viên (hậu tố chỉ người)', 'พนักงาน, ผู้ (ปัจจัยท้ายคำ)', 'суффикс лица по роду деятельности', 'sufijo para designar a una persona con un cargo o función', 'sufixo para designar ocupação'],
  ['愿意','yuànyì','verb','willing','istekli olmak, razı olmak', '원하다, 기꺼이 ~하다', '〜したい、望む', 'bersedia, mau', 'muốn, bằng lòng, tình nguyện', 'เต็มใจ, สมัครใจ', 'желать, хотеть', 'querer, estar dispuesto', 'querer, estar disposto'],
  ['越','yuè','adverb','more, increasingly','giderek daha fazla', '점점 더', 'ますます、いよいよ', 'semakin, kian', 'càng', 'ยิ่ง...ขึ้น', 'более, всё более', 'más, cada vez más', 'mais, cada vez mais'],
  ['月亮','yuèliang','noun','moon','ay', '달', '月', 'bulan', 'trăng, mặt trăng', 'พระจันทร์', 'луна', 'la luna', 'a lua'],
  ['运动会','yùndònghuì','noun','sports meet','spor müsabakası', '운동회', '運動会', 'pertandingan olahraga', 'đại hội thể thao', 'การแข่งขันกีฬา', 'спортивные соревнования', 'la competición deportiva', 'a competição esportiva'],
  ['运动员','yùndòngyuán','noun','athlete','sporcu', '운동선수', '選手、アスリート', 'atlet', 'vận động viên', 'นักกีฬา', 'спортсмен', 'el atleta, el deportista', 'o atleta'],
  ['咱们','zánmen','pronoun','we (inclusive)','biz (dahili)', '우리 (화자 포함)', '私たち（話し手と聞き手を含む）', 'kita', 'chúng ta (bao gồm người nghe)', 'พวกเรา (รวมผู้ฟัง)', 'мы (включая собеседника)', 'nosotros', 'nós'],
  ['脏','zāng, zàng','adjective','dirty','kirli', '더러운', '汚い', 'kotor', 'bẩn', 'สกปรก', 'грязный', 'sucio', 'sujo'],
  ['怎么办','zěnmebàn','verb','what to do','ne yapalım', '어떻게 하다', 'どうすればよいか、どうしよう', 'bagaimana cara mengatasi', 'làm thế nào, tính sao', 'ทำอย่างไรดี', 'что делать', 'qué hacer', 'o que fazer'],
  ['怎样','zěnyàng','pronoun','how','nasıl', '어떻게', 'どのように、どんなだ', 'bagaimana', 'như thế nào, ra sao', 'อย่างไร, อย่างไรบ้าง', 'как, каким образом', 'cómo', 'como'],
  ['张','zhāng','classifier','measure word for flat objects; to open','düz nesneler sayı sözcüğü; açmak', '장(평평한 물건), 펴다', '（平たいものを数える）枚、開く', 'kata penggolong untuk benda datar', 'lượng từ (vật phẳng), mở ra', 'แผ่น (ลักษณนามของสิ่งที่มีลักษณะแบน), กางออก', 'счётное слово для плоских предметов', 'clasificador para objetos planos', 'classificador para objetos planos'],
  ['着急','zháojí','adjective','anxious','endişeli, telaşlı', '조급하다, 안달하다', '焦る、じれったい', 'cemas, gelisah', 'lo lắng, vội vã', 'ร้อนใจ, รีบร้อน', 'взволнованный, беспокойный', 'ansioso, impaciente', 'ansioso'],
  ['照','zhào','verb','to shine, to photograph','parlatmak, fotoğraf çekmek', '비추다, 사진을 찍다', '照らす、写す、撮影する', 'menyinari, memotret', 'chiếu, chụp ảnh', 'ส่อง, ถ่ายภาพ', 'светить, фотографировать', 'alumbrar, fotografiar', 'iluminar, fotografar'],
  ['照顾','zhàogù','verb','to take care of','bakmak, ilgilenmek', '돌보다, 보살피다', '世話をする、面倒を見る', 'merawat, menjaga', 'chăm sóc', 'ดูแล', 'заботиться, ухаживать', 'cuidar, atender', 'cuidar de'],
  ['照片','zhàopiàn','noun','photo','fotoğraf', '사진', '写真', 'foto', 'ảnh, bức ảnh', 'รูปถ่าย', 'фотография', 'la fotografía, la foto', 'a fotografia, a foto'],
  ['照相','zhàoxiàng','verb','to take a picture','fotoğraf çekmek', '사진을 찍다', '写真を撮る', 'memotret', 'chụp ảnh', 'ถ่ายรูป', 'фотографировать', 'fotografiar, hacer fotos', 'tirar fotos'],
  ['直到','zhídào','verb','until','-e kadar', '~까지 이르다', '〜まで（ずっと）', 'sampai, hingga', 'cho đến khi', 'จนกระทั่ง', 'до, вплоть до', 'hasta', 'até'],
  ['只','zhǐ, zhī','adverb','only, merely','yalnızca, sadece', '마리 (동물 단위)', '（動物を数える）匹', 'kata penggolong untuk hewan', 'con (lượng từ)', 'ตัว (ลักษณนามสำหรับสัตว์)', 'счётное слово для животных', 'clasificador para animales', 'classificador para animais'],
  ['纸','zhǐ','noun','paper','kağıt', '종이', '紙', 'kertas', 'giấy', 'กระดาษ', 'бумага', 'el papel', 'o papel'],
  ['只能','zhǐnéng','adverb','can only','yalnızca yapabilmek', '~할 수밖에 없다', '〜するしかない', 'hanya bisa', 'chỉ có thể', 'ทำได้เพียง, ได้แค่', 'мочь только', 'solo poder', 'só poder'],
  ['只是','zhǐshì','adverb','only, merely; but','yalnızca; ama', '단지, 다만; 그러나', 'ただ〜だけだ、しかし', 'hanya, tetapi', 'chỉ là, nhưng mà', 'เพียงแต่, แค่เพียง', 'только, лишь; однако', 'solo, solamente, pero', 'apenas, somente, mas'],
  ['只要','zhǐyào','conjunction','as long as','-diği sürece', '~하기만 하면', '〜さえすれば', 'asalkan', 'chỉ cần', 'ขอเพียงแค่, เพียงแค่', 'лишь бы, если только', 'siempre que, con tal de que', 'contanto que'],
  ['只有','zhǐyǒu','conjunction','only if','yalnızca eğer', '~해야만', '〜でなければ〜ない、〜だけがある', 'hanya jika', 'chỉ có', 'มีเพียง, นอกจาก...แล้ว', 'только если', 'solo si', 'apenas se'],
  ['中','zhōng, zhòng','noun','middle','orta', '중간, 가운데', '中、中央', 'tengah', 'giữa, trung tâm', 'กลาง, ท่ามกลาง', 'середина', 'el medio, el centro', 'o meio, o centro'],
  ['中间','zhōngjiān','noun','middle, between','arasında, ortada', '중간, 가운데', '真ん中、間', 'tengah, antara', 'ở giữa, trung gian', 'ตรงกลาง, ระหว่าง', 'середина, между', 'el medio, entre', 'o meio, entre'],
  ['终于','zhōngyú','adverb','finally','sonunda', '마침내, 드디어', 'ついに、ようやく', 'akhirnya', 'cuối cùng', 'ในที่สุด', 'в конце концов, наконец', 'finalmente', 'finalmente'],
  ['种','zhǒng, zhòng','classifier','measure word for kinds','tür sayı sözcüğü', '1. 종류 2. 심다, 재배하다', '種類、植える', 'jenis, menanam', 'loại, trồng', 'ชนิด, ปลูก', '1) вид, сорт; 2) сажать, выращивать', 'clasificador para tipos, plantar', 'tipo, plantar'],
  ['重要','zhòngyào','adjective','important','önemli', '중요한', '重要だ', 'penting', 'quan trọng', 'สำคัญ', 'важный', 'importante', 'importante'],
  ['周末','zhōumò','noun','weekend','hafta sonu', '주말', '週末', 'akhir pekan', 'cuối tuần', 'สุดสัปดาห์', 'выходные', 'el fin de semana', 'o fim de semana'],
  ['主要','zhǔyào','adjective','main','ana, esas', '주요한, 주된', '主要な、主な', 'utama, pokok', 'chính, chủ yếu', 'หลัก, สำคัญ', 'главный, основной', 'principal', 'principal'],
  ['注意','zhùyì','verb','to pay attention to','dikkat etmek', '주의하다, 주목하다', '注意する、留意する', 'memperhatikan, waspada', 'chú ý, để ý', 'ระวัง, ใส่ใจ, สนใจ', 'обращать внимание, следить', 'prestar atención, fijarse', 'prestar atenção, atentar-se'],
  ['住院','zhùyuàn','verb','to be hospitalized','hastaneye yatmak', '입원하다', '入院する', 'dirawat di rumah sakit', 'nằm viện', 'นอนโรงพยาบาล, รักษาตัวในโรงพยาบาล', 'ложиться в больницу, лежать в больнице', 'ser hospitalizado', 'ser hospitalizado'],
  ['字典','zìdiǎn','noun','dictionary','sözlük', '자전, 사전', '辞書、字典', 'kamus', 'từ điển', 'พจนานุกรม', 'словарь', 'el diccionario', 'o dicionário'],
  ['自行车','zìxíngchē','noun','bicycle','bisiklet', '자전거', '自転車', 'sepeda', 'xe đạp', 'จักรยาน', 'велосипед', 'la bicicleta', 'a bicicleta'],
  ['子','zi','suffix','noun suffix','isim eki', '명사 뒤에 붙어 사물이나 사람을 나타내는 접미사', '名詞を作る接尾辞', 'akhiran kata benda', 'hậu tố danh từ', 'ปัจจัยท้ายคำนาม', 'суффикс существительных', 'sufijo nominal', 'sufixo nominal'],
  ['总','zǒng','adverb','always, invariably; (total, overall)','her zaman; (toplam)', '언제나, 늘; 총, 합계', 'いつも、総計の', 'selalu, total, keseluruhan', 'luôn, tổng cộng', 'เสมอ, รวม, ทั้งหมด', 'всегда, общий', 'siempre, total', 'sempre, total'],
  ['总是','zǒngshì','adverb','always','her zaman', '언제나, 늘', 'いつも、常に', 'selalu', 'luôn luôn', 'มักจะ...เสมอ, ตลอดเวลา', 'всегда', 'siempre', 'sempre'],
  ['嘴','zuǐ','noun','mouth','ağız', '입', '口', 'mulut', 'miệng', 'ปาก', 'рот', 'la boca', 'a boca'],
  ['最好','zuìhǎo','adverb','best','en iyi, mümkünse', '가장 좋은, 제일 좋은', '一番よい、〜したほうがよい', 'sebaiknya, paling baik', 'tốt nhất, nên', 'ดีที่สุด, ทางที่ดีควร', 'лучше всего, наилучший', 'lo mejor, más vale', 'o melhor, é melhor'],
  ['最后','zuìhòu','noun','last, final','son', '최후의, 마지막', '最後、最終', 'terakhir, akhirnya', 'cuối cùng', 'สุดท้าย', 'последний, в конце концов', 'el último, finalmente', 'último, final'],
  ['最近','zuìjìn','noun','recently','son zamanlarda', '최근에', '最近、このごろ', 'akhir-akhir ini, baru-baru ini', 'dạo gần đây, gần đây', 'เมื่อเร็วๆ นี้, ช่วงนี้', 'последнее время, недавно', 'el último tiempo, recientemente', 'o último período, recentemente'],
  ['做客','zuòkè','verb','to be a guest','misafir olmak', '손님으로 가다, 방문하다', '客になる、訪問する', 'bertamu', 'làm khách, đến chơi nhà', 'ไปเป็นแขก, ไปเยี่ยมเยียน', 'гостить, быть в гостях', 'ser invitado, visitar', 'ser convidado, visitar'],
  ['作业','zuòyè','noun','homework','ödev', '과제, 숙제', '宿題、作業', 'pekerjaan rumah, tugas', 'bài tập', 'การบ้าน', 'домашнее задание', 'la tarea, los deberes', 'o dever de casa'],
];
