// ignore_for_file: constant_identifier_names
// HSK Level 4 vocabulary — 1000 words
// Format: [simplified, pinyin, pos, en, tr]

const List<List<String>> kHsk4Words = [
  ['啊', 'ā', 'interjection', 'ah, oh', 'ah, oh'],
  ['爱情', 'àiqíng', 'noun', 'love', 'aşk, sevgi'],
  ['爱心', 'àixīn', 'noun', 'compassion, caring', 'şefkat, merhametlilik'],
  ['安检', 'ānjiǎn', 'verb', 'security check', 'güvenlik kontrolü'],
  ['安排', 'ānpái', 'verb', 'to arrange', 'düzenlemek, ayarlamak'],
  ['按', 'àn', 'verb', 'to press; according to', 'basmak; göre'],
  ['按时', 'ànshí', 'adverb', 'on time, on schedule', 'zamanında, programda'],
  ['按照', 'ànzhào', 'preposition', 'according to', 'göre, uyarınca'],
  ['白酒', 'báijiǔ', 'noun', 'liquor, spirit', 'rakı, viski'],
  ['办公', 'bàngōng', 'verb', 'to handle official business', 'resmi iş yürütmek'],
  ['办理', 'bànlǐ', 'verb', 'to handle, to process', 'işlem yapmak, halletmek'],
  ['办事', 'bànshì', 'verb', 'to handle matters', 'iş halletmek'],
  ['棒', 'bàng', 'adjective', 'great, excellent', 'harika, mükemmel'],
  ['保护', 'bǎohù', 'verb', 'to protect', 'korumak'],
  ['保证', 'bǎozhèng', 'verb', 'to guarantee', 'garanti etmek, güvence vermek'],
  ['抱', 'bào', 'verb', 'to hold, to embrace', 'tutmak, kucaklamak'],
  ['报考', 'bàokǎo', 'verb', 'to apply for an exam', 'sınava başvurmak'],
  ['报名', 'bàomíng', 'verb', 'to sign up, to register', 'kayıt olmak'],
  ['抱歉', 'bàoqiàn', 'adjective', 'sorry, apologetic', 'özür dilerim, üzgünüm'],
  ['背', 'bèi, bēi', 'verb', 'to carry on the back', 'sırtında taşımak'],
  ['背包', 'bēibāo', 'noun', 'backpack', 'sırt çantası'],
  ['北部', 'běibù', 'noun', 'northern part, north', 'kuzey bölgesi'],
  ['倍', 'bèi', 'classifier', 'times, -fold', 'kat, katı'],
  ['本科', 'běnkē', 'noun', 'undergraduate program', 'lisans programı'],
  ['本来', 'běnlái', 'adverb', 'originally, actually', 'aslında, başta'],
  ['笨', 'bèn', 'adjective', 'stupid, foolish', 'aptal, ahmak'],
  ['鼻子', 'bízi', 'noun', 'nose', 'burun'],
  ['笔试', 'bǐshì', 'noun', 'written test', 'yazılı sınav'],
  ['毕业', 'bìyè', 'verb', 'to graduate', 'mezun olmak'],
  ['毕业生', 'bìyèshēng', 'noun', 'graduate', 'mezun'],
  ['便于', 'biànyú', 'verb', 'to be convenient for', 'kolaylık sağlamak'],
  ['标准', 'biāozhǔn', 'noun', 'standard', 'standart'],
  ['表', 'biǎo', 'noun', 'watch, table, form', 'saat, form, tablo'],
  ['表格', 'biǎogé', 'noun', 'form, table', 'form, tablo'],
  ['表示', 'biǎoshì', 'verb', 'to express, to indicate', 'ifade etmek, belirtmek'],
  ['表现', 'biǎoxiàn', 'verb', 'to show, to display', 'göstermek, sergilemek'],
  ['表扬', 'biǎoyáng', 'verb', 'to praise, to commend', 'övmek, takdir etmek'],
  ['饼干', 'bǐnggān', 'noun', 'biscuit, cracker', 'bisküvi, kraker'],
  ['并', 'bìng', 'conjunction', 'and, also', 've, ayrıca'],
  ['并且', 'bìngqiě', 'conjunction', 'and, moreover', 'üstelik, ayrıca'],
  ['播放', 'bōfàng', 'verb', 'to broadcast, to play', 'yayınlamak, oynatmak'],
  ['博士', 'bóshì', 'noun', 'doctor (PhD)', 'doktor (akademik)'],
  ['不必', 'búbì', 'adverb', 'need not', 'gerek yok'],
  ['不便', 'búbiàn', 'adjective', 'inconvenient', 'elverişsiz, rahatsız'],
  ['不断', 'búduàn', 'adverb', 'continuously, constantly', 'sürekli, aralıksız'],
  ['不够', 'búgòu', 'adverb', 'not enough', 'yeterli değil'],
  ['不过', 'búguò', 'conjunction', 'but, however', 'ama, ancak'],
  ['不论', 'búlùn', 'conjunction', 'no matter, regardless', 'ne olursa olsun'],
  ['步', 'bù', 'noun', 'step, pace', 'adım'],
  ['部', 'bù', 'noun', 'department, part', 'bölüm, departman'],
  ['不得不', 'bùdébù', 'adverb', 'have to, cannot but', 'zorunda olmak'],
  ['部分', 'bùfen', 'noun', 'part, portion', 'kısım, bölüm'],
  ['不管', 'bùguǎn', 'conjunction', 'no matter, regardless of', 'ne olursa olsun'],
  ['不光', 'bùguāng', 'conjunction', 'not only', 'sadece değil'],
  ['不仅', 'bùjǐn', 'conjunction', 'not only', 'sadece değil'],
  ['不满', 'bùmǎn', 'adjective', 'dissatisfied, displeased', 'memnun olmayan'],
  ['部门', 'bùmén', 'noun', 'department, unit', 'bölüm, birim'],
  ['不如', 'bùrú', 'verb', 'not as good as', 'kadar iyi değil'],
  ['擦', 'cā', 'verb', 'to wipe, to rub', 'silmek, ovmak'],
  ['猜', 'cāi', 'verb', 'to guess', 'tahmin etmek'],
  ['材料', 'cáiliào', 'noun', 'material, data', 'malzeme, materyal'],
  ['参观', 'cānguān', 'verb', 'to visit, to tour', 'ziyaret etmek, gezmek'],
  ['参赛', 'cānsài', 'verb', 'to enter a competition', 'yarışmaya katılmak'],
  ['餐厅', 'cāntīng', 'noun', 'restaurant, dining hall', 'restoran, yemekhane'],
  ['操场', 'cāochǎng', 'noun', 'playground', 'spor sahası'],
  ['厕所', 'cèsuǒ', 'noun', 'toilet, restroom', 'tuvalet'],
  ['查看', 'chákàn', 'verb', 'to check, to view', 'kontrol etmek, incelemek'],
  ['茶叶', 'cháyè', 'noun', 'tea leaf', 'çay yaprağı'],
  ['查找', 'cházhǎo', 'verb', 'to search for, to look up', 'aramak, bulmak'],
  ['差点儿', 'chàdiǎnr', 'adverb', 'almost, nearly', 'az kalsın, neredeyse'],
  ['产生', 'chǎnshēng', 'verb', 'to produce, to generate, to arise', 'üretmek, oluşmak'],
  ['厂', 'chǎng', 'noun', 'factory, plant', 'fabrika'],
  ['场', 'chǎng', 'classifier', 'measure word for events', 'etkinlik sayacı'],
  ['超过', 'chāoguò', 'verb', 'to exceed, to surpass', 'aşmak, geçmek'],
  ['车速', 'chēsù', 'noun', 'vehicle speed', 'araç hızı'],
  ['车位', 'chēwèi', 'noun', 'parking space', 'park yeri'],
  ['城', 'chéng', 'noun', 'city, town', 'şehir, kasaba'],
  ['乘', 'chéng', 'verb', 'to ride, to take', 'binmek, taşımak'],
  ['成功', 'chénggōng', 'verb', 'to succeed; successful', 'başarmak; başarılı'],
  ['乘客', 'chéngkè', 'noun', 'passenger', 'yolcu'],
  ['诚实', 'chéngshí', 'adjective', 'honest', 'dürüst'],
  ['成为', 'chéngwéi', 'verb', 'to become', 'olmak'],
  ['乘坐', 'chéngzuò', 'verb', 'to ride, to take transportation', 'taşıta binmek'],
  ['吃惊', 'chījīng', 'verb', 'to be startled, to be shocked', 'şaşırmak, ürkmek'],
  ['迟', 'chí', 'adjective', 'late, delayed', 'geç, gecikmiş'],
  ['重', 'zhòng, chóng', 'adverb', 'again, once more', 'yeniden, tekrar'],
  ['重新', 'chóngxīn', 'adverb', 'again, anew', 'yeniden'],
  ['出差', 'chūchāi', 'verb', 'to go on a business trip', 'iş seyahatine çıkmak'],
  ['出口', 'chūkǒu', 'noun', 'exit', 'çıkış'],
  ['出现', 'chūxiàn', 'verb', 'to appear, to emerge', 'ortaya çıkmak'],
  ['出行', 'chūxíng', 'verb', 'to travel, to go out', 'seyahat etmek, dışarı çıkmak'],
  ['出租', 'chūzū', 'verb', 'to rent out', 'kiraya vermek'],
  ['厨房', 'chúfáng', 'noun', 'kitchen', 'mutfak'],
  ['厨师', 'chúshī', 'noun', 'chef, cook', 'aşçı, şef'],
  ['窗', 'chuāng', 'noun', 'window', 'pencere'],
  ['窗户', 'chuānghu', 'noun', 'window', 'pencere'],
  ['吹', 'chuī', 'verb', 'to blow', 'üflemek, esmek'],
  ['词语', 'cíyǔ', 'noun', 'word, phrase', 'kelime, sözcük'],
  ['此', 'cǐ', 'pronoun', 'this', 'bu'],
  ['此次', 'cǐcì', 'noun', 'this time', 'bu sefer'],
  ['此外', 'cǐwài', 'conjunction', 'besides, in addition, moreover', 'bunun dışında, ayrıca'],
  ['从此', 'cóngcǐ', 'adverb', 'from then on, since then', 'o andan itibaren'],
  ['从来', 'cónglái', 'adverb', 'always, at all times', 'her zaman, hiç'],
  ['从中', 'cóngzhōng', 'adverb', 'from among, from it', 'arasından'],
  ['粗', 'cū', 'adjective', 'coarse, rough, thick', 'kaba, pürüzlü, kalın'],
  ['粗心', 'cūxīn', 'adjective', 'careless', 'dikkatsiz'],
  ['村', 'cūn', 'noun', 'village', 'köy'],
  ['存', 'cún', 'verb', 'to store, to keep, to exist', 'depolamak, biriktirmek'],
  ['错过', 'cuòguò', 'verb', 'to miss, to let slip', 'kaçırmak'],
  ['错误', 'cuòwù', 'noun', 'mistake, error; wrong', 'hata; yanlış'],
  ['答应', 'dāying', 'verb', 'to agree, to promise, to reply', 'kabul etmek, söz vermek'],
  ['答', 'dá, dā', 'verb', 'to answer, to reply', 'cevap vermek'],
  ['答案', 'dáàn', 'noun', 'answer, solution', 'cevap, yanıt'],
  ['达到', 'dádào', 'verb', 'to reach, to achieve', 'ulaşmak, başarmak'],
  ['打招呼', 'dǎzhāohu', 'verb', 'to greet, to say hello', 'selamlamak'],
  ['打败', 'dǎbài', 'verb', 'to defeat, to beat', 'yenmek, mağlup etmek'],
  ['打工', 'dǎgōng', 'verb', 'to work a temporary job', 'geçici iş yapmak'],
  ['打扰', 'dǎrǎo', 'verb', 'to disturb, to bother', 'rahatsız etmek'],
  ['打印', 'dǎyìn', 'verb', 'to print', 'yazdırmak, basmak'],
  ['打印机', 'dǎyìnjī', 'noun', 'printer', 'yazıcı'],
  ['打折', 'dǎzhé', 'verb', 'to give a discount', 'indirim yapmak'],
  ['打针', 'dǎzhēn', 'verb', 'to get an injection', 'iğne olmak'],
  ['大巴', 'dàbā', 'noun', 'large bus, coach', 'otobüs, büyük otobüs'],
  ['大大', 'dàdà', 'adverb', 'greatly, significantly', 'büyük ölçüde'],
  ['大夫', 'dàifu', 'noun', 'doctor (medical)', 'doktor, hekim'],
  ['大量', 'dàliàng', 'adjective', 'large quantity, a large amount', 'büyük miktarda'],
  ['大赛', 'dàsài', 'noun', 'major competition, grand contest', 'büyük yarışma'],
  ['大厅', 'dàtīng', 'noun', 'hall, lobby', 'salon, lobi'],
  ['大约', 'dàyuē', 'adverb', 'approximately, about', 'yaklaşık, aşağı yukarı'],
  ['大自然', 'dàzìrán', 'noun', 'nature, the natural world', 'doğa, tabiat'],
  ['待', 'dài, dāi', 'verb', 'to stay', 'kalmak'],
  ['戴', 'dài', 'verb', 'to wear, to put on', 'takmak, giymek'],
  ['袋子', 'dàizi', 'noun', 'bag, sack', 'torba, çanta'],
  ['单位', 'dānwèi', 'noun', 'unit, department', 'birim, kurum'],
  ['当', 'dāng, dàng', 'verb', 'to serve as; at the time of', 'olarak hizmet etmek; zamanında'],
  ['当时', 'dāngshí', 'noun', 'at that time, then', 'o zaman, o sırada'],
  ['刀', 'dāo', 'noun', 'knife', 'bıçak'],
  ['导游', 'dǎoyóu', 'noun', 'tour guide', 'rehber, turist rehberi'],
  ['倒', 'dǎo, dào', 'verb', 'to fall, to collapse; however', 'devrilmek; ancak'],
  ['道', 'dào', 'noun', 'path, way, method', 'yol, yöntem'],
  ['到底', 'dàodǐ', 'adverb', 'finally, after all, to the end', 'sonunda, ne de olsa'],
  ['到来', 'dàolái', 'verb', 'to arrive', 'gelmek, ulaşmak'],
  ['道路', 'dàolù', 'noun', 'road, path', 'yol'],
  ['道歉', 'dàoqiàn', 'verb', 'to apologize', 'özür dilemek'],
  ['得意', 'déyì', 'adjective', 'proud, complacent', 'gururlu, mağrur'],
  ['登机', 'dēngjī', 'verb', 'to board a plane', 'uçağa binmek'],
  ['等', 'děng', 'auxiliary', 'and so on, etc.', 'vb., ve benzeri'],
  ['等到', 'děngdào', 'preposition', 'until, by the time', 'kadar, oluncaya kadar'],
  ['低', 'dī', 'adjective', 'low; to lower', 'düşük; alçaltmak'],
  ['低价', 'dījià', 'noun', 'low price', 'düşük fiyat'],
  ['低温', 'dīwēn', 'noun', 'low temperature', 'düşük sıcaklık'],
  ['低于', 'dīyú', 'verb', 'to be lower than', 'daha düşük olmak'],
  ['底', 'dǐ', 'noun', 'bottom, base', 'alt, taban'],
  ['底下', 'dǐxia', 'noun', 'below, underneath', 'altında, aşağısında'],
  ['地球', 'dìqiú', 'noun', 'earth', 'dünya'],
  ['地址', 'dìzhǐ', 'noun', 'address', 'adres'],
  ['点名', 'diǎnmíng', 'verb', 'to call the roll, to mention by name', 'yoklama yapmak'],
  ['点头', 'diǎntóu', 'verb', 'to nod', 'başını sallamak'],
  ['电动车', 'diàndòngchē', 'noun', 'electric vehicle, e-bike', 'elektrikli araç'],
  ['电视剧', 'diànshìjù', 'noun', 'TV drama', 'televizyon dizisi'],
  ['掉', 'diào', 'verb', 'to fall, to drop', 'düşmek'],
  ['调查', 'diàochá', 'verb', 'to investigate', 'araştırmak, soruşturmak'],
  ['订', 'dìng', 'verb', 'to order, to book', 'sipariş vermek, rezervasyon yapmak'],
  ['定', 'dìng', 'verb', 'to fix, to set, to determine', 'belirlemek, saptamak'],
  ['东部', 'dōngbù', 'noun', 'eastern part', 'doğu bölgesi'],
  ['动车', 'dòngchē', 'noun', 'high-speed train', 'hızlı tren'],
  ['动作', 'dòngzuò', 'noun', 'movement, action', 'hareket, eylem'],
  ['读者', 'dúzhě', 'noun', 'reader', 'okuyucu'],
  ['堵车', 'dǔchē', 'noun', 'traffic jam', 'trafik sıkışıklığı'],
  ['度假', 'dùjià', 'verb', 'to go on vacation', 'tatile gitmek'],
  ['肚子', 'dùzi', 'noun', 'belly, stomach', 'mide, karın'],
  ['短信', 'duǎnxìn', 'noun', 'text message', 'kısa mesaj'],
  ['队', 'duì', 'noun', 'team, squad', 'takım, ekip'],
  ['对方', 'duìfāng', 'noun', 'the other party, counterpart', 'karşı taraf'],
  ['对面', 'duìmiàn', 'noun', 'opposite side', 'karşı taraf'],
  ['对于', 'duìyú', 'preposition', 'regarding, concerning', 'konusunda, hakkında'],
  ['队员', 'duìyuán', 'noun', 'team member', 'takım üyesi'],
  ['队长', 'duìzhǎng', 'noun', 'team leader', 'takım kaptanı'],
  ['顿', 'dùn', 'classifier', 'measure word for meals', 'öğün sayacı'],
  ['多么', 'duōme', 'adverb', 'how, so, what', 'ne kadar'],
  ['多数', 'duōshù', 'noun', 'majority', 'çoğunluk'],
  ['多样', 'duōyàng', 'adjective', 'diverse, varied', 'çeşitli, farklı'],
  ['而', 'ér', 'conjunction', 'but, and, yet', 'ama, ve, oysa'],
  ['儿童', 'értóng', 'noun', 'child', 'çocuk'],
  ['发出', 'fāchū', 'verb', 'to send out, to issue', 'göndermek, çıkarmak'],
  ['发送', 'fāsòng', 'verb', 'to send', 'göndermek'],
  ['法', 'fǎ', 'noun', 'law', 'hukuk, kanun'],
  ['法律', 'fǎlǜ', 'noun', 'law', 'hukuk, kanun'],
  ['翻译', 'fānyì', 'verb', 'to translate; translation', 'çevirmek; çeviri'],
  ['烦', 'fán', 'adjective', 'annoyed, vexed', 'sinirli, rahatsız'],
  ['烦恼', 'fánnǎo', 'adjective', 'worried, distressed', 'kaygılı, üzgün'],
  ['反对', 'fǎnduì', 'verb', 'to oppose, to be against', 'karşı çıkmak'],
  ['方面', 'fāngmiàn', 'noun', 'aspect, side', 'yön, taraf'],
  ['方式', 'fāngshì', 'noun', 'way, method', 'yöntem, yol'],
  ['房东', 'fángdōng', 'noun', 'landlord', 'ev sahibi'],
  ['房租', 'fángzū', 'noun', 'rent', 'kira'],
  ['放弃', 'fàngqì', 'verb', 'to give up', 'vazgeçmek'],
  ['放松', 'fàngsōng', 'verb', 'to relax', 'rahatlamak'],
  ['费', 'fèi', 'noun', 'fee, expense', 'ücret, gider'],
  ['费用', 'fèiyong', 'noun', 'cost, expense', 'maliyet, gider'],
  ['分数', 'fēnshù', 'noun', 'score, grade, fraction', 'not, puan'],
  ['分为', 'fēnwéi', 'verb', 'to be divided into', 'bölünmek'],
  ['份', 'fèn', 'classifier', 'measure word for copies, shares', 'kopya sayacı'],
  ['丰富', 'fēngfù', 'adjective', 'rich, abundant', 'zengin, bol'],
  ['风景', 'fēngjǐng', 'noun', 'scenery, landscape', 'manzara'],
  ['否则', 'fǒuzé', 'conjunction', 'otherwise, if not', 'aksi takdirde'],
  ['幅', 'fú', 'classifier', 'measure word for paintings, photos', 'resim sayacı'],
  ['符合', 'fúhé', 'verb', 'to conform to, to match', 'uymak, karşılamak'],
  ['付', 'fù', 'verb', 'to pay', 'ödemek'],
  ['父母', 'fùmǔ', 'noun', 'parents', 'anne-baba, ebeveynler'],
  ['父女', 'fùnǚ', 'noun', 'father and daughter', 'baba ve kız'],
  ['父亲', 'fùqīn', 'noun', 'father', 'baba'],
  ['复印', 'fùyìn', 'verb', 'to photocopy, to duplicate', 'fotokopi çekmek'],
  ['复杂', 'fùzá', 'adjective', 'complicated, complex', 'karmaşık'],
  ['负责', 'fùzé', 'verb', 'to be responsible', 'sorumlu olmak'],
  ['负责人', 'fùzérén', 'noun', 'person in charge', 'sorumlu kişi'],
  ['父子', 'fùzǐ', 'noun', 'father and son', 'baba ve oğul'],
  ['改', 'gǎi', 'verb', 'to change, to alter', 'değiştirmek'],
  ['改变', 'gǎibiàn', 'verb', 'to change', 'değişmek, değiştirmek'],
  ['干', 'gān, gàn', 'adjective', 'dry', 'kuru'],
  ['干杯', 'gānbēi', 'verb', 'to toast, cheers', 'kadeh kaldırmak, şerefe'],
  ['赶', 'gǎn', 'verb', 'to hurry, to catch up', 'acele etmek, yetişmek'],
  ['敢', 'gǎn', 'verb', 'to dare', 'cesaret etmek'],
  ['感', 'gǎn', 'noun', 'sense, feeling', 'duygu, his'],
  ['感动', 'gǎndòng', 'adjective', 'moved, touched; to move', 'duygulandırmak, dokunaklı'],
  ['赶紧', 'gǎnjǐn', 'adverb', 'quickly, promptly', 'hemen, aceleyle'],
  ['感觉', 'gǎnjué', 'noun', 'feeling, sense; to feel', 'his, duygu, hissetmek'],
  ['赶快', 'gǎnkuài', 'adverb', 'quickly, at once', 'hemen, çabuk'],
  ['感情', 'gǎnqíng', 'noun', 'emotion, feeling', 'duygu, his'],
  ['感人', 'gǎnrén', 'adjective', 'touching, moving', 'dokunaklı, duygulandırıcı'],
  ['赶上', 'gǎnshàng', 'verb', 'to catch up, to keep up with', 'yetişmek'],
  ['感受', 'gǎnshòu', 'noun', 'feeling, experience; to feel', 'his, duygu, deneyim'],
  ['感谢', 'gǎnxiè', 'verb', 'to thank', 'teşekkür etmek'],
  ['干活儿', 'gànhuór', 'verb', 'to work', 'çalışmak, iş yapmak'],
  ['钢琴', 'gāngqín', 'noun', 'piano', 'piyano'],
  ['高价', 'gāojià', 'noun', 'high price', 'yüksek fiyat'],
  ['高考', 'gāokǎo', 'noun', 'Gaokao, college entrance examination', 'üniversite giriş sınavı'],
  ['高速', 'gāosù', 'adjective', 'high speed', 'yüksek hız'],
  ['高温', 'gāowēn', 'noun', 'high temperature', 'yüksek sıcaklık'],
  ['高于', 'gāoyú', 'verb', 'higher than, above', 'daha yüksek olmak'],
  ['胳膊', 'gēbo', 'noun', 'arm', 'kol'],
  ['歌声', 'gēshēng', 'noun', 'sound of singing, song', 'şarkı sesi'],
  ['歌手', 'gēshǒu', 'noun', 'singer', 'şarkıcı'],
  ['各', 'gè', 'pronoun', 'each, every', 'her, çeşitli'],
  ['各地', 'gèdì', 'noun', 'various places', 'çeşitli yerler'],
  ['各个', 'gègè', 'pronoun', 'each, every; one by one', 'her biri, tek tek'],
  ['各位', 'gèwèi', 'pronoun', 'everyone, all (respectful)', 'hepiniz'],
  ['各种', 'gèzhǒng', 'pronoun', 'various kinds, all kinds', 'çeşit çeşit, her türlü'],
  ['更加', 'gèngjiā', 'adverb', 'more, even more', 'daha da'],
  ['工厂', 'gōngchǎng', 'noun', 'factory', 'fabrika'],
  ['功夫', 'gōngfu', 'noun', 'kung fu, skill, effort', 'kung fu, beceri, çaba'],
  ['公共', 'gōnggòng', 'adjective', 'public, common', 'kamusal, ortak'],
  ['功课', 'gōngkè', 'noun', 'schoolwork, homework', 'ödev, ders çalışma'],
  ['公里', 'gōnglǐ', 'classifier', 'kilometer', 'kilometre'],
  ['公路', 'gōnglù', 'noun', 'highway, road', 'karayolu, otoyol'],
  ['工人', 'gōngrén', 'noun', 'worker', 'işçi'],
  ['工资', 'gōngzī', 'noun', 'wage, salary', 'maaş, ücret'],
  ['共', 'gòng', 'adverb', 'together, in total', 'birlikte, toplamda'],
  ['共同', 'gòngtóng', 'adjective', 'common, joint', 'ortak, müşterek'],
  ['够', 'gòu', 'adverb', 'enough; sufficiently', 'yeterli'],
  ['购买', 'gòumǎi', 'verb', 'to purchase', 'satın almak'],
  ['购物', 'gòuwù', 'verb', 'to shop', 'alışveriş yapmak'],
  ['估计', 'gūjì', 'verb', 'to estimate, to guess', 'tahmin etmek'],
  ['姑娘', 'gūniang', 'noun', 'girl', 'kız, genç kız'],
  ['鼓励', 'gǔlì', 'verb', 'to encourage', 'teşvik etmek, cesaretlendirmek'],
  ['顾客', 'gùkè', 'noun', 'customer', 'müşteri'],
  ['故意', 'gùyì', 'adverb', 'deliberately, on purpose', 'kasıtlı olarak, bilerek'],
  ['挂', 'guà', 'verb', 'to hang, to suspend', 'asmak'],
  ['关键', 'guānjiàn', 'adjective', 'key, crucial', 'kilit, önemli'],
  ['观看', 'guānkàn', 'verb', 'to watch, to view', 'izlemek, seyretmek'],
  ['观众', 'guānzhòng', 'noun', 'audience', 'seyirci, izleyici'],
  ['管', 'guǎn', 'verb', 'control, manage', 'yönetmek, kontrol etmek'],
  ['管理', 'guǎnlǐ', 'verb', 'manage', 'yönetmek'],
  ['光', 'guāng', 'noun', 'light; smooth; only', 'ışık; pürüzsüz; sadece'],
  ['广播', 'guǎngbō', 'noun', 'broadcast', 'yayın, radyo'],
  ['广告', 'guǎnggào', 'noun', 'advertisement', 'reklam'],
  ['逛', 'guàng', 'verb', 'stroll, roam, browse', 'gezmek, dolaşmak'],
  ['规定', 'guīdìng', 'noun', 'regulation, rule', 'kural, düzenleme'],
  ['国籍', 'guójí', 'noun', 'nationality', 'uyruk, milliyet'],
  ['国际', 'guójì', 'adjective', 'international', 'uluslararası'],
  ['果汁', 'guǒzhī', 'noun', 'fruit juice', 'meyve suyu'],
  ['过程', 'guòchéng', 'noun', 'process', 'süreç'],
  ['海洋', 'hǎiyáng', 'noun', 'ocean, sea', 'okyanus, deniz'],
  ['害羞', 'hàixiū', 'adjective', 'shy, bashful', 'utangaç'],
  ['寒假', 'hánjià', 'noun', 'winter vacation', 'kış tatili'],
  ['寒冷', 'hánlěng', 'adjective', 'cold, frigid, chilly', 'soğuk, dondurucu'],
  ['喊', 'hǎn', 'verb', 'shout', 'bağırmak, haykırmak'],
  ['汗', 'hàn', 'noun', 'sweat', 'ter'],
  ['航班', 'hángbān', 'noun', 'flight', 'uçuş, sefer'],
  ['好处', 'hǎochù', 'noun', 'benefit', 'fayda, avantaj'],
  ['好好', 'hǎohǎo', 'adverb', 'well, thoroughly', 'iyice, düzgünce'],
  ['好笑', 'hǎoxiào', 'adjective', 'funny, ridiculous', 'komik, gülünç'],
  ['合格', 'hégé', 'adjective', 'qualified', 'nitelikli, yeterli'],
  ['盒子', 'hézi', 'noun', 'box', 'kutu'],
  ['红包', 'hóngbāo', 'noun', 'red envelope, red packet', 'kırmızı zarf (para hediyesi)'],
  ['厚', 'hòu', 'adjective', 'thick', 'kalın'],
  ['后悔', 'hòuhuǐ', 'verb', 'regret', 'pişman olmak'],
  ['忽然', 'hūrán', 'adverb', 'suddenly', 'birdenbire, aniden'],
  ['互联网', 'hùliánwǎng', 'noun', 'Internet', 'internet'],
  ['护士', 'hùshi', 'noun', 'nurse', 'hemşire'],
  ['互相', 'hùxiāng', 'adverb', 'each other', 'birbirine'],
  ['话剧', 'huàjù', 'noun', 'drama', 'tiyatro oyunu'],
  ['怀疑', 'huáiyí', 'verb', 'doubt', 'şüphelenmek, kuşkulanmak'],
  ['坏处', 'huàichù', 'noun', 'disadvantage, harm', 'dezavantaj, zarar'],
  ['环保', 'huánbǎo', 'noun', 'environmental protection', 'çevre koruma'],
  ['换乘', 'huànchéng', 'verb', 'transfer, change', 'aktarma yapmak'],
  ['回复', 'huífù', 'verb', 'reply', 'cevap vermek'],
  ['回信', 'huíxìn', 'verb', 'reply to a letter, write back', 'mektuba cevap vermek'],
  ['回忆', 'huíyì', 'noun', 'memory', 'anı, hatıra'],
  ['会员', 'huìyuán', 'noun', 'membership', 'üyelik'],
  ['活', 'huó', 'verb', 'live; alive', 'yaşamak; canlı'],
  ['活动', 'huódòng', 'noun', 'activity, event', 'etkinlik, faaliyet'],
  ['活泼', 'huópō', 'adjective', 'lively', 'canlı, neşeli'],
  ['火', 'huǒ', 'noun', 'fire; popular, hot', 'ateş; popüler'],
  ['货', 'huò', 'noun', 'goods, commodity', 'mal, emtia'],
  ['获得', 'huòdé', 'verb', 'get, obtain', 'elde etmek, kazanmak'],
  ['获奖', 'huòjiǎng', 'verb', 'win a prize, receive an award', 'ödül almak'],
  ['获取', 'huòqǔ', 'verb', 'gain, obtain', 'edinmek, elde etmek'],
  ['基本', 'jīběn', 'adjective', 'basic, fundamental, essential', 'temel, esas'],
  ['基本上', 'jīběnshàng', 'adverb', 'basically', 'temelde, esasen'],
  ['基础', 'jīchǔ', 'noun', 'basics', 'temel, altyapı'],
  ['激动', 'jīdòng', 'adjective', 'excited, agitated', 'heyecanlı, coşkulu'],
  ['积极', 'jījí', 'adjective', 'positive', 'olumlu, aktif'],
  ['积累', 'jīlěi', 'verb', 'to accumulate, to build up', 'biriktirmek, birikmek'],
  ['及时', 'jíshí', 'adverb', 'timely, prompt, in time', 'zamanında, vakitli'],
  ['即使', 'jíshǐ', 'conjunction', 'even if', 'olsa bile'],
  ['既', 'jì', 'conjunction', 'both ... and ...', 'hem...hem de'],
  ['寄', 'jì', 'verb', 'send', 'göndermek (posta)'],
  ['计划', 'jìhuà', 'noun', 'plan, project', 'plan, proje'],
  ['既然', 'jìrán', 'conjunction', 'since', 'madem ki'],
  ['技术', 'jìshù', 'noun', 'technology', 'teknoloji'],
  ['继续', 'jìxù', 'verb', 'continue', 'devam etmek'],
  ['记者', 'jìzhě', 'noun', 'reporter', 'gazeteci, muhabir'],
  ['加班', 'jiābān', 'verb', 'work overtime', 'fazla mesai yapmak'],
  ['家具', 'jiājù', 'noun', 'furniture', 'mobilya'],
  ['加快', 'jiākuài', 'verb', 'speed up, accelerate', 'hızlandırmak'],
  ['加强', 'jiāqiáng', 'verb', 'strengthen, reinforce', 'güçlendirmek'],
  ['加入', 'jiārù', 'verb', 'add, join, become a member', 'katılmak, eklemek'],
  ['加上', 'jiāshàng', 'conjunction', 'plus, add, with the addition of', 'artı, ekleyerek'],
  ['家庭', 'jiātíng', 'noun', 'family', 'aile'],
  ['家乡', 'jiāxiāng', 'noun', 'hometown', 'memleket'],
  ['加油', 'jiāyóu', 'verb', 'make an all-out effort, cheer on', 'hadi, destek ver'],
  ['加油站', 'jiāyóuzhàn', 'noun', 'gas station', 'benzin istasyonu'],
  ['家长', 'jiāzhǎng', 'noun', 'parent, head of the family', 'veli, aile reisi'],
  ['假', 'jiǎ, jià', 'adjective', 'false, fake', 'sahte, yanlış'],
  ['价格', 'jiàgé', 'noun', 'price', 'fiyat'],
  ['价钱', 'jiàqián', 'noun', 'price', 'fiyat'],
  ['假日', 'jiàrì', 'noun', 'holiday, day off, vacation', 'tatil günü'],
  ['减', 'jiǎn', 'verb', 'to reduce, to decrease', 'azaltmak, indirmek'],
  ['减轻', 'jiǎnqīng', 'verb', 'to lighten, to ease, to alleviate', 'hafifletmek'],
  ['减少', 'jiǎnshǎo', 'verb', 'to reduce, to decrease', 'azaltmak'],
  ['健身', 'jiànshēn', 'verb', 'to exercise, to work out', 'egzersiz yapmak, spor yapmak'],
  ['健身房', 'jiànshēnfáng', 'noun', 'gym', 'spor salonu'],
  ['建议', 'jiànyì', 'noun', 'suggestion, proposal', 'öneri; önermek'],
  ['江', 'jiāng', 'noun', 'river', 'nehir'],
  ['将', 'jiāng, jiàng', 'adverb', 'will, shall, be about to', '-ecek, yakında'],
  ['将来', 'jiānglái', 'noun', 'future', 'gelecek'],
  ['将要', 'jiāngyào', 'adverb', 'will, be going to, be about to', 'olmak üzere'],
  ['奖', 'jiǎng', 'noun', 'prize, award, reward', 'ödül'],
  ['奖金', 'jiǎngjīn', 'noun', 'bonus, prize money, cash award', 'ikramiye, ödül parası'],
  ['奖学金', 'jiǎngxuéjīn', 'noun', 'scholarship, fellowship', 'burs'],
  ['降', 'jiàng', 'verb', 'to fall, to drop, to descend', 'inmek, düşmek'],
  ['降低', 'jiàngdī', 'verb', 'to reduce, to lower, to bring down', 'azaltmak, düşürmek'],
  ['降价', 'jiàngjià', 'verb', 'to reduce price', 'fiyat düşürmek, indirim yapmak'],
  ['降落', 'jiàngluò', 'verb', 'to descend, to land, to touch down', 'inmek, alçalmak'],
  ['降温', 'jiàngwēn', 'verb', 'to cool down, to lower the temperature', 'soğumak, sıcaklığı düşürmek'],
  ['交', 'jiāo', 'verb', 'to hand in; to make friends with', 'teslim etmek; arkadaş olmak'],
  ['骄傲', 'jiāoào', 'adjective', 'proud, arrogant; pride', 'gururlu, kibirli; gurur'],
  ['交警', 'jiāojǐng', 'noun', 'traffic police', 'trafik polisi'],
  ['交流', 'jiāoliú', 'verb', 'communicate', 'iletişim kurmak'],
  ['郊区', 'jiāoqū', 'noun', 'suburb', 'banliyö, şehir dışı'],
  ['交通', 'jiāotōng', 'noun', 'traffic', 'trafik, ulaşım'],
  ['教练', 'jiàoliàn', 'noun', 'coach', 'antrenör, koç'],
  ['教师', 'jiàoshī', 'noun', 'teacher', 'öğretmen'],
  ['教授', 'jiàoshòu', 'noun', 'professor', 'profesör'],
  ['教学', 'jiàoxué', 'noun', 'teaching, education', 'öğretmek, eğitim'],
  ['教育', 'jiàoyù', 'noun', 'education; to educate', 'eğitim; eğitmek'],
  ['叫作', 'jiàozuò', 'verb', 'be called, be known as', 'olarak bilinmek'],
  ['街道', 'jiēdào', 'noun', 'street', 'cadde, sokak'],
  ['接受', 'jiēshòu', 'verb', 'accept', 'kabul etmek'],
  ['接着', 'jiēzhe', 'adverb', 'then, next, subsequently', 'ardından, devam ederek'],
  ['结果', 'jiéguǒ', 'noun', 'result, outcome, consequence', 'sonuç'],
  ['节假日', 'jiéjiàrì', 'noun', 'festivals and holidays', 'bayram ve tatil günleri'],
  ['节约', 'jiéyuē', 'verb', 'to save, to economize, to conserve', 'tasarruf etmek'],
  ['结账', 'jiézhàng', 'verb', 'to pay the bill, to settle an account', 'hesabı ödemek'],
  ['解释', 'jiěshì', 'verb', 'to explain, to interpret', 'açıklamak'],
  ['今后', 'jīnhòu', 'noun', 'from now on, in the future', 'bundan sonra'],
  ['仅', 'jǐn', 'adverb', 'only, merely, solely', 'sadece, yalnızca'],
  ['尽管', 'jǐnguǎn', 'conjunction', 'although, even though', 'her ne kadar olsa da'],
  ['仅仅', 'jǐnjǐn', 'adverb', 'only, merely, barely', 'sadece, yalnızca'],
  ['紧张', 'jǐnzhāng', 'adjective', 'nervous, tense', 'gergin, sinirli'],
  ['进入', 'jìnrù', 'verb', 'to enter, to access', 'girmek'],
  ['进行', 'jìnxíng', 'verb', 'to carry out, to conduct', 'yürütmek, gerçekleştirmek'],
  ['禁止', 'jìnzhǐ', 'verb', 'to prohibit, to forbid, to ban', 'yasaklamak'],
  ['精彩', 'jīngcǎi', 'adjective', 'brilliant, splendid, wonderful', 'muhteşem, harika'],
  ['经济', 'jīngjì', 'noun', 'economy; economical', 'ekonomi; ekonomik'],
  ['京剧', 'jīngjù', 'noun', 'Beijing opera', 'Pekin operası'],
  ['经历', 'jīnglì', 'noun', 'experience, past; to experience', 'deneyim; deneyimlemek'],
  ['经验', 'jīngyàn', 'noun', 'experience', 'deneyim'],
  ['警察', 'jǐngchá', 'noun', 'police', 'polis'],
  ['景点', 'jǐngdiǎn', 'noun', 'scenic spot, tourist attraction', 'turistik yer, gezi noktası'],
  ['景区', 'jǐngqū', 'noun', 'scenic area, tourist attraction zone', 'turistik bölge'],
  ['景色', 'jǐngsè', 'noun', 'scenery', 'manzara'],
  ['竟然', 'jìngrán', 'adverb', 'unexpectedly', 'beklenmedik şekilde'],
  ['竞争', 'jìngzhēng', 'verb', 'compete', 'rekabet etmek'],
  ['镜子', 'jìngzi', 'noun', 'mirror', 'ayna'],
  ['究竟', 'jiūjìng', 'adverb', 'actually, exactly, after all', 'aslında, tam olarak'],
  ['就是', 'jiùshì', 'adverb', 'precisely, exactly', 'tam olarak, işte'],
  ['举', 'jǔ', 'verb', 'to raise; to hold; to give an example', 'kaldırmak; düzenlemek; örnek vermek'],
  ['举办', 'jǔbàn', 'verb', 'to hold, to host, to organize', 'düzenlemek, ev sahipliği yapmak'],
  ['举例', 'jǔlì', 'verb', 'to give an example', 'örnek vermek'],
  ['举行', 'jǔxíng', 'verb', 'to hold, to convene, to conduct', 'düzenlemek, gerçekleştirmek'],
  ['聚', 'jù', 'verb', 'to gather, to assemble', 'toplanmak'],
  ['聚餐', 'jùcān', 'verb', 'to have a dinner together', 'birlikte yemek yemek'],
  ['聚会', 'jùhuì', 'noun', 'party, gathering; to get together', 'parti; bir araya gelmek'],
  ['拒绝', 'jùjué', 'verb', 'to refuse, to reject, to decline', 'reddetmek'],
  ['距离', 'jùlí', 'noun', 'distance, gap', 'mesafe, uzaklık'],
  ['剧院', 'jùyuàn', 'noun', 'theater, opera house', 'tiyatro'],
  ['开玩笑', 'kāiwánxiào', 'verb', 'make fun of, to joke', 'şaka yapmak'],
  ['看法', 'kànfǎ', 'noun', 'view', 'görüş, fikir'],
  ['烤', 'kǎo', 'verb', 'to bake, to roast, to grill', 'pişirmek, fırınlamak'],
  ['考虑', 'kǎolǜ', 'verb', 'to consider, to think over', 'düşünmek, değerlendirmek'],
  ['考生', 'kǎoshēng', 'noun', 'examinee', 'sınav adayı'],
  ['棵', 'kē', 'classifier', 'measure word for trees, plants', 'ağaç sayacı'],
  ['科技', 'kējì', 'noun', 'science and technology', 'bilim ve teknoloji'],
  ['科学', 'kēxué', 'noun', 'science; scientific', 'bilim; bilimsel'],
  ['咳', 'ké', 'verb', 'to cough', 'öksürmek'],
  ['咳嗽', 'késou', 'verb', 'to cough', 'öksürmek'],
  ['可惜', 'kěxī', 'adjective', 'regrettable, unfortunate, a pity', 'yazık, ne yazık ki'],
  ['克', 'kè', 'classifier', 'gram', 'gram'],
  ['课程', 'kèchéng', 'noun', 'curriculum', 'müfredat, ders programı'],
  ['客气', 'kèqi', 'adjective', 'polite, courteous', 'nazik, kibar'],
  ['课堂', 'kètáng', 'noun', 'classroom', 'sınıf'],
  ['客厅', 'kètīng', 'noun', 'living room, parlor', 'oturma odası, salon'],
  ['肯定', 'kěndìng', 'adverb', 'surely, certainly, definitely', 'kesinlikle, elbette'],
  ['空', 'kōng, kòng', 'adjective', 'empty, vacant', 'boş, tenha'],
  ['空', 'kōng, kòng', 'verb', 'to leave empty, to make free time; free time', 'boş bırakmak; boş vakit'],
  ['空气', 'kōngqì', 'noun', 'atmosphere, air', 'hava, atmosfer'],
  ['恐怕', 'kǒngpà', 'adverb', 'I am afraid, perhaps, maybe', 'korkarım ki, belki'],
  ['口语', 'kǒuyǔ', 'noun', 'spoken language', 'konuşma dili'],
  ['苦', 'kǔ', 'adjective', 'bitter', 'acı'],
  ['快餐', 'kuàicān', 'noun', 'fast food', 'fast food, hazır yemek'],
  ['快递', 'kuàidì', 'noun', 'express delivery', 'kargo, hızlı teslimat'],
  ['快速', 'kuàisù', 'adjective', 'fast, high-speed', 'hızlı'],
  ['困', 'kùn', 'adjective', 'sleepy, tired', 'uykulu, yorgun'],
  ['困难', 'kùnnan', 'noun', 'difficulty; difficult', 'zorluk; zor'],
  ['拉', 'lā', 'verb', 'to pull, to drag', 'çekmek'],
  ['垃圾', 'lājī', 'noun', 'garbage, trash, rubbish', 'çöp'],
  ['辣', 'là', 'adjective', 'hot, spicy', 'acılı, baharatlı'],
  ['来不及', 'láibují', 'verb', 'there is not enough time', 'yetişmek mümkün değil'],
  ['来得及', 'láidejí', 'verb', 'there is still time, can make it in time', 'hâlâ zaman var, yetişebilir'],
  ['懒', 'lǎn', 'adjective', 'lazy, idle', 'tembel'],
  ['浪费', 'làngfèi', 'verb', 'to waste, to squander', 'israf etmek'],
  ['浪漫', 'làngmàn', 'adjective', 'romantic', 'romantik'],
  ['老虎', 'lǎohǔ', 'noun', 'tiger', 'kaplan'],
  ['老家', 'lǎojiā', 'noun', 'hometown, home state', 'memleket'],
  ['老年', 'lǎonián', 'noun', 'elderly', 'yaşlılık, ihtiyarlık'],
  ['老是', 'lǎoshì', 'adverb', 'always, constantly', 'hep, sürekli'],
  ['冷静', 'lěngjìng', 'adjective', 'calm, cool-headed', 'sakin, soğukkanlı'],
  ['理发', 'lǐfà', 'verb', 'to have a haircut, to cut hair', 'saç kestirmek'],
  ['理解', 'lǐjiě', 'verb', 'to understand, to comprehend', 'anlamak, kavramak'],
  ['礼貌', 'lǐmào', 'adjective', 'courtesy, politeness; polite', 'nezaket; kibar'],
  ['理想', 'lǐxiǎng', 'noun', 'ideal, dream; ideal', 'ideal, hayal; ideal'],
  ['厉害', 'lìhai', 'adjective', 'severe, fierce, impressive, excellent', 'şiddetli; etkileyici, harika'],
  ['力气', 'lìqi', 'noun', 'strength, physical power', 'güç, kuvvet'],
  ['例如', 'lìrú', 'verb', 'for example, such as', 'örneğin'],
  ['例子', 'lìzi', 'noun', 'example, instance', 'örnek'],
  ['俩', 'liǎ', 'number', 'two, both', 'ikisi, ikisi de'],
  ['连', 'lián', 'preposition', 'even, including', 'bile, dahil'],
  ['联系', 'liánxì', 'verb', 'to contact, to connect', 'iletişim kurmak'],
  ['凉', 'liáng', 'adjective', 'cool, cold', 'serin, soğuk'],
  ['量', 'liàng, liáng', 'verb', 'to measure, to weigh', 'ölçmek, tartmak'],
  ['两', 'liǎng', 'classifier', 'two; measure word for paired things', 'iki; çift sayacı'],
  ['亮', 'liàng', 'adjective', 'bright, light', 'parlak, aydınlık'],
  ['列', 'liè', 'verb', 'to list; measure word for rows', 'sıralamak; sıra sayacı'],
  ['零下', 'língxià', 'noun', 'below zero', 'sıfırın altında'],
  ['零花钱', 'línghuāqián', 'noun', 'pocket money, spending money', 'harçlık'],
  ['零钱', 'língqián', 'noun', 'change, small denominations of money', 'bozuk para'],
  ['零食', 'língshí', 'noun', 'snacks, between-meal nibbles', 'atıştırmalık'],
  ['另', 'lìng', 'pronoun', 'other, another', 'diğer, başka'],
  ['另外', 'lìngwài', 'conjunction', 'in addition, moreover; other', 'bunun dışında; diğer'],
  ['留', 'liú', 'verb', 'to stay, to remain, to keep', 'kalmak, tutmak'],
  ['流', 'liú', 'verb', 'to flow, to circulate', 'akmak'],
  ['流利', 'liúlì', 'adjective', 'fluent, smooth', 'akıcı'],
  ['留下', 'liúxia', 'verb', 'to leave behind, to remain', 'geride bırakmak'],
  ['流行', 'liúxíng', 'verb', 'to be popular, to be in fashion', 'popüler olmak, yaygın olmak'],
  ['路过', 'lùguò', 'verb', 'to pass by, to go by', 'yanından geçmek'],
  ['旅馆', 'lǚguǎn', 'noun', 'hotel, inn', 'otel, han'],
  ['旅客', 'lǚkè', 'noun', 'traveler, passenger', 'yolcu, gezgin'],
  ['旅行', 'lǚxíng', 'verb', 'to travel', 'seyahat etmek'],
  ['律师', 'lǜshī', 'noun', 'lawyer, attorney', 'avukat'],
  ['乱', 'luàn', 'adjective', 'messy, disorderly', 'dağınık, düzensiz'],
  ['落', 'luò, là, lào', 'verb', 'to fall, to drop, to land', 'düşmek, inmek'],
  ['麻烦', 'máfan', 'noun', 'troublesome; trouble', 'zahmetli; sorun'],
  ['馒头', 'mántou', 'noun', 'steamed bun, mantou', 'buharda pişmiş ekmek'],
  ['满', 'mǎn', 'adjective', 'full, filled', 'dolu'],
  ['毛巾', 'máojīn', 'noun', 'towel', 'havlu'],
  ['毛衣', 'máoyī', 'noun', 'sweater, woolen garment', 'kazak, yünlü'],
  ['帽子', 'màozi', 'noun', 'hat, cap', 'şapka'],
  ['美', 'měi', 'adjective', 'beautiful, pretty', 'güzel'],
  ['美好', 'měihǎo', 'adjective', 'beautiful, splendid', 'güzel, harika'],
  ['美景', 'měijǐng', 'noun', 'beautiful scenery', 'güzel manzara'],
  ['美丽', 'měilì', 'adjective', 'beautiful, lovely', 'güzel, hoş'],
  ['美食', 'měishí', 'noun', 'delicious food, cuisine', 'lezzetli yemek'],
  ['梦', 'mèng', 'noun', 'dream; to dream', 'rüya; rüya görmek'],
  ['梦想', 'mèngxiǎng', 'noun', 'dream; to dream', 'hayal; hayal etmek'],
  ['密码', 'mìmǎ', 'noun', 'password, PIN code', 'şifre, parola'],
  ['免费', 'miǎnfèi', 'verb', 'free of charge, to be free', 'ücretsiz'],
  ['面对', 'miànduì', 'verb', 'to face, to confront', 'yüz yüze gelmek, karşılaşmak'],
  ['面试', 'miànshì', 'noun', 'interview, audition', 'mülakat'],
  ['秒', 'miǎo', 'classifier', 'second, unit of time', 'saniye'],
  ['民族', 'mínzú', 'noun', 'ethnic group, nationality', 'etnik grup, millet'],
  ['末', 'mò', 'noun', 'end, last', 'son, nihayet'],
  ['母女', 'mǔnǚ', 'noun', 'mother and daughter', 'anne ve kız'],
  ['母亲', 'mǔqīn', 'noun', 'mother', 'anne'],
  ['母子', 'mǔzǐ', 'noun', 'mother and son', 'anne ve oğul'],
  ['目标', 'mùbiāo', 'noun', 'goal, target, objective', 'hedef, amaç'],
  ['目的', 'mùdì', 'noun', 'purpose, aim, goal', 'amaç, gaye'],
  ['目的地', 'mùdìdì', 'noun', 'destination', 'varış noktası'],
  ['目前', 'mùqián', 'noun', 'currently, at present', 'şu anda, şu sıralar'],
  ['耐心', 'nàixīn', 'noun', 'patient; patience', 'sabırlı; sabır'],
  ['南部', 'nánbù', 'noun', 'southern part, south', 'güney bölgesi'],
  ['难道', 'nándào', 'adverb', 'could it be that...?', 'masa ki, acaba'],
  ['男士', 'nánshì', 'noun', 'man, gentleman', 'erkek, bay'],
  ['难受', 'nánshòu', 'adjective', 'uncomfortable, painful', 'rahatsız, acı veren'],
  ['难忘', 'nánwàng', 'verb', 'unforgettable, hard to forget', 'unutulmaz'],
  ['男性', 'nánxìng', 'noun', 'male, masculine', 'erkek, eril'],
  ['内', 'nèi', 'noun', 'inside, within', 'içinde, içeri'],
  ['内容', 'nèiróng', 'noun', 'content, substance', 'içerik'],
  ['内心', 'nèixīn', 'noun', 'heart, inner self', 'iç dünya, kalp'],
  ['能否', 'néngfǒu', 'adverb', 'whether or not, can or cannot', 'yapıp yapamayacağını, olup olmadığını'],
  ['能够', 'nénggòu', 'verb', 'can, be able to, be capable of', 'yapabilmek'],
  ['能力', 'nénglì', 'noun', 'ability, capability, capacity', 'yetenek, kapasite'],
  ['嗯', 'ǹg', 'interjection', 'uh-huh, hmm', 'hı-hı, hmm'],
  ['年底', 'niándǐ', 'noun', 'end of the year', 'yıl sonu'],
  ['年龄', 'niánlíng', 'noun', 'age', 'yaş'],
  ['农村', 'nóngcūn', 'noun', 'rural area, countryside', 'kırsal bölge, köy'],
  ['弄', 'nòng', 'verb', 'to do, to handle, to mess with', 'yapmak, halletmek'],
  ['女性', 'nǚxìng', 'noun', 'female, feminine', 'kadın, dişil'],
  ['暖和', 'nuǎnhuo', 'adjective', 'warm; to warm up', 'ılık, sıcacık'],
  ['偶尔', 'ǒuěr', 'adverb', 'occasionally, sometimes', 'ara sıra, bazen'],
  ['拍', 'pāi', 'verb', 'to pat, to clap; to take a photo', 'vurmak; fotoğraf çekmek'],
  ['排', 'pái', 'noun', 'row, line; to line up', 'sıra; sıraya girmek'],
  ['牌', 'pái', 'noun', 'card, brand, plaque, sign', 'kart, marka'],
  ['排队', 'páiduì', 'verb', 'to line up, to queue up', 'sıraya girmek'],
  ['排球', 'páiqiú', 'noun', 'volleyball', 'voleybol'],
  ['牌子', 'páizi', 'noun', 'brand, sign, label', 'marka, tabela'],
  ['判断', 'pànduàn', 'verb', 'to judge, to determine', 'yargılamak, değerlendirmek'],
  ['陪', 'péi', 'verb', 'to accompany, to keep someone company', 'eşlik etmek'],
  ['批评', 'pīpíng', 'verb', 'to criticize', 'eleştirmek'],
  ['皮肤', 'pífū', 'noun', 'skin', 'cilt, deri'],
  ['脾气', 'píqi', 'noun', 'temperament, disposition, temper', 'huy, mizaç'],
  ['皮鞋', 'píxié', 'noun', 'leather shoes', 'deri ayakkabı'],
  ['篇', 'piān', 'classifier', 'measure word for essays, articles', 'makale sayacı'],
  ['片', 'piàn', 'classifier', 'piece, slice, area', 'parça, dilim'],
  ['乒乓球', 'pīngpāngqiú', 'noun', 'table tennis, ping-pong', 'masa tenisi'],
  ['平常', 'píngcháng', 'adjective', 'ordinary, usual', 'olağan, normal'],
  ['破', 'pò', 'adjective', 'broken, damaged', 'kırık, hasarlı'],
  ['葡萄', 'pútao', 'noun', 'grape', 'üzüm'],
  ['葡萄酒', 'pútaojiǔ', 'noun', 'wine, grape wine', 'şarap'],
  ['普遍', 'pǔbiàn', 'adjective', 'widespread, universal, common', 'yaygın, evrensel'],
  ['普通', 'pǔtōng', 'adjective', 'ordinary, common', 'sıradan, olağan'],
  ['普通话', 'pǔtōnghuà', 'noun', 'Mandarin Chinese, standard Chinese', 'Mandarin Çincesi'],
  ['期', 'qī', 'classifier', 'period, phase; measure word for issues', 'dönem, periyot'],
  ['期末', 'qīmò', 'noun', 'end of term, end of semester', 'dönem sonu'],
  ['期中', 'qīzhōng', 'noun', 'midterm, middle of the term', 'dönem ortası'],
  ['其次', 'qícì', 'pronoun', 'next, secondly, then', 'ikinci olarak, sıra ile'],
  ['其中', 'qízhōng', 'noun', 'among them, inside', 'aralarında, içinde'],
  ['起到', 'qǐdào', 'verb', 'to play the role of, to function as', 'rolünü oynamak'],
  ['气', 'qì', 'noun', 'air, gas, breath; to anger', 'hava, gaz; kızdırmak'],
  ['气候', 'qìhòu', 'noun', 'climate', 'iklim'],
  ['汽水', 'qìshuǐ', 'noun', 'soda, soft drink', 'gazlı içecek'],
  ['气温', 'qìwēn', 'noun', 'air temperature', 'hava sıcaklığı'],
  ['千克', 'qiānkè', 'classifier', 'kilogram', 'kilogram'],
  ['千万', 'qiānwàn', 'adverb', 'by all means, absolutely', 'kesinlikle, mutlaka'],
  ['签证', 'qiānzhèng', 'noun', 'visa; to issue a visa', 'vize'],
  ['前方', 'qiánfāng', 'noun', 'ahead, front', 'önde, ileride'],
  ['前后', 'qiánhòu', 'noun', 'front and back; around, about', 'önü ve arkası; yaklaşık'],
  ['强', 'qiáng, qiǎng, jiàng', 'adjective', 'strong, powerful', 'güçlü, kuvvetli'],
  ['敲', 'qiāo', 'verb', 'to knock, to tap, to strike', 'vurmak, çalmak'],
  ['桥', 'qiáo', 'noun', 'bridge', 'köprü'],
  ['巧', 'qiǎo', 'adjective', 'skillful, clever, opportune', 'becerili, ustaca'],
  ['巧克力', 'qiǎokèlì', 'noun', 'chocolate', 'çikolata'],
  ['亲戚', 'qīnqi', 'noun', 'relative, relative family member', 'akraba'],
  ['琴', 'qín', 'noun', 'musical instrument, piano', 'müzik aleti, piyano'],
  ['轻', 'qīng', 'adjective', 'light, not heavy, gentle, easy', 'hafif; nazik'],
  ['青年', 'qīngnián', 'noun', 'youth, young people', 'genç, gençlik'],
  ['轻松', 'qīngsōng', 'adjective', 'relaxed, light, easy', 'rahat, kolay'],
  ['情况', 'qíngkuàng', 'noun', 'situation, circumstance', 'durum, koşul'],
  ['庆祝', 'qìngzhù', 'verb', 'to celebrate', 'kutlamak'],
  ['球队', 'qiúduì', 'noun', 'sports team, ball team', 'spor takımı'],
  ['球迷', 'qiúmí', 'noun', 'fan, sports enthusiast', 'taraftar, fan'],
  ['区', 'qū', 'noun', 'district, area, region', 'ilçe, bölge'],
  ['区别', 'qūbié', 'noun', 'difference; to distinguish', 'fark, ayrım'],
  ['取', 'qǔ', 'verb', 'to take, to get, to obtain', 'almak'],
  ['取得', 'qǔdé', 'verb', 'to obtain, to gain', 'elde etmek'],
  ['取消', 'qǔxiāo', 'verb', 'to cancel, to call off', 'iptal etmek'],
  ['全', 'quán', 'adjective', 'whole, entire; completely', 'tüm; tamamen'],
  ['全部', 'quánbù', 'noun', 'all, the whole thing', 'tamamı, hepsi'],
  ['全都', 'quándōu', 'adverb', 'all, entirely', 'hepsi'],
  ['全球', 'quánqiú', 'noun', 'the whole world, global', 'küresel, dünya geneli'],
  ['全身', 'quánshēn', 'noun', 'whole body', 'tüm vücut'],
  ['缺', 'quē', 'verb', 'to lack, to be short of', 'eksik olmak'],
  ['缺点', 'quēdiǎn', 'noun', 'shortcoming, defect', 'eksiklik, kusur'],
  ['缺少', 'quēshǎo', 'verb', 'to lack, to be short of', 'yetersiz olmak'],
  ['却', 'què', 'adverb', 'but, yet, however', 'ama, oysa'],
  ['确实', 'quèshí', 'adverb', 'indeed, really', 'gerçekten'],
  ['然而', 'ráněr', 'conjunction', 'however, but', 'ancak, oysa'],
  ['热闹', 'rènao', 'adjective', 'lively, bustling', 'canlı, hareketli'],
  ['人生', 'rénshēng', 'noun', 'life', 'hayat, yaşam'],
  ['人数', 'rénshù', 'noun', 'number of people', 'kişi sayısı'],
  ['人员', 'rényuán', 'noun', 'personnel, staff', 'personel, çalışanlar'],
  ['任何', 'rènhé', 'pronoun', 'any, whatever', 'herhangi, her ne'],
  ['任务', 'rènwu', 'noun', 'task, assignment, mission', 'görev'],
  ['扔', 'rēng', 'verb', 'to throw, to toss', 'atmak, fırlatmak'],
  ['仍', 'réng', 'adverb', 'still, yet', 'hâlâ, yine de'],
  ['仍然', 'réngrán', 'adverb', 'still, yet', 'hâlâ, yine de'],
  ['日常', 'rìcháng', 'adjective', 'daily, everyday', 'günlük, her günkü'],
  ['日记', 'rìjì', 'noun', 'diary', 'günlük, diyari'],
  ['日期', 'rìqī', 'noun', 'date', 'tarih'],
  ['日子', 'rìzi', 'noun', 'day, life, time', 'gün, yaşam'],
  ['入', 'rù', 'verb', 'to enter, to go in', 'girmek'],
  ['入口', 'rùkǒu', 'noun', 'entrance', 'giriş'],
  ['入学', 'rùxué', 'verb', 'to enter school, to enroll', 'okula kaydolmak'],
  ['入住', 'rùzhù', 'verb', 'to check in, to move in', 'giriş yapmak'],
  ['散步', 'sànbù', 'verb', 'to take a walk, to stroll', 'yürüyüşe çıkmak'],
  ['扫码', 'sǎomǎ', 'verb', 'to scan a code', 'kod taramak'],
  ['森林', 'sēnlín', 'noun', 'forest', 'orman'],
  ['商量', 'shāngliang', 'verb', 'to discuss, to consult', 'tartışmak, danışmak'],
  ['商品', 'shāngpǐn', 'noun', 'product, commodity', 'ürün, mal'],
  ['伤心', 'shāngxīn', 'adjective', 'sad, heartbroken', 'üzgün, kalbı kırık'],
  ['上门', 'shàngmén', 'verb', 'to visit, to go to someones house', 'kapıya gelmek, ziyaret etmek'],
  ['稍', 'shāo', 'adverb', 'a little, slightly', 'biraz, hafifçe'],
  ['稍微', 'shāowēi', 'adverb', 'a little, slightly', 'biraz, hafifçe'],
  ['少见', 'shǎojiàn', 'adjective', 'rare, seldom seen', 'nadir, az görülen'],
  ['少量', 'shǎoliàng', 'adjective', 'small amount, a little', 'az miktarda'],
  ['少数', 'shǎoshù', 'noun', 'minority, small number', 'azınlık'],
  ['少年', 'shàonián', 'noun', 'juvenile, teenager, youth', 'genç, ergen'],
  ['社会', 'shèhuì', 'noun', 'society, community', 'toplum'],
  ['摄氏度', 'shèshìdù', 'classifier', 'degrees Celsius', 'santigrat derece'],
  ['身', 'shēn', 'noun', 'body, oneself', 'vücut, beden'],
  ['深', 'shēn', 'adjective', 'deep, profound', 'derin'],
  ['身份证', 'shēnfènzhèng', 'noun', 'ID card, identification card', 'kimlik kartı'],
  ['申请', 'shēnqǐng', 'verb', 'to apply, to file an application', 'başvurmak'],
  ['甚至', 'shènzhì', 'conjunction', 'even, so much as that', 'hatta, bile'],
  ['生', 'shēng', 'verb', 'to give birth, to produce, to grow', 'doğurmak, üretmek'],
  ['生', 'shēng', 'adjective', 'raw, uncooked, unripe; unfamiliar', 'çiğ, pişmemiş; yabancı'],
  ['生命', 'shēngmìng', 'noun', 'life', 'yaşam, hayat'],
  ['生意', 'shēngyi', 'noun', 'business, trade', 'iş, ticaret'],
  ['省', 'shěng, xǐng', 'noun', 'province', 'il, eyalet'],
  ['剩', 'shèng', 'verb', 'to be left over, to remain', 'artmak, geri kalmak'],
  ['失败', 'shībài', 'verb', 'to fail; failed, unsuccessful', 'başarısız olmak; başarısız'],
  ['师傅', 'shīfu', 'noun', 'master, skilled worker', 'usta, hoca'],
  ['失去', 'shīqù', 'verb', 'to lose, to be lost', 'kaybetmek'],
  ['师生', 'shīshēng', 'noun', 'teacher and student', 'öğretmen ve öğrenci'],
  ['失望', 'shīwàng', 'adjective', 'to be disappointed; disappointed', 'hayal kırıklığına uğramak; hayal kırıklığı'],
  ['十分', 'shífēn', 'adverb', 'very, extremely, fully', 'çok, son derece'],
  ['实际', 'shíjì', 'adjective', 'reality, actuality; actual, practical', 'gerçek, pratik'],
  ['时间表', 'shíjiānbiǎo', 'noun', 'schedule, timetable', 'program, zaman çizelgesi'],
  ['实际上', 'shíjìshàng', 'adverb', 'actually, in fact', 'aslında, gerçekte'],
  ['食品', 'shípǐn', 'noun', 'food, provisions', 'gıda, besin'],
  ['食堂', 'shítáng', 'noun', 'cafeteria, dining hall', 'yemekhane'],
  ['食物', 'shíwù', 'noun', 'food', 'yemek, gıda'],
  ['实在', 'shízài', 'adverb', 'honest, reliable; really, indeed', 'dürüst; gerçekten'],
  ['十字路口', 'shízìlùkǒu', 'noun', 'intersection, crossroads', 'kavşak, yol ayrımı'],
  ['使', 'shǐ', 'verb', 'to make, to cause, to use', 'sağlamak, neden olmak'],
  ['使馆', 'shǐguǎn', 'noun', 'embassy', 'büyükelçilik'],
  ['使用', 'shǐyòng', 'verb', 'to use, to employ', 'kullanmak'],
  ['市场', 'shìchǎng', 'noun', 'market, marketplace', 'pazar, piyasa'],
  ['是否', 'shìfǒu', 'adverb', 'whether or not, if', 'olup olmadığı'],
  ['适合', 'shìhé', 'verb', 'to suit, to fit, to be suitable', 'uymak, uygun olmak'],
  ['世纪', 'shìjì', 'noun', 'century', 'yüzyıl'],
  ['视频', 'shìpín', 'noun', 'video, video clip', 'video'],
  ['市区', 'shìqū', 'noun', 'urban area, city center', 'şehir merkezi'],
  ['试题', 'shìtí', 'noun', 'test questions, exam paper', 'sınav soruları'],
  ['适应', 'shìyìng', 'verb', 'to adapt, to fit, to suit', 'uyum sağlamak'],
  ['收费', 'shōufèi', 'verb', 'to charge a fee, to collect payment', 'ücret almak'],
  ['收入', 'shōurù', 'noun', 'income, revenue; to receive', 'gelir; almak'],
  ['收拾', 'shōushi', 'verb', 'to put in order, to tidy up, to pack', 'toplamak, düzenlemek'],
  ['收听', 'shōutīng', 'verb', 'to listen in, to tune in', 'dinlemek'],
  ['首', 'shǒu', 'classifier', 'measure word for songs, poems', 'şarkı sayacı'],
  ['首都', 'shǒudū', 'noun', 'capital', 'başkent'],
  ['首先', 'shǒuxiān', 'adverb', 'first, firstly', 'öncelikle, ilk olarak'],
  ['受不了', 'shòubuliǎo', 'verb', 'to be unable to bear, to be unable to stand', 'dayanamamak'],
  ['售票员', 'shòupiàoyuán', 'noun', 'ticket seller, conductor', 'biletçi'],
  ['受伤', 'shòushāng', 'verb', 'to be injured, to get hurt', 'yaralanmak'],
  ['输', 'shū', 'verb', 'to lose, to be defeated', 'kaybetmek, yenilmek'],
  ['熟', 'shú', 'adjective', 'ripe, cooked, mature', 'olgun, pişmiş'],
  ['熟悉', 'shúxi', 'verb', 'to be familiar with, to know well', 'aşina olmak'],
  ['暑假', 'shǔjià', 'noun', 'summer vacation', 'yaz tatili'],
  ['数', 'shù, shǔ', 'noun', 'number, figure; several', 'sayı; birkaç'],
  ['数量', 'shùliàng', 'noun', 'quantity, amount', 'miktar, adet'],
  ['树林', 'shùlín', 'noun', 'woods, forest', 'koru, orman'],
  ['数字', 'shùzì', 'noun', 'digit, figure, number', 'rakam, sayı'],
  ['帅', 'shuài', 'adjective', 'handsome, good-looking', 'yakışıklı'],
  ['顺便', 'shùnbiàn', 'adverb', 'conveniently, in passing', 'fırsat bu fırsat, yeri gelmişken'],
  ['顺利', 'shùnlì', 'adjective', 'smooth, successful, going well', 'sorunsuz, başarılı'],
  ['顺序', 'shùnxù', 'noun', 'order, sequence', 'sıra, düzen'],
  ['说法', 'shuōfǎ', 'noun', 'way of saying something, version, statement', 'söyleyiş biçimi'],
  ['说明', 'shuōmíng', 'noun', 'explanation, instructions; to explain', 'açıklama; açıklamak'],
  ['说明书', 'shuōmíngshū', 'noun', 'instruction manual, user guide', 'kullanım kılavuzu'],
  ['硕士', 'shuòshì', 'noun', 'master (degree)', 'yüksek lisans'],
  ['死', 'sǐ', 'verb', 'to die; dead; extremely', 'ölmek; ölü; son derece'],
  ['速度', 'sùdù', 'noun', 'speed', 'hız'],
  ['塑料', 'sùliào', 'noun', 'plastic', 'plastik'],
  ['酸', 'suān', 'adjective', 'sour, tart', 'ekşi'],
  ['酸奶', 'suānnǎi', 'noun', 'yogurt', 'yoğurt'],
  ['算', 'suàn', 'verb', 'to calculate, to count; considered', 'hesaplamak; sayılmak'],
  ['随便', 'suíbiàn', 'adjective', 'casual; do as one pleases', 'gelişigüzel; nasıl olsa'],
  ['随着', 'suízhe', 'preposition', 'along with, following', 'ile birlikte, takiben'],
  ['孙女', 'sūnnǚ', 'noun', 'granddaughter', 'torun kız'],
  ['孙子', 'sūnzi', 'noun', 'grandson', 'torun erkek'],
  ['所有', 'suǒyǒu', 'adjective', 'all, every; to possess', 'tüm; sahip olmak'],
  ['台', 'tái', 'classifier', 'measure word for machines, vehicles', 'makine sayacı; sahne'],
  ['抬', 'tái', 'verb', 'to lift, to raise', 'kaldırmak'],
  ['抬头', 'táitóu', 'verb', 'to raise ones head, to look up', 'başını kaldırmak'],
  ['态度', 'tàidù', 'noun', 'attitude, manner', 'tutum, davranış'],
  ['弹', 'tán, dàn', 'verb', 'to play (an instrument), to spring', 'çalmak, çekmek'],
  ['谈', 'tán', 'verb', 'to talk, to discuss', 'konuşmak, tartışmak'],
  ['汤', 'tāng', 'noun', 'soup', 'çorba'],
  ['躺', 'tǎng', 'verb', 'to lie down', 'uzanmak, yatmak'],
  ['趟', 'tàng', 'classifier', 'measure word for trips, journeys', 'gidiş sayacı'],
  ['讨论', 'tǎolùn', 'verb', 'to discuss, to talk over', 'tartışmak, görüşmek'],
  ['讨厌', 'tǎoyàn', 'adjective', 'disgusting, annoying; to dislike', 'iğrenç, sinir bozucu'],
  ['特点', 'tèdiǎn', 'noun', 'characteristic, feature', 'özellik'],
  ['提', 'tí, dī', 'verb', 'to carry; to lift; to mention, to bring up', 'taşımak; bahsetmek'],
  ['提出', 'tíchū', 'verb', 'to put forward, to propose, to raise', 'öne sürmek, önermek'],
  ['提到', 'tídào', 'verb', 'to mention, to refer to', 'bahsetmek'],
  ['提供', 'tígōng', 'verb', 'to provide, to supply, to offer', 'sağlamak, sunmak'],
  ['提前', 'tíqián', 'verb', 'to advance, to do something ahead of time', 'önceden yapmak'],
  ['提醒', 'tíxǐng', 'verb', 'to remind, to alert', 'hatırlatmak, uyarmak'],
  ['体检', 'tǐjiǎn', 'verb', 'to undergo a physical examination', 'sağlık kontrolü'],
  ['体温', 'tǐwēn', 'noun', 'body temperature', 'vücut sıcaklığı'],
  ['体重', 'tǐzhòng', 'noun', 'body weight', 'vücut ağırlığı'],
  ['填写', 'tiánxiě', 'verb', 'to fill in, to complete a form', 'doldurmak, tamamlamak'],
  ['条件', 'tiáojiàn', 'noun', 'condition, requirement, terms', 'koşul, şart'],
  ['听力', 'tīnglì', 'noun', 'listening ability, hearing', 'dinleme becerisi'],
  ['听众', 'tīngzhòng', 'noun', 'audience, listeners', 'dinleyici'],
  ['停', 'tíng', 'verb', 'to stop, to halt', 'durmak'],
  ['停车', 'tíngchē', 'verb', 'to park, to stop a vehicle', 'park etmek'],
  ['停车场', 'tíngchēchǎng', 'noun', 'parking lot', 'otopark'],
  ['停止', 'tíngzhǐ', 'verb', 'to stop, to cease', 'durdurmak, son vermek'],
  ['通', 'tōng', 'verb', 'to go through; to lead to, to connect', 'geçmek; bağlantılı'],
  ['通过', 'tōngguò', 'verb', 'to pass through; by means of', 'geçmek; aracılığıyla'],
  ['通知', 'tōngzhī', 'noun', 'notice, notification; to notify', 'bildirim; bildirmek'],
  ['童年', 'tóngnián', 'noun', 'childhood', 'çocukluk'],
  ['同时', 'tóngshí', 'conjunction', 'at the same time; meanwhile', 'aynı zamanda'],
  ['同样', 'tóngyàng', 'adjective', 'same, similar', 'aynı, benzer'],
  ['桶', 'tǒng', 'noun', 'bucket, barrel', 'kova, varil'],
  ['痛', 'tòng', 'adjective', 'painful, sore', 'ağrılı, acıyan'],
  ['头痛', 'tóutòng', 'adjective', 'headache', 'baş ağrısı'],
  ['图', 'tú', 'noun', 'picture, drawing, diagram', 'resim, şekil'],
  ['图片', 'túpiàn', 'noun', 'picture, image, photograph', 'resim, fotoğraf'],
  ['土', 'tǔ', 'noun', 'earth, soil, land', 'toprak'],
  ['推', 'tuī', 'verb', 'to push, to shove', 'itmek'],
  ['推迟', 'tuīchí', 'verb', 'to postpone, to delay', 'ertelemek'],
  ['推出', 'tuīchū', 'verb', 'to launch, to push out, to introduce', 'piyasaya sürmek'],
  ['脱', 'tuō', 'verb', 'to take off, to shed', 'çıkarmak (giysi)'],
  ['袜子', 'wàzi', 'noun', 'socks', 'çorap'],
  ['外出', 'wàichū', 'verb', 'to go out, to leave home', 'dışarı çıkmak'],
  ['外套', 'wàitào', 'noun', 'coat, jacket', 'mont, ceket'],
  ['完全', 'wánquán', 'adverb', 'completely, absolutely', 'tamamen'],
  ['晚安', 'wǎnān', 'verb', 'good night', 'iyi geceler'],
  ['晚餐', 'wǎncān', 'noun', 'dinner, supper', 'akşam yemeği'],
  ['网购', 'wǎnggòu', 'verb', 'to shop online', 'online alışveriş yapmak'],
  ['往往', 'wǎngwǎng', 'adverb', 'often, frequently', 'çoğunlukla, sıklıkla'],
  ['网页', 'wǎngyè', 'noun', 'webpage', 'web sayfası'],
  ['网友', 'wǎngyǒu', 'noun', 'netizen, internet user', 'internet kullanıcısı'],
  ['网址', 'wǎngzhǐ', 'noun', 'website URL, web address', 'web adresi'],
  ['危险', 'wēixiǎn', 'noun', 'dangerous; danger', 'tehlikeli; tehlike'],
  ['为', 'wèi, wéi', 'verb', 'to do, to act, to serve as', 'yapmak, olmak'],
  ['味', 'wèi', 'noun', 'taste, flavor', 'tat, lezzet'],
  ['味道', 'wèidào', 'noun', 'taste, flavor', 'tat, lezzet'],
  ['卫生', 'wèishēng', 'noun', 'hygiene, sanitation; clean, hygienic', 'hijyen, temizlik'],
  ['温度', 'wēndù', 'noun', 'temperature', 'sıcaklık'],
  ['闻', 'wén', 'verb', 'to smell, to sniff', 'koklamak'],
  ['文件', 'wénjiàn', 'noun', 'document, file', 'belge, dosya'],
  ['文章', 'wénzhāng', 'noun', 'essay, article', 'makale, yazı'],
  ['文字', 'wénzì', 'noun', 'writing, character', 'yazı, harf'],
  ['污染', 'wūrǎn', 'verb', 'contaminated; to contaminate', 'kirletmek, kirlenmiş'],
  ['无', 'wú', 'verb', 'to lack, to not have', 'olmamak, yokluk'],
  ['无法', 'wúfǎ', 'verb', 'unable, incapable', 'yapamamak'],
  ['无聊', 'wúliáo', 'adjective', 'boring, dull', 'sıkıcı'],
  ['无论', 'wúlùn', 'conjunction', 'no matter what, regardless', 'her ne olursa olsun'],
  ['午餐', 'wǔcān', 'noun', 'lunch', 'öğle yemeği'],
  ['误会', 'wùhuì', 'noun', 'misunderstanding; to misunderstand', 'yanlış anlama; yanlış anlamak'],
  ['吸', 'xī', 'verb', 'to suck, to inhale, to absorb', 'emmek, solumak'],
  ['西部', 'xībù', 'noun', 'western region, west part', 'batı bölgesi'],
  ['西红柿', 'xīhóngshì', 'noun', 'tomato', 'domates'],
  ['吸引', 'xīyǐn', 'verb', 'to attract', 'çekmek, cezbetmek'],
  ['细', 'xì', 'adjective', 'thin, fine, detailed', 'ince, ayrıntılı'],
  ['细心', 'xìxīn', 'adjective', 'careful, attentive', 'dikkatli, özenli'],
  ['下降', 'xiàjiàng', 'verb', 'to decline, to drop, to go down', 'düşmek, azalmak'],
  ['鲜', 'xiān', 'adjective', 'fresh', 'taze'],
  ['鲜花', 'xiānhuā', 'noun', 'fresh flower', 'taze çiçek'],
  ['咸', 'xián', 'adjective', 'salty', 'tuzlu'],
  ['现金', 'xiànjīn', 'noun', 'cash', 'nakit'],
  ['羡慕', 'xiànmù', 'verb', 'to envy, to admire', 'gıpta etmek, imrenmek'],
  ['线上', 'xiànshàng', 'noun', 'online, on the internet', 'çevrimiçi'],
  ['线下', 'xiànxià', 'noun', 'offline', 'çevrimdışı'],
  ['现有', 'xiànyǒu', 'adjective', 'existing, currently available', 'mevcut, şu anda var olan'],
  ['香', 'xiāng', 'adjective', 'fragrant', 'kokulu, güzel kokulu'],
  ['相比', 'xiāngbǐ', 'verb', 'to compare with, to contrast', 'kıyaslamak'],
  ['相反', 'xiāngfǎn', 'adjective', 'opposite, contrary; on the contrary', 'zıt, aksine'],
  ['相互', 'xiānghù', 'adverb', 'mutual, each other', 'karşılıklı'],
  ['相同', 'xiāngtóng', 'adjective', 'same, identical', 'aynı, özdeş'],
  ['详细', 'xiángxì', 'adjective', 'detailed, thorough', 'ayrıntılı'],
  ['响', 'xiǎng', 'verb', 'to make a sound, to ring; loud', 'ses çıkarmak; gürültülü'],
  ['想法', 'xiǎngfǎ', 'noun', 'thought, idea, opinion', 'düşünce, fikir'],
  ['项', 'xiàng', 'classifier', 'measure word for projects, items', 'proje sayacı'],
  ['消息', 'xiāoxi', 'noun', 'news, message, information', 'haber, mesaj'],
  ['小吃', 'xiǎochī', 'noun', 'snack, light meal', 'atıştırmalık, hafif yemek'],
  ['小伙子', 'xiǎohuǒzi', 'noun', 'young man, lad', 'genç adam, delikanlı'],
  ['小说', 'xiǎoshuō', 'noun', 'novel, fiction', 'roman, kurgu'],
  ['小组', 'xiǎozǔ', 'noun', 'small group, team', 'küçük grup'],
  ['效果', 'xiàoguǒ', 'noun', 'effect, result', 'etki, sonuç'],
  ['笑话', 'xiàohua', 'noun', 'joke; to joke, to laugh at', 'şaka, fıkra'],
  ['血', 'xiě', 'noun', 'blood', 'kan'],
  ['心', 'xīn', 'noun', 'heart', 'kalp, gönül'],
  ['辛苦', 'xīnkǔ', 'adjective', 'hard, laborious; to work hard', 'zahmetli, yorucu'],
  ['心情', 'xīnqíng', 'noun', 'mood, feeling', 'ruh hali, duygu'],
  ['信号', 'xìnhào', 'noun', 'signal', 'sinyal'],
  ['信息', 'xìnxī', 'noun', 'information, message', 'bilgi, mesaj'],
  ['信心', 'xìnxīn', 'noun', 'confidence, faith', 'özgüven, güven'],
  ['兴奋', 'xīngfèn', 'adjective', 'excited, thrilled; to excite', 'heyecanlı, coşkulu'],
  ['星星', 'xīngxing', 'noun', 'star', 'yıldız'],
  ['醒', 'xǐng', 'verb', 'to wake up, to sober up', 'uyanmak'],
  ['性', 'xìng', 'suffix', 'nature, character, quality', 'özellik, nitelik, -lık eki'],
  ['性别', 'xìngbié', 'noun', 'gender, sex', 'cinsiyet'],
  ['幸福', 'xìngfú', 'noun', 'happiness; happy, blissful', 'mutluluk; mutlu'],
  ['性格', 'xìnggé', 'noun', 'character', 'karakter, kişilik'],
  ['兄弟', 'xiōngdì', 'noun', 'brothers', 'erkek kardeşler'],
  ['熊', 'xióng', 'noun', 'bear', 'ayı'],
  ['修', 'xiū', 'verb', 'to repair, to fix', 'onarmak'],
  ['修理', 'xiūlǐ', 'verb', 'to repair, to fix', 'tamir etmek'],
  ['许多', 'xǔduō', 'number', 'many, numerous', 'çok, birçok'],
  ['学费', 'xuéfèi', 'noun', 'tuition fee', 'okul ücreti, harç'],
  ['学院', 'xuéyuàn', 'noun', 'college, academy, institute', 'kolej, yüksekokul'],
  ['压', 'yā', 'verb', 'to press, to push down, to weigh down', 'bastırmak'],
  ['压力', 'yālì', 'noun', 'pressure, stress', 'baskı, stres'],
  ['牙膏', 'yágāo', 'noun', 'toothpaste', 'diş macunu'],
  ['亚洲', 'Yàzhōu', 'noun', 'Asia', 'Asya'],
  ['烟', 'yān', 'noun', 'cigarette, smoke, mist', 'sigara, duman'],
  ['盐', 'yán', 'noun', 'salt', 'tuz'],
  ['严格', 'yángé', 'adjective', 'strict, stringent', 'sıkı, katı'],
  ['研究', 'yánjiū', 'verb', 'to research, to study', 'araştırmak'],
  ['研究生', 'yánjiūshēng', 'noun', 'graduate student, postgraduate', 'yüksek lisans öğrencisi'],
  ['严重', 'yánzhòng', 'adjective', 'serious, severe, grave', 'ciddi, ağır'],
  ['演', 'yǎn', 'verb', 'to act, to perform, to play', 'oynamak, sergilemek'],
  ['演唱', 'yǎnchàng', 'verb', 'to sing, to perform vocally', 'şarkı söylemek'],
  ['演出', 'yǎnchū', 'verb', 'to perform, to put on a show', 'gösteri yapmak'],
  ['眼镜', 'yǎnjìng', 'noun', 'eyeglasses, glasses', 'gözlük'],
  ['眼前', 'yǎnqián', 'noun', 'before ones eyes, at the moment', 'gözlerinin önünde'],
  ['演员', 'yǎnyuán', 'noun', 'actor, performer', 'aktör, sanatçı'],
  ['阳光', 'yángguāng', 'noun', 'sunlight, sunshine', 'güneş ışığı'],
  ['养成', 'yǎngchéng', 'verb', 'to develop, to cultivate, to form', 'geliştirmek, edinmek'],
  ['样子', 'yàngzi', 'noun', 'appearance, look, manner', 'görünüm, hal'],
  ['邀请', 'yāoqǐng', 'verb', 'to invite', 'davet etmek'],
  ['要是', 'yàoshi', 'conjunction', 'if, suppose', 'eğer, şayet'],
  ['钥匙', 'yàoshi', 'noun', 'key', 'anahtar'],
  ['也许', 'yěxǔ', 'adverb', 'maybe, perhaps', 'belki, muhtemelen'],
  ['夜', 'yè', 'noun', 'night', 'gece'],
  ['夜晚', 'yèwǎn', 'noun', 'night, evening', 'gece, akşam'],
  ['叶子', 'yèzi', 'noun', 'leaf', 'yaprak'],
  ['一切', 'yíqiè', 'pronoun', 'everything', 'her şey, hepsi'],
  ['已', 'yǐ', 'adverb', 'already', 'zaten, artık'],
  ['以内', 'yǐnèi', 'noun', 'within', 'içinde'],
  ['意见', 'yìjiàn', 'noun', 'opinion', 'görüş, fikir'],
  ['一生', 'yìshēng', 'noun', 'lifetime, all ones life', 'tüm hayat boyunca'],
  ['艺术', 'yìshù', 'noun', 'art', 'sanat'],
  ['因此', 'yīncǐ', 'conjunction', 'therefore', 'bu nedenle, dolayısıyla'],
  ['引起', 'yǐnqǐ', 'verb', 'cause', 'neden olmak'],
  ['印象', 'yìnxiàng', 'noun', 'impression', 'izlenim'],
  ['赢', 'yíng', 'verb', 'win', 'kazanmak'],
  ['赢得', 'yíngdé', 'verb', 'gain, win', 'kazanmak, elde etmek'],
  ['应聘', 'yìngpìn', 'verb', 'to apply for a job', 'iş başvurusunda bulunmak'],
  ['勇敢', 'yǒnggǎn', 'adjective', 'brave, courageous', 'cesur, yürekli'],
  ['永远', 'yǒngyuǎn', 'adverb', 'forever, always', 'sonsuza kadar, her zaman'],
  ['用来', 'yònglái', 'verb', 'to be used for, to serve as', 'için kullanılmak'],
  ['用于', 'yòngyú', 'verb', 'to be used for, to be applied to', 'için kullanılmak'],
  ['优点', 'yōudiǎn', 'noun', 'advantage, merit, strong point', 'avantaj, üstünlük'],
  ['幽默', 'yōumò', 'adjective', 'humorous', 'mizahi, eğlenceli'],
  ['优秀', 'yōuxiù', 'adjective', 'excellent, outstanding', 'mükemmel, üstün'],
  ['由', 'yóu', 'preposition', 'by, through, from, because of', 'tarafından, nedeniyle'],
  ['油', 'yóu', 'noun', 'oil, fat, grease', 'yağ'],
  ['尤其', 'yóuqí', 'adverb', 'especially, particularly', 'özellikle'],
  ['游玩', 'yóuwán', 'verb', 'to play, to have fun, to go sightseeing', 'eğlenmek, gezmek'],
  ['由于', 'yóuyú', 'conjunction', 'because of, due to; owing to', 'nedeniyle, dolayısıyla'],
  ['友好', 'yǒuhǎo', 'adjective', 'friendly', 'arkadaş canlısı, samimi'],
  ['友情', 'yǒuqíng', 'noun', 'friendship', 'dostluk'],
  ['有趣', 'yǒuqù', 'adjective', 'interesting, enjoyable, fun', 'ilginç, eğlenceli'],
  ['有效', 'yǒuxiào', 'verb', 'effective, to be effective', 'etkili, geçerli'],
  ['友谊', 'yǒuyì', 'noun', 'friendship', 'dostluk, arkadaşlık'],
  ['有着', 'yǒuzhe', 'verb', 'to have, to possess', 'sahip olmak'],
  ['愉快', 'yúkuài', 'adjective', 'pleasant, cheerful', 'keyifli, neşeli'],
  ['于是', 'yúshì', 'conjunction', 'therefore, hence, so', 'bunun üzerine, böylece'],
  ['与', 'yǔ, yù', 'conjunction', 'with, and', 'ile'],
  ['语法', 'yǔfǎ', 'noun', 'grammar', 'gramer, dilbilgisi'],
  ['预习', 'yùxí', 'verb', 'to preview, to prepare', 'önceden çalışmak'],
  ['原来', 'yuánlái', 'adverb', 'originally, actually', 'aslında, meğer'],
  ['原谅', 'yuánliàng', 'verb', 'to forgive, to excuse, to pardon', 'affetmek'],
  ['原因', 'yuányīn', 'noun', 'cause, reason', 'neden, sebep'],
  ['远离', 'yuǎnlí', 'verb', 'to stay away from, to keep away from', 'uzak durmak'],
  ['院长', 'yuànzhǎng', 'noun', 'dean, head of a college or institute', 'dekan'],
  ['院子', 'yuànzi', 'noun', 'courtyard, yard', 'avlu, bahçe'],
  ['约', 'yuē', 'verb', 'to make an appointment; about, approximately', 'randevu almak; yaklaşık'],
  ['约会', 'yuēhuì', 'noun', 'date, appointment; to date, to meet up', 'randevu, buluşma'],
  ['月饼', 'yuèbing', 'noun', 'mooncake', 'ay keki'],
  ['阅读', 'yuèdú', 'verb', 'to read, to read aloud', 'okumak'],
  ['月份', 'yuèfèn', 'noun', 'month', 'ay, ay dilimi'],
  ['云', 'yún', 'noun', 'cloud', 'bulut'],
  ['允许', 'yǔnxǔ', 'verb', 'to permit, to allow, to give permission', 'izin vermek'],
  ['杂志', 'zázhì', 'noun', 'magazine', 'dergi'],
  ['再次', 'zàicì', 'adverb', 'once again, once more', 'bir kez daha'],
  ['再说', 'zàishuō', 'conjunction', 'besides, moreover; to put off', 'üstelik; ertelemek'],
  ['暂时', 'zànshí', 'adjective', 'temporary, for the time being', 'geçici'],
  ['暂停', 'zàntíng', 'verb', 'to suspend, to pause', 'askıya almak, duraklatmak'],
  ['早餐', 'zǎocān', 'noun', 'breakfast', 'kahvaltı'],
  ['早晨', 'zǎochen', 'noun', 'morning', 'sabah'],
  ['责任', 'zérèn', 'noun', 'responsibility, duty', 'sorumluluk, görev'],
  ['增加', 'zēngjiā', 'verb', 'to increase, to add, to raise', 'artırmak'],
  ['增长', 'zēngzhǎng', 'verb', 'to increase, to grow, to rise', 'büyümek, artmak'],
  ['招聘', 'zhāopìn', 'verb', 'to recruit, to hire', 'işe almak, işe çekmek'],
  ['着', 'zhe, zháo, zhuó', 'verb', 'to touch, to get to, to catch', 'değmek, yakalamak'],
  ['着火', 'zháohuǒ', 'verb', 'to catch fire, to ignite', 'tutuşmak, yanmak'],
  ['者', 'zhě', 'suffix', 'person, one who', 'kişi, -cı/-ci eki'],
  ['真正', 'zhēnzhèng', 'adverb', 'true, genuine; truly, indeed', 'gerçek, sahici; gerçekten'],
  ['整', 'zhěng', 'adjective', 'whole, complete, entire', 'tam, eksiksiz'],
  ['整个', 'zhěnggè', 'adjective', 'whole, entire, all', 'tüm, bütün'],
  ['整理', 'zhěnglǐ', 'verb', 'to arrange, to put in order, to tidy up', 'düzenlemek, toplamak'],
  ['证', 'zhèng', 'noun', 'certificate, proof, evidence', 'sertifika, kanıt'],
  ['正常', 'zhèngcháng', 'adjective', 'normal, regular, proper', 'normal'],
  ['正好', 'zhènghǎo', 'adverb', 'exactly right, just in time; coincidentally', 'tam zamanında; tesadüfen'],
  ['证件', 'zhèngjiàn', 'noun', 'ID card, credentials, identification papers', 'kimlik belgesi'],
  ['证明', 'zhèngmíng', 'noun', 'proof, certificate; to prove', 'kanıt; kanıtlamak'],
  ['正确', 'zhèngquè', 'adjective', 'correct, right, accurate', 'doğru, yerinde'],
  ['正式', 'zhèngshì', 'adjective', 'formal, official', 'resmi'],
  ['之', 'zhī', 'auxiliary', 'auxiliary word (classical)', 'yardımcı sözcük'],
  ['支持', 'zhīchí', 'verb', 'to support, to back', 'desteklemek'],
  ['支付', 'zhīfù', 'verb', 'to pay (money)', 'ödemek'],
  ['之后', 'zhīhòu', 'noun', 'after, later, behind', 'sonra'],
  ['之间', 'zhījiān', 'noun', 'between, among', 'arasında'],
  ['之前', 'zhīqián', 'noun', 'before, prior to', 'önce, öncesinde'],
  ['知识', 'zhīshi', 'noun', 'knowledge', 'bilgi'],
  ['之中', 'zhīzhōng', 'noun', 'among, inside', 'içinde, arasında'],
  ['值', 'zhí', 'verb', 'to be worth, to be equal in value', 'değer olmak'],
  ['值得', 'zhídé', 'verb', 'to be worth, to deserve', 'değmek, hak etmek'],
  ['直接', 'zhíjiē', 'adjective', 'direct, straightforward', 'doğrudan'],
  ['植物', 'zhíwù', 'noun', 'plant, vegetation', 'bitki'],
  ['职业', 'zhíyè', 'noun', 'occupation, profession', 'meslek, iş'],
  ['指', 'zhǐ', 'verb', 'to point to, to indicate', 'işaret etmek'],
  ['指出', 'zhǐchū', 'verb', 'to point out, to indicate', 'belirtmek'],
  ['只好', 'zhǐhǎo', 'adverb', 'have to, be forced to', 'zorunda kalmak'],
  ['纸巾', 'zhǐjīn', 'noun', 'tissue paper, napkin', 'kagit mendil'],
  ['质量', 'zhìliàng', 'noun', 'quality', 'kalite'],
  ['至少', 'zhìshǎo', 'adverb', 'at least', 'en az'],
  ['中餐', 'zhōngcān', 'noun', 'Chinese food, Chinese meal', 'Cin yemegi'],
  ['中年', 'zhōngnián', 'noun', 'middle age', 'orta yas'],
  ['种', 'zhǒng, zhòng', 'verb', 'to plant, to grow', 'dikmek, ekmek'],
  ['重', 'zhòng, chóng', 'adjective', 'weight, importance; heavy, important', 'agir, onemli'],
  ['重点', 'zhòngdiǎn', 'noun', 'key point, emphasis', 'kilit nokta, vurgu'],
  ['重视', 'zhòngshì', 'verb', 'to pay attention to, to value', 'onem vermek'],
  ['周围', 'zhōuwéi', 'noun', 'around, surrounding', 'etraf, cevre'],
  ['主意', 'zhǔyi', 'noun', 'idea, thought, plan', 'fikir, plan'],
  ['祝', 'zhù', 'verb', 'to wish, to express good wishes', 'dilemek'],
  ['祝贺', 'zhùhè', 'verb', 'to congratulate, to offer congratulations', 'tebrik etmek'],
  ['著名', 'zhùmíng', 'adjective', 'famous, well-known', 'unlu, meshur'],
  ['专门', 'zhuānmén', 'adverb', 'specially, specifically; special', 'ozellikle, hususi'],
  ['专业', 'zhuānyè', 'noun', 'specialty, major; professional', 'uzmanlik; profesyonel'],
  ['转', 'zhuǎn, zhuàn', 'verb', 'to turn, to shift, to transfer', 'donmek, cevirmek'],
  ['转发', 'zhuǎnfā', 'verb', 'to forward a message, to retweet', 'iletmek, yonlendirmek'],
  ['转机', 'zhuǎnjī', 'verb', 'to transfer flight, to change planes', 'aktarma yapmak'],
  ['赚', 'zhuàn', 'verb', 'to earn, to make a profit', 'kazanmak, kar etmek'],
  ['装', 'zhuāng', 'verb', 'to load, to pack, to pretend, to install', 'yuklemek; yapmak gibi gorunmek'],
  ['准', 'zhǔn', 'adjective', 'accurate, exact, standard; definitely', 'dogru, kesin; kesinlikle'],
  ['准确', 'zhǔnquè', 'adjective', 'accurate, precise', 'dogru, isabetli'],
  ['准时', 'zhǔnshí', 'adjective', 'on time, punctual', 'zamaninda'],
  ['资料', 'zīliào', 'noun', 'materials, data, information', 'materyal, bilgi'],
  ['仔细', 'zǐxì', 'adjective', 'careful, attentive, meticulous', 'dikkatli, titiz'],
  ['自', 'zì', 'preposition', 'from, since, oneself', 'kendisi, itibaren'],
  ['自然', 'zìrán', 'noun', 'nature; natural; naturally, of course', 'doga; dogal; dogal olarak'],
  ['自习', 'zìxí', 'verb', 'to study on ones own', 'kendi basina calismak'],
  ['自信', 'zìxìn', 'noun', 'self-confidence; confident', 'ozguven; ozguvenli'],
  ['自学', 'zìxué', 'verb', 'to teach oneself, to self-study', 'kendi kendine ogrenmek'],
  ['总结', 'zǒngjié', 'noun', 'summary; to summarize, to sum up', 'ozet; ozetlemek'],
  ['租', 'zū', 'verb', 'to rent, to hire', 'kiralamak'],
  ['组', 'zǔ', 'noun', 'group, team', 'grup, takim'],
  ['最终', 'zuìzhōng', 'noun', 'final, ultimate', 'nihayet, son olarak'],
  ['尊重', 'zūnzhòng', 'verb', 'to respect, to value', 'saygi gostermek'],
  ['左右', 'zuǒyòu', 'noun', 'about, around, left and right', 'yaklasik, etrafinda'],
  ['座', 'zuò', 'classifier', 'seat, place; measure word for seats', 'koltuk, yer sayaci'],
  ['做法', 'zuòfǎ', 'noun', 'way of doing things, practice', 'yapis bicimi, yontem'],
  ['作家', 'zuòjiā', 'noun', 'writer, author', 'yazar'],
  ['做梦', 'zuòmèng', 'verb', 'to dream, to have a dream', 'ruya gormek'],
  ['作品', 'zuòpǐn', 'noun', 'work, composition, creation', 'eser'],
  ['作为', 'zuòwéi', 'verb', 'to act as, to serve as; as, being', 'olarak hareket etmek; olarak'],
  ['座位', 'zuòwèi', 'noun', 'seat', 'koltuk'],
  ['作文', 'zuòwén', 'noun', 'composition; to write a composition', 'kompozisyon, yazi'],
  ['作用', 'zuòyòng', 'noun', 'function, role', 'islev, rol'],
  ['作者', 'zuòzhě', 'noun', 'author, writer', 'yazar'],
];
