// ignore_for_file: constant_identifier_names
// HSK Level 4 vocabulary — 1000 words
// Format: [simplified, pinyin, pos, en, tr, ko]

const List<List<String>> kHsk4Words = [
  ['啊', 'ā', 'interjection', 'ah, oh', 'ah, oh', '아, 어 (감탄사)'],
  ['爱情', 'àiqíng', 'noun', 'love', 'aşk, sevgi', '사랑, 애정'],
  ['爱心', 'àixīn', 'noun', 'compassion, caring', 'şefkat, merhametlilik', '애심, 사랑하는 마음'],
  ['安检', 'ānjiǎn', 'verb', 'security check', 'güvenlik kontrolü', '보안 검사를 하다'],
  ['安排', 'ānpái', 'verb', 'to arrange', 'düzenlemek, ayarlamak', '안배하다, 계획하다'],
  ['按', 'àn', 'verb', 'to press; according to', 'basmak; göre', '누르다, 밀다'],
  ['按时', 'ànshí', 'adverb', 'on time, on schedule', 'zamanında, programda', '제시간에, 정시에'],
  ['按照', 'ànzhào', 'preposition', 'according to', 'göre, uyarınca', '~에 따라, ~에 의거하여'],
  ['白酒', 'báijiǔ', 'noun', 'liquor, spirit', 'rakı, viski', '백주, 고량주'],
  ['办公', 'bàngōng', 'verb', 'to handle official business', 'resmi iş yürütmek', '사무를 보다'],
  ['办理', 'bànlǐ', 'verb', 'to handle, to process', 'işlem yapmak, halletmek', '처리하다, 취급하다'],
  ['办事', 'bànshì', 'verb', 'to handle matters', 'iş halletmek', '일을 처리하다'],
  ['棒', 'bàng', 'adjective', 'great, excellent', 'harika, mükemmel', '훌륭하다, 뛰어나다'],
  ['保护', 'bǎohù', 'verb', 'to protect', 'korumak', '보호하다'],
  ['保证', 'bǎozhèng', 'verb', 'to guarantee', 'garanti etmek, güvence vermek', '보증하다, 보장하다, 약속하다'],
  ['抱', 'bào', 'verb', 'to hold, to embrace', 'tutmak, kucaklamak', '안다, 껴안다'],
  ['报考', 'bàokǎo', 'verb', 'to apply for an exam', 'sınava başvurmak', '응시하다'],
  ['报名', 'bàomíng', 'verb', 'to sign up, to register', 'kayıt olmak', '신청하다, 등록하다'],
  ['抱歉', 'bàoqiàn', 'adjective', 'sorry, apologetic', 'özür dilerim, üzgünüm', '미안하다, 죄송하다'],
  ['背', 'bèi, bēi', 'verb', 'to carry on the back', 'sırtında taşımak', '등, 짊어지다, 외우다'],
  ['背包', 'bēibāo', 'noun', 'backpack', 'sırt çantası', '배낭'],
  ['北部', 'běibù', 'noun', 'northern part, north', 'kuzey bölgesi', '북부, 북쪽'],
  ['倍', 'bèi', 'classifier', 'times, -fold', 'kat, katı', '~배, 곱절'],
  ['本科', 'běnkē', 'noun', 'undergraduate program', 'lisans programı', '학부'],
  ['本来', 'běnlái', 'adverb', 'originally, actually', 'aslında, başta', '본래, 원래'],
  ['笨', 'bèn', 'adjective', 'stupid, foolish', 'aptal, ahmak', '어리석다, 둔하다'],
  ['鼻子', 'bízi', 'noun', 'nose', 'burun', '코'],
  ['笔试', 'bǐshì', 'noun', 'written test', 'yazılı sınav', '필기시험'],
  ['毕业', 'bìyè', 'verb', 'to graduate', 'mezun olmak', '졸업하다'],
  ['毕业生', 'bìyèshēng', 'noun', 'graduate', 'mezun', '졸업생'],
  ['便于', 'biànyú', 'verb', 'to be convenient for', 'kolaylık sağlamak', '편리하다, 용이하다'],
  ['标准', 'biāozhǔn', 'noun', 'standard', 'standart', '표준, 기준'],
  ['表', 'biǎo', 'noun', 'watch, table, form', 'saat, form, tablo', '시계, 표, 서식'],
  ['表格', 'biǎogé', 'noun', 'form, table', 'form, tablo', '표, 서식'],
  ['表示', 'biǎoshì', 'verb', 'to express, to indicate', 'ifade etmek, belirtmek', '표시하다, 나타내다, 표현하다'],
  ['表现', 'biǎoxiàn', 'verb', 'to show, to display', 'göstermek, sergilemek', '나타내다, 표현하다, 행동'],
  ['表扬', 'biǎoyáng', 'verb', 'to praise, to commend', 'övmek, takdir etmek', '칭찬하다'],
  ['饼干', 'bǐnggān', 'noun', 'biscuit, cracker', 'bisküvi, kraker', '비스킷, 과자'],
  ['并', 'bìng', 'conjunction', 'and, also', 've, ayrıca', '그리고, 또한'],
  ['并且', 'bìngqiě', 'conjunction', 'and, moreover', 'üstelik, ayrıca', '게다가, 그리고'],
  ['播放', 'bōfàng', 'verb', 'to broadcast, to play', 'yayınlamak, oynatmak', '방송하다, 재생하다'],
  ['博士', 'bóshì', 'noun', 'doctor (PhD)', 'doktor (akademik)', '박사'],
  ['不必', 'búbì', 'adverb', 'need not', 'gerek yok', '~할 필요가 없다'],
  ['不便', 'búbiàn', 'adjective', 'inconvenient', 'elverişsiz, rahatsız', '불편하다'],
  ['不断', 'búduàn', 'adverb', 'continuously, constantly', 'sürekli, aralıksız', '끊임없이, 계속해서'],
  ['不够', 'búgòu', 'adverb', 'not enough', 'yeterli değil', '부족하다, 충분하지 않다'],
  ['不过', 'búguò', 'conjunction', 'but, however', 'ama, ancak', '그러나, 하지만, 단지'],
  ['不论', 'búlùn', 'conjunction', 'no matter, regardless', 'ne olursa olsun', '~와 상관없이, ~이든 아니든'],
  ['步', 'bù', 'noun', 'step, pace', 'adım', '걸음, 단계'],
  ['部', 'bù', 'noun', 'department, part', 'bölüm, departman', '부, 부분, 부서'],
  ['不得不', 'bùdébù', 'adverb', 'have to, cannot but', 'zorunda olmak', '하지 않을 수 없다, ~해야만 한다'],
  ['部分', 'bùfen', 'noun', 'part, portion', 'kısım, bölüm', '부분'],
  ['不管', 'bùguǎn', 'conjunction', 'no matter, regardless of', 'ne olursa olsun', '~와 상관없이, ~이든 아니든'],
  ['不光', 'bùguāng', 'conjunction', 'not only', 'sadece değil', '~뿐만 아니라'],
  ['不仅', 'bùjǐn', 'conjunction', 'not only', 'sadece değil', '~뿐만 아니라'],
  ['不满', 'bùmǎn', 'adjective', 'dissatisfied, displeased', 'memnun olmayan', '불만스럽다, 마음에 들지 않다'],
  ['部门', 'bùmén', 'noun', 'department, unit', 'bölüm, birim', '부문, 부서'],
  ['不如', 'bùrú', 'verb', 'not as good as', 'kadar iyi değil', '~만 못하다'],
  ['擦', 'cā', 'verb', 'to wipe, to rub', 'silmek, ovmak', '닦다, 문지르다'],
  ['猜', 'cāi', 'verb', 'to guess', 'tahmin etmek', '추측하다, 짐작하다'],
  ['材料', 'cáiliào', 'noun', 'material, data', 'malzeme, materyal', '재료, 자료'],
  ['参观', 'cānguān', 'verb', 'to visit, to tour', 'ziyaret etmek, gezmek', '방문하다, 참관하다'],
  ['参赛', 'cānsài', 'verb', 'to enter a competition', 'yarışmaya katılmak', '경기에 참가하다'],
  ['餐厅', 'cāntīng', 'noun', 'restaurant, dining hall', 'restoran, yemekhane', '식당'],
  ['操场', 'cāochǎng', 'noun', 'playground', 'spor sahası', '운동장'],
  ['厕所', 'cèsuǒ', 'noun', 'toilet, restroom', 'tuvalet', '화장실'],
  ['查看', 'chákàn', 'verb', 'to check, to view', 'kontrol etmek, incelemek', '살펴보다, 확인하다'],
  ['茶叶', 'cháyè', 'noun', 'tea leaf', 'çay yaprağı', '찻잎'],
  ['查找', 'cházhǎo', 'verb', 'to search for, to look up', 'aramak, bulmak', '찾다, 검색하다'],
  ['差点儿', 'chàdiǎnr', 'adverb', 'almost, nearly', 'az kalsın, neredeyse', '거의, 하마터면'],
  ['产生', 'chǎnshēng', 'verb', 'to produce, to generate, to arise', 'üretmek, oluşmak', '발생하다, 생기다, 산출하다'],
  ['厂', 'chǎng', 'noun', 'factory, plant', 'fabrika', '공장'],
  ['场', 'chǎng', 'classifier', 'measure word for events', 'etkinlik sayacı', '회, 번 (사건, 경기 등을 세는 단위)'],
  ['超过', 'chāoguò', 'verb', 'to exceed, to surpass', 'aşmak, geçmek', '넘다, 초과하다'],
  ['车速', 'chēsù', 'noun', 'vehicle speed', 'araç hızı', '차량 속도'],
  ['车位', 'chēwèi', 'noun', 'parking space', 'park yeri', '주차 공간'],
  ['城', 'chéng', 'noun', 'city, town', 'şehir, kasaba', '성, 도시'],
  ['乘', 'chéng', 'verb', 'to ride, to take', 'binmek, taşımak', '타다, 이용하다'],
  ['成功', 'chénggōng', 'verb', 'to succeed; successful', 'başarmak; başarılı', '성공하다, 성공적인'],
  ['乘客', 'chéngkè', 'noun', 'passenger', 'yolcu', '승객'],
  ['诚实', 'chéngshí', 'adjective', 'honest', 'dürüst', '정직하다'],
  ['成为', 'chéngwéi', 'verb', 'to become', 'olmak', '되다'],
  ['乘坐', 'chéngzuò', 'verb', 'to ride, to take transportation', 'taşıta binmek', '탑승하다, 이용하다'],
  ['吃惊', 'chījīng', 'verb', 'to be startled, to be shocked', 'şaşırmak, ürkmek', '놀라다, 깜짝 놀라다'],
  ['迟', 'chí', 'adjective', 'late, delayed', 'geç, gecikmiş', '늦다, 더디다'],
  ['重', 'zhòng, chóng', 'adverb', 'again, once more', 'yeniden, tekrar', '다시, 무겁다, 중요하다'],
  ['重新', 'chóngxīn', 'adverb', 'again, anew', 'yeniden', '다시, 새로'],
  ['出差', 'chūchāi', 'verb', 'to go on a business trip', 'iş seyahatine çıkmak', '출장 가다'],
  ['出口', 'chūkǒu', 'noun', 'exit', 'çıkış', '출구, 수출'],
  ['出现', 'chūxiàn', 'verb', 'to appear, to emerge', 'ortaya çıkmak', '출현하다, 나타나다'],
  ['出行', 'chūxíng', 'verb', 'to travel, to go out', 'seyahat etmek, dışarı çıkmak', '나가다, 여행하다'],
  ['出租', 'chūzū', 'verb', 'to rent out', 'kiraya vermek', '임대하다, 빌려주다'],
  ['厨房', 'chúfáng', 'noun', 'kitchen', 'mutfak', '주방, 부엌'],
  ['厨师', 'chúshī', 'noun', 'chef, cook', 'aşçı, şef', '요리사'],
  ['窗', 'chuāng', 'noun', 'window', 'pencere', '창문'],
  ['窗户', 'chuānghu', 'noun', 'window', 'pencere', '창문'],
  ['吹', 'chuī', 'verb', 'to blow', 'üflemek, esmek', '불다'],
  ['词语', 'cíyǔ', 'noun', 'word, phrase', 'kelime, sözcük', '어휘, 단어'],
  ['此', 'cǐ', 'pronoun', 'this', 'bu', '이, 이것'],
  ['此次', 'cǐcì', 'noun', 'this time', 'bu sefer', '이번'],
  ['此外', 'cǐwài', 'conjunction', 'besides, in addition, moreover', 'bunun dışında, ayrıca', '게다가, 그 외에'],
  ['从此', 'cóngcǐ', 'adverb', 'from then on, since then', 'o andan itibaren', '그때부터'],
  ['从来', 'cónglái', 'adverb', 'always, at all times', 'her zaman, hiç', '언제나, 늘'],
  ['从中', 'cóngzhōng', 'adverb', 'from among, from it', 'arasından', '그중에서'],
  ['粗', 'cū', 'adjective', 'coarse, rough, thick', 'kaba, pürüzlü, kalın', '굵다, 거칠다'],
  ['粗心', 'cūxīn', 'adjective', 'careless', 'dikkatsiz', '부주의하다, 덜렁대다'],
  ['村', 'cūn', 'noun', 'village', 'köy', '마을, 촌'],
  ['存', 'cún', 'verb', 'to store, to keep, to exist', 'depolamak, biriktirmek', '저장하다, 보관하다, 존재하다'],
  ['错过', 'cuòguò', 'verb', 'to miss, to let slip', 'kaçırmak', '놓치다, 어긋나다'],
  ['错误', 'cuòwù', 'noun', 'mistake, error; wrong', 'hata; yanlış', '잘못, 오류, 틀리다'],
  ['答应', 'dāying', 'verb', 'to agree, to promise, to reply', 'kabul etmek, söz vermek', '대답하다, 승낙하다, 약속하다'],
  ['答', 'dá, dā', 'verb', 'to answer, to reply', 'cevap vermek', '대답하다, 응답하다'],
  ['答案', 'dáàn', 'noun', 'answer, solution', 'cevap, yanıt', '답안, 정답'],
  ['达到', 'dádào', 'verb', 'to reach, to achieve', 'ulaşmak, başarmak', '도달하다, 달성하다'],
  ['打招呼', 'dǎzhāohu', 'verb', 'to greet, to say hello', 'selamlamak', '인사하다'],
  ['打败', 'dǎbài', 'verb', 'to defeat, to beat', 'yenmek, mağlup etmek', '패배시키다, 이기다'],
  ['打工', 'dǎgōng', 'verb', 'to work a temporary job', 'geçici iş yapmak', '아르바이트하다'],
  ['打扰', 'dǎrǎo', 'verb', 'to disturb, to bother', 'rahatsız etmek', '방해하다, 폐를 끼치다'],
  ['打印', 'dǎyìn', 'verb', 'to print', 'yazdırmak, basmak', '인쇄하다, 출력하다'],
  ['打印机', 'dǎyìnjī', 'noun', 'printer', 'yazıcı', '프린터'],
  ['打折', 'dǎzhé', 'verb', 'to give a discount', 'indirim yapmak', '할인하다'],
  ['打针', 'dǎzhēn', 'verb', 'to get an injection', 'iğne olmak', '주사 맞다'],
  ['大巴', 'dàbā', 'noun', 'large bus, coach', 'otobüs, büyük otobüs', '대형 버스, 고속버스'],
  ['大大', 'dàdà', 'adverb', 'greatly, significantly', 'büyük ölçüde', '크게, 대단히'],
  ['大夫', 'dàifu', 'noun', 'doctor (medical)', 'doktor, hekim', '의사'],
  ['大量', 'dàliàng', 'adjective', 'large quantity, a large amount', 'büyük miktarda', '다량의, 대량의'],
  ['大赛', 'dàsài', 'noun', 'major competition, grand contest', 'büyük yarışma', '대회, 큰 경기'],
  ['大厅', 'dàtīng', 'noun', 'hall, lobby', 'salon, lobi', '홀, 로비'],
  ['大约', 'dàyuē', 'adverb', 'approximately, about', 'yaklaşık, aşağı yukarı', '대략, 약'],
  ['大自然', 'dàzìrán', 'noun', 'nature, the natural world', 'doğa, tabiat', '대자연'],
  ['待', 'dài, dāi', 'verb', 'to stay', 'kalmak', '머무르다, 지내다'],
  ['戴', 'dài', 'verb', 'to wear, to put on', 'takmak, giymek', '쓰다, 끼다, 차다'],
  ['袋子', 'dàizi', 'noun', 'bag, sack', 'torba, çanta', '봉지, 가방'],
  ['单位', 'dānwèi', 'noun', 'unit, department', 'birim, kurum', '단위, 부서, 기관'],
  ['当', 'dāng, dàng', 'verb', 'to serve as; at the time of', 'olarak hizmet etmek; zamanında', '되다, 맡다, 여기다'],
  ['当时', 'dāngshí', 'noun', 'at that time, then', 'o zaman, o sırada', '당시, 그때'],
  ['刀', 'dāo', 'noun', 'knife', 'bıçak', '칼'],
  ['导游', 'dǎoyóu', 'noun', 'tour guide', 'rehber, turist rehberi', '가이드, 여행 안내원'],
  ['倒', 'dǎo, dào', 'verb', 'to fall, to collapse; however', 'devrilmek; ancak', '넘어지다, 쓰러지다'],
  ['道', 'dào', 'noun', 'path, way, method', 'yol, yöntem', '길, 도리, 방법'],
  ['到底', 'dàodǐ', 'adverb', 'finally, after all, to the end', 'sonunda, ne de olsa', '드디어, 마침내, 결국'],
  ['到来', 'dàolái', 'verb', 'to arrive', 'gelmek, ulaşmak', '도착하다, 이르다'],
  ['道路', 'dàolù', 'noun', 'road, path', 'yol', '도로, 길'],
  ['道歉', 'dàoqiàn', 'verb', 'to apologize', 'özür dilemek', '사과하다'],
  ['得意', 'déyì', 'adjective', 'proud, complacent', 'gururlu, mağrur', '득의양양하다, 우쭐하다'],
  ['登机', 'dēngjī', 'verb', 'to board a plane', 'uçağa binmek', '탑승하다'],
  ['等', 'děng', 'auxiliary', 'and so on, etc.', 'vb., ve benzeri', '기다리다, 등등'],
  ['等到', 'děngdào', 'preposition', 'until, by the time', 'kadar, oluncaya kadar', '~까지 기다리다, ~할 때까지'],
  ['低', 'dī', 'adjective', 'low; to lower', 'düşük; alçaltmak', '낮은; 낮추다'],
  ['低价', 'dījià', 'noun', 'low price', 'düşük fiyat', '저가, 싼 가격'],
  ['低温', 'dīwēn', 'noun', 'low temperature', 'düşük sıcaklık', '저온'],
  ['低于', 'dīyú', 'verb', 'to be lower than', 'daha düşük olmak', '~보다 낮다'],
  ['底', 'dǐ', 'noun', 'bottom, base', 'alt, taban', '바닥, 밑'],
  ['底下', 'dǐxia', 'noun', 'below, underneath', 'altında, aşağısında', '아래, 밑'],
  ['地球', 'dìqiú', 'noun', 'earth', 'dünya', '지구'],
  ['地址', 'dìzhǐ', 'noun', 'address', 'adres', '주소'],
  ['点名', 'diǎnmíng', 'verb', 'to call the roll, to mention by name', 'yoklama yapmak', '점호하다, 이름을 부르다'],
  ['点头', 'diǎntóu', 'verb', 'to nod', 'başını sallamak', '고개를 끄덕이다'],
  ['电动车', 'diàndòngchē', 'noun', 'electric vehicle, e-bike', 'elektrikli araç', '전기차, 전기 자전거'],
  ['电视剧', 'diànshìjù', 'noun', 'TV drama', 'televizyon dizisi', '드라마'],
  ['掉', 'diào', 'verb', 'to fall, to drop', 'düşmek', '떨어지다, 빠지다'],
  ['调查', 'diàochá', 'verb', 'to investigate', 'araştırmak, soruşturmak', '조사하다'],
  ['订', 'dìng', 'verb', 'to order, to book', 'sipariş vermek, rezervasyon yapmak', '예약하다, 주문하다, 정하다'],
  ['定', 'dìng', 'verb', 'to fix, to set, to determine', 'belirlemek, saptamak', '정하다, 결정하다'],
  ['东部', 'dōngbù', 'noun', 'eastern part', 'doğu bölgesi', '동부'],
  ['动车', 'dòngchē', 'noun', 'high-speed train', 'hızlı tren', '동차, 고속 열차'],
  ['动作', 'dòngzuò', 'noun', 'movement, action', 'hareket, eylem', '동작, 행동'],
  ['读者', 'dúzhě', 'noun', 'reader', 'okuyucu', '독자'],
  ['堵车', 'dǔchē', 'noun', 'traffic jam', 'trafik sıkışıklığı', '교통 체증, 차가 막히다'],
  ['度假', 'dùjià', 'verb', 'to go on vacation', 'tatile gitmek', '휴가를 보내다'],
  ['肚子', 'dùzi', 'noun', 'belly, stomach', 'mide, karın', '배'],
  ['短信', 'duǎnxìn', 'noun', 'text message', 'kısa mesaj', '문자 메시지'],
  ['队', 'duì', 'noun', 'team, squad', 'takım, ekip', '팀, 대, 줄'],
  ['对方', 'duìfāng', 'noun', 'the other party, counterpart', 'karşı taraf', '상대방'],
  ['对面', 'duìmiàn', 'noun', 'opposite side', 'karşı taraf', '맞은편, 건너편'],
  ['对于', 'duìyú', 'preposition', 'regarding, concerning', 'konusunda, hakkında', '~에 대하여, ~에 관하여'],
  ['队员', 'duìyuán', 'noun', 'team member', 'takım üyesi', '팀원, 대원'],
  ['队长', 'duìzhǎng', 'noun', 'team leader', 'takım kaptanı', '팀장, 대장'],
  ['顿', 'dùn', 'classifier', 'measure word for meals', 'öğün sayacı', '끼 (식사 횟수를 세는 단위)'],
  ['多么', 'duōme', 'adverb', 'how, so, what', 'ne kadar', '얼마나, 참으로'],
  ['多数', 'duōshù', 'noun', 'majority', 'çoğunluk', '대다수, 대부분'],
  ['多样', 'duōyàng', 'adjective', 'diverse, varied', 'çeşitli, farklı', '다양하다'],
  ['而', 'ér', 'conjunction', 'but, and, yet', 'ama, ve, oysa', '그러나, 그리고, ~하며'],
  ['儿童', 'értóng', 'noun', 'child', 'çocuk', '아동, 어린이'],
  ['发出', 'fāchū', 'verb', 'to send out, to issue', 'göndermek, çıkarmak', '발하다, 내보내다'],
  ['发送', 'fāsòng', 'verb', 'to send', 'göndermek', '보내다, 발송하다'],
  ['法', 'fǎ', 'noun', 'law', 'hukuk, kanun', '법, 방법'],
  ['法律', 'fǎlǜ', 'noun', 'law', 'hukuk, kanun', '법률'],
  ['翻译', 'fānyì', 'verb', 'to translate; translation', 'çevirmek; çeviri', '번역하다, 통역하다, 번역(통역)'],
  ['烦', 'fán', 'adjective', 'annoyed, vexed', 'sinirli, rahatsız', '번거롭다, 짜증나다'],
  ['烦恼', 'fánnǎo', 'adjective', 'worried, distressed', 'kaygılı, üzgün', '번민하다, 고민하다'],
  ['反对', 'fǎnduì', 'verb', 'to oppose, to be against', 'karşı çıkmak', '반대하다'],
  ['方面', 'fāngmiàn', 'noun', 'aspect, side', 'yön, taraf', '방면, 측면'],
  ['方式', 'fāngshì', 'noun', 'way, method', 'yöntem, yol', '방식, 방법'],
  ['房东', 'fángdōng', 'noun', 'landlord', 'ev sahibi', '집주인'],
  ['房租', 'fángzū', 'noun', 'rent', 'kira', '집세'],
  ['放弃', 'fàngqì', 'verb', 'to give up', 'vazgeçmek', '포기하다'],
  ['放松', 'fàngsōng', 'verb', 'to relax', 'rahatlamak', '긴장을 풀다, 완화하다'],
  ['费', 'fèi', 'noun', 'fee, expense', 'ücret, gider', '비용, 요금'],
  ['费用', 'fèiyong', 'noun', 'cost, expense', 'maliyet, gider', '비용, 경비'],
  ['分数', 'fēnshù', 'noun', 'score, grade, fraction', 'not, puan', '점수, 성적; 분수'],
  ['分为', 'fēnwéi', 'verb', 'to be divided into', 'bölünmek', '…으로 나뉘다, …으로 분류되다'],
  ['份', 'fèn', 'classifier', 'measure word for copies, shares', 'kopya sayacı', '몫, 부, 편'],
  ['丰富', 'fēngfù', 'adjective', 'rich, abundant', 'zengin, bol', '풍부하다, 다채롭다'],
  ['风景', 'fēngjǐng', 'noun', 'scenery, landscape', 'manzara', '풍경, 경치'],
  ['否则', 'fǒuzé', 'conjunction', 'otherwise, if not', 'aksi takdirde', '그렇지 않으면, 안 그러면'],
  ['幅', 'fú', 'classifier', 'measure word for paintings, photos', 'resim sayacı', '폭(그림이나 사진을 세는 단위)'],
  ['符合', 'fúhé', 'verb', 'to conform to, to match', 'uymak, karşılamak', '부합하다, 일치하다'],
  ['付', 'fù', 'verb', 'to pay', 'ödemek', '지불하다'],
  ['父母', 'fùmǔ', 'noun', 'parents', 'anne-baba, ebeveynler', '부모'],
  ['父女', 'fùnǚ', 'noun', 'father and daughter', 'baba ve kız', '아버지와 딸'],
  ['父亲', 'fùqīn', 'noun', 'father', 'baba', '아버지'],
  ['复印', 'fùyìn', 'verb', 'to photocopy, to duplicate', 'fotokopi çekmek', '복사하다'],
  ['复杂', 'fùzá', 'adjective', 'complicated, complex', 'karmaşık', '복잡하다'],
  ['负责', 'fùzé', 'verb', 'to be responsible', 'sorumlu olmak', '책임지다, 담당하다'],
  ['负责人', 'fùzérén', 'noun', 'person in charge', 'sorumlu kişi', '책임자, 담당자'],
  ['父子', 'fùzǐ', 'noun', 'father and son', 'baba ve oğul', '아버지와 아들'],
  ['改', 'gǎi', 'verb', 'to change, to alter', 'değiştirmek', '고치다, 변경하다'],
  ['改变', 'gǎibiàn', 'verb', 'to change', 'değişmek, değiştirmek', '변하다, 바꾸다'],
  ['干', 'gān, gàn', 'adjective', 'dry', 'kuru', '하다, 마르다'],
  ['干杯', 'gānbēi', 'verb', 'to toast, cheers', 'kadeh kaldırmak, şerefe', '건배하다'],
  ['赶', 'gǎn', 'verb', 'to hurry, to catch up', 'acele etmek, yetişmek', '서두르다, 쫓아내다'],
  ['敢', 'gǎn', 'verb', 'to dare', 'cesaret etmek', '감히 ~하다'],
  ['感', 'gǎn', 'noun', 'sense, feeling', 'duygu, his', '느낌, 감각'],
  ['感动', 'gǎndòng', 'adjective', 'moved, touched; to move', 'duygulandırmak, dokunaklı', '감동하다, 감동시키다'],
  ['赶紧', 'gǎnjǐn', 'adverb', 'quickly, promptly', 'hemen, aceleyle', '서둘러, 급히'],
  ['感觉', 'gǎnjué', 'noun', 'feeling, sense; to feel', 'his, duygu, hissetmek', '느낌, 감각, 느끼다'],
  ['赶快', 'gǎnkuài', 'adverb', 'quickly, at once', 'hemen, çabuk', '어서, 빨리'],
  ['感情', 'gǎnqíng', 'noun', 'emotion, feeling', 'duygu, his', '감정, 정'],
  ['感人', 'gǎnrén', 'adjective', 'touching, moving', 'dokunaklı, duygulandırıcı', '감동적이다'],
  ['赶上', 'gǎnshàng', 'verb', 'to catch up, to keep up with', 'yetişmek', '따라잡다, 제시간에 대다'],
  ['感受', 'gǎnshòu', 'noun', 'feeling, experience; to feel', 'his, duygu, deneyim', '느낌, 감상, 느끼다'],
  ['感谢', 'gǎnxiè', 'verb', 'to thank', 'teşekkür etmek', '감사하다'],
  ['干活儿', 'gànhuór', 'verb', 'to work', 'çalışmak, iş yapmak', '일하다'],
  ['钢琴', 'gāngqín', 'noun', 'piano', 'piyano', '피아노'],
  ['高价', 'gāojià', 'noun', 'high price', 'yüksek fiyat', '고가'],
  ['高考', 'gāokǎo', 'noun', 'Gaokao, college entrance examination', 'üniversite giriş sınavı', '대학 입학 시험(가오카오)'],
  ['高速', 'gāosù', 'adjective', 'high speed', 'yüksek hız', '고속'],
  ['高温', 'gāowēn', 'noun', 'high temperature', 'yüksek sıcaklık', '고온'],
  ['高于', 'gāoyú', 'verb', 'higher than, above', 'daha yüksek olmak', '~보다 높다'],
  ['胳膊', 'gēbo', 'noun', 'arm', 'kol', '팔'],
  ['歌声', 'gēshēng', 'noun', 'sound of singing, song', 'şarkı sesi', '노랫소리'],
  ['歌手', 'gēshǒu', 'noun', 'singer', 'şarkıcı', '가수'],
  ['各', 'gè', 'pronoun', 'each, every', 'her, çeşitli', '각, 각각의'],
  ['各地', 'gèdì', 'noun', 'various places', 'çeşitli yerler', '각지, 여러 곳'],
  ['各个', 'gègè', 'pronoun', 'each, every; one by one', 'her biri, tek tek', '각각, 개개의'],
  ['各位', 'gèwèi', 'pronoun', 'everyone, all (respectful)', 'hepiniz', '여러분 (높임말)'],
  ['各种', 'gèzhǒng', 'pronoun', 'various kinds, all kinds', 'çeşit çeşit, her türlü', '각종, 여러 종류의'],
  ['更加', 'gèngjiā', 'adverb', 'more, even more', 'daha da', '더욱, 한층 더'],
  ['工厂', 'gōngchǎng', 'noun', 'factory', 'fabrika', '공장'],
  ['功夫', 'gōngfu', 'noun', 'kung fu, skill, effort', 'kung fu, beceri, çaba', '쿵푸, 무술, 공(功), 노력, 공(工)'],
  ['公共', 'gōnggòng', 'adjective', 'public, common', 'kamusal, ortak', '공공의, 공용의'],
  ['功课', 'gōngkè', 'noun', 'schoolwork, homework', 'ödev, ders çalışma', '공부, 숙제'],
  ['公里', 'gōnglǐ', 'classifier', 'kilometer', 'kilometre', '킬로미터'],
  ['公路', 'gōnglù', 'noun', 'highway, road', 'karayolu, otoyol', '도로, 길'],
  ['工人', 'gōngrén', 'noun', 'worker', 'işçi', '노동자, 근로자'],
  ['工资', 'gōngzī', 'noun', 'wage, salary', 'maaş, ücret', '임금, 급여'],
  ['共', 'gòng', 'adverb', 'together, in total', 'birlikte, toplamda', '함께, 같이, 도합'],
  ['共同', 'gòngtóng', 'adjective', 'common, joint', 'ortak, müşterek', '공동의, 함께'],
  ['够', 'gòu', 'adverb', 'enough; sufficiently', 'yeterli', '충분히, 꽤'],
  ['购买', 'gòumǎi', 'verb', 'to purchase', 'satın almak', '구매하다'],
  ['购物', 'gòuwù', 'verb', 'to shop', 'alışveriş yapmak', '쇼핑하다, 물건을 사다'],
  ['估计', 'gūjì', 'verb', 'to estimate, to guess', 'tahmin etmek', '추정하다, 예상하다'],
  ['姑娘', 'gūniang', 'noun', 'girl', 'kız, genç kız', '아가씨, 처녀'],
  ['鼓励', 'gǔlì', 'verb', 'to encourage', 'teşvik etmek, cesaretlendirmek', '격려하다, 장려하다'],
  ['顾客', 'gùkè', 'noun', 'customer', 'müşteri', '고객, 손님'],
  ['故意', 'gùyì', 'adverb', 'deliberately, on purpose', 'kasıtlı olarak, bilerek', '고의로, 일부러'],
  ['挂', 'guà', 'verb', 'to hang, to suspend', 'asmak', '걸다, 매달다'],
  ['关键', 'guānjiàn', 'adjective', 'key, crucial', 'kilit, önemli', '관건, 핵심, 결정적인'],
  ['观看', 'guānkàn', 'verb', 'to watch, to view', 'izlemek, seyretmek', '관람하다, 구경하다'],
  ['观众', 'guānzhòng', 'noun', 'audience', 'seyirci, izleyici', '관중, 관객'],
  ['管', 'guǎn', 'verb', 'control, manage', 'yönetmek, kontrol etmek', '관리하다, 상관하다, 간섭하다'],
  ['管理', 'guǎnlǐ', 'verb', 'manage', 'yönetmek', '관리하다'],
  ['光', 'guāng', 'noun', 'light; smooth; only', 'ışık; pürüzsüz; sadece', '빛, (수량)뿐, 오직'],
  ['广播', 'guǎngbō', 'noun', 'broadcast', 'yayın, radyo', '방송'],
  ['广告', 'guǎnggào', 'noun', 'advertisement', 'reklam', '광고'],
  ['逛', 'guàng', 'verb', 'stroll, roam, browse', 'gezmek, dolaşmak', '거닐다, 돌아다니다, 구경하다'],
  ['规定', 'guīdìng', 'noun', 'regulation, rule', 'kural, düzenleme', '규정'],
  ['国籍', 'guójí', 'noun', 'nationality', 'uyruk, milliyet', '국적'],
  ['国际', 'guójì', 'adjective', 'international', 'uluslararası', '국제적인'],
  ['果汁', 'guǒzhī', 'noun', 'fruit juice', 'meyve suyu', '과일 주스'],
  ['过程', 'guòchéng', 'noun', 'process', 'süreç', '과정'],
  ['海洋', 'hǎiyáng', 'noun', 'ocean, sea', 'okyanus, deniz', '해양, 바다'],
  ['害羞', 'hàixiū', 'adjective', 'shy, bashful', 'utangaç', '부끄러워하다, 수줍어하다'],
  ['寒假', 'hánjià', 'noun', 'winter vacation', 'kış tatili', '겨울방학'],
  ['寒冷', 'hánlěng', 'adjective', 'cold, frigid, chilly', 'soğuk, dondurucu', '춥다, 차갑다'],
  ['喊', 'hǎn', 'verb', 'shout', 'bağırmak, haykırmak', '외치다, 소리치다'],
  ['汗', 'hàn', 'noun', 'sweat', 'ter', '땀'],
  ['航班', 'hángbān', 'noun', 'flight', 'uçuş, sefer', '항공편'],
  ['好处', 'hǎochù', 'noun', 'benefit', 'fayda, avantaj', '이익, 장점'],
  ['好好', 'hǎohǎo', 'adverb', 'well, thoroughly', 'iyice, düzgünce', '잘, 충분히'],
  ['好笑', 'hǎoxiào', 'adjective', 'funny, ridiculous', 'komik, gülünç', '우스꽝스럽다, 웃기다'],
  ['合格', 'hégé', 'adjective', 'qualified', 'nitelikli, yeterli', '합격한, 자격이 있는'],
  ['盒子', 'hézi', 'noun', 'box', 'kutu', '상자, 갑'],
  ['红包', 'hóngbāo', 'noun', 'red envelope, red packet', 'kırmızı zarf (para hediyesi)', '홍바오(축의금이나 세뱃돈을 넣는 붉은 봉투)'],
  ['厚', 'hòu', 'adjective', 'thick', 'kalın', '두꺼운'],
  ['后悔', 'hòuhuǐ', 'verb', 'regret', 'pişman olmak', '후회하다'],
  ['忽然', 'hūrán', 'adverb', 'suddenly', 'birdenbire, aniden', '갑자기, 문득'],
  ['互联网', 'hùliánwǎng', 'noun', 'Internet', 'internet', '인터넷'],
  ['护士', 'hùshi', 'noun', 'nurse', 'hemşire', '간호사'],
  ['互相', 'hùxiāng', 'adverb', 'each other', 'birbirine', '서로'],
  ['话剧', 'huàjù', 'noun', 'drama', 'tiyatro oyunu', '연극'],
  ['怀疑', 'huáiyí', 'verb', 'doubt', 'şüphelenmek, kuşkulanmak', '의심하다'],
  ['坏处', 'huàichù', 'noun', 'disadvantage, harm', 'dezavantaj, zarar', '나쁜 점, 폐단, 해악'],
  ['环保', 'huánbǎo', 'noun', 'environmental protection', 'çevre koruma', '환경 보호'],
  ['换乘', 'huànchéng', 'verb', 'transfer, change', 'aktarma yapmak', '갈아타다, 환승하다'],
  ['回复', 'huífù', 'verb', 'reply', 'cevap vermek', '회신하다, 답하다'],
  ['回信', 'huíxìn', 'verb', 'reply to a letter, write back', 'mektuba cevap vermek', '답장을 쓰다'],
  ['回忆', 'huíyì', 'noun', 'memory', 'anı, hatıra', '회상, 추억'],
  ['会员', 'huìyuán', 'noun', 'membership', 'üyelik', '회원'],
  ['活', 'huó', 'verb', 'live; alive', 'yaşamak; canlı', '살다, 생존하다'],
  ['活动', 'huódòng', 'noun', 'activity, event', 'etkinlik, faaliyet', '활동, 행사'],
  ['活泼', 'huópō', 'adjective', 'lively', 'canlı, neşeli', '활발하다, 쾌활하다'],
  ['火', 'huǒ', 'noun', 'fire; popular, hot', 'ateş; popüler', '불, 인기 있다'],
  ['货', 'huò', 'noun', 'goods, commodity', 'mal, emtia', '물건, 상품'],
  ['获得', 'huòdé', 'verb', 'get, obtain', 'elde etmek, kazanmak', '얻다, 획득하다'],
  ['获奖', 'huòjiǎng', 'verb', 'win a prize, receive an award', 'ödül almak', '수상하다'],
  ['获取', 'huòqǔ', 'verb', 'gain, obtain', 'edinmek, elde etmek', '획득하다, 얻다'],
  ['基本', 'jīběn', 'adjective', 'basic, fundamental, essential', 'temel, esas', '기본적인, 근본적인'],
  ['基本上', 'jīběnshàng', 'adverb', 'basically', 'temelde, esasen', '기본적으로, 대체로'],
  ['基础', 'jīchǔ', 'noun', 'basics', 'temel, altyapı', '기초, 기반'],
  ['激动', 'jīdòng', 'adjective', 'excited, agitated', 'heyecanlı, coşkulu', '격앙되다, 흥분하다'],
  ['积极', 'jījí', 'adjective', 'positive', 'olumlu, aktif', '적극적이다'],
  ['积累', 'jīlěi', 'verb', 'to accumulate, to build up', 'biriktirmek, birikmek', '축적하다, 쌓다'],
  ['及时', 'jíshí', 'adverb', 'timely, prompt, in time', 'zamanında, vakitli', '시기적절한, 때맞춘'],
  ['即使', 'jíshǐ', 'conjunction', 'even if', 'olsa bile', '비록 ~일지라도'],
  ['既', 'jì', 'conjunction', 'both ... and ...', 'hem...hem de', '이미, ~이자 ~이다'],
  ['寄', 'jì', 'verb', 'send', 'göndermek (posta)', '부치다, 보내다'],
  ['计划', 'jìhuà', 'noun', 'plan, project', 'plan, proje', '계획'],
  ['既然', 'jìrán', 'conjunction', 'since', 'madem ki', '기왕, ~인 바에야'],
  ['技术', 'jìshù', 'noun', 'technology', 'teknoloji', '기술'],
  ['继续', 'jìxù', 'verb', 'continue', 'devam etmek', '계속하다'],
  ['记者', 'jìzhě', 'noun', 'reporter', 'gazeteci, muhabir', '기자'],
  ['加班', 'jiābān', 'verb', 'work overtime', 'fazla mesai yapmak', '초과 근무하다, 야근하다'],
  ['家具', 'jiājù', 'noun', 'furniture', 'mobilya', '가구'],
  ['加快', 'jiākuài', 'verb', 'speed up, accelerate', 'hızlandırmak', '가속하다, 속도를 높이다'],
  ['加强', 'jiāqiáng', 'verb', 'strengthen, reinforce', 'güçlendirmek', '강화하다, 보강하다'],
  ['加入', 'jiārù', 'verb', 'add, join, become a member', 'katılmak, eklemek', '가입하다, 합류하다, 더하다'],
  ['加上', 'jiāshàng', 'conjunction', 'plus, add, with the addition of', 'artı, ekleyerek', '~을 더하여, ~을 포함하여'],
  ['家庭', 'jiātíng', 'noun', 'family', 'aile', '가정, 가족'],
  ['家乡', 'jiāxiāng', 'noun', 'hometown', 'memleket', '고향'],
  ['加油', 'jiāyóu', 'verb', 'make an all-out effort, cheer on', 'hadi, destek ver', '힘내다, 응원하다, 기름을 넣다'],
  ['加油站', 'jiāyóuzhàn', 'noun', 'gas station', 'benzin istasyonu', '주유소'],
  ['家长', 'jiāzhǎng', 'noun', 'parent, head of the family', 'veli, aile reisi', '학부모, 가장'],
  ['假', 'jiǎ, jià', 'adjective', 'false, fake', 'sahte, yanlış', '가짜의, 거짓의'],
  ['价格', 'jiàgé', 'noun', 'price', 'fiyat', '가격'],
  ['价钱', 'jiàqián', 'noun', 'price', 'fiyat', '값, 가격'],
  ['假日', 'jiàrì', 'noun', 'holiday, day off, vacation', 'tatil günü', '휴일, 공휴일, 휴가'],
  ['减', 'jiǎn', 'verb', 'to reduce, to decrease', 'azaltmak, indirmek', '줄다, 감소하다'],
  ['减轻', 'jiǎnqīng', 'verb', 'to lighten, to ease, to alleviate', 'hafifletmek', '경감하다, 완화하다'],
  ['减少', 'jiǎnshǎo', 'verb', 'to reduce, to decrease', 'azaltmak', '감소하다, 줄이다'],
  ['健身', 'jiànshēn', 'verb', 'to exercise, to work out', 'egzersiz yapmak, spor yapmak', '건강을 증진하다, 몸을 단련하다'],
  ['健身房', 'jiànshēnfáng', 'noun', 'gym', 'spor salonu', '체력 단련실, 헬스장'],
  ['建议', 'jiànyì', 'noun', 'suggestion, proposal', 'öneri; önermek', '제안, 의견'],
  ['江', 'jiāng', 'noun', 'river', 'nehir', '강'],
  ['将', 'jiāng, jiàng', 'adverb', 'will, shall, be about to', '-ecek, yakında', '장차, 앞으로'],
  ['将来', 'jiānglái', 'noun', 'future', 'gelecek', '장래, 미래'],
  ['将要', 'jiāngyào', 'adverb', 'will, be going to, be about to', 'olmak üzere', '장차 ~하려고 하다, 곧 ~할 것이다'],
  ['奖', 'jiǎng', 'noun', 'prize, award, reward', 'ödül', '상, 상금'],
  ['奖金', 'jiǎngjīn', 'noun', 'bonus, prize money, cash award', 'ikramiye, ödül parası', '상금, 보너스'],
  ['奖学金', 'jiǎngxuéjīn', 'noun', 'scholarship, fellowship', 'burs', '장학금'],
  ['降', 'jiàng', 'verb', 'to fall, to drop, to descend', 'inmek, düşmek', '내리다, 떨어지다'],
  ['降低', 'jiàngdī', 'verb', 'to reduce, to lower, to bring down', 'azaltmak, düşürmek', '낮추다, 저하시키다'],
  ['降价', 'jiàngjià', 'verb', 'to reduce price', 'fiyat düşürmek, indirim yapmak', '가격을 내리다, 할인하다'],
  ['降落', 'jiàngluò', 'verb', 'to descend, to land, to touch down', 'inmek, alçalmak', '내리다, 착륙하다'],
  ['降温', 'jiàngwēn', 'verb', 'to cool down, to lower the temperature', 'soğumak, sıcaklığı düşürmek', '기온이 내려가다, 냉각하다'],
  ['交', 'jiāo', 'verb', 'to hand in; to make friends with', 'teslim etmek; arkadaş olmak', '사귀다, 사귀게 되다; 건네주다'],
  ['骄傲', 'jiāoào', 'adjective', 'proud, arrogant; pride', 'gururlu, kibirli; gurur', '자랑스럽다, 오만하다, 자부심'],
  ['交警', 'jiāojǐng', 'noun', 'traffic police', 'trafik polisi', '교통 경찰'],
  ['交流', 'jiāoliú', 'verb', 'communicate', 'iletişim kurmak', '교류하다, 소통하다'],
  ['郊区', 'jiāoqū', 'noun', 'suburb', 'banliyö, şehir dışı', '교외'],
  ['交通', 'jiāotōng', 'noun', 'traffic', 'trafik, ulaşım', '교통'],
  ['教练', 'jiàoliàn', 'noun', 'coach', 'antrenör, koç', '코치, 감독'],
  ['教师', 'jiàoshī', 'noun', 'teacher', 'öğretmen', '교사'],
  ['教授', 'jiàoshòu', 'noun', 'professor', 'profesör', '교수'],
  ['教学', 'jiàoxué', 'noun', 'teaching, education', 'öğretmek, eğitim', '교수, 교육'],
  ['教育', 'jiàoyù', 'noun', 'education; to educate', 'eğitim; eğitmek', '교육, 교육하다'],
  ['叫作', 'jiàozuò', 'verb', 'be called, be known as', 'olarak bilinmek', '~라고 불리다, ~로 알려지다'],
  ['街道', 'jiēdào', 'noun', 'street', 'cadde, sokak', '거리, 가로'],
  ['接受', 'jiēshòu', 'verb', 'accept', 'kabul etmek', '받아들이다, 수용하다'],
  ['接着', 'jiēzhe', 'adverb', 'then, next, subsequently', 'ardından, devam ederek', '이어서, 계속해서'],
  ['结果', 'jiéguǒ', 'noun', 'result, outcome, consequence', 'sonuç', '결과'],
  ['节假日', 'jiéjiàrì', 'noun', 'festivals and holidays', 'bayram ve tatil günleri', '명절과 휴일'],
  ['节约', 'jiéyuē', 'verb', 'to save, to economize, to conserve', 'tasarruf etmek', '절약하다'],
  ['结账', 'jiézhàng', 'verb', 'to pay the bill, to settle an account', 'hesabı ödemek', '계산하다'],
  ['解释', 'jiěshì', 'verb', 'to explain, to interpret', 'açıklamak', '설명하다, 해석하다'],
  ['今后', 'jīnhòu', 'noun', 'from now on, in the future', 'bundan sonra', '금후, 앞으로'],
  ['仅', 'jǐn', 'adverb', 'only, merely, solely', 'sadece, yalnızca', '단지, 겨우'],
  ['尽管', 'jǐnguǎn', 'conjunction', 'although, even though', 'her ne kadar olsa da', '비록 ~일지라도, ~에도 불구하고'],
  ['仅仅', 'jǐnjǐn', 'adverb', 'only, merely, barely', 'sadece, yalnızca', '단지, 겨우'],
  ['紧张', 'jǐnzhāng', 'adjective', 'nervous, tense', 'gergin, sinirli', '긴장되다, 빠듯하다'],
  ['进入', 'jìnrù', 'verb', 'to enter, to access', 'girmek', '들어가다, 진입하다'],
  ['进行', 'jìnxíng', 'verb', 'to carry out, to conduct', 'yürütmek, gerçekleştirmek', '진행하다, 하다'],
  ['禁止', 'jìnzhǐ', 'verb', 'to prohibit, to forbid, to ban', 'yasaklamak', '금지하다'],
  ['精彩', 'jīngcǎi', 'adjective', 'brilliant, splendid, wonderful', 'muhteşem, harika', '훌륭하다, 뛰어나다'],
  ['经济', 'jīngjì', 'noun', 'economy; economical', 'ekonomi; ekonomik', '경제, 경제적이다'],
  ['京剧', 'jīngjù', 'noun', 'Beijing opera', 'Pekin operası', '경극'],
  ['经历', 'jīnglì', 'noun', 'experience, past; to experience', 'deneyim; deneyimlemek', '경험, 겪다'],
  ['经验', 'jīngyàn', 'noun', 'experience', 'deneyim', '경험'],
  ['警察', 'jǐngchá', 'noun', 'police', 'polis', '경찰'],
  ['景点', 'jǐngdiǎn', 'noun', 'scenic spot, tourist attraction', 'turistik yer, gezi noktası', '관광지, 명승지'],
  ['景区', 'jǐngqū', 'noun', 'scenic area, tourist attraction zone', 'turistik bölge', '관광 구역, 경승지'],
  ['景色', 'jǐngsè', 'noun', 'scenery', 'manzara', '경치, 풍경'],
  ['竟然', 'jìngrán', 'adverb', 'unexpectedly', 'beklenmedik şekilde', '뜻밖에, 의외로'],
  ['竞争', 'jìngzhēng', 'verb', 'compete', 'rekabet etmek', '경쟁하다'],
  ['镜子', 'jìngzi', 'noun', 'mirror', 'ayna', '거울'],
  ['究竟', 'jiūjìng', 'adverb', 'actually, exactly, after all', 'aslında, tam olarak', '도대체, 결국'],
  ['就是', 'jiùshì', 'adverb', 'precisely, exactly', 'tam olarak, işte', '바로, 다름 아닌'],
  ['举', 'jǔ', 'verb', 'to raise; to hold; to give an example', 'kaldırmak; düzenlemek; örnek vermek', '들다, 일으키다; 개최하다; (예를) 들다'],
  ['举办', 'jǔbàn', 'verb', 'to hold, to host, to organize', 'düzenlemek, ev sahipliği yapmak', '개최하다, 개최되다'],
  ['举例', 'jǔlì', 'verb', 'to give an example', 'örnek vermek', '예를 들다'],
  ['举行', 'jǔxíng', 'verb', 'to hold, to convene, to conduct', 'düzenlemek, gerçekleştirmek', '개최하다, 거행하다'],
  ['聚', 'jù', 'verb', 'to gather, to assemble', 'toplanmak', '모이다, 모으다'],
  ['聚餐', 'jùcān', 'verb', 'to have a dinner together', 'birlikte yemek yemek', '함께 식사하다'],
  ['聚会', 'jùhuì', 'noun', 'party, gathering; to get together', 'parti; bir araya gelmek', '모임, 파티, 모이다'],
  ['拒绝', 'jùjué', 'verb', 'to refuse, to reject, to decline', 'reddetmek', '거절하다, 거부하다'],
  ['距离', 'jùlí', 'noun', 'distance, gap', 'mesafe, uzaklık', '거리, 간격'],
  ['剧院', 'jùyuàn', 'noun', 'theater, opera house', 'tiyatro', '극장, 공연장'],
  ['开玩笑', 'kāiwánxiào', 'verb', 'make fun of, to joke', 'şaka yapmak', '농담하다, 장난치다'],
  ['看法', 'kànfǎ', 'noun', 'view', 'görüş, fikir', '견해, 생각'],
  ['烤', 'kǎo', 'verb', 'to bake, to roast, to grill', 'pişirmek, fırınlamak', '굽다'],
  ['考虑', 'kǎolǜ', 'verb', 'to consider, to think over', 'düşünmek, değerlendirmek', '고려하다, 생각하다'],
  ['考生', 'kǎoshēng', 'noun', 'examinee', 'sınav adayı', '수험생'],
  ['棵', 'kē', 'classifier', 'measure word for trees, plants', 'ağaç sayacı', '그루 (식물을 세는 단위)'],
  ['科技', 'kējì', 'noun', 'science and technology', 'bilim ve teknoloji', '과학 기술'],
  ['科学', 'kēxué', 'noun', 'science; scientific', 'bilim; bilimsel', '과학'],
  ['咳', 'ké', 'verb', 'to cough', 'öksürmek', '기침하다'],
  ['咳嗽', 'késou', 'verb', 'to cough', 'öksürmek', '기침하다'],
  ['可惜', 'kěxī', 'adjective', 'regrettable, unfortunate, a pity', 'yazık, ne yazık ki', '아쉽다, 유감스럽다'],
  ['克', 'kè', 'classifier', 'gram', 'gram', '그램'],
  ['课程', 'kèchéng', 'noun', 'curriculum', 'müfredat, ders programı', '교육 과정, 교과 과정'],
  ['客气', 'kèqi', 'adjective', 'polite, courteous', 'nazik, kibar', '예의 바르다, 겸손하다'],
  ['课堂', 'kètáng', 'noun', 'classroom', 'sınıf', '교실, 수업 시간'],
  ['客厅', 'kètīng', 'noun', 'living room, parlor', 'oturma odası, salon', '거실'],
  ['肯定', 'kěndìng', 'adverb', 'surely, certainly, definitely', 'kesinlikle, elbette', '분명히, 틀림없이'],
  ['空', 'kōng, kòng', 'adjective', 'empty, vacant', 'boş, tenha', '비어 있다, 한가하다, 틈을 내다'],
  ['空', 'kōng, kòng', 'verb', 'to leave empty, to make free time; free time', 'boş bırakmak; boş vakit', '비어 있다, 한가하다, 틈을 내다'],
  ['空气', 'kōngqì', 'noun', 'atmosphere, air', 'hava, atmosfer', '공기'],
  ['恐怕', 'kǒngpà', 'adverb', 'I am afraid, perhaps, maybe', 'korkarım ki, belki', '아마, 혹시'],
  ['口语', 'kǒuyǔ', 'noun', 'spoken language', 'konuşma dili', '구어, 회화체'],
  ['苦', 'kǔ', 'adjective', 'bitter', 'acı', '쓰다'],
  ['快餐', 'kuàicān', 'noun', 'fast food', 'fast food, hazır yemek', '패스트푸드'],
  ['快递', 'kuàidì', 'noun', 'express delivery', 'kargo, hızlı teslimat', '택배'],
  ['快速', 'kuàisù', 'adjective', 'fast, high-speed', 'hızlı', '빠르다, 신속하다'],
  ['困', 'kùn', 'adjective', 'sleepy, tired', 'uykulu, yorgun', '졸린, 피곤한'],
  ['困难', 'kùnnan', 'noun', 'difficulty; difficult', 'zorluk; zor', '어려움, 곤란; 어려운'],
  ['拉', 'lā', 'verb', 'to pull, to drag', 'çekmek', '당기다, 끌다'],
  ['垃圾', 'lājī', 'noun', 'garbage, trash, rubbish', 'çöp', '쓰레기'],
  ['辣', 'là', 'adjective', 'hot, spicy', 'acılı, baharatlı', '맵다'],
  ['来不及', 'láibují', 'verb', 'there is not enough time', 'yetişmek mümkün değil', '시간이 늦다, 미처 ~하지 못하다'],
  ['来得及', 'láidejí', 'verb', 'there is still time, can make it in time', 'hâlâ zaman var, yetişebilir', '시간이 충분하다, 제시간에 대다'],
  ['懒', 'lǎn', 'adjective', 'lazy, idle', 'tembel', '게으르다'],
  ['浪费', 'làngfèi', 'verb', 'to waste, to squander', 'israf etmek', '낭비하다'],
  ['浪漫', 'làngmàn', 'adjective', 'romantic', 'romantik', '낭만적이다'],
  ['老虎', 'lǎohǔ', 'noun', 'tiger', 'kaplan', '호랑이'],
  ['老家', 'lǎojiā', 'noun', 'hometown, home state', 'memleket', '고향'],
  ['老年', 'lǎonián', 'noun', 'elderly', 'yaşlılık, ihtiyarlık', '노년'],
  ['老是', 'lǎoshì', 'adverb', 'always, constantly', 'hep, sürekli', '늘, 항상, 자꾸'],
  ['冷静', 'lěngjìng', 'adjective', 'calm, cool-headed', 'sakin, soğukkanlı', '냉정하다, 침착하다'],
  ['理发', 'lǐfà', 'verb', 'to have a haircut, to cut hair', 'saç kestirmek', '이발하다, 머리를 자르다'],
  ['理解', 'lǐjiě', 'verb', 'to understand, to comprehend', 'anlamak, kavramak', '이해하다'],
  ['礼貌', 'lǐmào', 'adjective', 'courtesy, politeness; polite', 'nezaket; kibar', '예의 바르다, 예의'],
  ['理想', 'lǐxiǎng', 'noun', 'ideal, dream; ideal', 'ideal, hayal; ideal', '이상, 이상적인'],
  ['厉害', 'lìhai', 'adjective', 'severe, fierce, impressive, excellent', 'şiddetli; etkileyici, harika', '심하다, 사납다, 대단하다, 뛰어나다'],
  ['力气', 'lìqi', 'noun', 'strength, physical power', 'güç, kuvvet', '힘, 기력'],
  ['例如', 'lìrú', 'verb', 'for example, such as', 'örneğin', '예를 들다, 예를 들면'],
  ['例子', 'lìzi', 'noun', 'example, instance', 'örnek', '예, 보기'],
  ['俩', 'liǎ', 'number', 'two, both', 'ikisi, ikisi de', '둘, 두 사람'],
  ['连', 'lián', 'preposition', 'even, including', 'bile, dahil', '~조차, ~까지 (부사)'],
  ['联系', 'liánxì', 'verb', 'to contact, to connect', 'iletişim kurmak', '연락하다, 연계하다'],
  ['凉', 'liáng', 'adjective', 'cool, cold', 'serin, soğuk', '서늘하다, 차갑다'],
  ['量', 'liàng, liáng', 'verb', 'to measure, to weigh', 'ölçmek, tartmak', '양, 분량'],
  ['两', 'liǎng', 'classifier', 'two; measure word for paired things', 'iki; çift sayacı', '둘, 두 (수량)'],
  ['亮', 'liàng', 'adjective', 'bright, light', 'parlak, aydınlık', '밝다, 빛나다'],
  ['列', 'liè', 'verb', 'to list; measure word for rows', 'sıralamak; sıra sayacı', '열거하다, 나열하다; 열(줄)'],
  ['零下', 'língxià', 'noun', 'below zero', 'sıfırın altında', '영하'],
  ['零花钱', 'línghuāqián', 'noun', 'pocket money, spending money', 'harçlık', '용돈'],
  ['零钱', 'língqián', 'noun', 'change, small denominations of money', 'bozuk para', '잔돈'],
  ['零食', 'língshí', 'noun', 'snacks, between-meal nibbles', 'atıştırmalık', '간식'],
  ['另', 'lìng', 'pronoun', 'other, another', 'diğer, başka', '다른'],
  ['另外', 'lìngwài', 'conjunction', 'in addition, moreover; other', 'bunun dışında; diğer', '그 외에, 또한; 다른'],
  ['留', 'liú', 'verb', 'to stay, to remain, to keep', 'kalmak, tutmak', '머무르다, 남기다, 보관하다'],
  ['流', 'liú', 'verb', 'to flow, to circulate', 'akmak', '흐르다, 유통되다'],
  ['流利', 'liúlì', 'adjective', 'fluent, smooth', 'akıcı', '유창하다, 매끄럽다'],
  ['留下', 'liúxia', 'verb', 'to leave behind, to remain', 'geride bırakmak', '남기다, 남겨두다'],
  ['流行', 'liúxíng', 'verb', 'to be popular, to be in fashion', 'popüler olmak, yaygın olmak', '유행하다, 널리 퍼지다'],
  ['路过', 'lùguò', 'verb', 'to pass by, to go by', 'yanından geçmek', '지나가다, 경유하다'],
  ['旅馆', 'lǚguǎn', 'noun', 'hotel, inn', 'otel, han', '여관, 호텔'],
  ['旅客', 'lǚkè', 'noun', 'traveler, passenger', 'yolcu, gezgin', '여행객, 승객'],
  ['旅行', 'lǚxíng', 'verb', 'to travel', 'seyahat etmek', '여행하다'],
  ['律师', 'lǜshī', 'noun', 'lawyer, attorney', 'avukat', '변호사'],
  ['乱', 'luàn', 'adjective', 'messy, disorderly', 'dağınık, düzensiz', '어지럽다, 혼란스럽다, 무질서하다'],
  ['落', 'luò, là, lào', 'verb', 'to fall, to drop, to land', 'düşmek, inmek', '떨어지다, 빠뜨리다, 남다'],
  ['麻烦', 'máfan', 'noun', 'troublesome; trouble', 'zahmetli; sorun', '성가시다, 번거롭다, 귀찮은 일'],
  ['馒头', 'mántou', 'noun', 'steamed bun, mantou', 'buharda pişmiş ekmek', '만터우(중국식 찐빵)'],
  ['满', 'mǎn', 'adjective', 'full, filled', 'dolu', '가득 차다, 충만하다'],
  ['毛巾', 'máojīn', 'noun', 'towel', 'havlu', '수건'],
  ['毛衣', 'máoyī', 'noun', 'sweater, woolen garment', 'kazak, yünlü', '스웨터'],
  ['帽子', 'màozi', 'noun', 'hat, cap', 'şapka', '모자'],
  ['美', 'měi', 'adjective', 'beautiful, pretty', 'güzel', '아름답다, 좋다'],
  ['美好', 'měihǎo', 'adjective', 'beautiful, splendid', 'güzel, harika', '아름답다, 훌륭하다'],
  ['美景', 'měijǐng', 'noun', 'beautiful scenery', 'güzel manzara', '아름다운 경치'],
  ['美丽', 'měilì', 'adjective', 'beautiful, lovely', 'güzel, hoş', '아름답다, 예쁘다'],
  ['美食', 'měishí', 'noun', 'delicious food, cuisine', 'lezzetli yemek', '맛있는 음식, 미식'],
  ['梦', 'mèng', 'noun', 'dream; to dream', 'rüya; rüya görmek', '꿈, 꿈꾸다'],
  ['梦想', 'mèngxiǎng', 'noun', 'dream; to dream', 'hayal; hayal etmek', '꿈, 희망, 꿈꾸다'],
  ['密码', 'mìmǎ', 'noun', 'password, PIN code', 'şifre, parola', '비밀번호'],
  ['免费', 'miǎnfèi', 'verb', 'free of charge, to be free', 'ücretsiz', '무료이다, 공짜이다'],
  ['面对', 'miànduì', 'verb', 'to face, to confront', 'yüz yüze gelmek, karşılaşmak', '마주하다, 직면하다'],
  ['面试', 'miànshì', 'noun', 'interview, audition', 'mülakat', '면접'],
  ['秒', 'miǎo', 'classifier', 'second, unit of time', 'saniye', '초(시간 단위)'],
  ['民族', 'mínzú', 'noun', 'ethnic group, nationality', 'etnik grup, millet', '민족'],
  ['末', 'mò', 'noun', 'end, last', 'son, nihayet', '끝, 말기'],
  ['母女', 'mǔnǚ', 'noun', 'mother and daughter', 'anne ve kız', '모녀'],
  ['母亲', 'mǔqīn', 'noun', 'mother', 'anne', '어머니'],
  ['母子', 'mǔzǐ', 'noun', 'mother and son', 'anne ve oğul', '모자'],
  ['目标', 'mùbiāo', 'noun', 'goal, target, objective', 'hedef, amaç', '목표'],
  ['目的', 'mùdì', 'noun', 'purpose, aim, goal', 'amaç, gaye', '목적, 목표'],
  ['目的地', 'mùdìdì', 'noun', 'destination', 'varış noktası', '목적지'],
  ['目前', 'mùqián', 'noun', 'currently, at present', 'şu anda, şu sıralar', '현재, 지금'],
  ['耐心', 'nàixīn', 'noun', 'patient; patience', 'sabırlı; sabır', '인내심, 참을성, 참을성 있는'],
  ['南部', 'nánbù', 'noun', 'southern part, south', 'güney bölgesi', '남부, 남쪽'],
  ['难道', 'nándào', 'adverb', 'could it be that...?', 'masa ki, acaba', '설마'],
  ['男士', 'nánshì', 'noun', 'man, gentleman', 'erkek, bay', '남성, 신사'],
  ['难受', 'nánshòu', 'adjective', 'uncomfortable, painful', 'rahatsız, acı veren', '괴롭다, 거북하다'],
  ['难忘', 'nánwàng', 'verb', 'unforgettable, hard to forget', 'unutulmaz', '잊기 어렵다'],
  ['男性', 'nánxìng', 'noun', 'male, masculine', 'erkek, eril', '남성'],
  ['内', 'nèi', 'noun', 'inside, within', 'içinde, içeri', '안, 내부'],
  ['内容', 'nèiróng', 'noun', 'content, substance', 'içerik', '내용, 골자'],
  ['内心', 'nèixīn', 'noun', 'heart, inner self', 'iç dünya, kalp', '내심, 마음속'],
  ['能否', 'néngfǒu', 'adverb', 'whether or not, can or cannot', 'yapıp yapamayacağını, olup olmadığını', '할 수 있는지 없는지'],
  ['能够', 'nénggòu', 'verb', 'can, be able to, be capable of', 'yapabilmek', '할 수 있다'],
  ['能力', 'nénglì', 'noun', 'ability, capability, capacity', 'yetenek, kapasite', '능력'],
  ['嗯', 'ǹg', 'interjection', 'uh-huh, hmm', 'hı-hı, hmm', '응, 음'],
  ['年底', 'niándǐ', 'noun', 'end of the year', 'yıl sonu', '연말'],
  ['年龄', 'niánlíng', 'noun', 'age', 'yaş', '나이, 연령'],
  ['农村', 'nóngcūn', 'noun', 'rural area, countryside', 'kırsal bölge, köy', '농촌, 시골'],
  ['弄', 'nòng', 'verb', 'to do, to handle, to mess with', 'yapmak, halletmek', '하다, 다루다, 만들다'],
  ['女性', 'nǚxìng', 'noun', 'female, feminine', 'kadın, dişil', '여성'],
  ['暖和', 'nuǎnhuo', 'adjective', 'warm; to warm up', 'ılık, sıcacık', '따뜻하다'],
  ['偶尔', 'ǒuěr', 'adverb', 'occasionally, sometimes', 'ara sıra, bazen', '가끔, 이따금'],
  ['拍', 'pāi', 'verb', 'to pat, to clap; to take a photo', 'vurmak; fotoğraf çekmek', '치다, 두드리다, 사진을 찍다'],
  ['排', 'pái', 'noun', 'row, line; to line up', 'sıra; sıraya girmek', '줄, 열, 줄을 서다'],
  ['牌', 'pái', 'noun', 'card, brand, plaque, sign', 'kart, marka', '카드, 상표, 패'],
  ['排队', 'páiduì', 'verb', 'to line up, to queue up', 'sıraya girmek', '줄을 서다'],
  ['排球', 'páiqiú', 'noun', 'volleyball', 'voleybol', '배구'],
  ['牌子', 'páizi', 'noun', 'brand, sign, label', 'marka, tabela', '상표, 브랜드, 간판'],
  ['判断', 'pànduàn', 'verb', 'to judge, to determine', 'yargılamak, değerlendirmek', '판단하다, 분별하다'],
  ['陪', 'péi', 'verb', 'to accompany, to keep someone company', 'eşlik etmek', '동행하다, 곁을 지키다'],
  ['批评', 'pīpíng', 'verb', 'to criticize', 'eleştirmek', '비판하다, 꾸짖다'],
  ['皮肤', 'pífū', 'noun', 'skin', 'cilt, deri', '피부'],
  ['脾气', 'píqi', 'noun', 'temperament, disposition, temper', 'huy, mizaç', '성격, 성질'],
  ['皮鞋', 'píxié', 'noun', 'leather shoes', 'deri ayakkabı', '구두'],
  ['篇', 'piān', 'classifier', 'measure word for essays, articles', 'makale sayacı', '편(글을 세는 단위)'],
  ['片', 'piàn', 'classifier', 'piece, slice, area', 'parça, dilim', '조각, 얇은 것 (양사)'],
  ['乒乓球', 'pīngpāngqiú', 'noun', 'table tennis, ping-pong', 'masa tenisi', '탁구'],
  ['平常', 'píngcháng', 'adjective', 'ordinary, usual', 'olağan, normal', '평범하다, 보통이다'],
  ['破', 'pò', 'adjective', 'broken, damaged', 'kırık, hasarlı', '깨지다, 낡다, 해지다'],
  ['葡萄', 'pútao', 'noun', 'grape', 'üzüm', '포도'],
  ['葡萄酒', 'pútaojiǔ', 'noun', 'wine, grape wine', 'şarap', '포도주, 와인'],
  ['普遍', 'pǔbiàn', 'adjective', 'widespread, universal, common', 'yaygın, evrensel', '보편적인, 일반적인, 널리 퍼진'],
  ['普通', 'pǔtōng', 'adjective', 'ordinary, common', 'sıradan, olağan', '보통의, 평범한'],
  ['普通话', 'pǔtōnghuà', 'noun', 'Mandarin Chinese, standard Chinese', 'Mandarin Çincesi', '표준어(중국어)'],
  ['期', 'qī', 'classifier', 'period, phase; measure word for issues', 'dönem, periyot', '기간, 기(期, 잡지 등의 권수)'],
  ['期末', 'qīmò', 'noun', 'end of term, end of semester', 'dönem sonu', '학기 말, 기말'],
  ['期中', 'qīzhōng', 'noun', 'midterm, middle of the term', 'dönem ortası', '학기 중, 중간'],
  ['其次', 'qícì', 'pronoun', 'next, secondly, then', 'ikinci olarak, sıra ile', '그다음으로, 버금가는'],
  ['其中', 'qízhōng', 'noun', 'among them, inside', 'aralarında, içinde', '그중, 그 안에'],
  ['起到', 'qǐdào', 'verb', 'to play the role of, to function as', 'rolünü oynamak', '역할을 하다, 기능을 하다'],
  ['气', 'qì', 'noun', 'air, gas, breath; to anger', 'hava, gaz; kızdırmak', '공기, 기운, 화나다'],
  ['气候', 'qìhòu', 'noun', 'climate', 'iklim', '기후'],
  ['汽水', 'qìshuǐ', 'noun', 'soda, soft drink', 'gazlı içecek', '사이다, 탄산음료'],
  ['气温', 'qìwēn', 'noun', 'air temperature', 'hava sıcaklığı', '기온'],
  ['千克', 'qiānkè', 'classifier', 'kilogram', 'kilogram', '킬로그램'],
  ['千万', 'qiānwàn', 'adverb', 'by all means, absolutely', 'kesinlikle, mutlaka', '부디, 절대로, 수천만'],
  ['签证', 'qiānzhèng', 'noun', 'visa; to issue a visa', 'vize', '비자, 사증'],
  ['前方', 'qiánfāng', 'noun', 'ahead, front', 'önde, ileride', '앞, 전방'],
  ['前后', 'qiánhòu', 'noun', 'front and back; around, about', 'önü ve arkası; yaklaşık', '앞뒤, 전후, 주변, 근처'],
  ['强', 'qiáng, qiǎng, jiàng', 'adjective', 'strong, powerful', 'güçlü, kuvvetli', '강하다, 강력하다'],
  ['敲', 'qiāo', 'verb', 'to knock, to tap, to strike', 'vurmak, çalmak', '두드리다, 치다'],
  ['桥', 'qiáo', 'noun', 'bridge', 'köprü', '다리'],
  ['巧', 'qiǎo', 'adjective', 'skillful, clever, opportune', 'becerili, ustaca', '교묘하다, 공교롭다, 솜씨가 좋다'],
  ['巧克力', 'qiǎokèlì', 'noun', 'chocolate', 'çikolata', '초콜릿'],
  ['亲戚', 'qīnqi', 'noun', 'relative, relative family member', 'akraba', '친척'],
  ['琴', 'qín', 'noun', 'musical instrument, piano', 'müzik aleti, piyano', '악기, 피아노'],
  ['轻', 'qīng', 'adjective', 'light, not heavy, gentle, easy', 'hafif; nazik', '가볍다, 쉽다, 부드럽다'],
  ['青年', 'qīngnián', 'noun', 'youth, young people', 'genç, gençlik', '청년'],
  ['轻松', 'qīngsōng', 'adjective', 'relaxed, light, easy', 'rahat, kolay', '홀가분하다, 편안하다, 쉽다'],
  ['情况', 'qíngkuàng', 'noun', 'situation, circumstance', 'durum, koşul', '상황, 형편'],
  ['庆祝', 'qìngzhù', 'verb', 'to celebrate', 'kutlamak', '축하하다'],
  ['球队', 'qiúduì', 'noun', 'sports team, ball team', 'spor takımı', '구단, 팀'],
  ['球迷', 'qiúmí', 'noun', 'fan, sports enthusiast', 'taraftar, fan', '스포츠 팬'],
  ['区', 'qū', 'noun', 'district, area, region', 'ilçe, bölge', '구, 지역, 구역'],
  ['区别', 'qūbié', 'noun', 'difference; to distinguish', 'fark, ayrım', '구별하다, 차이'],
  ['取', 'qǔ', 'verb', 'to take, to get, to obtain', 'almak', '가지다, 얻다'],
  ['取得', 'qǔdé', 'verb', 'to obtain, to gain', 'elde etmek', '얻다, 취득하다'],
  ['取消', 'qǔxiāo', 'verb', 'to cancel, to call off', 'iptal etmek', '취소하다'],
  ['全', 'quán', 'adjective', 'whole, entire; completely', 'tüm; tamamen', '전체의, 모든; 완전히'],
  ['全部', 'quánbù', 'noun', 'all, the whole thing', 'tamamı, hepsi', '전부, 전체'],
  ['全都', 'quándōu', 'adverb', 'all, entirely', 'hepsi', '모두, 전부'],
  ['全球', 'quánqiú', 'noun', 'the whole world, global', 'küresel, dünya geneli', '전 세계, 지구 전체'],
  ['全身', 'quánshēn', 'noun', 'whole body', 'tüm vücut', '전신, 온몸'],
  ['缺', 'quē', 'verb', 'to lack, to be short of', 'eksik olmak', '부족하다, 모자라다'],
  ['缺点', 'quēdiǎn', 'noun', 'shortcoming, defect', 'eksiklik, kusur', '결점, 단점'],
  ['缺少', 'quēshǎo', 'verb', 'to lack, to be short of', 'yetersiz olmak', '부족하다, 결핍되다'],
  ['却', 'què', 'adverb', 'but, yet, however', 'ama, oysa', '그러나, 하지만'],
  ['确实', 'quèshí', 'adverb', 'indeed, really', 'gerçekten', '확실히, 정말로'],
  ['然而', 'ráněr', 'conjunction', 'however, but', 'ancak, oysa', '그러나, 그렇지만'],
  ['热闹', 'rènao', 'adjective', 'lively, bustling', 'canlı, hareketli', '북적거리다, 떠들썩하다'],
  ['人生', 'rénshēng', 'noun', 'life', 'hayat, yaşam', '인생'],
  ['人数', 'rénshù', 'noun', 'number of people', 'kişi sayısı', '인원수, 사람 수'],
  ['人员', 'rényuán', 'noun', 'personnel, staff', 'personel, çalışanlar', '인원, 직원'],
  ['任何', 'rènhé', 'pronoun', 'any, whatever', 'herhangi, her ne', '어떠한, 아무'],
  ['任务', 'rènwu', 'noun', 'task, assignment, mission', 'görev', '임무, 과제'],
  ['扔', 'rēng', 'verb', 'to throw, to toss', 'atmak, fırlatmak', '던지다, 버리다'],
  ['仍', 'réng', 'adverb', 'still, yet', 'hâlâ, yine de', '여전히'],
  ['仍然', 'réngrán', 'adverb', 'still, yet', 'hâlâ, yine de', '여전히'],
  ['日常', 'rìcháng', 'adjective', 'daily, everyday', 'günlük, her günkü', '일상적인, 매일의'],
  ['日记', 'rìjì', 'noun', 'diary', 'günlük, diyari', '일기'],
  ['日期', 'rìqī', 'noun', 'date', 'tarih', '날짜'],
  ['日子', 'rìzi', 'noun', 'day, life, time', 'gün, yaşam', '날, 하루, 생활'],
  ['入', 'rù', 'verb', 'to enter, to go in', 'girmek', '들어가다, 입다'],
  ['入口', 'rùkǒu', 'noun', 'entrance', 'giriş', '입구'],
  ['入学', 'rùxué', 'verb', 'to enter school, to enroll', 'okula kaydolmak', '입학하다'],
  ['入住', 'rùzhù', 'verb', 'to check in, to move in', 'giriş yapmak', '입주하다, 투숙하다'],
  ['散步', 'sànbù', 'verb', 'to take a walk, to stroll', 'yürüyüşe çıkmak', '산책하다'],
  ['扫码', 'sǎomǎ', 'verb', 'to scan a code', 'kod taramak', '큐알코드를 스캔하다'],
  ['森林', 'sēnlín', 'noun', 'forest', 'orman', '삼림, 숲'],
  ['商量', 'shāngliang', 'verb', 'to discuss, to consult', 'tartışmak, danışmak', '상의하다, 의논하다'],
  ['商品', 'shāngpǐn', 'noun', 'product, commodity', 'ürün, mal', '상품, 제품'],
  ['伤心', 'shāngxīn', 'adjective', 'sad, heartbroken', 'üzgün, kalbı kırık', '슬픈, 상심한'],
  ['上门', 'shàngmén', 'verb', 'to visit, to go to someones house', 'kapıya gelmek, ziyaret etmek', '방문하다, 찾아가다'],
  ['稍', 'shāo', 'adverb', 'a little, slightly', 'biraz, hafifçe', '조금, 약간'],
  ['稍微', 'shāowēi', 'adverb', 'a little, slightly', 'biraz, hafifçe', '조금, 약간'],
  ['少见', 'shǎojiàn', 'adjective', 'rare, seldom seen', 'nadir, az görülen', '드물다, 보기 힘들다'],
  ['少量', 'shǎoliàng', 'adjective', 'small amount, a little', 'az miktarda', '소량의, 적은 양의'],
  ['少数', 'shǎoshù', 'noun', 'minority, small number', 'azınlık', '소수'],
  ['少年', 'shàonián', 'noun', 'juvenile, teenager, youth', 'genç, ergen', '소년, 청소년'],
  ['社会', 'shèhuì', 'noun', 'society, community', 'toplum', '사회'],
  ['摄氏度', 'shèshìdù', 'classifier', 'degrees Celsius', 'santigrat derece', '섭씨(온도 단위)'],
  ['身', 'shēn', 'noun', 'body, oneself', 'vücut, beden', '몸, 신체'],
  ['深', 'shēn', 'adjective', 'deep, profound', 'derin', '깊다, 심오하다'],
  ['身份证', 'shēnfènzhèng', 'noun', 'ID card, identification card', 'kimlik kartı', '신분증'],
  ['申请', 'shēnqǐng', 'verb', 'to apply, to file an application', 'başvurmak', '신청하다'],
  ['甚至', 'shènzhì', 'conjunction', 'even, so much as that', 'hatta, bile', '심지어, ~까지도'],
  ['生', 'shēng', 'verb', 'to give birth, to produce, to grow', 'doğurmak, üretmek', '낳다, 생기다, 날것의, 익지 않은, 낯선'],
  ['生', 'shēng', 'adjective', 'raw, uncooked, unripe; unfamiliar', 'çiğ, pişmemiş; yabancı', '낳다, 생기다, 날것의, 익지 않은, 낯선'],
  ['生命', 'shēngmìng', 'noun', 'life', 'yaşam, hayat', '생명'],
  ['生意', 'shēngyi', 'noun', 'business, trade', 'iş, ticaret', '장사, 사업'],
  ['省', 'shěng, xǐng', 'noun', 'province', 'il, eyalet', '절약하다, 생략하다'],
  ['剩', 'shèng', 'verb', 'to be left over, to remain', 'artmak, geri kalmak', '남다, 나머지가 되다'],
  ['失败', 'shībài', 'verb', 'to fail; failed, unsuccessful', 'başarısız olmak; başarısız', '실패하다'],
  ['师傅', 'shīfu', 'noun', 'master, skilled worker', 'usta, hoca', '스승, 기사(기술자)'],
  ['失去', 'shīqù', 'verb', 'to lose, to be lost', 'kaybetmek', '잃다, 상실하다'],
  ['师生', 'shīshēng', 'noun', 'teacher and student', 'öğretmen ve öğrenci', '사제, 교사와 학생'],
  ['失望', 'shīwàng', 'adjective', 'to be disappointed; disappointed', 'hayal kırıklığına uğramak; hayal kırıklığı', '실망하다'],
  ['十分', 'shífēn', 'adverb', 'very, extremely, fully', 'çok, son derece', '매우, 아주, 충분히'],
  ['实际', 'shíjì', 'adjective', 'reality, actuality; actual, practical', 'gerçek, pratik', '실제, 현실, 실제의, 현실적인'],
  ['时间表', 'shíjiānbiǎo', 'noun', 'schedule, timetable', 'program, zaman çizelgesi', '시간표'],
  ['实际上', 'shíjìshàng', 'adverb', 'actually, in fact', 'aslında, gerçekte', '사실상, 실제로'],
  ['食品', 'shípǐn', 'noun', 'food, provisions', 'gıda, besin', '식품'],
  ['食堂', 'shítáng', 'noun', 'cafeteria, dining hall', 'yemekhane', '식당, 구내식당'],
  ['食物', 'shíwù', 'noun', 'food', 'yemek, gıda', '음식, 식료품'],
  ['实在', 'shízài', 'adverb', 'honest, reliable; really, indeed', 'dürüst; gerçekten', '정직하다, 성실하다, 정말로, 사실'],
  ['十字路口', 'shízìlùkǒu', 'noun', 'intersection, crossroads', 'kavşak, yol ayrımı', '십자로, 교차로'],
  ['使', 'shǐ', 'verb', 'to make, to cause, to use', 'sağlamak, neden olmak', '시키다, 하여금 ~하게 하다, 사용하다'],
  ['使馆', 'shǐguǎn', 'noun', 'embassy', 'büyükelçilik', '대사관'],
  ['使用', 'shǐyòng', 'verb', 'to use, to employ', 'kullanmak', '사용하다, 이용하다'],
  ['市场', 'shìchǎng', 'noun', 'market, marketplace', 'pazar, piyasa', '시장'],
  ['是否', 'shìfǒu', 'adverb', 'whether or not, if', 'olup olmadığı', '인지 아닌지, 과연'],
  ['适合', 'shìhé', 'verb', 'to suit, to fit, to be suitable', 'uymak, uygun olmak', '알맞다, 적합하다'],
  ['世纪', 'shìjì', 'noun', 'century', 'yüzyıl', '세기'],
  ['视频', 'shìpín', 'noun', 'video, video clip', 'video', '동영상, 비디오'],
  ['市区', 'shìqū', 'noun', 'urban area, city center', 'şehir merkezi', '시가지, 도심'],
  ['试题', 'shìtí', 'noun', 'test questions, exam paper', 'sınav soruları', '시험 문제'],
  ['适应', 'shìyìng', 'verb', 'to adapt, to fit, to suit', 'uyum sağlamak', '적응하다, 알맞다'],
  ['收费', 'shōufèi', 'verb', 'to charge a fee, to collect payment', 'ücret almak', '요금을 받다, 수수료를 징수하다'],
  ['收入', 'shōurù', 'noun', 'income, revenue; to receive', 'gelir; almak', '수입, 소득, 받아들이다'],
  ['收拾', 'shōushi', 'verb', 'to put in order, to tidy up, to pack', 'toplamak, düzenlemek', '정리하다, 치우다, 짐을 꾸리다'],
  ['收听', 'shōutīng', 'verb', 'to listen in, to tune in', 'dinlemek', '청취하다'],
  ['首', 'shǒu', 'classifier', 'measure word for songs, poems', 'şarkı sayacı', '수(노래나 시를 세는 단위)'],
  ['首都', 'shǒudū', 'noun', 'capital', 'başkent', '수도'],
  ['首先', 'shǒuxiān', 'adverb', 'first, firstly', 'öncelikle, ilk olarak', '우선, 먼저'],
  ['受不了', 'shòubuliǎo', 'verb', 'to be unable to bear, to be unable to stand', 'dayanamamak', '견딜 수 없다, 참을 수 없다'],
  ['售票员', 'shòupiàoyuán', 'noun', 'ticket seller, conductor', 'biletçi', '매표원, 승무원'],
  ['受伤', 'shòushāng', 'verb', 'to be injured, to get hurt', 'yaralanmak', '부상을 입다, 다치다'],
  ['输', 'shū', 'verb', 'to lose, to be defeated', 'kaybetmek, yenilmek', '지다, 패하다'],
  ['熟', 'shú', 'adjective', 'ripe, cooked, mature', 'olgun, pişmiş', '익다, 성숙하다'],
  ['熟悉', 'shúxi', 'verb', 'to be familiar with, to know well', 'aşina olmak', '익숙하다, 잘 알다'],
  ['暑假', 'shǔjià', 'noun', 'summer vacation', 'yaz tatili', '여름 방학'],
  ['数', 'shù, shǔ', 'noun', 'number, figure; several', 'sayı; birkaç', '세다, 계산하다'],
  ['数量', 'shùliàng', 'noun', 'quantity, amount', 'miktar, adet', '수량, 양'],
  ['树林', 'shùlín', 'noun', 'woods, forest', 'koru, orman', '숲, 수풀'],
  ['数字', 'shùzì', 'noun', 'digit, figure, number', 'rakam, sayı', '숫자'],
  ['帅', 'shuài', 'adjective', 'handsome, good-looking', 'yakışıklı', '멋지다, 잘생기다'],
  ['顺便', 'shùnbiàn', 'adverb', 'conveniently, in passing', 'fırsat bu fırsat, yeri gelmişken', '겸사겸사, 편에'],
  ['顺利', 'shùnlì', 'adjective', 'smooth, successful, going well', 'sorunsuz, başarılı', '순조롭다'],
  ['顺序', 'shùnxù', 'noun', 'order, sequence', 'sıra, düzen', '순서'],
  ['说法', 'shuōfǎ', 'noun', 'way of saying something, version, statement', 'söyleyiş biçimi', '말하는 방식, 견해, 주장'],
  ['说明', 'shuōmíng', 'noun', 'explanation, instructions; to explain', 'açıklama; açıklamak', '설명, 설명하다'],
  ['说明书', 'shuōmíngshū', 'noun', 'instruction manual, user guide', 'kullanım kılavuzu', '설명서'],
  ['硕士', 'shuòshì', 'noun', 'master (degree)', 'yüksek lisans', '석사'],
  ['死', 'sǐ', 'verb', 'to die; dead; extremely', 'ölmek; ölü; son derece', '죽다, 죽은, 매우'],
  ['速度', 'sùdù', 'noun', 'speed', 'hız', '속도'],
  ['塑料', 'sùliào', 'noun', 'plastic', 'plastik', '플라스틱'],
  ['酸', 'suān', 'adjective', 'sour, tart', 'ekşi', '시다'],
  ['酸奶', 'suānnǎi', 'noun', 'yogurt', 'yoğurt', '요구르트'],
  ['算', 'suàn', 'verb', 'to calculate, to count; considered', 'hesaplamak; sayılmak', '계산하다, 간주하다, 여기다'],
  ['随便', 'suíbiàn', 'adjective', 'casual; do as one pleases', 'gelişigüzel; nasıl olsa', '편하다, 마음대로 하다'],
  ['随着', 'suízhe', 'preposition', 'along with, following', 'ile birlikte, takiben', '~에 따라, ~와 함께'],
  ['孙女', 'sūnnǚ', 'noun', 'granddaughter', 'torun kız', '손녀'],
  ['孙子', 'sūnzi', 'noun', 'grandson', 'torun erkek', '손자'],
  ['所有', 'suǒyǒu', 'adjective', 'all, every; to possess', 'tüm; sahip olmak', '모든, 소유하다'],
  ['台', 'tái', 'classifier', 'measure word for machines, vehicles', 'makine sayacı; sahne', '대 (기계, 차량 등의 수량 단위)'],
  ['抬', 'tái', 'verb', 'to lift, to raise', 'kaldırmak', '들다, 들어 올리다'],
  ['抬头', 'táitóu', 'verb', 'to raise ones head, to look up', 'başını kaldırmak', '고개를 들다'],
  ['态度', 'tàidù', 'noun', 'attitude, manner', 'tutum, davranış', '태도'],
  ['弹', 'tán, dàn', 'verb', 'to play (an instrument), to spring', 'çalmak, çekmek', '연주하다, 튕기다'],
  ['谈', 'tán', 'verb', 'to talk, to discuss', 'konuşmak, tartışmak', '이야기하다, 논의하다'],
  ['汤', 'tāng', 'noun', 'soup', 'çorba', '국, 탕'],
  ['躺', 'tǎng', 'verb', 'to lie down', 'uzanmak, yatmak', '눕다'],
  ['趟', 'tàng', 'classifier', 'measure word for trips, journeys', 'gidiş sayacı', '번, 회 (왕복 횟수를 세는 단위)'],
  ['讨论', 'tǎolùn', 'verb', 'to discuss, to talk over', 'tartışmak, görüşmek', '토론하다, 의논하다'],
  ['讨厌', 'tǎoyàn', 'adjective', 'disgusting, annoying; to dislike', 'iğrenç, sinir bozucu', '밉다, 싫다, 귀찮다'],
  ['特点', 'tèdiǎn', 'noun', 'characteristic, feature', 'özellik', '특징, 특색'],
  ['提', 'tí, dī', 'verb', 'to carry; to lift; to mention, to bring up', 'taşımak; bahsetmek', '들다, 언급하다, 제기하다'],
  ['提出', 'tíchū', 'verb', 'to put forward, to propose, to raise', 'öne sürmek, önermek', '제기하다, 제출하다'],
  ['提到', 'tídào', 'verb', 'to mention, to refer to', 'bahsetmek', '언급하다'],
  ['提供', 'tígōng', 'verb', 'to provide, to supply, to offer', 'sağlamak, sunmak', '제공하다'],
  ['提前', 'tíqián', 'verb', 'to advance, to do something ahead of time', 'önceden yapmak', '앞당기다, 미리 하다'],
  ['提醒', 'tíxǐng', 'verb', 'to remind, to alert', 'hatırlatmak, uyarmak', '상기시키다, 주의를 주다'],
  ['体检', 'tǐjiǎn', 'verb', 'to undergo a physical examination', 'sağlık kontrolü', '신체검사를 하다'],
  ['体温', 'tǐwēn', 'noun', 'body temperature', 'vücut sıcaklığı', '체온'],
  ['体重', 'tǐzhòng', 'noun', 'body weight', 'vücut ağırlığı', '체중'],
  ['填写', 'tiánxiě', 'verb', 'to fill in, to complete a form', 'doldurmak, tamamlamak', '기입하다, 작성하다'],
  ['条件', 'tiáojiàn', 'noun', 'condition, requirement, terms', 'koşul, şart', '조건, 요건'],
  ['听力', 'tīnglì', 'noun', 'listening ability, hearing', 'dinleme becerisi', '청력, 듣기 능력'],
  ['听众', 'tīngzhòng', 'noun', 'audience, listeners', 'dinleyici', '청중, 청취자'],
  ['停', 'tíng', 'verb', 'to stop, to halt', 'durmak', '멈추다, 정지하다'],
  ['停车', 'tíngchē', 'verb', 'to park, to stop a vehicle', 'park etmek', '주차하다, 차를 세우다'],
  ['停车场', 'tíngchēchǎng', 'noun', 'parking lot', 'otopark', '주차장'],
  ['停止', 'tíngzhǐ', 'verb', 'to stop, to cease', 'durdurmak, son vermek', '중지하다, 멈추다'],
  ['通', 'tōng', 'verb', 'to go through; to lead to, to connect', 'geçmek; bağlantılı', '통하다, 연결되다'],
  ['通过', 'tōngguò', 'verb', 'to pass through; by means of', 'geçmek; aracılığıyla', '통과하다, ~을 통해'],
  ['通知', 'tōngzhī', 'noun', 'notice, notification; to notify', 'bildirim; bildirmek', '통지, 통지하다, 알리다'],
  ['童年', 'tóngnián', 'noun', 'childhood', 'çocukluk', '어린 시절'],
  ['同时', 'tóngshí', 'conjunction', 'at the same time; meanwhile', 'aynı zamanda', '동시에, 같은 때에'],
  ['同样', 'tóngyàng', 'adjective', 'same, similar', 'aynı, benzer', '같은, 비슷한'],
  ['桶', 'tǒng', 'noun', 'bucket, barrel', 'kova, varil', '통, 양동이'],
  ['痛', 'tòng', 'adjective', 'painful, sore', 'ağrılı, acıyan', '아프다'],
  ['头痛', 'tóutòng', 'adjective', 'headache', 'baş ağrısı', '머리가 아프다, 골치 아프다'],
  ['图', 'tú', 'noun', 'picture, drawing, diagram', 'resim, şekil', '그림, 도표, 지도'],
  ['图片', 'túpiàn', 'noun', 'picture, image, photograph', 'resim, fotoğraf', '그림, 사진, 이미지'],
  ['土', 'tǔ', 'noun', 'earth, soil, land', 'toprak', '흙, 땅'],
  ['推', 'tuī', 'verb', 'to push, to shove', 'itmek', '밀다, 미루다'],
  ['推迟', 'tuīchí', 'verb', 'to postpone, to delay', 'ertelemek', '연기하다, 미루다'],
  ['推出', 'tuīchū', 'verb', 'to launch, to push out, to introduce', 'piyasaya sürmek', '출시하다, 내놓다'],
  ['脱', 'tuō', 'verb', 'to take off, to shed', 'çıkarmak (giysi)', '벗다, 빠지다'],
  ['袜子', 'wàzi', 'noun', 'socks', 'çorap', '양말'],
  ['外出', 'wàichū', 'verb', 'to go out, to leave home', 'dışarı çıkmak', '외출하다'],
  ['外套', 'wàitào', 'noun', 'coat, jacket', 'mont, ceket', '외투, 겉옷'],
  ['完全', 'wánquán', 'adverb', 'completely, absolutely', 'tamamen', '완전히, 전적으로'],
  ['晚安', 'wǎnān', 'verb', 'good night', 'iyi geceler', '안녕히 주무세요'],
  ['晚餐', 'wǎncān', 'noun', 'dinner, supper', 'akşam yemeği', '저녁 식사'],
  ['网购', 'wǎnggòu', 'verb', 'to shop online', 'online alışveriş yapmak', '온라인 쇼핑하다'],
  ['往往', 'wǎngwǎng', 'adverb', 'often, frequently', 'çoğunlukla, sıklıkla', '왕왕, 흔히'],
  ['网页', 'wǎngyè', 'noun', 'webpage', 'web sayfası', '웹페이지'],
  ['网友', 'wǎngyǒu', 'noun', 'netizen, internet user', 'internet kullanıcısı', '네티즌, 온라인 친구'],
  ['网址', 'wǎngzhǐ', 'noun', 'website URL, web address', 'web adresi', '웹사이트 주소'],
  ['危险', 'wēixiǎn', 'noun', 'dangerous; danger', 'tehlikeli; tehlike', '위험하다; 위험'],
  ['为', 'wèi, wéi', 'verb', 'to do, to act, to serve as', 'yapmak, olmak', '~을 위하여, ~을 위해'],
  ['味', 'wèi', 'noun', 'taste, flavor', 'tat, lezzet', '맛'],
  ['味道', 'wèidào', 'noun', 'taste, flavor', 'tat, lezzet', '맛, 풍미'],
  ['卫生', 'wèishēng', 'noun', 'hygiene, sanitation; clean, hygienic', 'hijyen, temizlik', '위생, 보건; 위생적이다'],
  ['温度', 'wēndù', 'noun', 'temperature', 'sıcaklık', '온도'],
  ['闻', 'wén', 'verb', 'to smell, to sniff', 'koklamak', '냄새를 맡다, 듣다'],
  ['文件', 'wénjiàn', 'noun', 'document, file', 'belge, dosya', '문서, 파일'],
  ['文章', 'wénzhāng', 'noun', 'essay, article', 'makale, yazı', '글, 문장'],
  ['文字', 'wénzì', 'noun', 'writing, character', 'yazı, harf', '문자, 글자'],
  ['污染', 'wūrǎn', 'verb', 'contaminated; to contaminate', 'kirletmek, kirlenmiş', '오염되다, 오염시키다'],
  ['无', 'wú', 'verb', 'to lack, to not have', 'olmamak, yokluk', '없다'],
  ['无法', 'wúfǎ', 'verb', 'unable, incapable', 'yapamamak', '방법이 없다, ~할 수 없다'],
  ['无聊', 'wúliáo', 'adjective', 'boring, dull', 'sıkıcı', '지루하다, 심심하다'],
  ['无论', 'wúlùn', 'conjunction', 'no matter what, regardless', 'her ne olursa olsun', '어떠하든, 막론하고'],
  ['午餐', 'wǔcān', 'noun', 'lunch', 'öğle yemeği', '점심 식사'],
  ['误会', 'wùhuì', 'noun', 'misunderstanding; to misunderstand', 'yanlış anlama; yanlış anlamak', '오해, 오해하다'],
  ['吸', 'xī', 'verb', 'to suck, to inhale, to absorb', 'emmek, solumak', '빨아들이다, 흡수하다, 들이마시다'],
  ['西部', 'xībù', 'noun', 'western region, west part', 'batı bölgesi', '서부'],
  ['西红柿', 'xīhóngshì', 'noun', 'tomato', 'domates', '토마토'],
  ['吸引', 'xīyǐn', 'verb', 'to attract', 'çekmek, cezbetmek', '끌다, 매료시키다'],
  ['细', 'xì', 'adjective', 'thin, fine, detailed', 'ince, ayrıntılı', '가늘다, 자세하다'],
  ['细心', 'xìxīn', 'adjective', 'careful, attentive', 'dikkatli, özenli', '꼼꼼하다, 세심하다'],
  ['下降', 'xiàjiàng', 'verb', 'to decline, to drop, to go down', 'düşmek, azalmak', '하강하다, 떨어지다'],
  ['鲜', 'xiān', 'adjective', 'fresh', 'taze', '신선하다'],
  ['鲜花', 'xiānhuā', 'noun', 'fresh flower', 'taze çiçek', '생화, 꽃'],
  ['咸', 'xián', 'adjective', 'salty', 'tuzlu', '짠'],
  ['现金', 'xiànjīn', 'noun', 'cash', 'nakit', '현금'],
  ['羡慕', 'xiànmù', 'verb', 'to envy, to admire', 'gıpta etmek, imrenmek', '부러워하다, 선망하다'],
  ['线上', 'xiànshàng', 'noun', 'online, on the internet', 'çevrimiçi', '온라인'],
  ['线下', 'xiànxià', 'noun', 'offline', 'çevrimdışı', '오프라인'],
  ['现有', 'xiànyǒu', 'adjective', 'existing, currently available', 'mevcut, şu anda var olan', '현존하는, 현재 있는'],
  ['香', 'xiāng', 'adjective', 'fragrant', 'kokulu, güzel kokulu', '향기롭다, 맛있다'],
  ['相比', 'xiāngbǐ', 'verb', 'to compare with, to contrast', 'kıyaslamak', '비교하다'],
  ['相反', 'xiāngfǎn', 'adjective', 'opposite, contrary; on the contrary', 'zıt, aksine', '반대이다, 상반되다'],
  ['相互', 'xiānghù', 'adverb', 'mutual, each other', 'karşılıklı', '서로, 상호'],
  ['相同', 'xiāngtóng', 'adjective', 'same, identical', 'aynı, özdeş', '같다, 동일하다'],
  ['详细', 'xiángxì', 'adjective', 'detailed, thorough', 'ayrıntılı', '상세하다, 자세하다'],
  ['响', 'xiǎng', 'verb', 'to make a sound, to ring; loud', 'ses çıkarmak; gürültülü', '울리다, 소리 나다; 시끄러운'],
  ['想法', 'xiǎngfǎ', 'noun', 'thought, idea, opinion', 'düşünce, fikir', '생각, 의견'],
  ['项', 'xiàng', 'classifier', 'measure word for projects, items', 'proje sayacı', '항목, 건 (분류사)'],
  ['消息', 'xiāoxi', 'noun', 'news, message, information', 'haber, mesaj', '소식, 정보'],
  ['小吃', 'xiǎochī', 'noun', 'snack, light meal', 'atıştırmalık, hafif yemek', '간식, 군것질거리'],
  ['小伙子', 'xiǎohuǒzi', 'noun', 'young man, lad', 'genç adam, delikanlı', '청년, 젊은이'],
  ['小说', 'xiǎoshuō', 'noun', 'novel, fiction', 'roman, kurgu', '소설'],
  ['小组', 'xiǎozǔ', 'noun', 'small group, team', 'küçük grup', '소그룹, 조'],
  ['效果', 'xiàoguǒ', 'noun', 'effect, result', 'etki, sonuç', '효과, 결과'],
  ['笑话', 'xiàohua', 'noun', 'joke; to joke, to laugh at', 'şaka, fıkra', '농담, 비웃다'],
  ['血', 'xiě', 'noun', 'blood', 'kan', '피'],
  ['心', 'xīn', 'noun', 'heart', 'kalp, gönül', '마음, 심장'],
  ['辛苦', 'xīnkǔ', 'adjective', 'hard, laborious; to work hard', 'zahmetli, yorucu', '힘들다, 고생스럽다, 수고하다'],
  ['心情', 'xīnqíng', 'noun', 'mood, feeling', 'ruh hali, duygu', '기분, 심정'],
  ['信号', 'xìnhào', 'noun', 'signal', 'sinyal', '신호'],
  ['信息', 'xìnxī', 'noun', 'information, message', 'bilgi, mesaj', '정보, 메시지'],
  ['信心', 'xìnxīn', 'noun', 'confidence, faith', 'özgüven, güven', '신심, 자신'],
  ['兴奋', 'xīngfèn', 'adjective', 'excited, thrilled; to excite', 'heyecanlı, coşkulu', '흥분하다, 신나다'],
  ['星星', 'xīngxing', 'noun', 'star', 'yıldız', '별'],
  ['醒', 'xǐng', 'verb', 'to wake up, to sober up', 'uyanmak', '깨다, 정신이 들다'],
  ['性', 'xìng', 'suffix', 'nature, character, quality', 'özellik, nitelik, -lık eki', '~성 (성질이나 특성을 나타내는 접미사)'],
  ['性别', 'xìngbié', 'noun', 'gender, sex', 'cinsiyet', '성별'],
  ['幸福', 'xìngfú', 'noun', 'happiness; happy, blissful', 'mutluluk; mutlu', '행복, 행복하다'],
  ['性格', 'xìnggé', 'noun', 'character', 'karakter, kişilik', '성격'],
  ['兄弟', 'xiōngdì', 'noun', 'brothers', 'erkek kardeşler', '형제'],
  ['熊', 'xióng', 'noun', 'bear', 'ayı', '곰'],
  ['修', 'xiū', 'verb', 'to repair, to fix', 'onarmak', '수리하다, 고치다, 닦다'],
  ['修理', 'xiūlǐ', 'verb', 'to repair, to fix', 'tamir etmek', '수리하다, 고치다'],
  ['许多', 'xǔduō', 'number', 'many, numerous', 'çok, birçok', '많다, 다수'],
  ['学费', 'xuéfèi', 'noun', 'tuition fee', 'okul ücreti, harç', '학비'],
  ['学院', 'xuéyuàn', 'noun', 'college, academy, institute', 'kolej, yüksekokul', '학원, 단과 대학'],
  ['压', 'yā', 'verb', 'to press, to push down, to weigh down', 'bastırmak', '누르다, 압박하다, 억누르다'],
  ['压力', 'yālì', 'noun', 'pressure, stress', 'baskı, stres', '압력, 스트레스'],
  ['牙膏', 'yágāo', 'noun', 'toothpaste', 'diş macunu', '치약'],
  ['亚洲', 'Yàzhōu', 'noun', 'Asia', 'Asya', '아시아'],
  ['烟', 'yān', 'noun', 'cigarette, smoke, mist', 'sigara, duman', '담배, 연기'],
  ['盐', 'yán', 'noun', 'salt', 'tuz', '소금'],
  ['严格', 'yángé', 'adjective', 'strict, stringent', 'sıkı, katı', '엄격하다'],
  ['研究', 'yánjiū', 'verb', 'to research, to study', 'araştırmak', '연구하다'],
  ['研究生', 'yánjiūshēng', 'noun', 'graduate student, postgraduate', 'yüksek lisans öğrencisi', '대학원생'],
  ['严重', 'yánzhòng', 'adjective', 'serious, severe, grave', 'ciddi, ağır', '심각하다, 중대하다'],
  ['演', 'yǎn', 'verb', 'to act, to perform, to play', 'oynamak, sergilemek', '연기하다, 공연하다'],
  ['演唱', 'yǎnchàng', 'verb', 'to sing, to perform vocally', 'şarkı söylemek', '노래하다, 공연하다'],
  ['演出', 'yǎnchū', 'verb', 'to perform, to put on a show', 'gösteri yapmak', '공연하다, 연출하다'],
  ['眼镜', 'yǎnjìng', 'noun', 'eyeglasses, glasses', 'gözlük', '안경'],
  ['眼前', 'yǎnqián', 'noun', 'before ones eyes, at the moment', 'gözlerinin önünde', '눈앞, 현재'],
  ['演员', 'yǎnyuán', 'noun', 'actor, performer', 'aktör, sanatçı', '배우, 연기자'],
  ['阳光', 'yángguāng', 'noun', 'sunlight, sunshine', 'güneş ışığı', '햇빛, 양광'],
  ['养成', 'yǎngchéng', 'verb', 'to develop, to cultivate, to form', 'geliştirmek, edinmek', '양성하다, 길들이다, 형성하다'],
  ['样子', 'yàngzi', 'noun', 'appearance, look, manner', 'görünüm, hal', '모양, 모습, 태도'],
  ['邀请', 'yāoqǐng', 'verb', 'to invite', 'davet etmek', '초대하다, 초청하다'],
  ['要是', 'yàoshi', 'conjunction', 'if, suppose', 'eğer, şayet', '만약 ~라면'],
  ['钥匙', 'yàoshi', 'noun', 'key', 'anahtar', '열쇠'],
  ['也许', 'yěxǔ', 'adverb', 'maybe, perhaps', 'belki, muhtemelen', '아마, 어쩌면'],
  ['夜', 'yè', 'noun', 'night', 'gece', '밤'],
  ['夜晚', 'yèwǎn', 'noun', 'night, evening', 'gece, akşam', '밤, 야간'],
  ['叶子', 'yèzi', 'noun', 'leaf', 'yaprak', '잎사귀'],
  ['一切', 'yíqiè', 'pronoun', 'everything', 'her şey, hepsi', '모든 것, 전부'],
  ['已', 'yǐ', 'adverb', 'already', 'zaten, artık', '이미, 벌써'],
  ['以内', 'yǐnèi', 'noun', 'within', 'içinde', '이내, 안'],
  ['意见', 'yìjiàn', 'noun', 'opinion', 'görüş, fikir', '의견'],
  ['一生', 'yìshēng', 'noun', 'lifetime, all ones life', 'tüm hayat boyunca', '일생, 평생'],
  ['艺术', 'yìshù', 'noun', 'art', 'sanat', '예술'],
  ['因此', 'yīncǐ', 'conjunction', 'therefore', 'bu nedenle, dolayısıyla', '따라서, 그러므로'],
  ['引起', 'yǐnqǐ', 'verb', 'cause', 'neden olmak', '일으키다, 야기하다'],
  ['印象', 'yìnxiàng', 'noun', 'impression', 'izlenim', '인상'],
  ['赢', 'yíng', 'verb', 'win', 'kazanmak', '이기다, 승리하다'],
  ['赢得', 'yíngdé', 'verb', 'gain, win', 'kazanmak, elde etmek', '얻다, 획득하다'],
  ['应聘', 'yìngpìn', 'verb', 'to apply for a job', 'iş başvurusunda bulunmak', '응모하다, 지원하다'],
  ['勇敢', 'yǒnggǎn', 'adjective', 'brave, courageous', 'cesur, yürekli', '용감하다'],
  ['永远', 'yǒngyuǎn', 'adverb', 'forever, always', 'sonsuza kadar, her zaman', '영원히'],
  ['用来', 'yònglái', 'verb', 'to be used for, to serve as', 'için kullanılmak', '~하는 데 쓰이다'],
  ['用于', 'yòngyú', 'verb', 'to be used for, to be applied to', 'için kullanılmak', '~에 쓰이다, ~에 사용되다'],
  ['优点', 'yōudiǎn', 'noun', 'advantage, merit, strong point', 'avantaj, üstünlük', '장점, 미덕'],
  ['幽默', 'yōumò', 'adjective', 'humorous', 'mizahi, eğlenceli', '유머러스하다, 해학적이다'],
  ['优秀', 'yōuxiù', 'adjective', 'excellent, outstanding', 'mükemmel, üstün', '우수한, 뛰어난'],
  ['由', 'yóu', 'preposition', 'by, through, from, because of', 'tarafından, nedeniyle', '~에 의해, ~로부터, ~로 인하여'],
  ['油', 'yóu', 'noun', 'oil, fat, grease', 'yağ', '기름, 유류'],
  ['尤其', 'yóuqí', 'adverb', 'especially, particularly', 'özellikle', '특히'],
  ['游玩', 'yóuwán', 'verb', 'to play, to have fun, to go sightseeing', 'eğlenmek, gezmek', '놀다, 유람하다'],
  ['由于', 'yóuyú', 'conjunction', 'because of, due to; owing to', 'nedeniyle, dolayısıyla', '~때문에, ~로 인하여'],
  ['友好', 'yǒuhǎo', 'adjective', 'friendly', 'arkadaş canlısı, samimi', '우호적인'],
  ['友情', 'yǒuqíng', 'noun', 'friendship', 'dostluk', '우정'],
  ['有趣', 'yǒuqù', 'adjective', 'interesting, enjoyable, fun', 'ilginç, eğlenceli', '재미있다, 흥미롭다'],
  ['有效', 'yǒuxiào', 'verb', 'effective, to be effective', 'etkili, geçerli', '유효하다, 효과가 있다'],
  ['友谊', 'yǒuyì', 'noun', 'friendship', 'dostluk, arkadaşlık', '우정'],
  ['有着', 'yǒuzhe', 'verb', 'to have, to possess', 'sahip olmak', '가지고 있다, 지니다'],
  ['愉快', 'yúkuài', 'adjective', 'pleasant, cheerful', 'keyifli, neşeli', '유쾌하다, 즐겁다'],
  ['于是', 'yúshì', 'conjunction', 'therefore, hence, so', 'bunun üzerine, böylece', '그래서, 따라서'],
  ['与', 'yǔ, yù', 'conjunction', 'with, and', 'ile', '~와, ~및'],
  ['语法', 'yǔfǎ', 'noun', 'grammar', 'gramer, dilbilgisi', '문법'],
  ['预习', 'yùxí', 'verb', 'to preview, to prepare', 'önceden çalışmak', '예습하다'],
  ['原来', 'yuánlái', 'adverb', 'originally, actually', 'aslında, meğer', '원래, 사실은'],
  ['原谅', 'yuánliàng', 'verb', 'to forgive, to excuse, to pardon', 'affetmek', '용서하다, 너그럽게 봐주다'],
  ['原因', 'yuányīn', 'noun', 'cause, reason', 'neden, sebep', '원인'],
  ['远离', 'yuǎnlí', 'verb', 'to stay away from, to keep away from', 'uzak durmak', '멀리하다, 떨어져 있다'],
  ['院长', 'yuànzhǎng', 'noun', 'dean, head of a college or institute', 'dekan', '원장'],
  ['院子', 'yuànzi', 'noun', 'courtyard, yard', 'avlu, bahçe', '마당, 뜰'],
  ['约', 'yuē', 'verb', 'to make an appointment; about, approximately', 'randevu almak; yaklaşık', '약속하다, 대략'],
  ['约会', 'yuēhuì', 'noun', 'date, appointment; to date, to meet up', 'randevu, buluşma', '데이트, 약속'],
  ['月饼', 'yuèbing', 'noun', 'mooncake', 'ay keki', '월병'],
  ['阅读', 'yuèdú', 'verb', 'to read, to read aloud', 'okumak', '읽다, 독서하다'],
  ['月份', 'yuèfèn', 'noun', 'month', 'ay, ay dilimi', '월'],
  ['云', 'yún', 'noun', 'cloud', 'bulut', '구름'],
  ['允许', 'yǔnxǔ', 'verb', 'to permit, to allow, to give permission', 'izin vermek', '허락하다, 허가하다, 용납하다'],
  ['杂志', 'zázhì', 'noun', 'magazine', 'dergi', '잡지'],
  ['再次', 'zàicì', 'adverb', 'once again, once more', 'bir kez daha', '다시 한번, 재차'],
  ['再说', 'zàishuō', 'conjunction', 'besides, moreover; to put off', 'üstelik; ertelemek', '게다가, 더욱이; 나중에 말하다'],
  ['暂时', 'zànshí', 'adjective', 'temporary, for the time being', 'geçici', '일시적인, 잠시의'],
  ['暂停', 'zàntíng', 'verb', 'to suspend, to pause', 'askıya almak, duraklatmak', '일시 정지하다, 중단하다'],
  ['早餐', 'zǎocān', 'noun', 'breakfast', 'kahvaltı', '아침 식사'],
  ['早晨', 'zǎochen', 'noun', 'morning', 'sabah', '아침'],
  ['责任', 'zérèn', 'noun', 'responsibility, duty', 'sorumluluk, görev', '책임, 의무'],
  ['增加', 'zēngjiā', 'verb', 'to increase, to add, to raise', 'artırmak', '늘리다, 더하다, 증가하다'],
  ['增长', 'zēngzhǎng', 'verb', 'to increase, to grow, to rise', 'büyümek, artmak', '증가하다, 성장하다'],
  ['招聘', 'zhāopìn', 'verb', 'to recruit, to hire', 'işe almak, işe çekmek', '모집하다, 채용하다'],
  ['着', 'zhe, zháo, zhuó', 'verb', 'to touch, to get to, to catch', 'değmek, yakalamak', '고 (동작의 지속), 닿다, 얻다, 잡다'],
  ['着火', 'zháohuǒ', 'verb', 'to catch fire, to ignite', 'tutuşmak, yanmak', '불이 나다'],
  ['者', 'zhě', 'suffix', 'person, one who', 'kişi, -cı/-ci eki', '~하는 사람(접미사)'],
  ['真正', 'zhēnzhèng', 'adverb', 'true, genuine; truly, indeed', 'gerçek, sahici; gerçekten', '진정한, 참된, 정말로'],
  ['整', 'zhěng', 'adjective', 'whole, complete, entire', 'tam, eksiksiz', '전체의, 온전한'],
  ['整个', 'zhěnggè', 'adjective', 'whole, entire, all', 'tüm, bütün', '전체의, 온통'],
  ['整理', 'zhěnglǐ', 'verb', 'to arrange, to put in order, to tidy up', 'düzenlemek, toplamak', '정리하다, 정돈하다'],
  ['证', 'zhèng', 'noun', 'certificate, proof, evidence', 'sertifika, kanıt', '증명서, 증거'],
  ['正常', 'zhèngcháng', 'adjective', 'normal, regular, proper', 'normal', '정상적이다'],
  ['正好', 'zhènghǎo', 'adverb', 'exactly right, just in time; coincidentally', 'tam zamanında; tesadüfen', '마침, 딱 알맞다'],
  ['证件', 'zhèngjiàn', 'noun', 'ID card, credentials, identification papers', 'kimlik belgesi', '증명서, 신분증'],
  ['证明', 'zhèngmíng', 'noun', 'proof, certificate; to prove', 'kanıt; kanıtlamak', '증명하다, 증명서'],
  ['正确', 'zhèngquè', 'adjective', 'correct, right, accurate', 'doğru, yerinde', '올바르다, 정확하다'],
  ['正式', 'zhèngshì', 'adjective', 'formal, official', 'resmi', '정식의, 공식적인'],
  ['之', 'zhī', 'auxiliary', 'auxiliary word (classical)', 'yardımcı sözcük', '~의 (지시 대명사)'],
  ['支持', 'zhīchí', 'verb', 'to support, to back', 'desteklemek', '지지하다, 후원하다'],
  ['支付', 'zhīfù', 'verb', 'to pay (money)', 'ödemek', '지불하다'],
  ['之后', 'zhīhòu', 'noun', 'after, later, behind', 'sonra', '~의 뒤, ~후'],
  ['之间', 'zhījiān', 'noun', 'between, among', 'arasında', '~의 사이, ~간'],
  ['之前', 'zhīqián', 'noun', 'before, prior to', 'önce, öncesinde', '~의 앞, ~전'],
  ['知识', 'zhīshi', 'noun', 'knowledge', 'bilgi', '지식'],
  ['之中', 'zhīzhōng', 'noun', 'among, inside', 'içinde, arasında', '~의 가운데, ~중에서'],
  ['值', 'zhí', 'verb', 'to be worth, to be equal in value', 'değer olmak', '가치가 있다, ~에 상당하다'],
  ['值得', 'zhídé', 'verb', 'to be worth, to deserve', 'değmek, hak etmek', '가치가 있다, ~할 만하다'],
  ['直接', 'zhíjiē', 'adjective', 'direct, straightforward', 'doğrudan', '직접적이다, 솔직하다'],
  ['植物', 'zhíwù', 'noun', 'plant, vegetation', 'bitki', '식물'],
  ['职业', 'zhíyè', 'noun', 'occupation, profession', 'meslek, iş', '직업'],
  ['指', 'zhǐ', 'verb', 'to point to, to indicate', 'işaret etmek', '가리키다, 지적하다'],
  ['指出', 'zhǐchū', 'verb', 'to point out, to indicate', 'belirtmek', '지적하다, 짚어 내다'],
  ['只好', 'zhǐhǎo', 'adverb', 'have to, be forced to', 'zorunda kalmak', '그저 ~할 수밖에 없다'],
  ['纸巾', 'zhǐjīn', 'noun', 'tissue paper, napkin', 'kagit mendil', '티슈, 화장지'],
  ['质量', 'zhìliàng', 'noun', 'quality', 'kalite', '품질'],
  ['至少', 'zhìshǎo', 'adverb', 'at least', 'en az', '적어도, 최소한'],
  ['中餐', 'zhōngcān', 'noun', 'Chinese food, Chinese meal', 'Cin yemegi', '중국 요리, 중국 음식'],
  ['中年', 'zhōngnián', 'noun', 'middle age', 'orta yas', '중년'],
  ['种', 'zhǒng, zhòng', 'verb', 'to plant, to grow', 'dikmek, ekmek', '1. 종류 2. 심다, 재배하다'],
  ['重', 'zhòng, chóng', 'adjective', 'weight, importance; heavy, important', 'agir, onemli', '다시, 무겁다, 중요하다'],
  ['重点', 'zhòngdiǎn', 'noun', 'key point, emphasis', 'kilit nokta, vurgu', '중점, 핵심'],
  ['重视', 'zhòngshì', 'verb', 'to pay attention to, to value', 'onem vermek', '중시하다'],
  ['周围', 'zhōuwéi', 'noun', 'around, surrounding', 'etraf, cevre', '주위, 주변'],
  ['主意', 'zhǔyi', 'noun', 'idea, thought, plan', 'fikir, plan', '아이디어, 생각, 계획'],
  ['祝', 'zhù', 'verb', 'to wish, to express good wishes', 'dilemek', '빌다, 축원하다'],
  ['祝贺', 'zhùhè', 'verb', 'to congratulate, to offer congratulations', 'tebrik etmek', '축하하다'],
  ['著名', 'zhùmíng', 'adjective', 'famous, well-known', 'unlu, meshur', '유명하다'],
  ['专门', 'zhuānmén', 'adverb', 'specially, specifically; special', 'ozellikle, hususi', '전문적으로, 특별히; 전문적인'],
  ['专业', 'zhuānyè', 'noun', 'specialty, major; professional', 'uzmanlik; profesyonel', '전공, 전문 분야; 전문적인'],
  ['转', 'zhuǎn, zhuàn', 'verb', 'to turn, to shift, to transfer', 'donmek, cevirmek', '돌다, 회전하다, 갈아타다'],
  ['转发', 'zhuǎnfā', 'verb', 'to forward a message, to retweet', 'iletmek, yonlendirmek', '전달하다, 공유하다'],
  ['转机', 'zhuǎnjī', 'verb', 'to transfer flight, to change planes', 'aktarma yapmak', '비행기를 갈아타다'],
  ['赚', 'zhuàn', 'verb', 'to earn, to make a profit', 'kazanmak, kar etmek', '벌다, 이득을 보다'],
  ['装', 'zhuāng', 'verb', 'to load, to pack, to pretend, to install', 'yuklemek; yapmak gibi gorunmek', '담다, 설치하다, 가장하다'],
  ['准', 'zhǔn', 'adjective', 'accurate, exact, standard; definitely', 'dogru, kesin; kesinlikle', '정확하다, 기준에 맞다; 분명히'],
  ['准确', 'zhǔnquè', 'adjective', 'accurate, precise', 'dogru, isabetli', '정확하다, 정확하게'],
  ['准时', 'zhǔnshí', 'adjective', 'on time, punctual', 'zamaninda', '정시에, 때맞춰'],
  ['资料', 'zīliào', 'noun', 'materials, data, information', 'materyal, bilgi', '자료, 정보'],
  ['仔细', 'zǐxì', 'adjective', 'careful, attentive, meticulous', 'dikkatli, titiz', '주의 깊은, 꼼꼼한'],
  ['自', 'zì', 'preposition', 'from, since, oneself', 'kendisi, itibaren', '~로부터, 스스로'],
  ['自然', 'zìrán', 'noun', 'nature; natural; naturally, of course', 'doga; dogal; dogal olarak', '자연, 당연하다, 자연스럽다'],
  ['自习', 'zìxí', 'verb', 'to study on ones own', 'kendi basina calismak', '자습하다'],
  ['自信', 'zìxìn', 'noun', 'self-confidence; confident', 'ozguven; ozguvenli', '자신감, 자신감 있는'],
  ['自学', 'zìxué', 'verb', 'to teach oneself, to self-study', 'kendi kendine ogrenmek', '독학하다'],
  ['总结', 'zǒngjié', 'noun', 'summary; to summarize, to sum up', 'ozet; ozetlemek', '요약, 총괄하다, 정리하다'],
  ['租', 'zū', 'verb', 'to rent, to hire', 'kiralamak', '빌리다, 세를 내다'],
  ['组', 'zǔ', 'noun', 'group, team', 'grup, takim', '조, 그룹'],
  ['最终', 'zuìzhōng', 'noun', 'final, ultimate', 'nihayet, son olarak', '최종, 마지막'],
  ['尊重', 'zūnzhòng', 'verb', 'to respect, to value', 'saygi gostermek', '존중하다'],
  ['左右', 'zuǒyòu', 'noun', 'about, around, left and right', 'yaklasik, etrafinda', '좌우, 대략, 정도'],
  ['座', 'zuò', 'classifier', 'seat, place; measure word for seats', 'koltuk, yer sayaci', '좌석, 자리(큰 물건을 세는 단위)'],
  ['做法', 'zuòfǎ', 'noun', 'way of doing things, practice', 'yapis bicimi, yontem', '방법, 수법, 방식'],
  ['作家', 'zuòjiā', 'noun', 'writer, author', 'yazar', '작가'],
  ['做梦', 'zuòmèng', 'verb', 'to dream, to have a dream', 'ruya gormek', '꿈을 꾸다'],
  ['作品', 'zuòpǐn', 'noun', 'work, composition, creation', 'eser', '작품'],
  ['作为', 'zuòwéi', 'verb', 'to act as, to serve as; as, being', 'olarak hareket etmek; olarak', '로서, ~으로; ~하다'],
  ['座位', 'zuòwèi', 'noun', 'seat', 'koltuk', '좌석, 자리'],
  ['作文', 'zuòwén', 'noun', 'composition; to write a composition', 'kompozisyon, yazi', '작문; 작문을 하다'],
  ['作用', 'zuòyòng', 'noun', 'function, role', 'islev, rol', '작용, 역할'],
  ['作者', 'zuòzhě', 'noun', 'author, writer', 'yazar', '저자, 작가'],
];
